### ISSUE TITLE
Psort error

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#1001]
I am running the latest version of plaso and after completing the log2timeline starting from a directory on a mounted device using the command `log2timeline.py -p plasodump mountpoint/Documents\ and\ Settings\ `it completes. Then I run `psort.py -o 4n6time_sqlite -w plasodump.sqlite plasodump` and I get the error below. I am unable to delete the plasodump file also 
rm -rf plasodump : Text file busy.

```
plaso - psort version 1.4.1_20160912

Storage file	: plasodump

Identifier		PID	Status		Events		Reports
Main			30885	idle		0 (0)		0 (0)	
browser_search		30890	analyzing	0 (0)		0 (0)	

Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.4.1-20160912', u'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/EGG-INFO/scripts/psort.py", line 867, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/EGG-INFO/scripts/psort.py", line 853, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/EGG-INFO/scripts/psort.py", line 787, in ProcessStorage
    status_update_callback=status_update_callback)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/frontend/psort.py", line 103, in AnalyzeEvents
    status_update_callback=status_update_callback)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/multi_processing/psort.py", line 541, in AnalyzeEvents
    storage_writer.Open()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/storage/zip_file.py", line 3193, in Open
    self._storage_file.Open(path=self._output_file, read_only=False)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/storage/zip_file.py", line 2765, in Open
    self._OpenZIPFile(path, read_only)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/storage/zip_file.py", line 1744, in _OpenZIPFile
    os.rename(path, zipfile_path)
OSError: [Errno 26] Text file busy
```

Regards

Alan

**Comment by Onager** [comment]
Please use the issue template.

The command line and output don't match - it looks like the OSError was raised when psort was running with an analysis plugin, can you confirm that? Does this happen without the browser_search analysis plugin as well?

**Comment by odibrowne** [comment]
Yes psort.py was running with the browser_search analysis plugin and it doesn't happen when I don't use an analysis plugin

**Comment by joachimmetz** [comment]
@Onager mentioned having tracked down the issue and fixes are pending, hence assigning to him.
