### ISSUE TITLE
pycrypto required in python virtualenv

### ISSUE THREAD

**Issue by cshanahan** [log2timeline/plaso#1024]
**Plaso version:**
1.5.0 Release

**Operating system Plaso is running on:**
Ubuntu 16.04.1 64-bit

**Installation method:**
Installed Plaso from source using python virtualenv, described here: https://github.com/log2timeline/plaso/wiki/running-plaso-in-virtualenv

**Description of problem:**
I created a new virtual machine running Ubuntu 16.04.1 to test the installation routine for Plaso 1.5 using python virtualenv. I followed the usual directions and installed all dependencies without error, including libyaml-dev. Then I installed Plaso from source. Also no errors. Running Plaso commands (e.g., psort.py --help) generate the following error:

`
Traceback (most recent call last):
  File "/home/uvm/bin/plasoenv/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.0', 'psort.py')
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/psort.py", line 27, in <module>
    from plaso import filters  # pylint: disable=unused-import
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/__init__.py", line 4, in <module>
    from plaso.filters import dynamic_filter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/dynamic_filter.py", line 4, in <module>
    from plaso.filters import event_filter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/event_filter.py", line 4, in <module>
    from plaso.filters import interface
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/interface.py", line 7, in <module>
    from plaso.lib import pfilter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/lib/pfilter.py", line 16, in <module>
    from plaso.parsers import presets
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/parsers/__init__.py", line 8, in <module>
    from plaso.parsers import chrome_cache
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/parsers/chrome_cache.py", line 8, in <module>
    from dfvfs.resolver import resolver as path_spec_resolver
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/__init__.py", line 13, in <module>
    from dfvfs.resolver import encrypted_stream_resolver_helper
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/encrypted_stream_resolver_helper.py", line 5, in <module>
    import dfvfs.file_io.encrypted_stream_io
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/file_io/encrypted_stream_io.py", line 6, in <module>
    from dfvfs.encryption import manager as encryption_manager
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/encryption/__init__.py", line 4, in <module>
    from dfvfs.encryption import aes_decrypter
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/encryption/aes_decrypter.py", line 4, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
`

Looks like dfvfs needs pycrypto. Please add pycrypto to the requirements file to satisfy this error:
"ImportError: No module named Crypto.Cipher"

A simple `pip install pycrypto` in my virtualenv _appears_ to solve the Crypto.Cipher error.

Thanks.
## 

Chris

**Comment by joachimmetz** [comment]
I'll add some missing dependencies for virtualenv. But know that virtualenv is not a supported installation method, pypi changes too frequently to be a reliable installation method. So you might need to tweak package versions.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/308580044/

**Comment by cshanahan** [comment]
> But know that virtualenv is not a supported installation method, pypi changes too frequently to be a reliable installation method.

I understand that Joachim, but virtualenv is the best option for everyone _not_ running Ubuntu 14.04.

Thanks for looking.

--
Chris

**Comment by joachimmetz** [comment]
"best option" again this is a value judgment, it will really depends on your needs. virtualenv has pros and cons, same as any other installation method.

**Comment by joachimmetz** [comment]
This should be fixed now, pycrypto is in requirements.txt file https://github.com/log2timeline/plaso/blob/master/requirements.txt#L44
