### ISSUE TITLE
Unable to connect to Elasticsearch errors.

### ISSUE THREAD

**Issue by vdsilva** [log2timeline/plaso#1025]
**Plaso version:**

1.5.1_20160922

but applies to 1.5.0 too.

**Operating system Plaso is running on:**

Ubuntu 14.04 running  3.13.0-95-generic

**Installation method:**

Direct checkout from GitHub.

**Description of problem:**

One test fails when running run_test.py because it cannot connect to an elastic search backend. When I run psort to export a .plaso file to timesketch format I get the same error about failure to connect to the elastic search backend. This is the command. The error traceback is below.

psort.py -o timesketch -w acserver.ts acserver.plaso

**Debug output/tracebacks:**

```
======================================================================
ERROR: testEventToDict (output.elastic.ElasticSearchHelperTest)
Tests the _EventToDict function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/vijaydsilva/log2timeline/plaso/tests/output/elastic.py", line 59, in testEventToDict
    output_mediator, u'127.0.0.1', 9200, 1000, u'test', {}, u'test_type')
  File "./plaso/output/elastic.py", line 44, in __init__
    self._index = self._EnsureIndexExists(index_name, mapping)
  File "./plaso/output/elastic.py", line 82, in _EnsureIndexExists
    raise RuntimeError(u'Unable to connect to Elasticsearch backend.')
RuntimeError: Unable to connect to Elasticsearch backend.

----------------------------------------------------------------------
```

```
vdsilva@vdsilva:greendale$ psort.py -o timesketch -w acserver.ts acserver.plaso
2016-10-03 16:58:07,369 [INFO] (MainProcess) PID:9585 <timesketch_out> Document type: plaso_event
2016-10-03 16:58:07,369 [INFO] (MainProcess) PID:9585 <timesketch_out> Flush interval: 1000
2016-10-03 16:58:07,369 [INFO] (MainProcess) PID:9585 <timesketch_out> Index name: 1b4ba1c8a14b4ee7872a63db96e69ad1
2016-10-03 16:58:07,369 [INFO] (MainProcess) PID:9585 <timesketch_out> Timeline name:
2016-10-03 16:58:07,369 [INFO] (MainProcess) PID:9585 <timesketch_out> Owner of the timeline: None
Missing parameter timeline_name for output module: acoutput
2016-10-03 16:58:17,096 [INFO] (MainProcess) PID:9585 <timesketch_out> Document type: plaso_event
2016-10-03 16:58:17,096 [INFO] (MainProcess) PID:9585 <timesketch_out> Flush interval: 1000
2016-10-03 16:58:17,097 [INFO] (MainProcess) PID:9585 <timesketch_out> Index name: 1b4ba1c8a14b4ee7872a63db96e69ad1
2016-10-03 16:58:17,097 [INFO] (MainProcess) PID:9585 <timesketch_out> Timeline name: acoutput

2016-10-03 16:58:17,097 [INFO] (MainProcess) PID:9585 <timesketch_out> Owner of the timeline: None
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 868, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 854, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 798, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/path/to/log2timeline/plaso/plaso/frontend/psort.py", line 283, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/path/to/log2timeline/plaso/plaso/multi_processing/psort.py", line 609, in ExportEvents
    output_module, deduplicate_events)
  File "/path/to/log2timeline/plaso/plaso/output/event_buffer.py", line 91, in __init__
    self._output_module.WriteHeader()
  File "/path/to/log2timeline/plaso/plaso/output/timesketch_out.py", line 160, in WriteHeader
    self._index_name, _document_mapping, self._doc_type)
  File "/path/to/log2timeline/plaso/plaso/output/elastic.py", line 44, in __init__
    self._index = self._EnsureIndexExists(index_name, mapping)
  File "/path/to/log2timeline/plaso/plaso/output/elastic.py", line 82, in _EnsureIndexExists 
    raise RuntimeError(u'Unable to connect to Elasticsearch backend.')
RuntimeError: Unable to connect to Elasticsearch backend.

```

**Source data:**

This is part of the output of pinfo on the storage file used above.

```
************************** Plaso Storage Information ***************************
            Filename : acserver.plaso
      Format version : 20160715
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
535b6feb-7036-467b-8118-d7e9d236725f : 2016-09-29T22:04:49.362538+00:00
--------------------------------------------------------------------------------

**************** Session: 535b6feb-7036-467b-8118-d7e9d236725f *****************
                Start time : 2016-09-29T22:04:49.362538+00:00
           Completion time : 2016-09-29T22:18:38.865323+00:00
              Product name : plaso
           Product version : 1.5.0
    Command line arguments : 
                             /path/to/log2timeline/plaso/tools/log2timeline.py
                             acserver.plaso images/acserver.dd
-------------------------------------------------------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
> Missing parameter timeline_name for output module: acoutput

?

**Comment by joachimmetz** [comment]
Assigning to @berggren he might have some more insight into why this could be failing.

**Comment by Onager** [comment]
The test failing looks similar to #996, the test fails when the elasticsearch module is installed, but no server is running.

As for the error message when using the Timesketch output module, this looks like the message indicates, Plaso can't connect to an elasticsearch instance - do you have a server running at the default location, localhost:9200?

Finally, you shouldn't need the -w option here.

@joachimmetz 'acoutput' is the name for the timeline that @vdsilva entered after being prompted by psort.

**Comment by vdsilva** [comment]
Thanks for the input. I have solved this problem now. Elasticsearch was installed on my system. I incorrectly believed that Elasticsearch was running because of bug [#1465374](https://bugs.launchpad.net/ubuntu/+source/elasticsearch/+bug/1465374) and [#1535954](https://bugs.launchpad.net/ubuntu/+source/elasticsearch/+bug/1535954) which cause Elasticsearch versions between 1.3.9 and 2.2.1 to incorrectly report [OK] on startup even if startup fails.

The failure of Elasticsearch was due to my misunderstanding the [Timesketch Installation](https://github.com/google/timesketch/wiki/Installation) instruction. I added `For Elasticsearch 1.x: script.groovy.sandbox.enabled: true` instead of  `script.groovy.sandbox.enabled: true` to `/etc/elasticsearch/elasticsearch.yml config`. 

After fixing the config, Elasticsearch is now running, all Plaso tests pass and the export to Timesketch also works.
