### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_version'

### ISSUE THREAD

**Issue by adamziaja** [log2timeline/plaso#1033]
```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.1.post20161005', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/cli/extraction_tool.py", line 9, in <module>
    from plaso.engine import engine
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/engine/engine.py", line 14, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/preprocessors/macosx.py", line 11, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/parsers/__init__.py", line 11, in <module>
    from plaso.parsers import custom_destinations
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/parsers/custom_destinations.py", line 16, in <module>
    from plaso.parsers import winlnk
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/parsers/winlnk.py", line 18, in <module>
    dependencies.CheckModuleVersion(u'pylnk')
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.1.post20161005-py2.7.egg/plaso/dependencies.py", line 484, in CheckModuleVersion
    module_version = module_object.get_version()
AttributeError: 'module' object has no attribute 'get_version'
```

How can I fix that?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/997 should answer your question
