### ISSUE TITLE
Analysis plugin nsrlsvr: Incorrect results 

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1036]
**Plaso version:**

1.5.0 Release

**Operating system Plaso is running on:**

XUbuntu 64 bit

**Installation method:**

Installed from GiFT

**Description of problem:**

Using the `nsrlsvr` analysis plugin of `psort.py` yields incorrect results. The response from the server is mis-interpreted, causing the suggestion that no hash is listed at all.

**Source data:**

Problem seems to be related to line-endings, and may depend on the OS of the client or the OS of the NSRL server. Problem can be fixed by `rstrip`-ing the response from the server in line 67 of `plaso\analysis\nsrlsvr.py` :

    response = nsrl_socket.recv(self._RECEIVE_BUFFER_SIZE).rstrip()

Note that #1035 is related and needs fixing before this issue can be debugged.

**Comment by kinky-it** [comment]
When testing, make sure that your test NSRL server actually has the queried hash types. The analysis plugin code will query only *one* hash per file. When your dump file has both sha256 and a md5 hashes for one file, the analysis plugin will take the sha256 hash, and query for that. When the NSRL server only has md5 hashes, it will return a non-hit for the sha256 hash. This result suggests that the file is not present in the database, while it may be available on its md5 hash.

As far as I know, the suggested https://rjhansen.github.io/nsrlsvr/ only has import code for md5 hashes.

It would make sense to primarily use the md5 hash in the queries.

**Comment by joachimmetz** [comment]
> Problem seems to be related to line-endings, and may depend on the OS of the client or the OS of the NSRL server. 

Can you provide an example of such a line.

**Comment by joachimmetz** [comment]
I've also create the following instructions: https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-nsrlsvr

Feel free to improve them.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/312850043/

**Comment by pettai** [comment]
I applied your patchset to plaso-1.5.0 and ran it again. It doesn't bail now, but nsrlsvr plugin is killed  and then psort hangs waiting...

Command:

`~$ psort.py -d --analysis nsrlsvr --nsrlsvr-host localhost --nsrlsvr-port 9120 -o null plaso-1.5.0-md5.plaso 2> psort.patched.err > psort.patched.out`

Stdout:

```
plaso - psort version 1.5.0

Storage file	: plaso-1.5.0-md5.plaso

Identifier		PID	Status		Events		Reports
Main			107398	running		491248 (0)	0 (0)
nsrlsvr			107406	killed		491248 (0)	1 (1)

^C
```

Debug log (stderr):

```
~$ tail -f psort.patched.err
2016-10-16 12:25:40,297 [DEBUG] (nsrlsvr   ) PID:107406 <zeromq_queue> Pop on nsrlsvr input event queue queue, port 37872
2016-10-16 12:25:40,297 [DEBUG] (MainProcess) PID:107398 <zeromq_queue> nsrlsvr output event queue sending item
2016-10-16 12:25:40,297 [DEBUG] (MainProcess) PID:107398 <zeromq_queue> nsrlsvr output event queue sent item
2016-10-16 12:25:40,298 [DEBUG] (MainProcess) PID:107398 <psort> Processing analysis plugin results.
2016-10-16 12:25:40,298 [DEBUG] (nsrlsvr   ) PID:107406 <analysis_process> ConsumeItems exiting, dequeued QueueAbort object.
2016-10-16 12:25:40,298 [DEBUG] (nsrlsvr   ) PID:107406 <analysis_process> nsrlsvr (PID: 107406) stopped monitoring event queue.
2016-10-16 12:25:40,298 [INFO] (nsrlsvr   ) PID:107406 <interface> nsrlsvr hash analysis plugin running. 1045 hashes in queue, estimated completion time Sun Oct 16 12:25:40 2016.
2016-10-16 12:25:42,088 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:42,093 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:42,120 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:42,150 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:42,165 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:42,201 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:44,825 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:44,833 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:44,848 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:44,863 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:25:44,868 [DEBUG] (nsrlsvr   ) PID:107406 <nsrlsvr> Opening connection to localhost:9120
2016-10-16 12:26:12,329 [DEBUG] (nsrlsvr   ) PID:107406 <analysis_process> Analysis plugin: nsrlsvr (PID: 107406) stopped
2016-10-16 12:26:12,329 [DEBUG] (nsrlsvr   ) PID:107406 <zeromq_queue> nsrlsvr input event queue queue closing, will linger for up to 10 seconds
2016-10-16 12:26:17,558 [DEBUG] (nsrlsvr   ) PID:107406 <base_process> Process: nsrlsvr process status RPC server stopped
2016-10-16 12:26:17,559 [DEBUG] (nsrlsvr   ) PID:107406 <base_process> Process: nsrlsvr (PID: 107406) stopped
2016-10-16 12:26:18,896 [ERROR] (MainProcess) PID:107398 <psort> Process nsrlsvr (PID: 107406) is not functioning correctly. Status code: killed.
2016-10-16 12:26:19,834 [WARNING] (MainProcess) PID:107398 <engine> Terminating process: (PID: 107406).
2016-10-16 12:26:20,145 [DEBUG] (MainProcess) PID:107398 <engine> Process: nsrlsvr (PID: 107406) has been removed from the monitoring list.
```

Hangs until ^C is pressed...

(I'm still running this on xenial with the ppa:gift/dev branch)

**Comment by joachimmetz** [comment]
> t doesn't bail now, but nsrlsvr plugin is killed and then psort hangs waiting...

FYI, already looking into that, the patches are not finished yet.

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "tools/psort.py", line 869, in <module>
    if not Main():
  File "tools/psort.py", line 855, in Main
    tool.ProcessStorage()
  File "tools/psort.py", line 821, in ProcessStorage
    self._PrintAnalysisReportsDetails(storage_reader)
  File "tools/psort.py", line 251, in _PrintAnalysisReportsDetails
    for index, analysis_report in enumerate(storage.GetAnalysisReports()):
  File "plaso/storage/zip_file.py", line 2524, in GetAnalysisReports
    data_stream, u'analysis_report'):
  File "plaso/storage/zip_file.py", line 1798, in _ReadAttributeContainersFromStream
    data_stream, container_type)
  File "plaso/storage/zip_file.py", line 1784, in _ReadAttributeContainerFromStreamEntry
    entry_data = data_stream.ReadEntry()
  File "plaso/storage/zip_file.py", line 495, in ReadEntry
    u'Unable to read data entry size value out of bounds.')
IOError: Unable to read data entry size value out of bounds.
```

**Comment by pettai** [comment]
@joachimmetz much appreciated!

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "tools/psort.py", line 869, in <module>
    if not Main():
  File "tools/psort.py", line 855, in Main
    tool.ProcessStorage()
  File "tools/psort.py", line 788, in ProcessStorage
    status_update_callback=status_update_callback)
  File "plaso/frontend/psort.py", line 103, in AnalyzeEvents
    status_update_callback=status_update_callback)
  File "plaso/multi_processing/psort.py", line 590, in AnalyzeEvents
    self._StopAnalysisProcesses(abort=self._abort)
  File "plaso/multi_processing/psort.py", line 444, in _StopAnalysisProcesses
    event_queue.PushItem(plaso_queue.QueueAbort(), block=False)
  File "plaso/engine/zeromq_queue.py", line 448, in PushItem
    raise errors.QueueFull
plaso.lib.errors.QueueFull
```

**Comment by joachimmetz** [comment]
@pettai can you double check if it is unresponsive or just still working on writing a huge analysis report?

**Comment by pettai** [comment]
Right, I got
```
2016-10-16 22:49:38,782 [DEBUG] (MainProcess) PID:113211 <zeromq_queue> nsrlsvr output event queue sending item
2016-10-16 22:49:38,782 [DEBUG] (MainProcess) PID:113211 <zeromq_queue> nsrlsvr output event queue could not send an item
2016-10-16 22:49:38,782 [ERROR] (MainProcess) PID:113211 <zeromq_queue> nsrlsvr output event queue unable to push item, raising.
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 868, in <module>
    if not Main():
  File "/usr/local/bin/psort.py", line 854, in Main
    tool.ProcessStorage()
  File "/usr/local/bin/psort.py", line 788, in ProcessStorage
    status_update_callback=status_update_callback)
  File "/usr/local/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 103, in AnalyzeEvents
    status_update_callback=status_update_callback)
  File "/usr/local/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 567, in AnalyzeEvents
    self._StopAnalysisProcesses(abort=self._abort)
  File "/usr/local/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 423, in _StopAnalysisProcesses
    event_queue.PushItem(plaso_queue.QueueAbort(), block=False)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/zeromq_queue.py", line 448, in PushItem
    raise errors.QueueFull
plaso.lib.errors.QueueFull
```

**Comment by joachimmetz** [comment]
changes merged
