### ISSUE TITLE
Inconsistent Results - Plaso v1.5.1

### ISSUE THREAD

**Issue by cshanahan** [log2timeline/plaso#1073]
**Plaso version:**
1.5.1 Release

**Operating system Plaso is running on:**
openSUSE 42.1 64-bit

**Installation method:**
Installed Plaso from source using python virtualenv, described here: https://github.com/log2timeline/plaso/wiki/running-plaso-in-virtualenv

**Description of problem:**
I tested the new release (v1.5.1) using the evidence images from SANS FOR508 and I have experienced inconsistent results when compared to results generated by v1.5.0, as seen in the attached text files.

For example, using the nfury image Plaso (log2timeline) v1.5.0 and v1.5.1 both correctly identify the operating system (Windows 7 Ent 64-bit). Both versions also enable most of the same parsers and plugins, yet the results are dramatically different. Plaso v1.5.0 produces 1451110 total events while Plaso v1.5.1 produces 38918 total events. There are other differences as well, such as errors. For my tests, I ran log2timeline using the "kitchen sink" approach, with and without VSS selected.
`e.g., log2timeline.py nfury.dump nfury.E01`

I also tried the nfury image on a second system (Ubuntu 16.04 in VMware WS) using both Plaso v1.5.0 and Plaso v1.5.1 and got the same results.

If needed, I have 5 dump files from Plaso v1.5.1 which I could share. They average between 2.4 MB and 3.2 MB each. I could also run pinfo against any/all of the dump files I created if you need more examples for comparison.
[Plaso_v1.5.0.txt](https://github.com/log2timeline/plaso/files/559254/Plaso_v1.5.0.txt)
[Plaso_v1.5.1.txt](https://github.com/log2timeline/plaso/files/559255/Plaso_v1.5.1.txt)

If you'd like me to try anything else, let me know. I'd be happy to help.

--
Chris

**Comment by joachimmetz** [comment]
> Plaso v1.5.0 produces 1451110 total events while Plaso v1.5.1 produces 38918 total events.

Thanks having a look.

**Comment by Onager** [comment]
I've been able to reproduce this, but no root cause yet - I'm still investigating.

**Comment by maurermj08** [comment]
I have noticed the same issue and started compiling some test results here http://diftdisk.blogspot.com/2016/11/plaso-15-inconsistent-results.html. I will comment on this issue if I find anything useful.

**Comment by Onager** [comment]
Hey folks - in your log2timeline runs where you see odd results, are you also getting messages like this when processing is complete:
```
Path specifications that could not be processed:
type: OS, location: /media/greendale_images/student-pc1.dd
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x06500000
type: TSK, inode: 74819, location: /Windows/winsxs/amd64_microsoft-windows-ie-htmlapplication_31bf3856ad364e35_11.2.9600.16428_none_3bb1024f1e6bc086
```

After a bit of digging around, I think this might be due to tasks becoming abandoned, perhaps due to some locking or contention in the main thread.

**Comment by cshanahan** [comment]
No sir, I haven't encountered that error message in my tests.


Chris

**Comment by maurermj08** [comment]
@Onager I have not seen that error, all my tests show no errors stored. However, I believe your theory about the tasks is correct because all my tests with "--single_process" work just fine.

**Comment by Onager** [comment]
These aren't stored errors, they messages are displayed when log2timeline completes. For example:

```
Source path	: /media/greendale_images/student-pc1.dd
Source type	: storage media image

Processing started.
Processing completed with errors.

Number of errors encountered while extracting events: 17.

Use pinfo to inspect errors in more detail.

Path specifications that could not be processed:
type: OS, location: /media/greendale_images/student-pc1.dd
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x06500000
type: TSK, inode: 74819, location: /Windows/winsxs/amd64_microsoft-windows-ie-htmlapplication_31bf3856ad364e35_11.2.9600.16428_none_3bb1024f1e6bc086

type: OS, location: /media/greendale_images/student-pc1.dd
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x06500000
type: TSK, inode: 7061, location: /Windows/winsxs/amd64_microsoft-windows-p..ormancebasecounters_31bf3856ad364e35_6.1.7600.16385_none_8d682f6a76cad93f

type: OS, location: /media/greendale_images/student-pc1.dd
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x06500000
type: VSHADOW, location: /vss1, store index: 0
type: TSK, inode: 40145, location: /Windows/SysWOW64/en-US/shellstyle.dll.mui
```

**Comment by maurermj08** [comment]
Here are the errors I got on some tests that I ran with and without ZeroMQ:

With ZeroMQ:
```
plaso - log2timeline version 1.5.1

Source path	: /home/user/Downloads/xp-tdungan-c-drive.E01
Source type	: storage media image

Identifier	PID	Status		Sources		Events		File
Main		4921	completed	42744 (0)	153136 (0)	
Worker_00	4929	running		12921 (0)	42688 (4)	TSK:/WINDOWS/$NtUninstallKB943729$/spuninst/spuninst.inf
Worker_01	4933	running		11793 (0)	42420 (4)	TSK:/WINDOWS/system32/DirectX/Dinput/msf1f_5.png
Worker_02	4937	idle		9892 (0)	42432 (8)	TSK:/WINDOWS/system32/DirectX/Dinput/msprw_8.png
Worker_03	4941	running		8196 (0)	42472 (8)	TSK:/WINDOWS/$NtUninstallKB971657_0$/spuninst/updspapi.dll

2016-11-09 21:35:37,301 [WARNING] (MainProcess) PID:4921 <engine> Terminating process: Worker_00 (PID: 4929).
2016-11-09 21:35:37,301 [WARNING] (MainProcess) PID:4921 <engine> Terminating process: Worker_01 (PID: 4933).
2016-11-09 21:35:37,302 [WARNING] (MainProcess) PID:4921 <engine> Terminating process: Worker_03 (PID: 4941).
2016-11-09 21:35:37,302 [WARNING] (MainProcess) PID:4921 <engine> Terminating process: Worker_02 (PID: 4937).
2016-11-09 21:35:41,261 [WARNING] (MainProcess) PID:4921 <zeromq_queue> main_task_queue timeout waiting for a request.
2016-11-09 21:35:45,262 [WARNING] (MainProcess) PID:4921 <zeromq_queue> main_task_queue timeout waiting for a request.
2016-11-09 21:35:45,262 [INFO] (MainProcess) PID:4921 <zeromq_queue> Queue main_task_queue responder exiting.
Processing completed with errors.

Path specifications that could not be processed:
type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 40255, location: /WINDOWS/$NtServicePackUninstall$/reg00742

type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 2971, location: /Documents and Settings/tdungan/Local Settings/Application Data/Mozilla/Firefox/Profiles/uimccx5n.default/Cache/0/17/8C481d01

type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 14916, location: /WINDOWS/$NtServicePackUninstall$/fltlib.dll

...
```

Without ZeroMQ:
```
plaso - log2timeline version 1.5.1

Source path	: /home/user/Downloads/xp-tdungan-c-drive.E01
Source type	: storage media image

Identifier	PID	Status		Sources		Events		File
Main		5065	completed	42744 (0)	154297 (0)	
Worker_00	5070	idle		9829 (0)	42457 (0)	GZIP:/Documents and Settings/tdungan/Local Settings/Temporary Internet Files/Content.IE5/O52ZG5AZ/confirmation[1].aspx
Worker_01	5072	idle		12226 (0)	42878 (0)	GZIP:/Documents and Settings/tdungan/Local Settings/Temporary Internet Files/Content.IE5/KTI305MV/thank-you[1].aspx
Worker_02	5074	idle		12312 (0)	42805 (0)	GZIP:/Documents and Settings/tdungan/Local Settings/Temporary Internet Files/Content.IE5/GLABKD23/broker-config_s2[1].js
Worker_03	5076	idle		8435 (0)	42769 (0)	GZIP:/Documents and Settings/tdungan/Local Settings/Temporary Internet Files/Content.IE5/KTI305MV/broker-config_s1[2].js

2016-11-09 23:01:41,094 [WARNING] (MainProcess) PID:5065 <engine> Terminating process: Worker_01 (PID: 5072).
Processing completed with errors.

Path specifications that could not be processed:
type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 15104, location: /WINDOWS/$NtServicePackUninstall$/ipevldpc.dll

type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 23696, location: /Program Files/McAfee/MSC/mcinstru.dll

type: OS, location: /home/user/Downloads/xp-tdungan-c-drive.E01
type: EWF
type: TSK, inode: 14414, location: /WINDOWS/$NtServicePackUninstall$/capesnpn.dll

...
```

I feel like heapq is failing to merge events back, because after a while **main** stops adding events:

![strange_error](https://cloud.githubusercontent.com/assets/13810976/20164935/f38deb3c-a6d6-11e6-908a-0a44ae70d355.gif)

**Comment by Onager** [comment]
No, this isn't an issue with heapq, main isn't merging because it's lost track of all the tasks and doesn't try to merge them.

**Comment by joachimmetz** [comment]
Maybe related:

```
Source path     : student-pc1.dd
Source type     : storage media image

Identifier      PID     Status          Sources         Events          File
Main            22970   merging         225900 (0)      996307 (28)     c792041752084304b98c07a3cc094f69
Worker_00       22978   extracting      17185 (0)       2707035 (54)    VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-dot3gpui_31bf3856ad364e35_6.1.7600.16385_none_955df32cf619d67a/dot3gpui.dll
Worker_01       22982   idle            38282 (0)       204800 (60)     VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-deviceuxres_31bf3856ad364e35_6.1.7600.16385_none_2045027d2f4afade/DeviceUx.ptxml
Worker_02       22986   idle            16938 (0)       2909965 (66)    VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-directshow-dvdupgrd_31bf3856ad364e35_6.1.7600.16385_none_7d9cbcec3df8da86/dvdupgrd.exe
Worker_03       22990   running         51047 (0)       242654 (19)     VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-directshow-mpeg2_31bf3856ad364e35_6.1.7600.16385_none_b5e580c10398bf75/mpg2splt.ax
Worker_04       22994   idle            39104 (0)       376189 (27)     VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-dhcp-client-dll_31bf3856ad364e35_6.1.7601.17514_none_d961938b8cd1e885/dhcpcsvc.dll
Worker_05       22998   running         36269 (0)       281499 (0)      VSS1:TSK:/Windows/winsxs/x86_microsoft-windows-difxapi_31bf3856ad364e35_6.1.7600.16385_none_0819f3b1f785b1ce/difxapi.dll
Worker_06       23002   running         27072 (0)       363822 (0)      TSK:/ProgramData/Microsoft/Windows Defender/Scans/CleanStore/Resources/E0/E074684A38F7C238445C68488AAF766F4C8C1801

Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "plaso/multi_processing/task_engine.py", line 535, in _StatusUpdateThreadMain
    self._CheckStatusWorkerProcess(pid)
  File "plaso/multi_processing/engine.py", line 173, in _CheckStatusWorkerProcess
    self._StartMonitoringProcess(replacement_process.pid)
  File "plaso/multi_processing/engine.py", line 320, in _StartMonitoringProcess
    pid))
IOError: RPC client unable to determine server (PID: 25099) port.
```

**Comment by joachimmetz** [comment]
Found and fixed some issues in libvshadow; tested with [updated version](https://github.com/libyal/libvshadow/releases/tag/20161111) and heapy. 
![screenshot from 2016-11-12 09-46-17](https://cloud.githubusercontent.com/assets/3888750/20236725/0c70d630-a8be-11e6-887a-c786c53f8a8a.png)

I'm disabling hachoir and testing again.

**Comment by joachimmetz** [comment]
With: https://github.com/log2timeline/plaso/commit/8815ada9b29a5e8de4ef1e2b1be1b86733fe5db3

average worker memory consumption per worker
* 1.6 - 1.7 GiB with hachoir enabled (default)
* 150 - 200 MiB with hachoir disabled (--parsers='!hachoir')

**Comment by joachimmetz** [comment]
hachoir is enabled by default this is a regression bug.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/323770043/
