### ISSUE TITLE
efilter.protocols error

### ISSUE THREAD

**Issue by futex** [log2timeline/plaso#1095]
"Plaso version:*  1.5.1 Release and github version *

**Operating system Plaso is running on: Kali rolling release and Debian stretch**

When i launch log2timeline.py command line i have this error

`﻿# log2timeline.py 
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/extraction_tool.py", line 9, in <module>
    from plaso.engine import engine
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 11, in <module>
    from plaso.engine import knowledge_base
  File "/usr/lib/python2.7/dist-packages/plaso/engine/knowledge_base.py", line 12, in <module>
    from plaso.containers import artifacts
  File "/usr/lib/python2.7/dist-packages/plaso/containers/__init__.py", line 4, in <module>
    from plaso.containers import artifacts
  File "/usr/lib/python2.7/dist-packages/plaso/containers/artifacts.py", line 4, in <module>
    from plaso.containers import interface
  File "/usr/lib/python2.7/dist-packages/plaso/containers/interface.py", line 4, in <module>
    from efilter.protocols import structured
ImportError: No module named efilter.protocols`

I have try to install structured 0.1 python module from pip, and i have the same error

**Comment by Onager** [comment]
This looks like efilter is missing - is it installed? Which version?

**Comment by Onager** [comment]
Also, the structured pip module is not required by Plaso - you need
efilter, which is here: https://pypi.python.org/pypi/efilter

**Comment by futex** [comment]
arf right, i was confused with the import structured. thank
