### ISSUE TITLE
Timelib and pytz issue on OSX

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#11]
Error is:

$ PYTHONPATH=. python2.7 plaso/lib/output.py
Traceback (most recent call last):
  File "plaso/lib/output.py", line 39, in <module>
    import pytz
  File "/Library/Python/2.7/site-packages/pytz/__init__.py", line 29, in <module>
    from pkg_resources import resource_stream
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 72, in <module>

  File "/Users/dmwhite/code/plaso/plaso/lib/parser.py", line 33, in <module>
  File "/Users/dmwhite/code/plaso/plaso/lib/event.py", line 25, in <module>
    from plaso.lib import timelib
  File "/Users/dmwhite/code/plaso/plaso/lib/timelib.py", line 51, in <module>
    class Timestamp(object):
  File "/Users/dmwhite/code/plaso/plaso/lib/timelib.py", line 142, in Timestamp
    def CopyToIsoFormat(cls, timestamp, timezone=pytz.utc, raise_error=False):
AttributeError: 'module' object has no attribute 'utc'

Which appears to be due to a circular dependency somewhere.

Workaround is stopping pytz from loading resource_stream from pkg_resources. In __init__.py for pytz, comment out these lines:
 try:
     from pkg_resources import resource_stream
 except ImportError:
     resource_stream = None

**Comment by joachimmetz** [comment]
Marking as wontfix for now.
