### ISSUE TITLE
traceback: libsmraw_handle_read_buffer: unable to read buffer from segments stream.

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#111]
I luckily saw a python exception scrolling by on the screen which might be the cause for the lockup also described in #108.

This happened after ~2 hours when running log2timeline.py in an ubuntu 14.04 VM against a traditional DD image (180GB) without any further options. My plaso version is:

```
$ log2timeline.py --version
log2timeline - plaso back-end 1.2.0
```

Here the full log as far as I was able to capture it. I will try to reproduce the crash again.

```
2015-02-12 17:24:16,261 [INFO] (MainProcess) PID:2284 <foreman> Worker_0 [2299] - Events Extracted: 765534 - File (/Windows/System32/config/RegBack/SYSTEM) - Running: True <sleeping>
2015-02-12 17:24:16,261 [WARNING] (MainProcess) PID:2284 <foreman> Unable to connect to RPC socket to: Worker_1 at http://localhost:2300
2015-02-12 17:24:16,262 [ERROR] (MainProcess) PID:2284 <foreman> Process Worker_1 [2300] is not functioning when it should be. Terminating it and removing from list.
2015-02-12 17:24:16,262 [WARNING] (MainProcess) PID:2284 <foreman> Process Worker_1 [2300] is still alive.
Process Worker_0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 604, in run
    self._extraction_worker.Run()
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 268, in Run
    self.ConsumeItems()
  File "/usr/lib/python2.7/dist-packages/plaso/engine/queue.py", line 171, in ConsumeItems
    self._ConsumeItem(item)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 95, in _ConsumeItem
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 74, in OpenFileEntry
    return file_system.GetFileEntryByPathSpec(path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_system.py", line 115, in GetFileEntryByPathSpec
    tsk_file = self._tsk_file_system.open_meta(inode=inode)
RuntimeError: 'pysmraw_handle_read_buffer: unable to read data. libfdata_stream_read_buffer: unable to read segment: 0 data at offset: 0x106bbc800. libsmraw_handle_read_buffer: unable to read buffer from segments stream.'
FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error reading image file (ntfs_dinode_lookup: Error reading MFT Entry at 3332098048)
2015-02-12 17:24:26,265 [WARNING] (MainProcess) PID:2284 <foreman> Unable to connect to RPC socket to: Worker_0 at http://localhost:2299
2015-02-12 17:24:26,266 [ERROR] (MainProcess) PID:2284 <foreman> Process Worker_0 [2299] is not functioning when it should be. Terminating it and removing from list.
...
```

**Comment by joachimmetz** [comment]
> libsmraw_handle_read_buffer: unable to read buffer from segments stream.

This happens when smraw gets a different amount of data back then requested.
Do you see read errors some where?

**Comment by joachimmetz** [comment]
So echo $(( 0x106bbc800 / ( 1024 * 1024 * 1024 ) )) = 4

What architecture are you running 32-bit or 64-bit?

**Comment by bf** [comment]
I'm running 64bit, x86_64 with a 3.31.0 kernel in the VM.

**Comment by joachimmetz** [comment]
Ok then smraw being built with 32-bit file offsets support is unlikely. What about the other factors that could impose a 4G limit e.g. FAT? or other IO issues?

**Comment by bf** [comment]
IO was over usb 3.0 HDD -> arch linux -> Ubuntu 14.04 VM. The disk is from Win7, I selected 10 shadow file systems to be analyzed by l2t. Is there a possibility that the VM goes to sleep and IO breaks?

**Comment by joachimmetz** [comment]
Is possible normally dmesg will show you such issues.

**Comment by joachimmetz** [comment]
No update from OP. Unable to solve.
