### ISSUE TITLE
Setup failed with ubuntu package

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1117]
**Plaso version:**

1.5.1-1ppa1~trusty 

**Operating system Plaso is running on:**

Ubuntu 14.04 trusty

**Installation method:**

http://ppa.launchpad.net/gift/stable/ubuntu trusty main 

**Description of problem:**

I cannot install plaso with the ubuntu package

**Debug output/tracebacks:**

python /usr/bin/log2timeline.py
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/extraction_tool.py", line 9, in <module>
    from plaso.engine import engine
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 11, in <module>
    from plaso.engine import knowledge_base
  File "/usr/lib/python2.7/dist-packages/plaso/engine/knowledge_base.py", line 12, in <module>
    from plaso.containers import artifacts
  File "/usr/lib/python2.7/dist-packages/plaso/containers/__init__.py", line 4, in <module>
    from plaso.containers import artifacts
  File "/usr/lib/python2.7/dist-packages/plaso/containers/artifacts.py", line 4, in <module>
    from plaso.containers import interface
  File "/usr/lib/python2.7/dist-packages/plaso/containers/interface.py", line 4, in <module>
    from efilter.protocols import structured
ImportError: cannot import name structured

**Comment by nwf9** [comment]
They don't miss any dependencies.

Thanks

**Comment by joachimmetz** [comment]
Which efilter version do you have installed?

**Comment by nwf9** [comment]
I'm using the release python-efilter/trusty,trusty,now 1.5-1ppa1~trusty

**Comment by joachimmetz** [comment]
I'm unable to reproduce your issue when I install plaso 1.5.1 on a Unbuntu 14.04 live CD following https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release

Can you double check if you installed efilter correctly, or if there is a second version installed e.g. via pip.

**Comment by nwf9** [comment]
Thanks joachim it works now.
