### ISSUE TITLE
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'

### ISSUE THREAD

**Issue by jasonblanks** [log2timeline/plaso#112]
Trying to submit a new output formatter for review, running through steps before posting and having issues with run_test.  using current vanilla source..  still doesn't pass.

```
./setup.py build 
 
running build_scripts
creating build/scripts-2.7
copying and adjusting plaso/frontend/pinfo.py -> build/scripts-2.7
copying and adjusting plaso/frontend/psort.py -> build/scripts-2.7
copying and adjusting plaso/frontend/preg.py -> build/scripts-2.7
copying and adjusting plaso/frontend/pshell.py -> build/scripts-2.7
copying and adjusting plaso/frontend/pprof.py -> build/scripts-2.7
copying and adjusting plaso/frontend/log2timeline.py -> build/scripts-2.7
copying and adjusting plaso/frontend/image_export.py -> build/scripts-2.7
copying and adjusting plaso/frontend/plasm.py -> build/scripts-2.7
error: file '/home/jason/Dev/plaso/plaso/tools/plaso_extract_search_history.py' does not exist

copied old plaso_extract_search_history.py, then build install:
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing plaso-1.2.1_20150129-py2.7.egg
Copying plaso-1.2.1_20150129-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding plaso 1.2.1-20150129 to easy-install.pth file
Installing plaso_extract_search_history.py script to /usr/local/bin
Installing plasm.py script to /usr/local/bin
Installing pprof.py script to /usr/local/bin
Installing image_export.py script to /usr/local/bin
Installing psort.py script to /usr/local/bin
Installing preg.py script to /usr/local/bin
Installing pshell.py script to /usr/local/bin
Installing pinfo.py script to /usr/local/bin
Installing log2timeline.py script to /usr/local/bin
Installed /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150129-py2.7.egg
Processing dependencies for plaso==1.2.1-20150129
Finished processing dependencies for plaso==1.2.1-20150129


check to make sure everything is pretty much they same ass the repo:
jason@Danzig:~/Dev/plaso/plaso$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	plaso/output/__init__.py.1
	plaso/output/json_flat_out.py
	plaso/output/json_flat_out_notthetword.py
	remove
	tools/plaso_extract_search_history.py

./run_test.py erros:
Test copying an UTF-16 byte stream to a string. ... ok
======================================================================
ERROR: testExtractionWorker (plaso.engine.worker_test.BaseEventExtractionWorkerTest)
Tests the extraction worker functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/worker_test.py", line 69, in testExtractionWorker
    extraction_worker.Run()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/worker.py", line 371, in Run
    self.ConsumeItems()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/queue.py", line 171, in ConsumeItems
    self._ConsumeItem(item)
  File "/home/jason/Dev/plaso/plaso/plaso/engine/worker.py", line 105, in _ConsumeItem
    self.ParseFileEntry(file_entry)
  File "/home/jason/Dev/plaso/plaso/plaso/engine/worker.py", line 334, in ParseFileEntry
    is_compressed_stream = self._ProcessCompressedStreamFile(file_entry)
  File "/home/jason/Dev/plaso/plaso/plaso/engine/worker.py", line 224, in _ProcessCompressedStreamFile
    file_entry.path_spec, resolver_context=self._resolver_context)
TypeError: GetCompressedStreamTypeIndicators() got an unexpected keyword argument 'resolver_context'
======================================================================
ERROR: testFileSystemCollection (plaso.engine.collector_test.CollectorTest)
Test collection on the file system.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector_test.py", line 137, in testFileSystemCollection
    test_collector.Collect()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector.py", line 212, in Collect
    if not path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testFileSystemWithFilterCollection (plaso.engine.collector_test.CollectorTest)
Test collection on the file system with a filter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector_test.py", line 168, in testFileSystemWithFilterCollection
    test_collector.Collect()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector.py", line 212, in Collect
    if not path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testImageCollection (plaso.engine.collector_test.CollectorTest)
Test collection on a storage media image file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector_test.py", line 238, in testImageCollection
    test_collector.Collect()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector.py", line 212, in Collect
    if not path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testImageWithFilterCollection (plaso.engine.collector_test.CollectorTest)
Test collection on a storage media image file with a filter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector_test.py", line 272, in testImageWithFilterCollection
    test_collector.Collect()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector.py", line 212, in Collect
    if not path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testEngine (plaso.engine.single_process_test.SingleProcessEngineTest)
Test the engine functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/engine/single_process_test.py", line 104, in testEngine
    test_engine.SetSource(source_path_spec, resolver_context=resolver_context)
  File "/home/jason/Dev/plaso/plaso/plaso/engine/engine.py", line 249, in SetSource
    if path_spec_factory.Factory.IsSystemLevelTypeIndicator(
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testProcessSourceExtractWithDateFilter (plaso.frontend.image_export_test.Log2TimelineFrontendTest)
Tests extract with file filter and date filter functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export_test.py", line 72, in testProcessSourceExtractWithDateFilter
    test_front_end.ProcessSource(options)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 585, in ProcessSource
    self._ExtractWithFilter(filter_file, options.path)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 416, in _ExtractWithFilter
    resolver_context=self._resolver_context)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 493, in _GetSourceFileSystemSearcher
    if path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testProcessSourceExtractWithExtensions (plaso.frontend.image_export_test.Log2TimelineFrontendTest)
Tests extract with extensions process source functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export_test.py", line 98, in testProcessSourceExtractWithExtensions
    test_front_end.ProcessSource(options)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 591, in ProcessSource
    self._ExtractWithExtensions(extensions, options.path)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 392, in _ExtractWithExtensions
    image_collector.Collect()
  File "/home/jason/Dev/plaso/plaso/plaso/engine/collector.py", line 212, in Collect
    if not path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testProcessSourceExtractWithFilter (plaso.frontend.image_export_test.Log2TimelineFrontendTest)
Tests extract with filter process source functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export_test.py", line 121, in testProcessSourceExtractWithFilter
    test_front_end.ProcessSource(options)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 585, in ProcessSource
    self._ExtractWithFilter(filter_file, options.path)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 416, in _ExtractWithFilter
    resolver_context=self._resolver_context)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/image_export.py", line 493, in _GetSourceFileSystemSearcher
    if path_spec_factory.Factory.IsSystemLevelTypeIndicator(type_indicator):
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
======================================================================
ERROR: testGetStorageInformation (plaso.frontend.log2timeline_test.Log2TimelineFrontendTest)
Tests the get storage information function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/log2timeline_test.py", line 60, in testGetStorageInformation
    test_front_end.ProcessSource(options)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/frontend.py", line 1589, in ProcessSource
    self._ProcessSourceMultiProcessMode(options)
  File "/home/jason/Dev/plaso/plaso/plaso/frontend/frontend.py", line 1125, in _ProcessSourceMultiProcessMode
    self.GetSourcePathSpec(), resolver_context=self._resolver_context)
  File "/home/jason/Dev/plaso/plaso/plaso/engine/engine.py", line 249, in SetSource
    if path_spec_factory.Factory.IsSystemLevelTypeIndicator(
AttributeError: type object 'Factory' has no attribute 'IsSystemLevelTypeIndicator'
----------------------------------------------------------------------
Ran 315 tests in 30.823s
FAILED (errors=10)
```

**Comment by joachimmetz** [comment]
Updating dfvfs should fix the issue. Regarding running the development release also see:
https://github.com/log2timeline/plaso/wiki/Development-release-Ubuntu

**Comment by joachimmetz** [comment]
> error: file '/home/jason/Dev/plaso/plaso/tools/plaso_extract_search_history.py' does not exist

update your plaso as well, this issue has been fixed

**Comment by jasonblanks** [comment]
Up and working again, thanks for setting me straight.
