### ISSUE TITLE
dfvfs_protobuf_serializer error

### ISSUE THREAD

**Issue by futex** [log2timeline/plaso#1124]
Plaso version: 1.5.1+dfsg-3

OS version: Debian SID

When i run log2timeline.py i have this error

`$ log2timeline.py 
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.1.post20160314', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 25, in <module>
    from plaso.frontend import log2timeline
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/plaso/frontend/log2timeline.py", line 15, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/plaso/output/__init__.py", line 12, in <module>
    from plaso.output import pstorage
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/plaso/output/pstorage.py", line 9, in <module>
    from plaso.storage import zip_file
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/plaso/storage/zip_file.py", line 74, in <module>
    from plaso.serializer import protobuf_serializer
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160314-py2.7.egg/plaso/serializer/protobuf_serializer.py", line 6, in <module>
    from dfvfs.serializer import protobuf_serializer as dfvfs_protobuf_serializer
ImportError: cannot import name protobuf_serializer
`
I have  python-dfvfs version: 20160918-1

I have another machine, witch kali linux it run perfectly and on it, i use plaso 1.5.1+dfsg-2 and the same version of python-dfvfs: 20160918-1

Any idea?

Thank

**Comment by Onager** [comment]
Per your traceback, you're not running the version of Plaso you think you are:
```File "/usr/local/lib/python2.7/dist-packages/plaso-**1.4.1.post20160314**-py2.7.egg```

1.4.1 won't work with the version of dfvfs you have installed.

**Comment by Onager** [comment]
No further news from reporter, and this look like an installation issue. Closing out.

**Comment by futex** [comment]
Sorry, yes, that's was an installation issue. thank
