### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AdoptTask'

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1130]
**Plaso version:**

Version 1.5.2_20170116

**Operating system Plaso is running on:**

Lubuntu 14.04 running on Vmware (Fusion)
**Installation method:**
Git clone https://github.com/log2timeline/plaso.git
ppa:gift/dev and Stable for Trusty.

**Description of problem:**
Attach a USB SSD drive onto the VM image containing L2T.
run log2timeline.py on a EnCase (E01) image from the SSD USB location.
Writing the plaso and temp drive locally in the VM image.
There are 6 CPU used for this VM image.

The source E01 image is captured using FTK imager (latest)
All settings at default (I belief compression is set default to 6)

It will stop after running for a while. Message:

Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
   self.run()
 File "/usr/lib/python2.7/threading.py", line 754, in run
   self.__target(*self.__args, **self.__kwargs)
 File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 494, in _StatusUpdateThreadMain
   self._CheckStatusWorkerProcess(pid)
 File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/engine.py", line 135, in _CheckStatusWorkerProcess
   self._UpdateProcessingStatus(pid, process_status)
 File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170116-py2.7.egg/plaso/multi_processing/task_engine.py", line 658, in _UpdateProcessingStatus
   task_manager.AdoptTask(task)
AttributeError: 'module' object has no attribute 'AdoptTask'

2017-01-17 15:40:50,003 [WARNING] (MainProcess) PID:3140 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 15:40:56,691 [WARNING] (MainProcess) PID:3140 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 15:41:03,227 [WARNING] (MainProcess) PID:3140 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 15:41:10,251 [WARNING] (MainProcess) PID:3140 <zeromq_queue> main_task_queue timeout waiting for a request.
2017-01-17 15:41:18,091 [WARNING] (MainProcess) PID:3140 <zeromq_queue> main_task_queue timeout waiting for a request.

Issues is reproducible in 2 different images from 2 systems using FTK imager.
disable zeromq does not work.

Warm Regards

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/3ef9e000b18c09347c13c555ac16657f232c3f96/plaso/multi_processing/task_engine.py#L658

```
 task_manager.AdoptTask(task)
```

should be
```
 self._task_manager.AdoptTask(task)
```

**Comment by joachimmetz** [comment]
I'll prep a patch later today
