### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'debug_output'

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1136]
```
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 678, in <module>
    if not Main():
  File "./tools/log2timeline.py", line 664, in Main
    tool.ProcessSources()
  File "./tools/log2timeline.py", line 575, in ProcessSources
    worker_memory_limit=self._worker_memory_limit)
  File "/tmp/test/plaso/frontend/extraction_frontend.py", line 379, in ProcessSources
    status_update_callback=status_update_callback)
  File "/tmp/test/plaso/engine/single_process.py", line 330, in ProcessSources
    storage_writer, filter_find_specs=filter_find_specs)
  File "/tmp/test/plaso/engine/single_process.py", line 147, in _ProcessSources
    extraction_worker, parser_mediator, event_source.path_spec)
  File "/tmp/test/plaso/engine/single_process.py", line 77, in _ProcessPathSpec
    if self._processing_configuration.debug_output:
AttributeError: 'NoneType' object has no attribute 'debug_output'
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/311560043/
