### ISSUE TITLE
Plaso package v1.5.1 for OS X: missing pefile module

### ISSUE THREAD

**Issue by texereda** [log2timeline/plaso#1147]
Plaso version: 1.5.1
OS: OS X 10.12.2
Installation method: Plaso Package 1.5.1 for OS X 10.12 downloaded from GitHub

**Description of problem:**
The aforementioned package is missing the pefile module, that was distributed together with previous releases of the package (eg: 1.5.0).

**Debug output/tracebacks:**
$ log2timeline.sh -h
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 9, in <module>
    from plaso.engine import engine
  File "/Library/Python/2.7/site-packages/plaso/engine/engine.py", line 14, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/macosx.py", line 11, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 33, in <module>
    from plaso.parsers import pe
  File "/Library/Python/2.7/site-packages/plaso/parsers/pe.py", line 3, in <module>
    import pefile
ImportError: No module named pefile

**Comment by joachimmetz** [comment]
You can get the missing package from:
https://github.com/log2timeline/l2tbinaries/tree/master/macosx

I'll have a look why this might be missing

**Comment by Onager** [comment]
Heimdall release include pefile, closing this out as obsolete.
