### ISSUE TITLE
psort.py error processing dump file

### ISSUE THREAD

**Issue by chrisprickaerts** [log2timeline/plaso#115]
I've installed latest version of plaso using Github. Depencies checked with dependency check  script (all ok).

When running psort.py on dump file I get the following error:

```
plaso@delorean://home/plaso$ psort.py test.dmp 
datetime,timestamp_desc,source,source_long,message,parser,display_name,tag,store_number,store_index
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150211', 'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150211-py2.7.egg/EGG-INFO/scripts/psort.py", line 752, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150211-py2.7.egg/EGG-INFO/scripts/psort.py", line 726, in Main
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150211-py2.7.egg/EGG-INFO/scripts/psort.py", line 348, in ParseStorage
    
AttributeError: 'PsortFrontend' object has no attribute '_ProcessOutput'
plaso@delorean://home/plaso$ 
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/202020043/

**Comment by joachimmetz** [comment]
Additionally Kristinn can you add a test for this code path in psort before closing out this issue.

**Comment by kiddinn** [comment]
pushed out a fix for this bug, c6fd483888870bdefea26dcefbad6ab99ca99704 

Not closing the issue until test coverage has been improved though

**Comment by kiddinn** [comment]
adding http://codereview.appspot.com/234230043

**Comment by kiddinn** [comment]
This has been fixed and tests added to catch this in the future, closing the issue.
