### ISSUE TITLE
KeyError: u'Already managing process: Worker_xxxx (PID: xxxx)

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1165]
**Plaso version:**

plaso-1.5.2.post20170206

**Operating system Plaso is running on:**

Ubuntu 16.04

**Installation method:**

Git clone method. Install all dependencies. Run Check_dependencies and Run-tests.

**Description of problem:**

Source is a MAC hdd image in ENCASE format.
After running for 2 days, all worker process were killed with the trackback error below.

**Debug output/tracebacks:**
```
Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170206-py2.7.egg/plaso/multi_processing/task_engine.py", line 487, in _StatusUpdateThreadMain
    self._CheckStatusWorkerProcess(pid)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170206-py2.7.egg/plaso/multi_processing/engine.py", line 159, in _CheckStatusWorkerProcess
    replacement_process = self._StartWorkerProcess(self._storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170206-py2.7.egg/plaso/multi_processing/task_engine.py", line 454, in _StartWorkerProcess
    self._RegisterProcess(process)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.5.2.post20170206-py2.7.egg/plaso/multi_processing/engine.py", line 241, in _RegisterProcess
    process.name, process.pid))
KeyError: u'Already managing process: Worker_30674 (PID: 10616)'
```

**Source data:**

It seems the mult-processing engines are not handing the work load well?

**Comment by joachimmetz** [comment]
> It seems the mult-processing engines are not handing the work load well?

seems more like an issue in the task manager

**Comment by Onager** [comment]
This codepath has been refactored in #1301 and #1254, so this specific situation is no longer relevant. I'm closing this out, but if you encounter further issues in processing, please open a new issue.
