### ISSUE TITLE
LookupError: unknown encoding: unicode

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#117]
I've encountered the following error when processing a disk image with the current stable version of plaso. The affected file doesn't sound too interesting, but I thought I'd let you know.

```
2015-02-16 10:01:43,853 [WARNING] (Worker_0  ) PID:3036 <worker> [openxml] Unable to process file: type: OS, location: /tmp/180gb.img
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x40200000
type: TSK, inode: 78473, location: /Program Files (x86)/Microsoft Office/Templates/1031/Access/Northwind.accdt
 with error: unknown encoding: unicode.
2015-02-16 10:01:43,854 [ERROR] (Worker_0  ) PID:3036 <worker> unknown encoding: unicode
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/oxml.py", line 138, in Parse
    root = ElementTree.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
LookupError: unknown encoding: unicode
```

**Comment by joachimmetz** [comment]
Thanks for letting us know. Not sure yet but this looks like it could be an issue in Python's xml.etree.

**Comment by joachimmetz** [comment]
Since this appears to be a template file any chance of sharing it with us?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/master/plaso/parsers/oxml.py#L116

**Comment by joachimmetz** [comment]
The following code snippet reproduces the error:
```
ElementTree.fromstring(
   '<?xml version="1.0" encoding="unicode"?><a></a>')
```

**Comment by joachimmetz** [comment]
Not a 1.4 blocker this is a very unique edge case

**Comment by joachimmetz** [comment]
Found a sample file

```
<?xml version="1.0" encoding="unicode"?>
<SAFREG><VENDOR ID="CN=Microsoft Corporation,L=Redmond,S=Washington,C=US" PUBLICKEY="" USERACCOUNT="SUPPORT_388945a0"><PRODUCT ID="Microsoft Remote Assistance" SECURITY="" NOTIFICATION=""><UI SKU="Professional_32" LANGUAGE="1033" VENDORNAME="Microsoft Corporation" PRODUCTNAME="Ask a friend to help" ICON="hcp://CN=Microsoft%20Corporation,L=Redmond,S=Washington,C=US/logo.gif" URL="hcp://CN=Microsoft%20Corporation,L=Redmond,S=Washington,C=US/Remote%20Assistance/Escalation/Common/rcscreen1.htm">Invite a friend to connect to your computer with Remote Assistance.</UI></PRODUCT><PRODUCT ID="PSS Online Assisted Support" SECURITY="" NOTIFICATION=""><UI SKU="Professional_32" LANGUAGE="1033" VENDORNAME="Microsoft Corporation" PRODUCTNAME="Get help from Microsoft" ICON="" URL="hcp://CN=Microsoft Corporation,L=Redmond,S=Washington,C=US/Connection.htm">Ask a support professional for help by using Microsoft Online Assisted Support.</UI></PRODUCT><PRODUCT ID="Windows_Newsgroups" SECURITY="" NOTIFICATION=""><UI SKU="Professional_32" LANGUAGE="1033" VENDORNAME="Microsoft Corporation" PRODUCTNAME="Go to a Windows Web site forum" ICON="" URL="hcp://system/blurbs/windows_newsgroups.htm">Communicate with other Windows users at the Windows newsgroups Web site.</UI></PRODUCT></VENDOR></SAFREG>
```

File seems to have a byte-order-mark

```
00000000  ff fe 3c 00 3f 00 78 00  6d 00 6c 00 20 00 76 00  |..<.?.x.m.l. .v.|
00000010  65 00 72 00 73 00 69 00  6f 00 6e 00 3d 00 22 00  |e.r.s.i.o.n.=.".|
```

**Comment by joachimmetz** [comment]
This is exception is now surfacing in the plist parser as well.

**Comment by joachimmetz** [comment]
Also seen in combination with UCS-2

```
00000000  ff fe 3c 00 3f 00 78 00  6d 00 6c 00 20 00 76 00  |..<.?.x.m.l. .v.|
00000010  65 00 72 00 73 00 69 00  6f 00 6e 00 3d 00 22 00  |e.r.s.i.o.n.=.".|
00000020  31 00 2e 00 30 00 22 00  20 00 65 00 6e 00 63 00  |1...0.". .e.n.c.|
00000030  6f 00 64 00 69 00 6e 00  67 00 3d 00 22 00 55 00  |o.d.i.n.g.=.".U.|
00000040  43 00 53 00 2d 00 32 00  22 00 20 00 73 00 74 00  |C.S.-.2.". .s.t.|
00000050  61 00 6e 00 64 00 61 00  6c 00 6f 00 6e 00 65 00  |a.n.d.a.l.o.n.e.|
00000060  3d 00 22 00 79 00 65 00  73 00 22 00 3f 00 3e 00  |=.".y.e.s.".?.>.|
00000070  0d 00 0a 00 3c 00 61 00  73 00 73 00 65 00 6d 00  |....<.a.s.s.e.m.|
```

**Comment by joachimmetz** [comment]
For now catch the LookupError. Possible ways to parse the XML

* re-encode to UTF-8 and update XML encoding hint
* enforce a comparable encoding e.g. UTF-16-LE for "unicode" with BOM
