### ISSUE TITLE
testExamineEventAndCompileReport failing

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1184]
**Plaso version:**

version 1.5.2_20170325

**Operating system Plaso is running on:**

Ubuntu 16.04

**Installation method:**

Github clone. All dependencies installed and tested with check_dependencies

**Description of problem:**

Error during "run_tests.py" command after "python setup.py install" of the new set of plaso files.

```
======================================================================
FAIL: testExamineEventAndCompileReport (analysis.tagging.TaggingAnalysisPluginTest)
Tests the ExamineEvent and CompileReport functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/plaso/tests/analysis/tagging.py", line 105, in testExamineEventAndCompileReport
    self.assertEqual(len(storage_writer.event_tags), 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
```

Please describe the source that is causing the issue.

**Comment by joachimmetz** [comment]
Can you provide us with which 3 tags are returned:
```
PYTHONPATH=. python tests/analysis/tagging.py
```

**Comment by madsumm** [comment]
```
root@ubuntu:~/plaso# PYTHONPATH=. python tests/analysis/tagging.py
FWARNING:root:Unable to build query from rule: "some text here" with error: Unexpected symbol 'text'. Were you looking for an operator?
WARNING:root:Unable to build query from rule: "some other invalid text." with error: Unexpected symbol 'other'. Were you looking for an operator?
.
======================================================================
FAIL: testExamineEventAndCompileReport (__main__.TaggingAnalysisPluginTest)
Tests the ExamineEvent and CompileReport functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/analysis/tagging.py", line 105, in testExamineEventAndCompileReport
    self.assertEqual(len(storage_writer.event_tags), 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 2 tests in 0.009s
```

**Comment by joachimmetz** [comment]
please add a `print(storage_writer.event_tags)` before `self.assertEqual(len(storage_writer.event_tags), 4)` to determine what is in the tags

**Comment by madsumm** [comment]
This is what I have :

```
testExamineEventAndCompileReport (analysis.tagging.TaggingAnalysisPluginTest)
Tests the ExamineEvent and CompileReport functions. ... [<plaso.containers.events.EventTag object at 0x7f74e40c8d50>, <plaso.containers.events.EventTag object at 0x7f74e7c763d0>, <plaso.containers.events.EventTag object at 0x7f74f7cad210>]
FAIL
testParseTaggingFile (analysis.tagging.TaggingAnalysisPluginTest)
Tests the _ParseTaggingFile function. ... WARNING:root:Unable to build query from rule: "some text here" with error: Unexpected symbol 'text'. Were you looking for an operator?
WARNING:root:Unable to build query from rule: "some other invalid text." with error: Unexpected symbol 'other'. Were you looking for an operator?
```

**Comment by joachimmetz** [comment]
@madsumm do you know if this issue still persists with the recent releases?

**Comment by joachimmetz** [comment]
Not a blocker for December release, so bumped release.

Unable to fix if issue cannot be reproduced.
So close out on next release if no additional input from OP.

**Comment by Onager** [comment]
No news on this, closing out.
