### ISSUE TITLE
flaky test: UnableToParseFile: [plist] File is not a plist file: Invalid plist file.

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#122]
One of the tests seem to be flaky after the recent dfVFS changes. I've only seen this happen on Ubuntu so far.

```
ERROR: testParse (plaso.parsers.plist_test.PlistParserTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "plaso/parsers/plist_test.py", line 23, in testParse
    event_queue_consumer = self._ParseFile(self._parser, test_file)
  File "plaso/parsers/test_lib.py", line 168, in _ParseFile
    parser_object, path_spec, knowledge_base_values=knowledge_base_values)
  File "plaso/parsers/test_lib.py", line 195, in _ParseFileByPathSpec
    parser_object.Parse(parser_mediator)
  File "plaso/parsers/plist.py", line 112, in Parse
    top_level_object = self.GetTopLevel(file_object, file_entry.name)
  File "plaso/parsers/plist.py", line 57, in GetTopLevel
    self.NAME, utils.GetUnicodeString(exception)))
UnableToParseFile: [plist] File is not a plist file: Invalid plist file.
```

**Comment by joachimmetz** [comment]
http://codereview.appspot.com/208760043
