### ISSUE TITLE
KeyError in CompleteTask

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1274]
```
  File "/opt/plaso/tools/log2timeline.py", line 70, in <module>
    if not Main():
  File "/opt/plaso/tools/log2timeline.py", line 56, in Main
    tool.ExtractEventsFromSources()
  File "/opt/plaso/plaso/cli/log2timeline_tool.py", line 712, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/opt/plaso/plaso/multi_processing/task_engine.py", line 797, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/opt/plaso/plaso/multi_processing/task_engine.py", line 310, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/opt/plaso/plaso/multi_processing/task_engine.py", line 403, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "/opt/plaso/plaso/multi_processing/task_engine.py", line 251, in _MergeTaskStorage
    self._task_manager.CompleteTask(self._merge_task)
  File "/opt/plaso/plaso/multi_processing/task_manager.py", line 161, in CompleteTask
    raise KeyError(u'Task {0:s} is not active'.format(task.identifier))
KeyError: u'Task 5464d76275e04e9d94b2123b044d2195 is not active'
```

**Comment by Onager** [comment]
Task seems to have been adopted:
`2017-07-06 15:35:40,325 [WARNING] (MainProcess) PID:7206 <task_manager> Previously abandoned task 5464d76275e04e9d94b2123b044d2195 is now pending merge`

**Comment by madsumm** [comment]
Had similar errors.

```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20170708', 'log2timeline.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 70, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 56, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/cli/log2timeline_tool.py", line 654, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/multi_processing/task_engine.py", line 793, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/multi_processing/task_engine.py", line 310, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/multi_processing/task_engine.py", line 401, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/multi_processing/task_engine.py", line 251, in _MergeTaskStorage
    self._task_manager.CompleteTask(self._merge_task)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20170708-py2.7.egg/plaso/multi_processing/task_manager.py", line 161, in CompleteTask
    raise KeyError(u'Task {0:s} is not active'.format(task.identifier))
KeyError: u'Task 2094b92cf545430591d87e71ba66fc81 is not active'
```

Process hung there and no longer moving forward.

**Comment by Onager** [comment]
Thanks for the report @madsumm - I've found a few more issues in the task manager, #1301 should resolve this, and related issues.
