### ISSUE TITLE
Issue with the custom destination parser and the parser_chain attribute

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#129]
Parsing the nfury SANS test image gets me now:

2015-03-03 10:05:04,324 [WARNING] (Worker_1  ) PID:3905 <worker> [custom_destinations] Unable to process file: type: OS, location: /PATH/test_images/win7-64-nfury-10.3.58.6/win7-64-nfury-c-drive/win7-64-nfury-c-drive.E01
type: EWF
type: TSK, inode: 63808, location: /Users/Administrator/AppData/Roaming/Microsoft/Windows/Recent/CustomDestinations/5afe4de1b92fc382.customDestinations-ms
 **with error: 'ParserMediator' object has no attribute 'parser_chain'.**

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150301-py2.7.egg/plaso/engine/worker.py", line 146, in _ParseFileEntryWithParser 
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150301-py2.7.egg/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150301-py2.7.egg/plaso/parsers/custom_destinations.py", line 63, in Parse
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150301-py2.7.egg/plaso/parsers/custom_destinations.py", line 153, in ParseFileObject
AttributeError: 'ParserMediator' object has no attribute 'parser_chain'

**Comment by kiddinn** [comment]
added the parser chain property to the parser mediator since this attribute is called by several parsers

**Comment by kiddinn** [comment]
added in code review: https://codereview.appspot.com/203470043/

**Comment by Onager** [comment]
Fixed in https://codereview.appspot.com/206420043/
