### ISSUE TITLE
win_firewall parser producing unserializable event

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1296]
Stack trace
```
2017-07-10 13:26:03,074 [ERROR] (Worker_06 ) PID:7191 <worker_process> ([], {u'tcp_ack': [([], {...})]}) is not JSON serializable
Traceback (most recent call last):
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/worker_process.py", line 216, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 769, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 592, in _ProcessFileEntry
    mediator, file_entry, data_stream.name)
  File "/home/onager/PycharmProjects/onager_plaso/tests/engine/bad_worker.py", line 33, in _ProcessFileEntryDataStream
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 688, in _ProcessFileEntryDataStream
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 304, in _ExtractContentFromDataStream
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 298, in ParseDataStream
    file_object=file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 269, in _ParserFileEntryWithParsers
    parser_mediator, parser, file_entry, file_object=file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 203, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/text_parser.py", line 519, in ParseFileObject
    parser_mediator, use_key, parsed_structure)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/winfirewall.py", line 206, in ParseRecord
    self._ParseLogLine(parser_mediator, structure)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/winfirewall.py", line 183, in _ParseLogLine
    parser_mediator.ProduceEventWithEventData(event, event_data)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/mediator.py", line 487, in ProduceEventWithEventData
    self.ProduceEvent(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/mediator.py", line 448, in ProduceEvent
    self._storage_writer.AddEvent(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/storage/interface.py", line 791, in AddEvent
    self._storage_file.AddEvent(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/storage/gzip_file.py", line 131, in AddEvent
    self._WriteAttributeContainer(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/storage/gzip_file.py", line 105, in _WriteAttributeContainer
    attribute_container)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/storage/interface.py", line 243, in _SerializeAttributeContainer
    attribute_container)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/serializer/json_serializer.py", line 418, in WriteSerialized
    return json.dumps(json_dict)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ([], {u'tcp_ack': [([], {...})]}) is not JSON serializable
```

**Comment by joachimmetz** [comment]
@Onager which test image was this?

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/c6a12c257d8f6271c882f214fa49790dbb8a302c
