### ISSUE TITLE
systemd_journal parser crashing

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1297]
```
2017-07-10 13:26:08,125 [WARNING] (Worker_01 ) PID:7109 <worker_process> Unhandled exception while processing path specification: OS:/home/onager/PycharmProjects/onager_plaso/test_data/systemd/journal/system@00053f9c9a4c1e0e-2e18a70e8b327fed.journalTILDE.

2017-07-10 13:26:08,125 [ERROR] (Worker_01 ) PID:7109 <worker_process> object offset should be after hash tables (4308912 < 2527472)
Traceback (most recent call last):
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/worker_process.py", line 216, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 769, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 592, in _ProcessFileEntry
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 688, in _ProcessFileEntryDataStream
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/worker.py", line 304, in _ExtractContentFromDataStream
    mediator, file_entry, data_stream_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 298, in ParseDataStream
    file_object=file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 269, in _ParserFileEntryWithParsers
    parser_mediator, parser, file_entry, file_object=file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/engine/extractors.py", line 203, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/systemd_journal.py", line 326, in ParseFileObject
    self._ParseJournalEntry(parser_mediator, file_object, entry_offset)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/parsers/systemd_journal.py", line 240, in _ParseJournalEntry
    offset, self._max_journal_file_offset))
```

**Comment by Onager** [comment]
@rgayon can you take a look at this one please?

**Comment by rgayon** [comment]
https://codereview.appspot.com/326030043  was commited and merged
