### ISSUE TITLE
add artifact based targeted collection

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1313]
- [x] image_export
- [x] log2timeline
- [x] psteal

**Comment by rgayon** [comment]
https://github.com/log2timeline/plaso/commit/e3271a4d6d34e8c3067cfeb204ac7e45a71ac788  broke windows end2end tests https://plaso-ci.log2timeline.net/jenkins/job/plaso-win64-e2e-student_pc1-vss/294/console
Probably due to `setattr(configuration_object, '_artifacts_registry', registry)` being removed in `plaso/cli/helpers/artifact_definitions.py`
Can you fix?

**Comment by Onager** [comment]
Also the linux tests:

```
/usr/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 68, in <module>
    if not Main():
  File "./tools/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/tmp/jenkins/workspace/plaso-linux-e2e-studentpc10/plaso/cli/log2timeline_tool.py", line 414, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/tmp/jenkins/workspace/plaso-linux-e2e-studentpc10/plaso/cli/extraction_tool.py", line 172, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/tmp/jenkins/workspace/plaso-linux-e2e-studentpc10/plaso/engine/engine.py", line 270, in PreprocessSources
    self.knowledge_base)
  File "/tmp/jenkins/workspace/plaso-linux-e2e-studentpc10/plaso/preprocessors/manager.py", line 276, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/tmp/jenkins/workspace/plaso-linux-e2e-studentpc10/plaso/preprocessors/manager.py", line 137, in CollectFromFileSystem
    artifact_definition = artifacts_registry.GetDefinitionByName(
AttributeError: 'NoneType' object has no attribute 'GetDefinitionByName'
```

**Comment by jnettesheim** [comment]
Will look at this right away

**Comment by jnettesheim** [comment]
https://github.com/log2timeline/plaso/pull/1985 should fix this, but I think that build is failing for unrelated pywfsi issue - https://github.com/log2timeline/plaso/issues/1987

**Comment by Onager** [comment]
Thanks for the work on this @jnettesheim - can this be closed now? It looks like there's no artifact support in psteal at the moment though, it's probably worth adding `--artifact_filters`, IMO.

**Comment by Onager** [comment]
I think it's better to have these split out to separate issues. I'll create some.

**Comment by joachimmetz** [comment]
This has been completed, closing issue.
