### ISSUE TITLE
Fix version dependency version issue

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1356]
https://travis-ci.org/log2timeline/plaso/jobs/265287533

```
Traceback (most recent call last):
  File "run_tests.py", line 24, in <module>
    if not dependency_helper.CheckTestDependencies():
  File "./utils/dependencies.py", line 324, in CheckTestDependencies
    if not self.CheckDependencies(verbose_output=verbose_output):
  File "./utils/dependencies.py", line 301, in CheckDependencies
    result, status_message = self._CheckPythonModule(dependency)
  File "./utils/dependencies.py", line 149, in _CheckPythonModule
    dependency.minimum_version, dependency.maximum_version)
  File "./utils/dependencies.py", line 191, in _CheckPythonModuleVersion
    map(int, self._VERSION_SPLIT_REGEX.split(module_version)))
ValueError: invalid literal for int() with base 10: 'b1'
Coverage.py warning: No data was collected. (no-data-collected)
```

**Comment by joachimmetz** [comment]
https://pypi.python.org/pypi/pyzmq

pyzmq 17.0.0b1

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/328270043

**Comment by joachimmetz** [comment]
Fixed tests, issue still persist in tools version check.
