### ISSUE TITLE
Psteal crashes in artifact definition

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1412]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

Developer installer

**Description of problem:**

Psteal crashes

**Debug output/tracebacks:**
```
python  ./tools/psteal.py --source ~/cases/greendale/registrar.dd -o dynamic -w /tmp/registrar.csv                                            master
The following partitions were found:
Identifier	Offset (in bytes)	Size (in bytes)
p1		1048576 (0x00100000)	100.0MiB / 104.9MB (104857600 B)
p2		105906176 (0x06500000)	24.9GiB / 26.7GB (26736590848 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
2


Source path	: /home/onager/cases/greendale/registrar.dd
Source type	: storage media image

Processing started.
Traceback (most recent call last):
  File "./tools/psteal.py", line 60, in <module>
    if not Main():
  File "./tools/psteal.py", line 45, in Main
    tool.ExtractEventsFromSources()
  File "/home/onager/code/upstream/plaso/plaso/cli/psteal_tool.py", line 339, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/home/onager/code/upstream/plaso/plaso/cli/psteal_tool.py", line 193, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/home/onager/code/upstream/plaso/plaso/engine/engine.py", line 177, in PreprocessSources
    artifacts_registry, file_system, mount_point, self.knowledge_base)
  File "/home/onager/code/upstream/plaso/plaso/preprocessors/manager.py", line 275, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/home/onager/code/upstream/plaso/plaso/preprocessors/manager.py", line 136, in CollectFromFileSystem
    artifact_definition = artifacts_registry.GetDefinitionByName(
AttributeError: 'NoneType' object has no attribute 'GetDefinitionByName'
```

**Source data:**

N/A

**Comment by Onager** [comment]
Fixed by b3aa979
