### ISSUE TITLE
Efilter: issue when upgrading from plaso 1.3 to 20171020 - dev

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1491]
```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 10, in <module>
    from plaso.cli import log2timeline_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 18, in <module>
    from plaso import filters  # pylint: disable=unused-import
  File "/usr/lib/python2.7/dist-packages/plaso/filters/__init__.py", line 4, in <module>
    from plaso.filters import dynamic_filter
  File "/usr/lib/python2.7/dist-packages/plaso/filters/dynamic_filter.py", line 6, in <module>
    from plaso.filters import event_filter
  File "/usr/lib/python2.7/dist-packages/plaso/filters/event_filter.py", line 6, in <module>
    from plaso.filters import interface
  File "/usr/lib/python2.7/dist-packages/plaso/filters/interface.py", line 9, in <module>
    from plaso.lib import pfilter
  File "/usr/lib/python2.7/dist-packages/plaso/lib/pfilter.py", line 16, in <module>
    from plaso.parsers import presets
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/__init__.py", line 4, in <module>
    from plaso.parsers import asl
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/asl.py", line 12, in <module>
    from plaso.containers import events
  File "/usr/lib/python2.7/dist-packages/plaso/containers/__init__.py", line 4, in <module>
    from plaso.containers import artifacts
  File "/usr/lib/python2.7/dist-packages/plaso/containers/artifacts.py", line 6, in <module>
    from plaso.containers import interface
  File "/usr/lib/python2.7/dist-packages/plaso/containers/interface.py", line 8, in <module>
    from efilter.protocols import structured
ImportError: cannot import name structured
```

**Comment by Onager** [comment]
This looks like the wrong version of efilter is installed. See https://github.com/log2timeline/plaso/issues/1117 for a similar issue.

**Comment by joachimmetz** [comment]
deployment issue with efilter installed in /usr/local/ outside dpkg.

**Comment by joachimmetz** [comment]
non-plaso issue marking as invalid
