### ISSUE TITLE
libsmdev issue: when upgrading from plaso 1.3 to 20171020 - dev

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1492]
```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 70, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 56, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 474, in ExtractEventsFromSources
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 1084, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 565, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 375, in _ScanNode
    source_path_spec = self.ScanForStorageMediaImage(scan_node.path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 624, in ScanForStorageMediaImage
    source_path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 338, in GetStorageMediaImageTypeIndicators
    resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 183, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 118, in OpenFileObject
    file_object.open(path_spec=path_spec_object)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_io.py", line 70, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/os_file_io.py", line 94, in _Open
    self._file_object.open(location, mode=mode)
IOError: pysmdev_handle_open: unable to open handle. libsmdev_handle_get_bytes_per_sector: unsupported platform. libsmdev_handle_open: unable to retrieve bytes per sector.
```

**Comment by joachimmetz** [comment]
likely related to https://github.com/libyal/libsmdev/commit/21b09a61ac46aa13c16dd5e7ad32ae5da80b10c4#diff-c80546e071ba288fb8d9190d3ec3c75a

**Comment by joachimmetz** [comment]
Pending new release https://github.com/libyal/libsmdev/releases/tag/20171112
