### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1495]
**Plaso version:**
log2timeline version 20171107

**Operating system Plaso is running on:**
Ubuntu 16.04.01 on VMWare Fusion on a MacBook.

**Installation method:**
Github Plaso and dependencies install directly.

**Description of problem:**
Running log2timeline.py against a mounted Encase volume (using ewfmount and mount commands),
after a while, it failed. Please see the filed message

I am running off SSD mounted as a SHARED folder into Fusion.
Also run another storage via Thunderbolt via Shared folder in Fusion, similar results.

All use to work before, but not the current version.

**Debug output/tracebacks:**

```Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20171107', 'log2timeline.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 66, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 52, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/cli/log2timeline_tool.py", line 597, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/multi_processing/task_engine.py", line 796, in ProcessSources
    storage_writer.WriteSessionCompletion(aborted=self._abort)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/storage/interface.py", line 1465, in WriteSessionCompletion
    self._storage_file.WriteSessionCompletion(session_completion)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/storage/zip_file.py", line 2723, in WriteSessionCompletion
    self.Flush()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/storage/zip_file.py", line 2386, in Flush
    self._WriteSerializedAttributeContainerList('event_source')
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/storage/zip_file.py", line 1941, in _WriteSerializedAttributeContainerList
    offset_table.Write()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171107-py2.7.egg/plaso/storage/zip_file.py", line 533, in Write
    self._zip_file.writestr(self._stream_name, table_data)
  File "/usr/lib/python2.7/zipfile.py", line 1249, in writestr
    self.fp.write(bytes)
IOError: [Errno 2] No such file or directory```

**Comment by Onager** [comment]
We've had a couple of reports now about strange thing happening when using shared folders and VMs. This one is also strange - the fix here might be more defensiveness around IO.

@madsumm were there any reports of workers dying during this session? Was the crash reproducible?

**Comment by joachimmetz** [comment]
ZIP-based storage is on the deprecation list: https://github.com/log2timeline/plaso/projects/1

@madsumm could you give the experimental SQLite-based storage a try.
```log2timeline.py --storage-format=sqlite ...`

**Comment by joachimmetz** [comment]
Closing this out for now.
