### ISSUE TITLE
log2timeline shouldn't raise when dfvfs can't stat a broken symlink

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1509]
**Plaso version:**

$ python tools/log2timeline.py --version
plaso - log2timeline version 20171118

**Operating system Plaso is running on:**

# uname -a
Linux vm-1510933385 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Installation method:**
Gift PPA packages

**Description of problem:**

When running log2timeline.py on a directory, log2timeline.py stops processing after it encounters a broken link, which happens quite often on a mounted filesystem

**Debug output/tracebacks:**
```
# log2timeline.py /home/romaing/fs.plaso /mnt/
Checking availability and versions of dependencies.
[OK]


Source path     : /mnt
Source type     : directory

Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 531, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 468, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 179, in PreprocessSources
    artifacts_registry, file_system, mount_point, self.knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 277, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 147, in CollectFromFileSystem
    knowledge_base, artifact_definition, searcher, file_system)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 83, in Collect
    for path_specification in searcher.Find(find_specs=[find_spec]):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 469, in Find
    for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 442, in _FindInFileEntry
    sub_file_entry, sub_find_specs, search_depth):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 440, in _FindInFileEntry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 244, in sub_file_entries
    yield OSFileEntry(self._resolver_context, self._file_system, path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 108, in __init__
    exception))
dfvfs.lib.errors.BackEndError: Unable to retrieve stat object with error: [Errno 2] No such file or directory: '/mnt/etc/favicon.png'

# ls -lah /mnt/etc/favicon.png 
lrwxrwxrwx. 1 root root 56 Nov 15 01:29 /mnt/etc/favicon.png -> /usr/share/icons/hicolor/16x16/apps/fedora-logo-icon.png
```

**Source data:**
Centos image

**Comment by joachimmetz** [comment]
@rgayon let's test with HEAD dfvfs and plaso
