### ISSUE TITLE
Tests failing with tzfile "magic" error

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1517]
```
Traceback (most recent call last):
  File "plaso/tests/cli/tools.py", line 149, in testListTimeZones
    cli_tool.ListTimeZones()
  File "./plaso/cli/tools.py", line 290, in ListTimeZones
    local_timezone = pytz.timezone(timezone_name)
  File "/usr/lib/python2.7/site-packages/pytz/__init__.py", line 170, in timezone
    _tzinfo_cache[zone] = build_tzinfo(zone, fp)
  File "/usr/lib/python2.7/site-packages/pytz/tzfile.py", line 33, in build_tzinfo
    assert magic == _byte_string('TZif'), 'Got magic %s' % repr(magic)
AssertionError: Got magic '# Al'
```

**Comment by joachimmetz** [comment]
Is tzfile.py not correctly following the TZif format?

**Comment by joachimmetz** [comment]
Could an old version of pytz be the culprit?
`pytz-2016.10-4.fc26`

**Comment by joachimmetz** [comment]
Marking as invalid, since it is not a plaso issue, updating to pytz-2017.3 solved the issue
