### ISSUE TITLE
 <engine> Unable to open file system with error: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1565]
**Plaso version:**

plaso - log2timeline version 20171218

**Operating system Plaso is running on:**

MacOSX 10.13.2

**Installation method:**

Download dependecies from L2Tbinaries for Mac and install.
Git pull from Plaso latest version. Check_dependencies and "PYTHONPATH=. python setup.py install"
run_test

**Description of problem:**

When running log2timeline to generate plaso file from set of encase images of 1 system, error occurs.
This issue is not seen in Linux Ubuntu install of the same version

The difference here is I inserted "--ob" offset bytes to direct the log2timeline to proper offset in the Encase image to extract the timeline info. Without OB, things seems to be working in MacOS version of it.

**Debug output/tracebacks:**

[ERROR] (MainProcess) PID:8967 <engine> Unable to open file system with error: [Errno 24] Too many open files: <Encasefile>
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
  File "/Library/Python/2.7/site-packages/plaso-20171218-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 68, in <module>
  File "/Library/Python/2.7/site-packages/plaso-20171218-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 54, in Main
  File "/Library/Python/2.7/site-packages/plaso-20171218-py2.7.egg/plaso/cli/log2timeline_tool.py", line 572, in ExtractEventsFromSources
  File "/Library/Python/2.7/site-packages/plaso-20171218-py2.7.egg/plaso/multi_processing/task_engine.py", line 734, in ProcessSources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 123, in cpu_count
OSError: [Errno 24] Too many open files

**Source data:**

**Comment by joachimmetz** [comment]
The likely cause is that there are many EWF (or as you refer to Encase) image segment files

a work around is to change the limit of number of file handles on your MacOS system

https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

a second work around is to use ewfmount, xmount, or equiv to mount the EWF image instead

**Comment by Onager** [comment]
See also #669 and #580

Perhaps its worth adding something to error message when this comes up, as this isn't a problem we can solve in Plaso.

**Comment by madsumm** [comment]
I had increased the max limit to 1,000,000 files. Same error...

**Comment by madsumm** [comment]
Good hint. Thanks.

On High Sierra, "ulimit -n 1000000" works.
use "ulimit -a" to check open files.

However this is NOT persistent. Its within the terminal session I think. But it works.
