### ISSUE TITLE
Maximum number of cached values reached

### ISSUE THREAD

**Issue by andreafabrizi** [log2timeline/plaso#165]
Just installed on my Ubuntu 14.04 following the procedure described in the wiki.
When I try to launch log2timeline I start getting a flow of errors like this:

```
2015-04-16 08:29:42,855 [WARNING] (Worker_1  ) PID:30746 <worker> [mcafee_protection] Unable to process file: type: OS, location: /mnt/disk/image.E01
type: EWF
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00007e00
type: TSK, inode: 19992, location: /Documents and Settings/Admin/Local Settings/Application Data/Mozilla/Firefox/Profiles/zh7qgqef.default/cache2/entries/E427DA38E1D00113B60686A3BD97CA4510242CBC
 with error: Maximum number of cached values reached..
2015-04-16 08:29:42,855 [WARNING] (MainProcess) PID:30660 <multi_process> Terminating worker: Worker_1 process: 30746
2015-04-16 08:29:42,856 [ERROR] (Worker_1  ) PID:30746 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/text_parser.py", line 456, in Parse
    file_object = file_entry.GetFileObject()
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 125, in GetFileObject
    self.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_io.py", line 79, in open
    self._resolver_context.CacheFileObject(path_spec, self)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/context.py", line 52, in CacheFileObject
    self._file_object_cache.CacheObject(path_spec.comparable, file_object)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.
```
Command line used: log2timeline.py -z CET output.bin /mnt/disk/image.E01

Thanks!

**Comment by kiddinn** [comment]
It looks like you are running an old version of log2timeline with a new version of dfvfs.

Can you tell me the version of each one?

**Comment by joachimmetz** [comment]
For context issue discussed here: https://github.com/log2timeline/dfvfs/issues/10

**Comment by joachimmetz** [comment]
No response from OP. Closing issue.
