### ISSUE TITLE
Crash when deserializing OS pathspec with data_stream

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1650]
Traceback:
```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 481, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 827, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 323, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 425, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 242, in _MergeTaskStorage
    maximum_number_of_containers=self._MAXIMUM_NUMBER_OF_CONTAINERS)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite_file.py", line 1137, in MergeAttributeContainers
    self._active_container_type, serialized_data)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 540, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_data)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 390, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 407, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 235, in _ConvertDictToObject
    attribute_value = cls._ConvertDictToObject(attribute_value)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 208, in _ConvertDictToObject
    return cls._ConvertDictToPathSpec(json_dict)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 323, in _ConvertDictToPathSpec
    json_dict['parent'] = cls._ConvertDictToPathSpec(json_dict['parent'])
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 329, in _ConvertDictToPathSpec
    type_indicator, **json_dict)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/factory.py", line 116, in NewPathSpec
    return path_spec_type(**kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/os_path_spec.py", line 45, in __init__
    super(OSPathSpec, self).__init__(location=location, parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/location_path_spec.py", line 29, in __init__
    super(LocationPathSpec, self).__init__(parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/path_spec.py", line 31, in __init__
    ', '.join(kwargs)))
ValueError: Unused keyword arguments: data_stream.
```

This might turn out to be a dfvfs issue, but it's not immediately clear to me how an OS pathspec would come to exist with a data_stream attribute.

**Comment by Onager** [comment]
Plaso version is 20171231

**Comment by Onager** [comment]
Problem is likely here: https://github.com/log2timeline/plaso/blob/master/plaso/engine/worker.py#L683

**Comment by Onager** [comment]
This is reproducible when running log2timeline.py on the test_data folder.

**Comment by Onager** [comment]
Possible fixes:

1. Add data_stream to OSFileEntry in dfvfs. Possibly, add this further up the dfvfs pathspec hierarchy.
1. Don't add a data_stream to the file_entry in the https://github.com/log2timeline/plaso/blob/master/plaso/engine/worker.py#L683 if it's the default.

Going to go with option 2 for the minute, as OS pathspecs don't really have explicit data streams, just the implicit default stream.
