### ISSUE TITLE
yaml as a requirement

### ISSUE THREAD

**Issue by Splinks** [log2timeline/plaso#166]
When trying to install the development version via setup.py install plaso looks for "yaml" from pypi (http://pypi.python.org/simple/yaml) which is now located here https://pypi.python.org/pypi/PyYAML.

It is impossible for me atleast to install beacuse the requirements need to be changed.

**Comment by joachimmetz** [comment]
I'll hardcode a check to convert yaml (the import naming) to PyYAML the pypi naming.

**Comment by Splinks** [comment]
Thanks, here's the two errors associated with it

Using setup.py install:

Installed /usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg
Processing dependencies for plaso==1.2.1-20150416
Searching for yaml>=3.10
Reading https://pypi.python.org/simple/yaml/
Couldn't find index page for 'yaml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/

After it breaking there you can still run psort.py for example and you get the following from python
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: yaml>=3.10

**Comment by joachimmetz** [comment]
CL pending: https://codereview.appspot.com/225610043/

**Comment by Splinks** [comment]
There's also this issue with log2timeline.py

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150416', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 470, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 433, in Main
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 214, in ParseArguments
    
  File "build/bdist.linux-x86_64/egg/plaso/cli/storage_media_tool.py", line 135, in AddStorageMediaImageOptions
ValueError: Unknown format code 's' for object of type 'int'

I get that error every single time i try to run it. I also opened this issue on timesketch (https://github.com/google/timesketch/issues/69) as my end-goal is to get the psort.py -o timesketch function to work

**Comment by joachimmetz** [comment]
Moving this to a separate issue.
