### ISSUE TITLE
log2timeline: formatting error

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#168]
Initially reported in: https://github.com/log2timeline/plaso/issues/166

There's also this issue with log2timeline.py

```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150416', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 470, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 433, in Main
    
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150416-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 214, in ParseArguments
    
  File "build/bdist.linux-x86_64/egg/plaso/cli/storage_media_tool.py", line 135, in AddStorageMediaImageOptions
ValueError: Unknown format code 's' for object of type 'int'
```

I get that error every single time i try to run it. I also opened this issue on timesketch (https://github.com/google/timesketch/issues/69) as my end-goal is to get the psort.py -o timesketch function to work

**Comment by joachimmetz** [comment]
CL: http://codereview.appspot.com/229060043
