### ISSUE TITLE
Traceback in Psort: Unhandled exception when missing event timestamp

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1680]
Git revision a8531ae485244bbf84708fa12d50fbeb861b1731
```
2018-01-23 07:14:34,978 [Warning] (MainProcess) PID:4922 <psort_tool> Appending to an already existing storage file.
Traceback (most recent call last):
  File "./tools/psort.py", line 68, in <module>
    if not Main():
  File "./tools/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/cli/psort_tool.py", line 550, in ProcessStorage
    profiling_configuration=configuration.profiling)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/multi_processing/psort.py", line 1026, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/multi_processing/psort.py", line 508, in _ExportEvents
    output_module, event, deduplicate_events=deduplicate_events)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/multi_processing/psort.py", line 418, in _ExportEvent
    output_module, deduplicate_events=deduplicate_events)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/multi_processing/psort.py", line 560, in _FlushExportBuffer
    output_module.WriteEvent(event)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/output/interface.py", line 73, in WriteEvent
    self.WriteEventBody(event)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/output/dynamic.py", line 404, in WriteEventBody
    event, field_name)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/output/dynamic.py", line 327, in GetFormattedField
    output_value = callback_function(event)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/output/dynamic.py", line 88, in _FormatDateTime
    raise_error=True)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/lib/timelib.py", line 275, in CopyToIsoFormat
    timestamp, timezone, raise_error=raise_error)
  File "/tmp/jenkins/workspace/plaso-e2e-registrar-sqlite/plaso/lib/timelib.py", line 247, in CopyToDatetime
    datetime_object += datetime.timedelta(microseconds=timestamp)
TypeError: unsupported type for timedelta microseconds component: NoneType
```

**Comment by Onager** [comment]
Pulling down the storage file, the event that triggered this traceback is from the chrome cache plugin - data_type is 'chrome:cache:entry'. Timestamp is set to None.

Two actions:

1. Investigate why the chrome cache parser is producing events with no timestamps
1. Improve error handling in the CopyToDatetime method, and code that calls that method

**Comment by Onager** [comment]
Interestingly, this error only seems to have been triggered on the end-to-end tests once. Perhaps the timestampless Chrome Cache event was triggered due to some transient issue.

Regarding Option 1 from https://github.com/log2timeline/plaso/issues/1680#issuecomment-360511810 however, timestamp is defaulted to None in a bunch of code, so it's worth handling that error as elegantly as possible, so that we don't bring down output altogether.

**Comment by Onager** [comment]
#1685 stopped psort crashing when this happens, but we still need to review the Chrome in the chrome cache parser, and possibly other places where timestamps might be None.

**Comment by Onager** [comment]
Closing, Chrome cache parser was substantially rewritten in https://github.com/log2timeline/plaso/commit/7278716cbe627984e4055a5669bf0f7ff63d00a5#diff-7a7c1432874162421c78d1bdea4c99c3 and the other fixes mentioned above also alleviate the risk of a crash that was the original trigger for this event.
