### ISSUE TITLE
OSX 10.13.2 post install failure

### ISSUE THREAD

**Issue by NetwarSystem** [log2timeline/plaso#1697]
I just installed to OSX 10.13.2 from the most recent package on here. A simple invocation without parameters causes the following error, both with the log2timeline.py and log2timeline.sh

> log2timeline.py 
> Traceback (most recent call last):
>   File "/usr/local/bin/log2timeline.py", line 12, in <module>
>     from plaso.cli import log2timeline_tool
>   File "/Library/Python/2.7/site-packages/plaso/cli/log2timeline_tool.py", line 20, in <module>
>     from plaso.cli import extraction_tool
>   File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 14, in <module>
>     from plaso import parsers  # pylint: disable=unused-import
>   File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 42, in <module>
>     from plaso.parsers import pe
>   File "/Library/Python/2.7/site-packages/plaso/parsers/pe.py", line 6, in <module>
>     import pefile
>   File "/Library/Python/2.7/site-packages/pefile.py", line 23, in <module>
>     from builtins import bytes
> ImportError: No module named builtins

I don't think I do anything super weird with Python - just install Tweepy and some other random stuff. But I did have to disable OSX System Integrity Protection a while back and fiddle with updating six, because it was causing problems. Maybe that is the root of this issue?

https://gist.github.com/NetwarSystem/012447fe37a563b4618151e6b55eeb83

So I edited /Library/Python/2.7/site-packages/pefile.py, commenting out all of the mentions of builtins, and now I can invoke the log2timeline command. I am going to play with it a bit and see if it actually runs.

Are any other OSX users seeing this problem?

**Comment by joachimmetz** [comment]
Could you indicate how you installed plaso and the dependencies.

**Comment by joachimmetz** [comment]
Based on your gist I assume you used pip. Which is **not** recommended without virtualenv. Also see:
https://github.com/log2timeline/plaso/wiki/Running-plaso-in-virtualenv

If you had used https://github.com/log2timeline/plaso/blob/master/requirements.txt you'd noticed that it also installs future on which pefile depends.

**Comment by Onager** [comment]
I read this as the install being from the .dmg from the last release:
> I just installed to OSX 10.13.2 from the most recent package on here

But this isn't clear. @NetwarSystem - please use the issue template next time, so we don't have to chase this up. Looking at the MacOS package, future does seem to be missing. I'll take a look.

**Comment by joachimmetz** [comment]
Assigning to @Onager seeing he's having a look.

**Comment by rgayon** [comment]
Once the .dmg was installed, I was able to run log2timline.py after running easy_install on packages:

- future
- urllib3
- chardet
- certifi
- idna

**Comment by Onager** [comment]
This needs a fix in l2tdevtools, to regenerate the macos install script when update-dependencies is run.

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/l2tdevtools/issues/321
