### ISSUE TITLE
psort  + filter error

### ISSUE THREAD

**Issue by TofBaasken** [log2timeline/plaso#171]
Hello , 

I have an issue when executing psort.py using a date filter. 

The error occurs when i execute :
psort.py -w test.csv dump.dump "date > '2014-05-31' and date < '2014-07-01'"

When executing the psort.py command without the filter everything executes correctly and the csv is created.

Error : 
```
[WARNING] Unable to automatically determine data location.
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150417', u'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/EGG-INFO/scripts/psort.py", line 253, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/EGG-INFO/scripts/psort.py", line 227, in Main
    counter = front_end.ProcessStorage(options)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/plaso/frontend/psort.py", line 315, in ProcessStorage
    self._output_format, output_mediator_object, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/plaso/output/manager.py", line 91, in NewOutputModule
    return output_class(output_mediator, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/plaso/output/dynamic.py", line 70, in __init__
    output_mediator, output_writer=output_writer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/plaso/output/interface.py", line 137, in __init__
    super(LinearOutputModule, self).__init__(output_mediator, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150417-py2.7.egg/plaso/output/interface.py", line 44, in __init__
    u', '.join(kwargs.keys())))
ValueError: Unused keyword arguments: field_filter.
```

I have pulled and installed the most recent git release 
 (git clone https://github.com/log2timeline/plaso.git )

So my current version is :  
log2timeline - psort version 1.2.1_20150417

when executing python utils/check_dependencies.py I receive
```
Checking availability and versions of plaso dependencies.
[OK]            bencode <br>
[OK]            binplist version: 0.1.4 <br>
[OK]            construct version: 2.5.2
[OK]            dateutil version: 1.5
[OK]            dfvfs version: 20150303
[OK]            dpkt version: 1.8
[OK]            google.protobuf
[OK]            hachoir_core version: 1.3.3
[OK]            hachoir_parser version: 1.3.4
[OK]            hachoir_metadata version: 1.3.3
[OK]            IPython version: 2.0.0
[OK]            psutil version: 1.2.1
[OK]            pyparsing version: 2.0.3
[OK]            pytz
[OK]            six version: 1.9.0
[OK]            sqlite3 version: 3.7.9
[OK]            yaml version: 3.11
[OK]            SleuthKit version: 4.1.3
[OK]            pytsk3 version: 20140506
[INFO]          libbde (pybde) version: 20150106 installed, version: 20150204 available.
[OK]            libesedb (pyesedb) version: 20150409
[OK]            libevt (pyevt) version: 20150105
[OK]            libevtx (pyevtx) version: 20150105
[INFO]          libewf (pyewf) version: 20140608 installed, version: 20150126 available.
[INFO]          libfwsi (pyfwsi) version: 20150105 installed, version: 20150124 available.
[OK]            liblnk (pylnk) version: 20150105
[OK]            libmsiecf (pymsiecf) version: 20150314
[OK]            libolecf (pyolecf) version: 20150413
[OK]            libqcow (pyqcow) version: 20150105
[OK]            libregf (pyregf) version: 20150315
[INFO]          libsigscan (pysigscan) version: 20150114 installed, version: 20150125 available.
[OK]            libsmdev (pysmdev) version: 20150105
[OK]            libsmraw (pysmraw) version: 20150105
[OK]            libvhdi (pyvhdi) version: 20150110
[OK]            libvmdk (pyvmdk) version: 20150325
[OK]            libvshadow (pyvshadow) version: 20150106
```
I have installed the GIFT/PPA and my ubuntu release is Ubuntu 12.04.5 LTS

Thank you in advance !

**Comment by joachimmetz** [comment]
Thanks for reporting looks like an issue introduced after the recent output modules refactor. I'll have a look. Bottom line more test coverage and better format documentation is needed there.

**Comment by joachimmetz** [comment]
Pending fix: https://codereview.appspot.com/230980043/

**Comment by joachimmetz** [comment]
Should be fixed now, reopen if not.

**Comment by TofBaasken** [comment]
Hey Joachim , 
The problem is fixed now ! Thanx a lot to you and everybody from the plaso team for donig a great job.
thx !
