### ISSUE TITLE
plaso tests fail on changes in dfdatetime 20180222 

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1728]
dfdatetime since 20180222 (pre-release) uses the number of seconds since Jan 1, 1970 as a floating point value to calculate the "plaso timestamp". This seems to allow for 1 - 2 microseconds difference in the timestamps. Have a closer look into this, possible options:

* revert back to previous Plaso timestamps methods
* change floating point value to contain number of microseconds?
* other

```
Traceback (most recent call last):
  File "plaso/tests/parsers/sqlite_plugins/chrome.py", line 217, in testProcess59
    self.CheckTimestamp(event.timestamp, '2018-01-21 14:08:52.037692')
  File "./tests/parsers/test_lib.py", line 215, in CheckTimestamp
    self.assertEqual(date_time, expected_date_time)
AssertionError: u'2018-01-21 14:08:52.037691' != u'2018-01-21 14:08:52.037692'
- 2018-01-21 14:08:52.037691
?                          ^
+ 2018-01-21 14:08:52.037692
```

To do:
* [x] https://codereview.appspot.com/339360043/
* [x] dfdatetime use round instead of ceil and remove quantize
  * https://codereview.appspot.com/335700043/
* [x] update plaso tests
  * https://codereview.appspot.com/335700043/

**Comment by joachimmetz** [comment]
dfdatetime-20180313 now uses Python decimal (fixed point instead of float)

Still some minor issues to sort out with dfvfs and dfdatetime-20180313

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/339360043/

**Comment by joachimmetz** [comment]
Flaky test remaining:

```
======================================================================
FAIL: testProcess (parsers.sqlite_plugins.safari.SafariHistoryPluginTest)
Tests the process function on a Safari History.db database file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/parsers/sqlite_plugins/safari.py", line 35, in testProcess
    self.CheckTimestamp(event.timestamp, '2017-11-09 21:24:28.829571')
  File "./tests/parsers/test_lib.py", line 215, in CheckTimestamp
    self.assertEqual(date_time, expected_date_time)
AssertionError: u'2017-11-09 21:24:29.000000' != u'2017-11-09 21:24:28.829571'
- 2017-11-09 21:24:29.000000
+ 2017-11-09 21:24:28.829571
```

**Comment by joachimmetz** [comment]
Issue with safari parser test is `'_main_'` instead of `'__main__'`

**Comment by joachimmetz** [comment]
fixed in https://github.com/log2timeline/plaso/commit/dc6fb8fa8bf5839d8e037b1295ec28b57d84a5bb
