### ISSUE TITLE
Failing test on Windows

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#173]
```
ERROR: testGetValue (plaso.preprocessors.windows_test.WindowsVersionTest)
Tests the GetValue function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\plaso\preprocessors\windows_test.py", line 230, in testGetValue
    plugin.Run(self._searcher, knowledge_base_object)
  File ".\plaso\preprocessors\interface.py", line 112, in Run
    value = self.GetValue(searcher, knowledge_base)
  File ".\plaso\preprocessors\windows.py", line 134, in GetValue
    file_location, exception))
PreProcessFail: Unable to open Registry file: /Windows/System32/config/SOFTWARE with error: pyregf_file_open_file_object: unable to open file. libregf_hive_bin_read_header: unable to read hive bin header data.
```

**Comment by joachimmetz** [comment]
File object returning the wrong size?

**Comment by joachimmetz** [comment]
Proposed fixes: http://codereview.appspot.com/230300043

**Comment by joachimmetz** [comment]
AppVeyor green again.
