### ISSUE TITLE
backports module missing, breaking tests

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1747]
```
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/plaso/plaso/cli/log2timeline_tool.py", line 20, in <module>
    from plaso.cli import extraction_tool
  File "/plaso/plaso/cli/extraction_tool.py", line 14, in <module>
    from plaso import parsers  # pylint: disable=unused-import
  File "/plaso/plaso/plaso-linux-e2e-registrar/plaso/parsers/__init__.py", line 55, in <module>
    from plaso.parsers import systemd_journal
  File "/plaso/plaso/parsers/systemd_journal.py", line 15, in <module>
    from backports import lzma
ImportError: No module named backports
```

I'm not sure if this is due to the GIFT package or plaso

**Comment by Onager** [comment]
This is an issue with the package, moving to https://github.com/log2timeline/l2tdevtools/issues/277
