### ISSUE TITLE
Failed to merge, high number of abandoned tasks, Python error

### ISSUE THREAD

**Issue by OliverHochgartz** [log2timeline/plaso#1761]
**Plaso version/ install method**
Plaso version 20180127
Cert.org ADIA updated with yum
ADIA is running with VirtualBox 5.2.8 with all extensions on the same level.
Virtual Box on Mac OS 10.12.6, 12k MB and 4 CPUs@100% assigned (max values), on a MacBook Pro 15" with i7
Data to analyze is on an external USB HDD. The raw image represents the C Drive (Bitlocker encrypted).

**Additional info**
Run since 15.3 17:05 with around 8 processes. Yesterday (17.3) plaso started to climb up to 11-13 processes and up to 250 items to merge and it always went down to 0/1 @ up to 13 processes. This morning 18.3 I saw the higher value of abandoned workers/ processes
XXXXXX, YYYYYY, ZZZZZZ are used to hide personal/ identifyable information.

**Command used**
```
log2timeline.py -z Europe/Zurich --status_view window —logfile /home/examiner/Documents/201803_c_Hoc.log /home/examiner/Documents/201803_c_Hoc.plaso /run/media/examiner/Evidence/Cases/2018_03/XXXXXX_sdd2_enc_C_Hoc.dd --credential recovery_password:XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX --partition all
```

**Plaso log** 
```
2018-03-15 12:04:22,506 [ERROR] (MainProcess) PID:4967 <engine> Unable to open file system with error: FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
2018-03-15 12:04:22,506 [INFO] (MainProcess) PID:4967 <engine> Preprocessing detected operating systems: Windows
2018-03-15 12:04:22,506 [INFO] (MainProcess) PID:4967 <extraction_tool> Parser filter expression changed to: win7
2018-03-15 12:04:23,869 [ERROR] (MainProcess) PID:4967 <extractors> Unable to open file entry with error: Unable to open file system with error: FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
2018-03-15 12:29:29,798 [WARNING] (MainProcess) PID:4967 <engine> Process: Worker_01 (PID: 5026) killed because it exceeded the memory limit: 2147483648.
2018-03-15 12:29:30,333 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_01 (PID: 5026) is not functioning correctly. Status code: killed.
2018-03-15 12:29:30,333 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 5026).
2018-03-15 12:29:30,334 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_01
2018-03-15 13:32:42,876 [WARNING] (MainProcess) PID:4967 <engine> Process: Worker_00 (PID: 5022) killed because it exceeded the memory limit: 2147483648.
2018-03-15 13:32:43,452 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_00 (PID: 5022) is not functioning correctly. Status code: killed.
2018-03-15 13:32:43,452 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 5022).
2018-03-15 13:32:43,453 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_00
2018-03-15 18:25:06,013 [WARNING] (MainProcess) PID:4967 <engine> Process: Worker_05 (PID: 7101) killed because it exceeded the memory limit: 2147483648.
2018-03-15 18:25:06,709 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_05 (PID: 7101) is not functioning correctly. Status code: killed.
2018-03-15 18:25:06,709 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 7101).
2018-03-15 18:25:06,709 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_05
2018-03-15 20:40:56,586 [WARNING] (MainProcess) PID:4967 <engine> Process: Worker_09 (PID: 2239) killed because it exceeded the memory limit: 2147483648.
2018-03-15 20:40:57,396 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_09 (PID: 2239) is not functioning correctly. Status code: killed.
2018-03-15 20:40:57,396 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 2239).
2018-03-15 20:40:57,396 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_09
2018-03-17 17:47:17,822 [WARNING] (MainProcess) PID:4967 <engine> Process: Worker_08 (PID: 11971) killed because it exceeded the memory limit: 2147483648.
2018-03-17 17:47:18,780 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_08 (PID: 11971) is not functioning correctly. Status code: killed.
2018-03-17 17:47:18,781 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 11971).
2018-03-17 17:47:18,781 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_08
2018-03-17 19:02:24,933 [ERROR] (MainProcess) PID:4967 <task_engine> Process Worker_17 (PID: 28409) has not reported activity within the timeout period.
2018-03-17 19:02:24,944 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_17 (PID: 28409) is not functioning correctly. Status code: not responding.
2018-03-17 19:02:24,944 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 28409).
2018-03-17 19:02:30,063 [WARNING] (MainProcess) PID:4967 <engine> Killing process: (PID: 28409).
2018-03-17 19:02:30,064 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_17
2018-03-17 19:03:29,767 [ERROR] (MainProcess) PID:4967 <task_engine> Process Worker_03 (PID: 7089) has not reported activity within the timeout period.
2018-03-17 19:03:29,767 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_03 (PID: 7089) is not functioning correctly. Status code: not responding.
2018-03-17 19:03:29,767 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 7089).
2018-03-17 19:03:35,220 [WARNING] (MainProcess) PID:4967 <engine> Killing process: (PID: 7089).
2018-03-17 19:03:35,221 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_03
2018-03-18 01:19:02,993 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_16 (PID: 28405) is not functioning correctly. Status code: killed.
2018-03-18 01:19:03,005 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 28405).
2018-03-18 01:19:03,008 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_16
2018-03-18 01:31:57,012 [ERROR] (MainProcess) PID:4967 <engine> Process Worker_21 (PID: 2148) is not functioning correctly. Status code: killed.
2018-03-18 01:31:57,013 [WARNING] (MainProcess) PID:4967 <engine> Terminating process: (PID: 2148).
2018-03-18 01:31:57,014 [INFO] (MainProcess) PID:4967 <engine> Starting replacement worker process for Worker_21
```

**Worker Logs**
_Worker 4 log_
```
2018-03-17 18:29:48,203 [WARNING] (Worker_04 ) PID:7097 <extractors> openxml unable to parse file: TSK:/Program Files (x86)/McAfee/Common Framework/naziplib.dll with error: Invalid offset value less than zero.
```

_Worker 6 log_
```
2018-03-16 18:51:59,375 [WARNING] (Worker_06 ) PID:11960 <extractors> chrome_cache unable to parse file: TSK:/Users/XXXXXX/Dropbox/Segeln Norwegen/Fotos AAAAAA with error: Not a regular file.
```

_Worker 10 log_
```
2018-03-16 18:52:04,494 [WARNING] (Worker_10 ) PID:2246 <extractors> chrome_cache unable to parse file: TSK:/Users/XXXXXX/Dropbox/Segeln Norwegen/Fotos ZZZZZZ with error: Not a regular file.
```

_Worker 11 log_
```
2018-03-16 18:52:00,082 [WARNING] (Worker_11 ) PID:2250 <extractors> chrome_cache unable to parse file: TSK:/Users/XXXXXX/Dropbox/Segeln Norwegen/Fotos YYYYYY with error: Not a regular file.
```

_Worker 13 log_
```
2018-03-16 04:08:03,324 [WARNING] (Worker_13 ) PID:12762 <extractors> chrome_cache unable to parse file: TSK:/Users/XXXXXX/Dropbox/Segeln Norwegen with error: Not a regular file.
```

_Worker 21 log_
```
2018-03-18 01:22:08,050 [WARNING] (Worker_21 ) PID:2148 <extractors> openxml unable to parse file: TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/XXXXXX_59432.jpg with error: Invalid offset value less than zero.
```

All other logs are empty

**Output on screen** waiting to die with memory allocation error
```
plaso - log2timeline version 20180127

Source path	: /run/media/examiner/Evidence/Cases/2018_03/k11911_sdd2_C_enc_Hoc.dd
Source type	: storage media image

Tasks:          Queued  Processing      To merge        Abandoned       Total
                10002   19              0               8               124509

Identifier      PID     Status          Memory          Sources         Events          File
Main            4967    running         1.4 GiB         330447 (0)      1911146 (0)     
Worker_00       5022    killed          0 B             42286 (0)       47874 (0)       
Worker_01       5026    killed          0 B             2280 (0)        490564 (4)      
Worker_02       5030    running         557.9 MiB       24716 (0)       100317 (0)      TSK:/Program Files (x86)/SAP/FrontEnd/SAPgui/Lang/settingLV.txt
Worker_03       7089    not responding  789.9 MiB       31683 (0)       80060 (0)       TSK:/Windows/Microsoft.NET/Framework/v4.0.30319/ngen_service.old.log
Worker_04       7097    running         1004.2 MiB      22287 (0)       289251 (0)      TSK:/Windows/winsxs/Manifests/x86_system.web_b03f5f7f11d50a3a_6.1.7601.22965_none_b4bb4d5fecca1310.manifest
Worker_05       7101    killed          0 B             2947 (0)        34648 (4)       
Worker_06       11960   extracting      805.3 MiB       20768 (0)       63194 (0)       TSK:/Windows/SysWOW64/CCM/Logs/ContentTransferManager.log
Worker_07       11966   running         939.8 MiB       20689 (0)       299369 (0)      TSK:/Windows/winsxs/Manifests/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.22965_none_f432e2a80e320b63.manifest
Worker_08       11971   killed          0 B             25199 (0)       47450 (4)       
Worker_09       2239    killed          0 B             813 (0)         1293 (0)        
Worker_10       2246    running         869.7 MiB       20259 (0)       43450 (0)       TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/XXXXXX_58954.jpg
Worker_11       2250    running         943.7 MiB       22906 (0)       46737 (0)       TSK:/Program Files (x86)/SAP/SapSetup/LOGs/NwSapSetup_01.log
Worker_12       12757   running         1.0 GiB         66394 (0)       201986 (0)      TSK:/Users/XXXXXX/AppData/Local/Dropbox/logs/1/1-59e5ee86
Worker_13       12762   running         948.6 MiB       12946 (0)       41582 (0)       TSK:/Users/XXXXXX/AppData/Roaming/Microsoft/SystemCertificates/My/Keys/XXXXXX
Worker_14       12767   running         967.3 MiB       13778 (0)       45383 (0)       TSK:/Windows/winsxs/Manifests/x86_system.web_b03f5f7f11d50a3a_6.1.7601.18758_none_cb87afa1d323e645.manifest
Worker_15       28400   running         1.7 GiB         38 (0)          4662 (0)        TSK:/Windows/winsxs/Manifests/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.18758_none_0aff44e9f48bde98.manifest
Worker_16       28405   killed          0 B             84 (0)          5195 (0)        
Worker_17       28409   not responding  1.5 GiB         7 (0)           2158 (0)        TSK:/Windows/Microsoft.NET/Framework64/v4.0.30319/ngen_service.old.log
Worker_18       2021    running         1.6 GiB         24 (0)          2005 (0)        TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/XXXXX_58953.jpg
Worker_19       2025    running         1.7 GiB         116 (0)         2857 (0)        TSK:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
Worker_20       2056    running         1.6 GiB         25 (0)          52315 (0)       TSK:/Users/XXXXXX/AppData/Roaming/Microsoft/SystemCertificates/My/Keys/XXXXXX
Worker_21       2148    running         1.7 GiB         15 (0)          1866 (0)        TSK:/Users/Public/Pictures/Pictures Gallery XXXXX/Normal_normal_normale_(4-3)/XXXXXX_9439.jpg
Worker_22       2150    running         1.7 GiB         48 (0)          3550 (0)        TSK:/Windows/servicing/Packages/Package_for_KB3019215_SP1~31bf3856ad364e35~amd64~~6.1.1.1.cat
Worker_23       2156    running         1.6 GiB         138 (0)         3049 (0)        TSK:/Program Files (x86)/SAP/FrontEnd/SAPgui/WCRContainer.dll
Worker_24       31528   running         1.5 GiB         0 (0)           266 (0)         TSK:/Windows/servicing/Packages/Package_for_KB3019215~31bf3856ad364e35~amd64~~6.1.1.1.mum
Worker_25       31538   running         1.5 GiB         0 (0)           296 (0)         TSK:/Windows/winsxs/Manifests/x86_netfx-aspnet_wp_exe_b03f5f7f11d50a3a_6.1.7601.22965_none_827c782d628f84dd.manifest
Worker_26       31542   running         1.5 GiB         0 (0)           287 (0)         TSK:/Windows/Installer/$PatchCache$/Managed/00004109110000000000000000F01FEC/14.0.4763/STSCOPY.DLL_0001.x86
```

```
plaso - log2timeline version 20180127

Source path	: /run/media/examiner/Evidence/Cases/2018_03/XXXXXX_sdd2_C_enc_Hoc.dd
Source type	: storage media image

Tasks:          Queued  Processing      To merge        Abandoned       Total
                10002   19              0               8               124509

Identifier      PID     Status          Memory          Sources         Events          File
Main            4967    running         1.4 GiB         330447 (0)      1911146 (0)     
Worker_00       5022    killed          0 B             42286 (0)       47874 (0)       
Worker_01       5026    killed          0 B             2280 (0)        490564 (4)      
Worker_02       5030    running         557.8 MiB       24716 (0)       100317 (0)      TSK:/Program Files (x86)/SAP/FrontEnd/SAPgui/Lang/settingLV.txt
Worker_03       7089    not responding  789.9 MiB       31683 (0)       80060 (0)       TSK:/Windows/Microsoft.NET/Framework/v4.0.30319/ngen_service.old.log
Worker_04       7097    running         1004.2 MiB      22287 (0)       289251 (0)      TSK:/Windows/winsxs/Manifests/x86_system.web_b03f5f7f11d50a3a_6.1.7601.22965_none_b4bb4d5fecca1310.manifest
Worker_05       7101    killed          0 B             2947 (0)        34648 (4)       
Worker_06       11960   extracting      805.3 MiB       20768 (0)       63194 (0)       TSK:/Windows/SysWOW64/CCM/Logs/ContentTransferManager.log
Worker_07       11966   running         939.7 MiB       20689 (0)       299369 (0)      TSK:/Windows/winsxs/Manifests/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.22965_none_f432e2a80e320b63.manifest
Worker_08       11971   killed          0 B             25199 (0)       47450 (4)       
Worker_09       2239    killed          0 B             813 (0)         1293 (0)        
Worker_10       2246    running         869.7 MiB       20259 (0)       43450 (0)       TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/XXXXXX_58954.jpg
Worker_11       2250    running         943.6 MiB       22906 (0)       46737 (0)       TSK:/Program Files (x86)/SAP/SapSetup/LOGs/NwSapSetup_01.log
Worker_12       12757   running         1.0 GiB         66394 (0)       201986 (0)      TSK:/Users/XXXXXX/AppData/Local/Dropbox/logs/1/1-59e5ee86
Worker_13       12762   running         948.5 MiB       12946 (0)       41582 (0)       TSK:/Users/XXXXXX/AppData/Roaming/Microsoft/SystemCertificates/My/Keys/XXXXXX
Worker_14       12767   running         967.2 MiB       13778 (0)       45383 (0)       TSK:/Windows/winsxs/Manifests/x86_system.web_b03f5f7f11d50a3a_6.1.7601.18758_none_cb87afa1d323e645.manifest
Worker_15       28400   running         1.7 GiB         38 (0)          4662 (0)        TSK:/Windows/winsxs/Manifests/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.18758_none_0aff44e9f48bde98.manifest
Worker_16       28405   killed          0 B             84 (0)          5195 (0)        
Worker_17       28409   not responding  1.5 GiB         7 (0)           2158 (0)        TSK:/Windows/Microsoft.NET/Framework64/v4.0.30319/ngen_service.old.log
Worker_18       2021    running         1.6 GiB         24 (0)          2005 (0)        TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/Zug_58953.jpg
Worker_19       2025    running         1.7 GiB         116 (0)         2857 (0)        TSK:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
Worker_20       2056    running         1.6 GiB         25 (0)          52315 (0)       TSK:/Users/XXXXXX/AppData/Roaming/Microsoft/SystemCertificates/My/Keys/XXXXXX
Worker_21       2148    running         1.7 GiB         15 (0)          1866 (0)        TSK:/Users/Public/Pictures/Pictures Gallery XXXXXX/Normal_normal_normale_(4-3)/Zug_9439.jpg
Worker_22       2150    running         1.7 GiB         48 (0)          3550 (0)        TSK:/Windows/servicing/Packages/Package_for_KB3019215_SP1~31bf3856ad364e35~amd64~~6.1.1.1.cat
Worker_23       2156    running         1.6 GiB         138 (0)         3049 (0)        TSK:/Program Files (x86)/SAP/FrontEnd/SAPgui/WCRContainer.dll
Worker_24       31528   running         1.5 GiB         0 (0)           266 (0)         TSK:/Windows/servicing/Packages/Package_for_KB3019215~31bf3856ad364e35~amd64~~6.1.1.1.mum
Worker_25       31538   running         1.5 GiB         0 (0)           296 (0)         TSK:/Windows/winsxs/Manifests/x86_netfx-aspnet_wp_exe_b03f5f7f11d50a3a_6.1.7601.22965_none_827c782d628f84dd.manifest
Worker_26       31542   running         1.5 GiB         0 (0)           287 (0)         TSK:/Windows/Installer/$PatchCache$/Managed/00004109110000000000000000F01FEC/14.0.4763/STSCOPY.DLL_0001.x86

Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/plaso/multi_processing/task_engine.py", line 544, in _StatusUpdateThreadMain
    self._CheckStatusWorkerProcess(pid)
  File "/usr/lib/python2.7/site-packages/plaso/multi_processing/engine.py", line 181, in _CheckStatusWorkerProcess
    process.name, self._storage_writer)
  File "/usr/lib/python2.7/site-packages/plaso/multi_processing/task_engine.py", line 490, in _StartWorkerProcess
    process.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

WARNING:root:Previously abandoned task 82a6dec9859644eb977c3e89140cdbdb is now pending merge
```

**Comment by joachimmetz** [comment]
Thx for the report, we'll have a closer look as soon as time permits

**Comment by Onager** [comment]
I'll take a look at this one, along with some other related issues

**Comment by OliverHochgartz** [comment]
Give me a kick if I can test something.

**Comment by joachimmetz** [comment]
High number of abandoned tasks further analyzed in https://github.com/log2timeline/plaso/issues/1832

**Comment by Onager** [comment]
Should have been fixed by the changes discussed in https://github.com/log2timeline/plaso/issues/1832 please reopen if issue resurfaces
