### ISSUE TITLE
Filestat test fails if path is too long

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#178]
If the filepath to the test is too long the filestat parser test will fail to complete.

    ======================================================================
    FAIL: testGzipFile (__main__.FileStatTest)
    Test a GZIP file.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "plaso/parsers/filestat_test.py", line 88, in testGzipFile
        self._TestGetMessageStrings(event_object, expected_msg, expected_msg_short)
      File "build/bdist.linux-x86_64/egg/plaso/parsers/test_lib.py", line 221, in _TestGetMessageStrings
        self.assertEqual(message_short, expected_message_short)
    AssertionError: u'/ENTER_A_LONG_PATH_HERE/plaso/test_data/syslo. [truncated]... != u'/ENTER_A_LONG_PATH_HERE/plaso/test_data/syslog [truncated]...
    - /ENTER_A_LONG_PATH_HERE/plaso/test_data/syslo...
    ?                                                                               ^^
    + /ENTER_A_LONG_PATH_HERE/plaso/test_data/syslog.gz
    ?                                                                              + ^^

**Comment by kiddinn** [comment]
CL in: http://codereview.appspot.com/231990043

**Comment by kiddinn** [comment]
fixed, works now
