### ISSUE TITLE
Flaky tests on AppVeyor

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1791]
Flaky test:

* https://ci.appveyor.com/project/joachimmetz/plaso/build/4254/job/ncex72e3uih58l7f
* https://ci.appveyor.com/project/joachimmetz/plaso/build/4363/job/axu5jpc9yro4fnlk

```
======================================================================
FAIL: testParseSystem (parsers.winreg.WinRegistryParserTest)
Tests the Parse function on a SYSTEM file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\plaso\tests\parsers\winreg.py", line 103, in testParseSystem
    self.assertEqual(parser_chains.get(parser_chain, 0), 831)
AssertionError: 832 != 831
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
https://ci.appveyor.com/project/joachimmetz/plaso/build/4497/job/6o294yetkc6v9gdj

```
======================================================================
FAIL: testProcess (parsers.esedb_plugins.srum.SystemResourceUsageMonitorESEDBPluginTest)
Tests the Process function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\plaso\tests\parsers\esedb_plugins\srum.py", line 36, in testProcess
    self.assertEqual(data_types['windows:srum:application_usage'], 16183)
AssertionError: 16184 != 16183
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
still happening from time to time
