### ISSUE TITLE
Flaky test on Travis-CI

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1800]
From: https://travis-ci.org/log2timeline/plaso/jobs/360552849#L3750

```
======================================================================
ERROR: testExtractEventsFromSourcePartitionedImage (cli.psteal_tool.PstealToolTest)
Tests the ExtractEventsFromSources function on a partitioned image.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/log2timeline/plaso/tests/cli/psteal_tool.py", line 287, in testExtractEventsFromSourcePartitionedImage
    test_tool.ExtractEventsFromSources()
  File "./plaso/cli/psteal_tool.py", line 344, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "./plaso/multi_processing/task_engine.py", line 783, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "./plaso/multi_processing/task_engine.py", line 315, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "./plaso/multi_processing/task_engine.py", line 412, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "./plaso/multi_processing/task_engine.py", line 234, in _MergeTaskStorage
    maximum_number_of_containers=self._MAXIMUM_NUMBER_OF_CONTAINERS)
  File "./plaso/storage/sqlite/merge_reader.py", line 132, in MergeAttributeContainers
    self._cursor.execute(self._TABLE_NAMES_QUERY)
OperationalError: disk I/O error
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
Not seen recently, closing issue.
