### ISSUE TITLE
Add elasticsearch-py to required / default set of dependencies

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1828]
pyelasticsearch missing from pyinstaller packaged version of plaso
https://github.com/log2timeline/plaso/issues/1825#issuecomment-382394231

and to improve timesketch / elastic output module test coverage

if needed consider moving to elasticsearch-py seeing pyelasticsearch depends on this and requires less sub dependencies (https://github.com/elastic/elasticsearch-py/blob/master/setup.py) 

* [x] changes to l2tdevtools
  * https://codereview.appspot.com/342050043/
* [x] elasticsearch-py added to GIFT ppa
* [x] elasticsearch-py added to GIFT copr
* [x] elasticsearch-py added to l2tbinaries (win32, win64, macos)
* [x] changes to plaso dependencies
  * https://codereview.appspot.com/343860043/

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/342050043/

**Comment by joachimmetz** [comment]
Apparently it is elasticsearch-py

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "plaso/tests/output/elastic.py", line 63, in testEventToDict
    output_mediator, '127.0.0.1', 9200, 1000, 'test', {}, 'test_type')
  File "./plaso/output/elastic.py", line 58, in __init__
    self._index = self._EnsureIndexExists(index_name, mapping)
  File "./plaso/output/elastic.py", line 100, in _EnsureIndexExists
    exception))
RuntimeError: Unable to connect to Elasticsearch backend with error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa0c0b307d0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa0c0b307d0>: Failed to establish a new connection: [Errno 111] Connection refused)
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/8cb20321dd5b517a1a7ced8f71006597cd58496a
