### ISSUE TITLE
Analysis plugins are broken in Psort

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#187]
Recent refactors have broken analysis plugins. Example crashes:

```
PYTHONPATH=. ./tools/psort.py --analysis list                                

******************************* Analysis Plugins *******************************
Traceback (most recent call last):
  File "./tools/psort.py", line 604, in <module>
    if not Main():
  File "./tools/psort.py", line 581, in Main
    tool.ListAnalysisPlugins()
  File "./tools/psort.py", line 297, in ListAnalysisPlugins
    analysis_plugins = self._front_end.GetAnalysisPlugins()
  File "/home/onager/code/plaso/plaso/frontend/psort.py", line 96, in GetAnalysisPlugins
    return analysis_manager.AnalysisPluginManager.ListAllPluginNames()
  File "/home/onager/code/plaso/plaso/analysis/manager.py", line 55, in ListAllPluginNames
    for cls_obj in interface.AnalysisPlugin.classes.itervalues():
AttributeError: type object 'AnalysisPlugin' has no attribute 'classes'
```

```
PYTHONPATH=. ./tools/psort.py --analysis windows_services ~/test.plaso 
Traceback (most recent call last):
  File "./tools/psort.py", line 604, in <module>
    if not Main():
  File "./tools/psort.py", line 576, in Main
    if not tool.ParseArguments():
  File "./tools/psort.py", line 457, in ParseArguments
    self.AddAnalysisPluginOptions(analysis_group, plugin_names)
  File "./tools/psort.py", line 178, in AddAnalysisPluginOptions
    analysis_plugins = self._front_end.GetAnalysisPlugins()
  File "/home/onager/code/plaso/plaso/frontend/psort.py", line 96, in GetAnalysisPlugins
    return analysis_manager.AnalysisPluginManager.ListAllPluginNames()
  File "/home/onager/code/plaso/plaso/analysis/manager.py", line 55, in ListAllPluginNames
    for cls_obj in interface.AnalysisPlugin.classes.itervalues():
AttributeError: type object 'AnalysisPlugin' has no attribute 'classes'
```

**Comment by Onager** [comment]
I'm working on fixing this, code should be ready for review soon.

**Comment by joachimmetz** [comment]
@Onager can this issue be closed?

**Comment by Onager** [comment]
Analysis plugins are not completing, so they're still broken (or have broken again).

More fixes to come.

**Comment by Onager** [comment]
Should be fixed now.
