### ISSUE TITLE
Linux pre-processor fails on mounted xfs directory of RHEL installation

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1894]
While testing plaso on RHEL

```
Traceback (most recent call last):
File "plaso/tools/log2timeline.py", line 68, in <module> if not Main():
File "plaso/tools/log2timeline.py", line 54, in Main tool.ExtractEventsFromSources()
File "/plaso/cli/log2timeline_tool.py", line 410, in ExtractEventsFromSources self._PreprocessSources(extraction_engine)
File "/plaso/cli/extraction_tool.py", line 171, in _PreprocessSources resolver_context=self._resolver_context)
File "/plaso/engine/engine.py", line 254, in PreprocessSources artifacts_registry, file_system, mount_point, self.knowledge_base)
File "/plaso/preprocessors/manager.py", line 276, in RunPlugins artifacts_registry, knowledge_base, searcher, file_system)
File "/plaso/preprocessors/manager.py", line 146, in CollectFromFileSystem knowledge_base, artifact_definition, searcher, file_system)
File "/plaso/preprocessors/interface.py", line 82, in Collect source.separator)
File "/plaso/preprocessors/interface.py", line 135, in _ParsePathSpecification self._ParseFileEntry(knowledge_base, file_entry)
File "/plaso/preprocessors/interface.py", line 171, in _ParseFileEntry self._ParseFileData(knowledge_base, file_object)
File "/plaso/preprocessors/linux.py", line 158, in _ParseFileData key, value = line.split('=') ValueError: need more than 1 value to unpack
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/master/plaso/preprocessors/linux.py#L158
https://github.com/ForensicArtifacts/artifacts/blob/dc90e1be0419cc6d55d4513e77c912be5ee607a0/data/linux.yaml#L420

Cause empty line in '/etc/os-release'
