### ISSUE TITLE
Task storage file missing on WSL1

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1897]
```
Traceback (most recent call last):
  File "/home/onager/code/onager_plaso/tools/log2timeline.py", line 68, in <module>
    if not Main():
  File "/home/onager/code/onager_plaso/tools/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/home/onager/code/onager_plaso/plaso/cli/log2timeline_tool.py", line 444, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/home/onager/code/onager_plaso/plaso/multi_processing/task_engine.py", line 827, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/home/onager/code/onager_plaso/plaso/multi_processing/task_engine.py", line 346, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/home/onager/code/onager_plaso/plaso/multi_processing/task_engine.py", line 452, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "/home/onager/code/onager_plaso/plaso/multi_processing/task_engine.py", line 214, in _MergeTaskStorage
    storage_writer.PrepareMergeTaskStorage(task)
  File "/home/onager/code/onager_plaso/plaso/storage/interface.py", line 1522, in PrepareMergeTaskStorage
    task.storage_file_size = os.path.getsize(processed_storage_file_path)
  File "/home/onager/virtualenvs/plaso27/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/tmp/tmpGiJtXB/processed/70c9485e423949faa8d1437266e5ad26.plaso'
```

After triggering an unhandled exception in a worker

**Comment by Onager** [comment]
I can only reproduce this on Windows Subsystem for Linux, so possibly this is something to do with the filesystem implementation there.

**Comment by Onager** [comment]
Only appears on WSL, so removing from milestone.

**Comment by joachimmetz** [comment]
AppVeyor now seems to support WSL https://www.appveyor.com/blog/

Let's add a WSL test case

**Comment by joachimmetz** [comment]
Closing issue since WSL1 has been superseded by WSL2
