### ISSUE TITLE
plaso-20180524-amd64 missing dfvfs/lib/cpio.yaml

### ISSUE THREAD

**Issue by johnmccash** [log2timeline/plaso#1917]
When running the new plaso-20180524-amd64 windows binary of log2timeline against an E01 image, I get the following errors:

log2timeline --workers 28 --status_view window plaso_dump image.E01
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]

Traceback (most recent call last):
  File "tools\log2timeline.py", line 68, in <module>
  File "tools\log2timeline.py", line 54, in Main
  File "plaso\cli\log2timeline_tool.py", line 368, in ExtractEventsFromSources
  File "plaso\cli\storage_media_tool.py", line 1099, in ScanSource
  File "site-packages\dfvfs\helpers\source_scanner.py", line 565, in Scan
  File "site-packages\dfvfs\helpers\source_scanner.py", line 366, in _ScanNode
  File "site-packages\dfvfs\resolver\resolver.py", line 55, in OpenFileEntry
  File "site-packages\dfvfs\resolver\resolver.py", line 158, in OpenFileSystem
  File "site-packages\dfvfs\resolver\resolver.py", line 35, in _GetResolverHelper
  File "C:\Projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\dfvfs\resolver_helpers\__init__.py", line 10, in <module>
  File "C:\Projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\dfvfs\resolver_helpers\cpio_resolver_helper.py", line 10, in <module>
  File "C:\Projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\dfvfs\vfs\cpio_file_system.py", line 6, in <module>
  File "C:\Projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\dfvfs\lib\cpio.py", line 43, in <module>
  File "site-packages\dfvfs\lib\cpio.py", line 52, in CPIOArchiveFile
IOError: [Errno 2] No such file or directory: u'D:\\DOWNLO~1\\PLASO-~1\\dfvfs\\lib\\cpio.yaml'
[11652] Failed to execute script log2timeline

**Comment by joachimmetz** [comment]
Looks like the yaml files are not copied by Pyinstaller. I'll update the build script.

**Comment by joachimmetz** [comment]
@johnmccash a work around is to copy the dfvfs and dfwinreg yaml files into the corresponding subdirectories within the Pyinstaller packaged directory.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/343260043/

**Comment by flyp3navy** [comment]
I have the same problem with Linux (centOS).  I just updated about 11:30 on 6/13/2018.  Is there a fix or will it fixed soon?

**Comment by joachimmetz** [comment]
Though this bug should not affect CentOS.

**Comment by flyp3navy** [comment]
This is what I received:
[root@ADIA QDE1_1_Timeline]# log2timeline.py plaso.dump /run/media/examiner/Proficiency_Test_2018/2018\ Proficiency/Images_1/HDD/e01_image.E01
Checking availability and versions of dependencies.
[OK]

Traceback (most recent call last):
  File "/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 368, in ExtractEventsFromSources
    scan_context = self.ScanSource(self._source_path)
  File "/usr/lib/python2.7/site-packages/plaso/cli/storage_media_tool.py", line 1099, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 565, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 366, in _ScanNode
    scan_node.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 55, in OpenFileEntry
    path_spec_object, resolver_context=resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 158, in OpenFileSystem
    resolver_helper = cls._GetResolverHelper(path_spec_object.type_indicator)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 35, in _GetResolverHelper
    from dfvfs.resolver_helpers import manager
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/__init__.py", line 10, in <module>
    from dfvfs.resolver_helpers import cpio_resolver_helper
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/cpio_resolver_helper.py", line 10, in <module>
    from dfvfs.vfs import cpio_file_system
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/cpio_file_system.py", line 6, in <module>
    from dfvfs.lib import cpio
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 43, in <module>
    class CPIOArchiveFile(data_format.DataFormat):
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 59, in CPIOArchiveFile
    'cpio_binary_big_endian_file_entry')
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1811, in CreateDataTypeMap
    return DataTypeMapFactory.CreateDataTypeMapByType(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1829, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1342, in __init__
    data_type_definition, self._data_type_map_cache)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1542, in _GetMemberDataTypeMaps
    member_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1829, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 217, in __init__
    self._operation = self._GetByteStreamOperation()
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 150, in _GetByteStreamOperation
    return byte_operations.StructOperation(format_string)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/byte_operations.py", line 55, in __init__
    'with error: {0!s}').format(exception))
dtfabric.errors.FormatError: Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode

**Comment by joachimmetz** [comment]
@flyp3navy this is a different issue
```
Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode
```

This looks like a version of the struct Python module that does not support a unicode argument.

What version of Python 2.7 do you run:
```
python -V
```

**Comment by flyp3navy** [comment]
I'm running the CERT ADIA linux appliance in a VM and updated it after installation.

**Comment by flyp3navy** [comment]
I see python 3.7.1 in some of the software descriptions.   Trying to find out more on this distro.

**Comment by joachimmetz** [comment]
Try:
```
python2.7 -V
```

**Comment by flyp3navy** [comment]
python -V
Python 2.7.5

**Comment by joachimmetz** [comment]
That is quite an old version. I've created: https://github.com/libyal/dtfabric/issues/11

One way would be to upgrade your version of Python.

I can try to build in a backward compatibility work around, but I would need to figure out when the struct module changed its interface first.

**Comment by flyp3navy** [comment]
What version do you recommend, the latest?

**Comment by joachimmetz** [comment]
the latest if 2.7 version if you can but definitely anything later that 2.7.10 due to fixes for SSL/TSL issues

**Comment by johnmccash** [comment]
Joachim - Per your comment "@johnmccash a work around is to copy the dfvfs and dfwinreg yaml files into the corresponding subdirectories within the Pyinstaller packaged directory." 

Where do I find those files to copy them?

**Comment by johnmccash** [comment]
Nevermind. Found them at https://raw.githubusercontent.com/log2timeline/dfwinreg/master/dfwinreg/dtfabric.yaml, https://raw.githubusercontent.com/log2timeline/dfvfs/master/dfvfs/lib/cpio.yaml,  and https://raw.githubusercontent.com/log2timeline/dfvfs/master/dfvfs/lib/gzipfile.yaml

Interesting;ly, I never got an error about that first one being missing. Seems to be working now though. Thanks

**Comment by joachimmetz** [comment]
Closing issue. Scripts updated to fix next deployment.
