### ISSUE TITLE
Issues with syslog parser (text parser really)

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#200]
While trying to parse the file npm-ls.html the following exception is raised:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 169, in _ParseFileEntryWithParser
        parser_object.UpdateChainAndParse(self._parser_mediator)
      File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
        self.Parse(parser_mediator, **kwargs)
      File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 256, in Parse
        self.ParseFileObject(parser_mediator, file_object, **kwargs)
      File "/usr/lib/python2.7/dist-packages/plaso/parsers/text_parser.py", line 160, in ParseFileObject
        _ = self.NextToken()
      File "/usr/lib/python2.7/dist-packages/plaso/lib/lexer.py", line 191, in NextToken
        return Lexer.NextToken(self)
      File "/usr/lib/python2.7/dist-packages/plaso/lib/lexer.py", line 99, in NextToken
        possible_next_state = callback(string=m.group(0), match=m)
      File "/usr/lib/python2.7/dist-packages/plaso/parsers/text_parser.py", line 119, in ParseIncomplete
        self.attributes['body'] += match.group(0)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

The "offending" line is:
    └─┬ init-package-json@0.0.4

**Comment by kiddinn** [comment]
http://codereview.appspot.com/242720043

**Comment by kiddinn** [comment]
issue fixed, the code now handles this case better
