### ISSUE TITLE
run_tests.py with arguments "lint_test" causes psteal test to fail

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2024]
run_tests.py lint_test causes psort test to fail

```
Tests the ParseArguments function ... usage: run_tests.py [-h] [-V] [--preferred_year YEAR] [--process_archives]
                    [--skip_compressed_streams] [--storage_file PATH]
                    [--partition PARTITION] [--partitions PARTITIONS]
                    [--offset IMAGE_OFFSET] [--ob IMAGE_OFFSET_BYTES]
                    [--sector_size BYTES_PER_SECTOR] [--credential TYPE:DATA]
                    [--status_view TYPE] [--source SOURCE] [--data PATH]
                    [--language LANGUAGE] [-z TIMEZONE] [-o FORMAT]
                    [-w OUTPUT_FILE] [--fields FIELDS]
                    [--additional_fields ADDITIONAL_FIELDS]
                    [--buffer_size BUFFER_SIZE] [--queue_size QUEUE_SIZE]
                    [--single_process] [--process_memory_limit SIZE]
                    [--temporary_directory DIRECTORY]
                    [--worker_memory_limit SIZE] [--workers WORKERS]
                    [--disable_zeromq]
run_tests.py: error: unrecognized arguments: lint_test
ERROR
```

```
======================================================================
ERROR: testParseArguments (cli.psteal_tool.PstealToolTest)
Tests the ParseArguments function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./plaso/tests/cli/psteal_tool.py", line 171, in testParseArguments
    result = test_tool.ParseArguments()
  File "./plaso/cli/psteal_tool.py", line 412, in ParseArguments
    options = argument_parser.parse_args()
  File "/usr/lib64/python2.7/argparse.py", line 1704, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib64/python2.7/argparse.py", line 2374, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib64/python2.7/argparse.py", line 2362, in exit
    _sys.exit(status)
SystemExit: 2
```

```
======================================================================
FAIL: testParseArguments (cli.image_export_tool.ImageExportToolTest)
Tests the ParseArguments function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./plaso/tests/cli/image_export_tool.py", line 218, in testParseArguments
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: testEmptyBufferedQueues (engine.zeromq_queue.ZeroMQQueuesTest)
Tests the Empty method for buffered queues.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./plaso/tests/engine/zeromq_queue.py", line 139, in testEmptyBufferedQueues
    queue.PushItem('item', block=False)
AssertionError: QueueFull not raised
```

**Comment by joachimmetz** [comment]
Closing, issue has not surfaced in a while.

**Comment by joachimmetz** [comment]
Change ParseArguments to take `list[str]` argument so `sys.argv` can be passed to ParseArguments

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2658
