### ISSUE TITLE
JSON serializer failing to encode binary data

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#205]
```
Process StorageWriter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/onager/code/plaso/plaso/multi_processing/multi_process.py", line 517, in run
    self._Main()
  File "/home/onager/code/plaso/plaso/multi_processing/multi_process.py", line 670, in _Main
    self._storage_writer.WriteEventObjects()
  File "/home/onager/code/plaso/plaso/lib/storage.py", line 1648, in WriteEventObjects
    self.ConsumeItems()
  File "/home/onager/code/plaso/plaso/engine/queue.py", line 132, in ConsumeItems
    self._ConsumeItem(item, **kwargs)
  File "/home/onager/code/plaso/plaso/lib/storage.py", line 1635, in _ConsumeItem
    self._storage_file.AddEventObject(event_object)
  File "/home/onager/code/plaso/plaso/lib/storage.py", line 1262, in AddEventObject
    event_object)
  File "/home/onager/code/plaso/plaso/serializer/json_serializer.py", line 688, in WriteSerialized
    return json.dumps(event_object, cls=_EventObjectJSONEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x90 in position 7: invalid start byte
```

**Comment by Onager** [comment]
This kills the StorageWriter too, and its not restarted

**Comment by joachimmetz** [comment]
Also see: https://github.com/log2timeline/plaso/issues/195 I'm closing that one in favor of this one.

**Comment by joachimmetz** [comment]
I can reproduce it by adding a binary string to the JSON test data.
```
u'binary_string': b'\xc0\x90\x90:event2',
```

**Comment by joachimmetz** [comment]
One of the culprits is registry_type in windows:registry:key_value

**Comment by Onager** [comment]
Investigation led to the PE parser as the source of at least these strings, specifically the section_names attribute:
 {section_names} ['.data\x00j\x08', '.xdata\x00\x90', '.text\x00\x8b\x06', '.extrel\x00', '.reloc\x00\x90']

It's possible that there are other parsers/plugins generating binaries attributes too.

**Comment by joachimmetz** [comment]
> It's possible that there are other parsers/plugins generating binaries attributes too.

Agree, doing a couple of clean up CLs to see if we can catch binary strings and maybe base64 encode them.
