### ISSUE TITLE
FAILURE: eleasticsearch version 6.2.0 is too recent, 5.5.1 or earlier required

### ISSUE THREAD

**Issue by dolhijn** [log2timeline/plaso#2053]
**Description of problem:**

I installed plaso to be able to use log2timeline in SIFT. I cant get past the FAILURE eleasticsearch version 6.2.0 is too recent, 5.5.1 or earlier required

I ran: sudo log2timeline.py --status_view window test.plaso /mnt/ewf_mount/ewf1 whcih triggers the failure: eleasticsearch version 6.2.0 is too recent, 5.5.1 or earlier required

I purged my current elasticsearch and installed 5.0.2 but the failure keeps popping up.

Here is the installed package info after purging
apt-cache policy elasticsearch
elasticsearch:
  Installed: (none)
  Candidate: 1.7.3+dfsg-3
  Version table:
     1.7.3+dfsg-3 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu xenial/universe i386 Packages

I downloaded and installed an earlier version 5.0.2 which triggers this

sudo ./elasticsearch-5.0.2/bin/elasticsearch
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

I am stuck. Anyone recognizes this failure?

**Comment by Onager** [comment]
@dolhijn if you don't need the elasticsearch output right now (and from the command you're running, that seems to be the case) just pass flag `--no-dependencies-check` per https://github.com/log2timeline/plaso/issues/1969

**Comment by Onager** [comment]
Fixed in  https://github.com/log2timeline/plaso/pull/2087
