### ISSUE TITLE
MemoryError during merge of worker thread that parsed large $MFT file

### ISSUE THREAD

**Issue by john-corcoran** [log2timeline/plaso#2074]
**Description of problem:**

log2timeline 20180630 crashes with a MemoryError when merging the worker thread that has parsed a large $MFT file (3.9GB). Parsing seemed to complete OK, but during the merge at the end of the run the main thread reached 4.0GB memory then crashed.

Host machine has 16GB of RAM, no other memory intensive processes running at the time, swap space enabled. Log2timeline was running in a Docker instance but no memory limits were placed on the instance.

Final progress update was as follows:

```
plaso - log2timeline version 20180630

Source path	: /input
Source type	: directory
Processing time	: 02:14:21

Tasks:          Queued  Processing      Merging         Abandoned       Total
                0       0               1               0               590

Identifier      PID     Status          Memory          Sources         Events          File
Main            8       running         4.0 GiB         590 (0)         1413948 (0)     [redacted]
Worker_00       15      idle            184.7 MiB       11 (0)          144143 (0)      OS:[redacted]
Worker_01       17      idle            219.1 MiB       18 (0)          308081 (0)      OS:[redacted]
Worker_02       21      idle            319.7 MiB       496 (0)         216208 (0)      OS:[redacted]
Worker_03       25      idle            496.0 MiB       1 (0)           41633372 (0)    OS:/input/$MFT
Worker_04       29      idle            219.7 MiB       10 (0)          289743 (0)      OS:[redacted]
Worker_05       33      idle            323.2 MiB       41 (0)          242232 (0)      OS:[redacted]
Worker_06       37      idle            322.2 MiB       12 (0)          213538 (0)      OS:[redacted]
```

**Command line and arguments:**

Instantiated via:
`docker run --rm -ti -v /local/output/folder:/output -v /local/input/folder:/input log2timeline --logfile /output/plaso.log /output/plaso.db /input/`

**Source data:**

Log2timeline was run against a folder containing artefacts manually extracted from a disk image - registry hives, event logs, $MFT file.

**Plaso version:**

20180630 using official Docker image (https://hub.docker.com/r/log2timeline/plaso/tags/) 

**Operating system Plaso is running on:**

Ubuntu 18.04

**Installation method:**

Installed via:
`docker pull log2timeline/plaso`

**Debug output/tracebacks:**
Traceback as follows:
```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 445, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 830, in ProcessSources
    storage_writer.WriteSessionCompletion(aborted=self._abort)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1714, in WriteSessionCompletion
    self._storage_file.WriteSessionCompletion(session_completion)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 1036, in WriteSessionCompletion
    self._WriteAttributeContainer(session_completion)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 368, in _WriteAttributeContainer
    serialized_data = self._SerializeAttributeContainer(attribute_container)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 438, in _SerializeAttributeContainer
    attribute_container)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 430, in WriteSerialized
    json_dict = cls.WriteSerializedDict(attribute_container)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 443, in WriteSerializedDict
    return cls._ConvertAttributeContainerToDict(attribute_container)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 68, in _ConvertAttributeContainerToDict
    attribute_value)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 107, in _ConvertAttributeValueToDict
    attribute_value = cls._ConvertCollectionsCounterToDict(attribute_value)
  File "/usr/lib/python2.7/dist-packages/plaso/serializer/json_serializer.py", line 154, in _ConvertCollectionsCounterToDict
    json_dict[attribute_name] = attribute_value
MemoryError
```

**Comment by joachimmetz** [comment]
log2timeline sets a process memory limit see command line option `--process_memory_limit`, which is 4GiB by default.

**Comment by john-corcoran** [comment]
Ah, thanks for the pointer and apologies for my ignorance!
