### ISSUE TITLE
bump required dtfabric version to 20180808

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/plaso#2104]
current dtfabric (dtfabric-20180707) version does not work with code in head, problem is fixed updating to latest release 20180808

Traceback (most recent call last):
  File "tools/log2timeline.py", line 68, in <module>
    if not Main():
  File "tools/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/code/plaso/plaso/cli/log2timeline_tool.py", line 434, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "/code/plaso/plaso/engine/single_process.py", line 246, in ProcessSources
    processing_configuration.parser_filter_expression))
  File "/code/plaso/plaso/engine/worker.py", line 97, in __init__
    parser_filter_expression=parser_filter_expression)
  File "/code/plaso/plaso/engine/extractors.py", line 62, in __init__
    parser_filter_expression=parser_filter_expression)
  File "/code/plaso/plaso/engine/extractors.py", line 134, in _InitializeParserObjects
    parser_filter_expression=parser_filter_expression)
  File "/code/plaso/plaso/parsers/manager.py", line 331, in GetParserObjects
    parser_object = parser_class()
  File "/code/plaso/plaso/parsers/dtfabric_parser.py", line 81, in __init__
    self._fabric = self._ReadDefinitionFile(self._DEFINITION_FILE)
  File "/code/plaso/plaso/parsers/dtfabric_parser.py", line 188, in _ReadDefinitionFile
    return dtfabric_fabric.DataTypeFabric(yaml_definition=definition)
  File "/plaso-venv/lib/python2.7/site-packages/dtfabric/runtime/fabric.py", line 26, in __init__
    definitions_reader.ReadFileObject(definitions_registry, file_object)
  File "/plaso-venv/lib/python2.7/site-packages/dtfabric/reader.py", line 947, in ReadFileObject
    raise errors.FormatError(error_message)
dtfabric.errors.FormatError: in: bsm_token_data_exec_args in: strings unsupported variable size element data type: cstring

**Comment by aguilajesus** [comment]
Thanks @joachimmetz
