### ISSUE TITLE
image_export.py broken - missing method

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#211]
```
./tools/image_export.py --help
Traceback (most recent call last):
  File "./tools/image_export.py", line 312, in <module>
    if not Main():
  File "./tools/image_export.py", line 281, in Main
    if not tool.ParseArguments():
  File "./tools/image_export.py", line 94, in ParseArguments
    self.AddDataOptions(argument_parser)
AttributeError: 'ImageExportTool' object has no attribute 'AddDataOptions'
```

**Comment by joachimmetz** [comment]
Note to self have a look at second invocation of: _ParseDataLocationOption
See: https://codereview.appspot.com/243840043

**Comment by Onager** [comment]
Fix is done, but some more refactor is indicated.

**Comment by joachimmetz** [comment]
http://codereview.appspot.com/244860043
