### ISSUE TITLE
AttributeError raised by pyopenssl when running log2timeline.py --version

### ISSUE THREAD

**Issue by supertimeline** [log2timeline/plaso#2110]
**Description of problem:**
I'm trying to use the latest version of plaso with any required dependencies, by getting taking an Ubuntu 16.04 LTS instance, installing SIFT from SANS, and then installing GiFT PPA, but I seem to be running into some issues (there's a good chance this is user error) 

**Installation method:**
Ubuntu 16.04 LTS
https://github.com/sans-dfir/sift-cli#installation
[GiFT PPA][https://launchpad.net/~gift] stable track

When I try just checking the version of my plaso instance, I get the following error:

```
# log2timeline.py --version
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 16, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "/usr/lib/python2.7/dist-packages/plaso/output/__init__.py", line 5, in <module>
    from plaso.output import elastic
  File "/usr/lib/python2.7/dist-packages/plaso/output/elastic.py", line 8, in <module>
    from plaso.output import shared_elastic
  File "/usr/lib/python2.7/dist-packages/plaso/output/shared_elastic.py", line 11, in <module>
    import elasticsearch
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/__init__.py", line 17, in <module>
    from .client import Elasticsearch
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 5, in <module>
    from ..transport import Transport
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 5, in <module>
    from .connection import Urllib3HttpConnection
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/__init__.py", line 2, in <module>
    from .http_requests import RequestsHttpConnection
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

Any help will be greatly appreciated.

**Comment by supertimeline** [comment]
Python 2.7.12
OpenSSL 1.0.2g 1 Mar 2016 (I opened Python, typed import ssl, then ssl.OPENSSL_Version to get this)

For ElasticSearch, I see the following when I run sudo apt list --installed | grep -i elasticsearch:

elasticsearch/now 2.3.3 all [installed,local]
python-elasticsearch/xenial,xenial,now 6.3.1-1ppa1~xenial all [installed,automatic]
python-elasticsearch5/now 5.5.4ppa1~xenial all [installed,upgradable to: 5.5.5-1ppa1~xenial]

Thanks for your help.

**Comment by joachimmetz** [comment]
Thx, looking at it again (later on the day) this could be an issue with pyopenssl itself.

```
 File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

I websearched the last part of the backtrace and found some references that point out the same issue in a different context:
https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init

**Comment by ajgerth** [comment]
I had the same issue with trying to execute "log2timeilne.py" after a fresh SIFT install on 16.04.5.

I fixed the issue by using pip to uninstall and then install pyopenssl - as noted in Joachim's reference.

pip uninstall pyopenssl
pip install pyopenssl

**Comment by Onager** [comment]
@supertimeline - did @ajgerth's fix work for you?

**Comment by Onager** [comment]
No reply from reporter, closing.
