### ISSUE TITLE
More misc unicode issues

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#212]
```
/home/onager/plaso/plaso/parsers/text_parser.py:700: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if line in [u'\n', u'\r\n']:
```

```
/home/onager/plaso/plaso/parsers/opera.py", line 173, in _ReadRecord
    if len(title_raw) == max_line_length and not title_raw.endswith(u'\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 300: ordinal not in range(128)
```

```
/home/onager/plaso/plaso/parsers/sqlite.py:160: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if data != self.MAGIC:
```

```
/home/onager/plaso/plaso/parsers/winfirewall.py:175: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if line == u'#Version: 1.5':
```

```
/home/onager/plaso/plaso/parsers/iis.py", line 150, in VerifyStructure
    if self.SIGNATURE in line:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by Onager** [comment]
All known unicode errors are fixed at the moment, but I suspect there are others, so leaving this open for now.

**Comment by jpoling-dswrx** [comment]
Uncertain if this fits in here or not... 

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
  File "/usr/lib/python2.7/site-packages/plaso/parsers/text_parser.py", line 1029, in Parse
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/file_entry.py", line 125, in GetFileObject
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
  File "/usr/lib/python2.7/site-packages/dfvfs/file_io/file_io.py", line 75, in open
  File "/usr/lib/python2.7/site-packages/dfvfs/file_io/os_file_io.py", line 73, in _Open
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 268: ordinal not in range(128)

Seems to occur when parsing any file names with special (non-ascii) characters. Is this an issue to be concerned with? If so, how do we go about fixing (or has it already been fixed)?

**Comment by joachimmetz** [comment]
> Seems to occur when parsing any file names with special (non-ascii) characters.

As you can see [here](https://github.com/log2timeline/dfvfs/blob/master/dfvfs/file_io/os_file_io.py#L73) this code path is only taken if the file is inaccessible. Can you:

* Indicate which version of dfvfs you are using?
* If it it correct that you open the files under Python.

**Comment by jpoling-dswrx** [comment]
What's the easiest way to find out which version of dfvfs I'm using?

**Comment by joachimmetz** [comment]
``
python
```
```
import dfvfs
print(dfvfs.__version__)
```

or via plaso's `./utils/check_dependencies.py`

**Comment by Onager** [comment]
@jpoling-dswrx Any update on this?

**Comment by jpoling-dswrx** [comment]
Apologies for the delay. I no longer have access to the item to test that it can be opened by Python but the dfvfs version is "20150414".

**Comment by Onager** [comment]
I'm going to close this bug out, and we can reopen other bugs for specific unicode issues.

**Comment by apapadop** [comment]
$ psort.py -o L2tcsv analyst018.db -w l2t_csv
[INFO] Data files will be loaded from /usr/share/plaso by default.
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 646, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 641, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 593, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 236, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 422, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 241, in __exit__
    self.End()
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 233, in End
    self.Flush()
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 198, in Flush
    self._output_module.WriteEvent(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/interface.py", line 55, in WriteEvent
    self.WriteEventBody(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/l2t_csv.py", line 77, in WriteEventBody
    event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/output/mediator.py", line 122, in GetFormattedMessages
    return event_formatter.GetMessages(self._formatter_mediator, event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/formatters/msiecf.py", line 34, in GetMessages
    event_values[u'http_headers'] = http_headers.replace(u'\r\n', u' - ')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 115: ordinal not in range(128)

$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dfvfs
>>> print(dfvfs.__version__)
20150708

plaso - log2timeline version 1.3.0

Please let me know what other info I can provide to help debug this.

**Comment by joachimmetz** [comment]
Moving to: https://github.com/log2timeline/plaso/issues/287 since this issue was closed.
