### ISSUE TITLE
Winevtx formatter fails with Python 3 and a None attribute

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2128]
**Description of problem:**
Running end-to-end tests with Python 3 fails due to an attribute being None.

**Command line and arguments:**

N/A

**Source data:**

End to end test data

**Plaso version:**

HEAD

**Operating system Plaso is running on:**

N/A

**Installation method:**

Development install

**Debug output/tracebacks:**
```
2018-09-05 14:54:26,927 [WARNING] (MainProcess) PID:233136 <psort_tool> Appending to an already existing storage file.
Traceback (most recent call last):
  File "/home/onager/PycharmProjects/onager_plaso/tools/psort.py", line 68, in <module>
    if not Main():
  File "/home/onager/PycharmProjects/onager_plaso/tools/psort.py", line 54, in Main
    tool.ProcessStorage()
  File "/home/onager/PycharmProjects/onager_plaso/plaso/cli/psort_tool.py", line 561, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/psort.py", line 1021, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/psort.py", line 538, in _ExportEvents
    output_module, event, deduplicate_events=deduplicate_events)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/psort.py", line 435, in _ExportEvent
    output_module, deduplicate_events=deduplicate_events)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/multi_processing/psort.py", line 607, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/interface.py", line 118, in WriteEventMACBGroup
    self.WriteEvent(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/interface.py", line 73, in WriteEvent
    self.WriteEventBody(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/dynamic.py", line 392, in WriteEventBody
    event, field_name)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/dynamic.py", line 315, in GetFormattedField
    output_value = callback_function(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/dynamic.py", line 145, in _FormatMessage
    message, _ = self._output_mediator.GetFormattedMessages(event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/output/mediator.py", line 90, in GetFormattedMessages
    return event_formatter.GetMessages(self._formatter_mediator, event)
  File "/home/onager/PycharmProjects/onager_plaso/plaso/formatters/winevtx.py", line 63, in GetMessages
    event_values['message_string'] = message_string.format(*strings)
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by Onager** [comment]
2 possible solutions:

- Change winevt-rc.db database to use string conversion ({0!s} vs. {0:s{)
- Remove/replace none value in attributes passed to format()

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/390405509e02c2c427dc55a0b1be54149b9e13c8
