### ISSUE TITLE
Error processing compressed file

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#215]
```
[ERROR] An uncaught exception occurred: Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid code lengths set..
Traceback (most recent call last):
  File "/home/onager/plaso/plaso/frontend/extraction_frontend.py", line 470, in _ProcessSourceSingleProcessMode
    storage_serializer_format=storage_serializer_format)
  File "/home/onager/plaso/plaso/frontend/extraction_frontend.py", line 536, in _StartSingleThread
    hasher_names_string=hasher_names_string)
  File "/home/onager/plaso/plaso/engine/single_process.py", line 214, in ProcessSource
    extraction_worker.Run()
  File "/home/onager/plaso/plaso/engine/worker.py", line 517, in Run
    self.ConsumeItems()
  File "/home/onager/plaso/plaso/engine/queue.py", line 132, in ConsumeItems
    self._ConsumeItem(item, **kwargs)
  File "/home/onager/plaso/plaso/engine/worker.py", line 101, in _ConsumeItem
    digests = self.HashFileEntry(file_entry)
  File "/home/onager/plaso/plaso/engine/worker.py", line 387, in HashFileEntry
    data = file_object.read(self.DEFAULT_HASH_READ_SIZE)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 103, in read
    return self._file_object.read(size)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 216, in read
    self._AlignUncompressedDataOffset(self._current_offset)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 145, in _AlignUncompressedDataOffset
    read_count = self._ReadCompressedData(self._COMPRESSED_DATA_BUFFER_SIZE)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 173, in _ReadCompressedData
    self._decompressor.Decompress(self._compressed_data))
  File "/usr/lib/python2.7/dist-packages/dfvfs/compression/zlib_decompressor.py", line 50, in Decompress
    u'{0:s}.').format(exception))
BackEndError: Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid code lengths set.
```

**Comment by joachimmetz** [comment]
Can you trace the file for me so I can have a closer look.

**Comment by Onager** [comment]
Yep, will do - this is a placeholder to remind me.

**Comment by joachimmetz** [comment]
Similar issue by running log2timeline on the firefox cache files in test_data.

**Comment by Onager** [comment]
This is still a live issue - worker crashes on firefox cache test files.

**Comment by joachimmetz** [comment]
Firefox test fail because the cache files are not well formed gzip file. I opt to implement: 
https://codereview.appspot.com/284870043/. Also see: https://github.com/log2timeline/plaso/issues/467

**Comment by joachimmetz** [comment]
@Onager with https://github.com/log2timeline/plaso/commit/bfe70efc7530321f7be6d6c9ade5348e6b84037e is this still an issue?

**Comment by Onager** [comment]
Fixed now.
