### ISSUE TITLE
Yaml files missing in macOS installer

### ISSUE THREAD

**Issue by pjbakker** [log2timeline/plaso#2150]
**Description of problem:**

Cannot run plaso latest release on macOS.

The *.yaml files don't seem to be present in _/Library/Python/2.7/site-packages/plaso/parsers/_.

```
$ ls /Library/Python/2.7/site-packages/plaso/parsers/*.yaml
ls: /Library/Python/2.7/site-packages/plaso/parsers/*.yaml: No such file or directory
```

**Command line and arguments:**

```
$ log2timeline.sh test.plaso Chrome_History_File
Checking availability and versions of dependencies.
[OPTIONAL]	missing: hachoir_core.
[OPTIONAL]	missing: hachoir_metadata.
[OPTIONAL]	missing: hachoir_parser.
[OPTIONAL]	missing: lzma.
[OK]


Source path	: Chrome_History_file
Source type	: single file
Processing time	: 00:00:00

Processing started.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/local/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/Library/Python/2.7/site-packages/plaso/cli/log2timeline_tool.py", line 434, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "/Library/Python/2.7/site-packages/plaso/engine/single_process.py", line 246, in ProcessSources
    processing_configuration.parser_filter_expression))
  File "/Library/Python/2.7/site-packages/plaso/engine/worker.py", line 97, in __init__
    parser_filter_expression=parser_filter_expression)
  File "/Library/Python/2.7/site-packages/plaso/engine/extractors.py", line 62, in __init__
    parser_filter_expression=parser_filter_expression)
  File "/Library/Python/2.7/site-packages/plaso/engine/extractors.py", line 134, in _InitializeParserObjects
    parser_filter_expression=parser_filter_expression)
  File "/Library/Python/2.7/site-packages/plaso/parsers/manager.py", line 331, in GetParserObjects
    parser_object = parser_class()
  File "/Library/Python/2.7/site-packages/plaso/parsers/dtfabric_parser.py", line 81, in __init__
    self._fabric = self._ReadDefinitionFile(self._DEFINITION_FILE)
  File "/Library/Python/2.7/site-packages/plaso/parsers/dtfabric_parser.py", line 185, in _ReadDefinitionFile
    with open(path, 'rb') as file_object:
IOError: [Errno 2] No such file or directory: u'/Library/Python/2.7/site-packages/plaso/parsers/recycler.yaml'
```

**Plaso version:**

20180818

**Operating system Plaso is running on:**

macOS High Sierra 10.13.6

**Installation method:**

I just downloaded plaso-20180818-macos-10.13.dmg from the Releases, opened it and ran `sudo sh install.sh`

Ran without issues.

**Comment by joachimmetz** [comment]
Thx, for the report we'll have a look as soon as time permits.

**Comment by grayfold3d** [comment]
Just noticed this is an issue in the packaged Windows release as well.  Extracting the files from source resolves the issue.

**Comment by joachimmetz** [comment]
Reopen if issue still persist but if I recall correctly this issue has been addressed.

**Comment by kudkud** [comment]
@grayfold3d 
I'm using 20180930 as well and still get this issue..

IOError: [Errno 2] No such file or directory: u'/home/xxxxxx/.local/lib/python2.7/site-packages/plaso/parsers/esedb_plugins/types.yaml'

Which commands did you use to solve this problem?
What is the source?

Sorry, I'm new to this field and not very familar with plaso yet, but it's a useful tool and I want to learn more about it!

Kind regards

**Comment by joachimmetz** [comment]
@kudkud please use the latest release https://github.com/log2timeline/plaso/releases/tag/20190131
