### ISSUE TITLE
log2timeline.py ImportError: No module named dtfabric

### ISSUE THREAD

**Issue by Lyro1** [log2timeline/plaso#2165]
**Description of problem:**

When I run `log2timeline.py`, I get the following error (see Command line and arguments). I am thinking that it might be an installation error, but when I want to check my dependencies, I get another error:

```
$ python check_dependencies.py 
Traceback (most recent call last):
  File "check_dependencies.py", line 13, in <module>
    import utils.dependencies  # pylint: disable=wrong-import-position
ImportError: No module named utils.dependencies
```
I verified that the utils/dependencies.py exists.

**Command line and arguments:**

```
$ log2timeline.py
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20180930', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/cli/log2timeline_tool.py", line 19, in <module>
    from plaso.cli import extraction_tool
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/cli/extraction_tool.py", line 12, in <module>
    from plaso import parsers  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/parsers/__init__.py", line 4, in <module>
    from plaso.parsers import asl
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/parsers/asl.py", line 13, in <module>
    from plaso.parsers import dtfabric_parser
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/parsers/dtfabric_parser.py", line 9, in <module>
    from dtfabric import errors as dtfabric_errors
ImportError: No module named dtfabric
```

**Plaso version:**

20180930

**Operating system Plaso is running on:**

Debian 9

**Installation method:**

Installed from the package *plaso-20180930.tar.gz*, extracting the content and running
```
$ sudo python setup.py build
$ sudo python setup.py install
```

**Comment by joachimmetz** [comment]
`ImportError: No module named utils.dependencies`

Make sure to run the script as following:

```
PYTHONPATH=. python utils/check_dependencies.py 
```

**Comment by joachimmetz** [comment]
```
sudo python setup.py install
```

Plaso its setup.py does not install dependencies, use requirements.txt for that.

**Comment by joachimmetz** [comment]
`ImportError: No module named dtfabric`

Yes this looks like a missing dependency

**Comment by Lyro1** [comment]
> `ImportError: No module named utils.dependencies`
> 
> Make sure to run the script as following:
> 
> ```
> PYTHONPATH=. python utils/check_dependencies.py 
> ```

I tried your command and I get the same error

**Comment by joachimmetz** [comment]
is these a `utils/dependencies.py` and `utils/__init__.py` ? You'll likely need the full source for this script to work.

**Comment by Lyro1** [comment]
> is these a `utils/dependencies.py` and `utils/__init__.py` ? You'll likely need the full source for this script to work.

I just have a those files in the 20180930 release:
```
$ ls utils
check_dependencies.py dependencies.py
```
I will try to clone the entire repository.

**Comment by joachimmetz** [comment]
Do you have `utils/__init__.py` in utils?

**Comment by Lyro1** [comment]
> Do you have `utils/__init__.py` in utils?

No it is not provided in the plaso-20180930 package

**Comment by joachimmetz** [comment]
@Lyro1 If you don't have utils/__init__.py in utils you can create an empty file with that name.

**Comment by Lyro1** [comment]
> @Lyro1 If you don't have utils/**init**.py in utils you can create an empty file with that name.

Thanks, it seems that it fixed all my issues.
