### ISSUE TITLE
log2timeline.py 20180930 fails to run with python3.6 during vss selection

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#2167]
**Description of problem:**

log2timeline.py fails to run with python3.6 during vss selection (runs fine with python2.7 or when there are no vss)

**Command line and arguments:**

```
# log2timeline.py foo.plaso /media/FOR508/win7-32-nromanoff-10.3.58.5/win7-32-nromanoff-c-drive/win7-32-nromanoff-c-drive.E01 
Checking availability and versions of dependencies.
[OPTIONAL]      missing: hachoir_core.
[OPTIONAL]      missing: hachoir_metadata.
[OPTIONAL]      missing: hachoir_parser.
[OK]

The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2012-03-15T23:12:03.571361+00:00
vss2            2012-03-23T04:00:15.654095+00:00
vss3            2012-03-31T04:00:12.210449+00:00
vss4            2012-04-04T20:05:02.502647+00:00

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores can
be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can
also be combined as: 1,3..5. The first store is 1. All stores can be defined
as "all". If no stores are specified none will be processed. You
can abort with Ctrl^C.

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/local/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/log2timeline_tool.py", line 369, in ExtractEventsFromSources
    scan_context = self.ScanSource(self._source_path)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 1114, in ScanSource
    self._ScanVolume(scan_context, scan_node)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 846, in _ScanVolume
    scan_context, sub_scan_node, selected_vss_stores)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 882, in _ScanVolumeScanNode
    self._ScanVolumeScanNodeVSS(scan_node, selected_vss_stores)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 949, in _ScanVolumeScanNodeVSS
    volume_scan_node, vss_stores=self._vss_stores)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 284, in _GetVSSStoreIdentifiers
    volume_system, volume_identifiers, vss_stores=vss_stores)
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/storage_media_tool.py", line 794, in _PromptUserForVSSStoreIdentifiers
    selected_vss_stores = self._input_reader.Read()
  File "/usr/local/lib/python3.6/site-packages/plaso/cli/tools.py", line 459, in Read
    string = encoded_string.decode(self._encoding, errors=self._errors)
AttributeError: 'str' object has no attribute 'decode'
```

**Plaso version:**

20180930

**Comment by Onager** [comment]
Thanks for the report, I'll take a look at this.
