### ISSUE TITLE
sqlite3.DatabaseError: file is encrypted or is not a database (log2timeline 20180930)

### ISSUE THREAD

**Issue by koenigswinter** [log2timeline/plaso#2181]
**Description of problem:**

log2timeline 20180930 throws error "sqlite3.DatabaseError: file is encrypted or is not a database" on Ubuntu 16.04.5

**Command line and arguments:**

log2timeline.py --parsers linux plasofile.plaso rawimage.raw

**Plaso version:**

plaso - log2timeline version 20180930

**Operating system Plaso is running on:**

Ubuntu 16.04.5

**Installation method:**

1st uninstalled  [GiFT PPA][https://launchpad.net/~gift] stable track
then
git pull https://github.com/log2timeline/plaso.git
Dependencies: python utils/check_dependencies.py [OK]

**Debug output/tracebacks:**

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20180930', 'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/cli/log2timeline_tool.py", line 445, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/multi_processing/task_engine.py", line 819, in ProcessSources
    storage_writer.Open()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/storage/interface.py", line 1508, in Open
    self._storage_file.Open(path=self._output_file, read_only=False)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/storage/sqlite/sqlite_file.py", line 963, in Open
    self._cursor.execute('PRAGMA synchronous=OFF')
**sqlite3.DatabaseError: file is encrypted or is not a database**

**Comment by Onager** [comment]
Hey Heiko, your command line looks a bit strange - you haven't specified a storage file or any data to analyze - can you try something like:

`log2timeline.py --parsers linux something.plaso /path/to/data`?

**Comment by koenigswinter** [comment]
> Hey @koenigswinter, your command line looks a bit strange - you haven't specified a storage file or any data to analyze - can you try something like:
> 
> `log2timeline.py --parsers linux something.plaso /path/to/data`?

Sorry about that, I did not format the markup correctly.
=> log2timeline.py --parsers linux plasofile.plaso rawimage.raw

The Debian package installation via PPA  [GiFT PPA][https://launchpad.net/~gift] stable track worked without any debug error outputs. However the workers idled for several hours on a certain image file, so I tried the most current Github version.

**Comment by Onager** [comment]
Thanks for the extra context @koenigswinter  - what filesystem is "plasofile.plaso" being created on? Is it a network filesystem, or is the an AV or backup software that could be locking the .plaso file?
Is the .plaso file present on the filesystem after log2timeline crashes?

**Comment by joachimmetz** [comment]
Closing due to lack of input from original reporter.
