### ISSUE TITLE
Error: unable to process path specification with error: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)

### ISSUE THREAD

**Issue by fguitart** [log2timeline/plaso#2187]
**Description of problem:**

Several errors when trying to generate timeline on a tar file.

log2timeline seems to end without processing several files inside the archive.

"pinfo.py file.plaso"  shows a lot of errors like this one:

********************************** Error: 10 ***********************************
Message : unable to process path specification with error: 'ascii'
                 codec can't decode byte 0xc3 in position 128: ordinal not
                     in range(128)
Parser chain :
Path specification :  type: OS, location:
                     /cases/path/to/file.tar
                            : type: TAR, location:
                     /some/path/inside/archive/tar/

**Command line and arguments:**

log2timeline.py --process_archives --hasher_file_size_limit 512 --hashers md5 --parsers linux -z Europe/London  /cases/path/to/storagefile.plaso /cases/path/to/file.tar

**Source data:**

TAR file that untars correctly.

**Plaso version:**

plaso - log2timeline version 20180930

**Operating system Plaso is running on:**

SIFT Workstation based in Ubuntu 16.04.5 LTS

**Installation method:**

installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Debug output/tracebacks:**

2018-10-24 13:38:38,455 [WARNING] (MainProcess) PID:28261 <worker> File-object not explicitly closed for file: OS:/cases/path/to/file.tar
2018-10-24 13:38:38,456 [WARNING] (MainProcess) PID:28261 <single_process> Unhandled exception while processing path spec: OS:/cases/path/to/file.tar
2018-10-24 13:38:38,456 [ERROR] (MainProcess) PID:28261 <single_process> 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 48, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 818, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 641, in _ProcessFileEntry
    self._ProcessFileEntryDataStream(mediator, file_entry, data_stream)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 720, in _ProcessFileEntryDataStream
    self._ProcessArchiveTypes(mediator, path_spec, archive_types)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 487, in _ProcessArchiveTypes
    for generated_path_spec in path_spec_generator:
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 643, in ExtractPathSpecs
    resolver_context=resolver_context):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 477, in _ExtractPathSpecs
    resolver_context=resolver_context):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 610, in _ExtractPathSpecsFromFileSystem
    file_entry):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 498, in _ExtractPathSpecsFromDirectory
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tar_file_entry.py", line 204, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tar_file_entry.py", line 47, in _EntriesGenerator
    if not path or not path.startswith(tar_path):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 128: ordinal not in range(128)
> /usr/lib/python2.7/dist-packages/dfvfs/vfs/tar_file_entry.py(47)_EntriesGenerator()
-> if not path or not path.startswith(tar_path):

**Comment by Onager** [comment]
This looks to be a bug in dfvfs, not Plaso directly. I'll move this over there.
