### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by siftuser** [log2timeline/plaso#2190]
**Description of problem:**

appears similar to https://github.com/log2timeline/plaso/issues/1761

```
Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 547, in _StatusUpdateThreadMain
    self._CheckStatusWorkerProcess(pid)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/engine.py", line 181, in _CheckStatusWorkerProcess
    process.name, self._storage_writer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 516, in _StartWorkerProcess
    process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Command line and arguments:**

log2timeline.py --no-dependencies-check --status_view window --logfile des_plaso1.log e1.plaso win10.E01

**Source data:**

Win10 E01 image created using ftkimager

**Plaso version:**

20180930

**Operating system Plaso is running on:**

Ubuntu 16.04.5

**Installation method:**

For example:

* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch

**Comment by Onager** [comment]
There can be a few issues that can cause a memory error - @siftuser was there a high number of failed tasks? Is there anything you can share from the "des_plaso1.log" file?

**Comment by joachimmetz** [comment]
There is a max memory threshold on the processes as well

**Comment by MariasStory** [comment]
I have the same problem. Repeated execution gives the same problem:

 [WARNING] (MainProcess) PID:21630 <plaso_xmlrpc> Unable to make RPC call with error: [Errno 111] Connection refused
[ERROR] (MainProcess) PID:21630 <engine> Process Worker_04 (PID: 22127) is not functioning correctly. Status code: killed.
[WARNING] (MainProcess) PID:21630 <engine> Terminating process: (PID: 22127).
[INFO] (MainProcess) PID:21630 <engine> Starting replacement worker process for Worker_04
Exception in thread Status update:
Traceback (most recent call last):
...

**Comment by joachimmetz** [comment]
@MariasStory could you include the part where it says `OSError: [Errno 12] Cannot allocate memory` in your error output?

**Comment by MariasStory** [comment]
2018-11-13 10:36:16,520 [WARNING] (MainProcess) PID:21630 <plaso_xmlrpc> Unable to make RPC call with error: [Errno 111] Connection refused
2018-11-13 10:36:16,576 [ERROR] (MainProcess) PID:21630 <engine> Process Worker_04 (PID: 22127) is not functioning correctly. Status code: killed.
2018-11-13 10:36:16,577 [WARNING] (MainProcess) PID:21630 <engine> Terminating process: (PID: 22127).
2018-11-13 10:36:16,578 [INFO] (MainProcess) PID:21630 <engine> Starting replacement worker process for Worker_04
Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/multi_processing/task_engine.py", line 547, in _StatusUpdateThreadMain
    self._CheckStatusWorkerProcess(pid)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/multi_processing/engine.py", line 181, in _CheckStatusWorkerProcess
    process.name, self._storage_writer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20180930-py2.7.egg/plaso/multi_processing/task_engine.py", line 516, in _StartWorkerProcess
    process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by joachimmetz** [comment]
@MariasStory I would need more context to be able to troubleshoot this issue. Could you provide input on the following question:

* what are the command line and arguments:
* what is the source data:
* What operating system Plaso is running on:

@MariasStory @siftuser what is the overall memory consumption of the foreman and worker processes. 

Could you profile with https://github.com/log2timeline/plaso/wiki/Profiling#profiling-memory-usage and provide us with the profiling results.

**Comment by joachimmetz** [comment]
@siftuser @MariasStory we need your input to be able to fix this issue.

**Comment by joachimmetz** [comment]
No response from reporters, closing in favor of https://github.com/log2timeline/plaso/issues/2243
