### ISSUE TITLE
pyparsing 2.3.0 causes CI tests to fail

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2197]
From https://travis-ci.org/log2timeline/plaso/jobs/452673645

```
======================================================================
ERROR: testOSXParseLog (parsers.gdrive_synclog.GoogleDriveSyncLogUnitTest)
Tests the Parse function on OS X log.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/gdrive_synclog.py", line 87, in testOSXParseLog
    storage_writer = self._ParseFile(['sync_log-osx.log'], parser)
  File "./tests/parsers/test_lib.py", line 107, in _ParseFile
    timezone=timezone)
  File "./tests/parsers/test_lib.py", line 135, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "./plaso/parsers/interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "./plaso/parsers/text_parser.py", line 621, in ParseFileObject
    raise errors.UnableToParseFile('Wrong file structure.')
UnableToParseFile: Wrong file structure.
======================================================================
ERROR: testParseLog (parsers.gdrive_synclog.GoogleDriveSyncLogUnitTest)
Tests the Parse function on normal log.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/gdrive_synclog.py", line 23, in testParseLog
    storage_writer = self._ParseFile(['sync_log.log'], parser)
  File "./tests/parsers/test_lib.py", line 107, in _ParseFile
    timezone=timezone)
  File "./tests/parsers/test_lib.py", line 135, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "./plaso/parsers/interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "./plaso/parsers/text_parser.py", line 621, in ParseFileObject
    raise errors.UnableToParseFile('Wrong file structure.')
UnableToParseFile: Wrong file structure.
======================================================================
FAIL: testParse (parsers.apache_access.ApacheAccessUnitTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/apache_access.py", line 25, in testParse
    self.assertEqual(storage_writer.number_of_errors, 0)
AssertionError: 5 != 0
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
Also see: https://github.com/log2timeline/l2tdevtools/issues/476

The errors above surface after datetime update

**Comment by joachimmetz** [comment]
Was able to reproduce this locally with pyparsing 2.3.0

**Comment by joachimmetz** [comment]
gdrive_synclog parser date and time validation seems to fail: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/gdrive_synclog.py#L206

`unable to parse time zone offset with error: invalid literal for int() with base 10`

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2198

**Comment by joachimmetz** [comment]
With GIFT PPA update and pyparsing fixes in plaso Linux and MacOS tests are passing again
https://travis-ci.org/log2timeline/plaso/builds/453537329
