### ISSUE TITLE
Unicode issue with psort

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#221]
Trying to use psort to parse the data from the "*evil*" test image results in the following traceback:

     Traceback (most recent call last):
      File "/usr/local/bin/psort.py", line 5, in <module>
        pkg_resources.run_script('plaso==1.2.1-20150602', u'psort.py')
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/EGG-INFO/scripts/psort.py", line 552, in <module>
        if not Main():
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/EGG-INFO/scripts/psort.py", line 547, in Main
        tool.ProcessStorage()
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/EGG-INFO/scripts/psort.py", line 500, in ProcessStorage
        self._ProcessStorage()
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/EGG-INFO/scripts/psort.py", line 150, in _ProcessStorage
        use_time_slicer=self._use_time_slicer)
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/plaso/frontend/psort.py", line 378, in ProcessStorage
    
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/plaso/frontend/psort.py", line 467, in ProcessOutput
    
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/plaso/frontend/psort.py", line 63, in _AppendEvent
    
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/plaso/output/interface.py", line 193, in Append
      File "/usr/local/lib/python2.7/dist-packages/plaso-1.2.1_20150602-py2.7.egg/plaso/lib/event.py", line 186, in EqualityString
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2748: ordinal not in range(128)

The error lies in the EqualityString function inside the event library.

**Comment by kiddinn** [comment]
Issue is:

    (Pdb) !u'|'.join(map(unicode, identity))
    *** UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2748: ordinal not in range(128)

This is the culprit:

    (Pdb) !unicode(identity[7])
    *** UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2748: ordinal not in range(128)

Or more specifically this text:

 *you can work in the host\x92s shared desktop*

(well, \x92 appears three times in the line)

The reason here is that the text is encoded using CP1252 (user's encoding) and not Unicode. This is the "right single quotation mark" in cp1252.

This should be fixed in the parser, especially since this is a false hit, the PLS parser should not be run on a Windows image, which in this case it did because of another issue (#217).

The fix should therefor fix the root cause, which is bad assumptions made by the PLS recall parser. Looking at the offending file, it starts with:

    <HTML>
    <HEAD>

    <style TYPE="text/css">

Therefore clearly a HTML file, not a PLS SQL database.

    In [16]: par.VerifyFile(fh)
    Out[16]: True

(where ``par`` is the pls recall parser object)

Let's check closer:

    In [17]: fh.seek(0)
    In [18]: structure = par.PLS_STRUCT.parse_stream(fh)
    In [19]: structure
    Out[19]: Container({u'Username': '...

    In [21]: timestamp = timelib.Timestamp.FromDelphiTime(structure.TimeStamp)
    In [22]: timestamp
    Out[22]: 238803299584000000
    In [23]: print timelib.Timestamp.CopyToIsoFormat(timestamp)
    9537-05-18T01:53:04+00:00

Timestamp is clearly out of "regular" bounds. The only check made is just if it is ``> 0``.

The other tests are just to make sure that the following values are text: Username, Query and Database

They all are... just not the "correct" type of text...

    In [24]: structure.Username
    Out[24]: 'D>\r\n\r\n<style TYPE="text/css">\r\n'
    In [25]: structure.Query
    Out[25]: 'nt-size: 110%;  \r\n\t\tmargin-top: 1.5em;\r\n\t...

    In [26]: structure.Database
    Out[26]: '\r\nh1\r\n\t\t{ font-size: 125%; \r\n\t\tmargin-bottom:" .5

Adding two more test to the VerifyFile routine. Also adding more error tolerance into the EqualityString function.

Added changes to: https://codereview.appspot.com/245760043/

**Comment by kiddinn** [comment]
Cl is in, and this has been fixed:

- [x] EqualityString should be more resiliant now
- [x] pls_recall parser has been updated to add few more tests to make it less like to trigger on wrong files
