### ISSUE TITLE
Latest version of libesedb doesn't have attribute is_long_value

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#222]
libesedb (pyesedb) version: 20150409
Running bleeding edge Plaso tests with bleeding edge version of libesedb gives me error:

```
Traceback (most recent call last):
  File "./plaso/parsers/esedb_plugins/msie_webcache_test.py", line 25, in testProcess
    [test_file_name], self._plugin)
  File "./plaso/parsers/esedb_plugins/test_lib.py", line 55, in _ParseEseDbFileWithPlugin
    plugin_object.Process(parser_mediator, database=esedb_file, cache=cache)
  File "./plaso/parsers/esedb_plugins/interface.py", line 288, in Process
    parser_mediator, database=database, cache=cache, **kwargs)
  File "./plaso/parsers/esedb_plugins/interface.py", line 259, in GetEntries
    **kwargs)
  File "./plaso/parsers/esedb_plugins/msie_webcache.py", line 229, in ParseContainersTable
    record_values = self._GetRecordValues(table.name, esedb_record)
  File "./plaso/parsers/esedb_plugins/interface.py", line 193, in _GetRecordValues
    value = self._GetRecordValue(record, value_entry)
  File "./plaso/parsers/esedb_plugins/interface.py", line 122, in _GetRecordValue
    if record.is_long_value(value_entry):
AttributeError: 'pyesedb.record' object has no attribute 'is_long_value'
```

Looking at the pyesedb code shows that this attribute is no longer present. We should update plaso/parsers/esedb_plugins/interface.py to fix this, or is this a bug in libesedb?

ping @joachimmetz

**Comment by joachimmetz** [comment]
Issue in your system environment. Will not fix.

Root cause is something that will be addressed: https://github.com/log2timeline/l2tdevtools/issues/18
