### ISSUE TITLE
Exception in pysigscan  - cache filled

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#225]
Seems to be triggering on Firefox cache files:

```
2015-06-04 13:09:21,354 [WARNING] (MainProcess) PID:24954 <worker> Unable to parse file: type: OS, location: <firefox cache file>
type: GZIP
 with error: pysigscan_scanner_scan_file_object: unable to scan file. pysigscan_file_object_read_buffer: unable to read from file object with error: BackEndError(u'Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid block type.',). pysigscan_file_object_io_handle_read: unable to read from file object. libbfio_handle_read_buffer: unable to read from handle. libsigscan_scanner_scan_file_io_handle: unable to read buffer.
2015-06-04 13:09:21,389 [ERROR] (MainProcess) PID:24954 <extraction_frontend> An uncaught exception occurred: Maximum number of cached values reached..
Traceback (most recent call last):
  File "/home/onager/plaso/plaso/frontend/extraction_frontend.py", line 478, in _ProcessSourcesSingleProcessMode
    storage_serializer_format=storage_serializer_format)
  File "/home/onager/plaso/plaso/frontend/extraction_frontend.py", line 546, in _StartSingleThread
    hasher_names_string=hasher_names_string)
  File "/home/onager/plaso/plaso/engine/single_process.py", line 200, in ProcessSources
    extraction_worker.Run()
  File "/home/onager/plaso/plaso/engine/worker.py", line 530, in Run
    self.ConsumeItems()
  File "/home/onager/plaso/plaso/engine/queue.py", line 132, in ConsumeItems
    self._ConsumeItem(item, **kwargs)
  File "/home/onager/plaso/plaso/engine/worker.py", line 92, in _ConsumeItem
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 53, in OpenFileEntry
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 163, in OpenFileSystem
    file_system.Open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_system.py", line 234, in Open
    self._resolver_context.CacheFileSystem(path_spec, self)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/context.py", line 62, in CacheFileSystem
    self._file_system_cache.CacheObject(identifier, file_system)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.

> /usr/lib/python2.7/dist-packages/dfvfs/resolver/cache.py(83)CacheObject()
-> raise errors.CacheFullError(u'Maximum number of cached values reached.')
(Pdb) 

```

**Comment by Onager** [comment]
Not sure if this a pysigscan bug, or if there's something plaso should be doing to stop the cache filling up.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/commit/112d2f298a2d6d46c635cd68a4f8c9eabe972393

**Comment by Onager** [comment]
This looks to be resolved - now getting:
```
type: GZIP
 with error: pysigscan_scanner_scan_file_object: unable to scan file. pysigscan_file_object_read_buffer: unable to read from file object with error: BackEndError(u'Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid distance too far back.',). pysigscan_file_object_io_handle_read: unable to read from file object. libbfio_handle_read_buffer: unable to read from handle. libsigscan_scanner_scan_file_io_handle: unable to read buffer.
```

Which is expected (according to Joachim)
