### ISSUE TITLE
Tests failing with NotImplementedError

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2255]
Due to recent updates of dependencies CI tests are failing with:

```
======================================================================
ERROR: testParseTruncated (parsers.winevtx.WinEvtxParserTest)
Tests the Parse function on a truncated file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/winevtx.py", line 130, in testParseTruncated
    storage_writer = self._ParseFile(['System2.evtx'], parser)
  File "./tests/parsers/test_lib.py", line 107, in _ParseFile
    timezone=timezone)
  File "./tests/parsers/test_lib.py", line 135, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "./plaso/parsers/interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "./plaso/parsers/winevtx.py", line 267, in ParseFileObject
    self._ParseRecords(parser_mediator, evtx_file)
  File "./plaso/parsers/winevtx.py", line 227, in _ParseRecords
    self._ParseRecord(parser_mediator, record_index, evtx_record)
  File "./plaso/parsers/winevtx.py", line 188, in _ParseRecord
    parser_mediator, record_index, evtx_record, recovered=recovered)
  File "./plaso/parsers/winevtx.py", line 163, in _GetEventData
    for rule in rules:
NotImplementedError: pyevtx_strings_init: initialize of strings not supported.
----------------------------------------------------------------------
```

Looks like issue with call to pyevtx_strings_init from pyevtx_strings_new. Similar issue in pyevt see below.

**Comment by joachimmetz** [comment]
Issue appears that pyevtx_strings_init is called from pyevtx_strings_new and pyevtx_strings_init now always raises NotImplementedError, seeing pyevtx_strings is supposed to be only created by the Python bindings. Updating pyevt and pyevtx.

**Comment by joachimmetz** [comment]
Pushed update to GIFT PPA and l2tbinaries dev tracks
