### ISSUE TITLE
no_vss option not working with Python3

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2258]
Command line:
```
/usr/bin/python3 ./tools/log2timeline.py --status-view=none --partitions all --no_vss --debug --log-file plaso-out/log2timeline.log.gz --profilers memory,parsers,processing,serializers,storage,task_queue,tasks --profiling_directory plaso-out/profiling /tmp/tmp_ko94_bs/registrar.plaso /media/greendale_images/registrar.dd
```
This seems to prompt for input:
```
Checking availability and versions of dependencies.
[OPTIONAL]      missing: hachoir_core.
[OPTIONAL]      missing: hachoir_metadata.
[OPTIONAL]      missing: hachoir_parser.
[OK]

The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2015-09-11 00:00:17.9328027

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores
can be defined as: 1,3,5 (a list of comma separated values). Ranges
and lists can also be combined as: 1,3..5. The first store is 1. All
stores can be defined as "all". If no stores are specified none will
be processed. You can abort with Ctrl^C.

VSS identifiers:
```

And then also crash

Back trace:
```
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 68, in <module>
    if not Main():
  File "./tools/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/log2timeline_tool.py", line 370, in ExtractEventsFromSources
    scan_context = self.ScanSource(self._source_path)
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 1174, in ScanSource
    self._ScanVolume(scan_context, sub_scan_node, base_path_specs)
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 1004, in _ScanVolume
    self._ScanVolume(scan_context, sub_scan_node, base_path_specs)
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 986, in _ScanVolume
    self._ScanVolumeSystemRoot(scan_context, scan_node, base_path_specs)
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 1026, in _ScanVolumeSystemRoot
    volume_identifiers = self._GetVSSStoreIdentifiers(scan_node),
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 296, in _GetVSSStoreIdentifiers
    volume_system, volume_identifiers)
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 856, in _PromptUserForVSSStoreIdentifiers
    volume_system, prefix='vss')
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/storage_media_tool.py", line 887, in _ReadSelectedVolumes
    volume_identifiers_string = self._input_reader.Read()
  File "/home/user/code/plaso-ubuntu-e2e-registrar-py3/plaso/cli/tools.py", line 459, in Read
    string = codecs.decode(encoded_string, self._encoding, self._errors)
TypeError: decoding with 'UTF-8' codec failed (TypeError: a bytes-like object is required, not 'str')
```

Still investigating

**Comment by Onager** [comment]
Looks like two issues:

1. The process_vss option isn't respected
1. The input reader isn't handling a unicode input string correctly

**Comment by Onager** [comment]
For point 1, there doesn't seem to be any check for the process_vss option when scanning volumes.

For point 2, this is looks like the fix for #2167 wasn't complete.

PRs #2259 and #2260 are out to fix these issues.

**Comment by joachimmetz** [comment]
@Onager changes have been merged

**Comment by Onager** [comment]
This is now fixed.
