### ISSUE TITLE
More gracefully handle running log2timeline.py on a locked database

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#2265]
**Description of problem:**

In order to reproduce #2041 , I ran this command from 2 different shells:

log2timeline.py /tmp/plaso /dev/sdb1

The first shell would have worker a'working.
The second shell displays, as expected:

```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 445, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 820, in ProcessSources
    storage_writer.WriteSessionStart()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1740, in WriteSessionStart
    self._storage_file.WriteSessionStart(session_start)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 1067, in WriteSessionStart
    self._WriteAttributeContainer(session_start)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 434, in _WriteAttributeContainer
    self._cursor.execute(query, (serialized_data, ))
sqlite3.OperationalError: database is locked
```

The problem is this process is frozen and I can't ctrl-c out of it to get back to my shell prompt.

```
sqlite3.OperationalError: database is locked
^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C
```

**Command line and arguments:**

Please provide the command with arguments you ran when you experienced
the problem.

**Source data:**

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

**Plaso version:**

# log2timeline.py --version
plaso - log2timeline version 20180930

**Operating system Plaso is running on:**

# uname -a
Linux gcp-vm 4.15.0-1025-gcp #26~16.04.1-Ubuntu SMP Wed Nov 21 10:13:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Installation method:**

deb http://ppa.launchpad.net/gift/stable/ubuntu xenial main

**Comment by joachimmetz** [comment]
@rgayon please check this with http://ppa.launchpad.net/gift/dev/ubuntu as well. Seeing that we're nearing a release. (dev track has a recent pre-release)

**Comment by rgayon** [comment]
```
# apt policy python-plaso
python-plaso:
  Installed: 20181215-1ppa1~xenial
  Candidate: 20181215-1ppa1~xenial
  Version table:
 *** 20181215-1ppa1~xenial 500
        500 http://ppa.launchpad.net/gift/dev/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
# dpkg -S log2timeline.py
plaso-tools: /usr/bin/log2timeline.py
# apt policy plaso-tools
plaso-tools:
  Installed: 20181215-1ppa1~xenial
  Candidate: 20181215-1ppa1~xenial
  Version table:
 *** 20181215-1ppa1~xenial 500
        500 http://ppa.launchpad.net/gift/dev/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
# log2timeline.py --version
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 11, in <module>
    from plaso import dependencies
ImportError: No module named 'plaso'
```
*whines*

**Comment by rgayon** [comment]
May be due to 
```
# head -n 1 /usr/bin/log2timeline.py

#!/usr/bin/python3.5
```

**Comment by rgayon** [comment]
once python3-plaso is installed, I could try to reproduce the hanging issue:

Killing does look a bit messy, but works:

```
xception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock() 
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
  File "/usr/lib/python3.5/multiprocessing/heap.py", line 209, in free
AttributeError: 'NoneType' object has no attribute 'getpid'
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
  File "/usr/lib/python3.5/multiprocessing/heap.py", line 209, in free
AttributeError: 'NoneType' object has no attribute 'getpid'
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 186, in __call__
  File "/usr/lib/python3.5/multiprocessing/heap.py", line 209, in free
AttributeError: 'NoneType' object has no attribute 'getpid'
Exception ignored in: <Finalize object, dead>
<snip>
```

**Comment by joachimmetz** [comment]
> ImportError: No module named 'plaso'

I've created https://github.com/log2timeline/l2tdevtools/issues/527, for some yet unknown reason dpkg build process changes the shebang of the plaso-tools scripts.

**Comment by joachimmetz** [comment]
Add a write test before starting event extraction

**Comment by joachimmetz** [comment]
Steps to reproduce,

1. Create a database `sqlite3 test.plaso`
1. Lock database
```
PRAGMA locking_mode = EXCLUSIVE;
BEGIN EXCLUSIVE;
```
1. Run `log2timeline.py` on `test.plaso`

**Comment by joachimmetz** [comment]
Changes in https://github.com/log2timeline/plaso/pull/3743
