### ISSUE TITLE
RuntimeError on VSS

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2276]
Backtrace on VSS1 in greendale registrar image:

```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 446, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 827, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 329, in _ProcessSources
    for path_spec in path_spec_generator:
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 643, in ExtractPathSpecs
    resolver_context=resolver_context):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 451, in _ExtractPathSpecs
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 55, in OpenFileEntry
    path_spec_object, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 164, in OpenFileSystem
    file_system.Open(path_spec_object)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_system.py", line 262, in Open
    self._Open(path_spec, mode=mode)
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_system.py", line 68, in _Open
    tsk_file_system = pytsk3.FS_Info(tsk_image_object)
RuntimeError: 'pyvshadow_store_read_buffer: unable to read data.
libcdata_tree_node_free: invalid node - connected to other nodes.
libcdata_btree_node_remove_value: unable to free remaining sub node.
libcdata_btree_node_remove_value: unable to remove value from parent node.
libcdata_btree_remove_value: unable to remove value: 7491 from upper node.
libvshadow_block_tree_insert: unable to remove reverse block descriptor: 0x37995c000 from reverse block tree node.
libvshadow_store_descriptor_read_store_block_list: unable to insert block descriptor in tree.
libvshadow_store_descriptor_read_block_descriptors: unable to read store block list.
libvshadow_store_descriptor_read_buffer: unable to read block descriptors.
libvshadow_internal_store_read_buffer_from_file_io_handle: unable to read buffer from store descriptor: 0.
libvshadow_store_read_buffer: unable to read buffer.'
FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
```

**Comment by joachimmetz** [comment]
Re-enable plaso-linux-e2e-registrar-vss test?

**Comment by joachimmetz** [comment]
`libcdata_tree_node_free: invalid node - connected to other nodes.`
Looks like an issue with the interaction between libvshadow and libcdata

**Comment by joachimmetz** [comment]
Traced this down to a bug in libcdata.

**Comment by joachimmetz** [comment]
libcdata bug addressed in https://github.com/libyal/libcdata/commit/9d7a02fcbbd60e0165492f22a2ec40526bbf9ad5

**Comment by joachimmetz** [comment]
Pushed new libvshadow release https://github.com/libyal/libvshadow/releases/tag/20190112

**Comment by joachimmetz** [comment]
Local test with latest libvshadow no longer raises the RuntimeError.

**Comment by joachimmetz** [comment]
Updated libvshadow in l2tbinaries (dev, testing), GIFT PPA (dev, stable, testing) and COPR (dev, stable, testing)

**Comment by joachimmetz** [comment]
Closing issue.
