### ISSUE TITLE
Investigate Travis failures

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2297]
Travis tests run with Tox on Linux are failing with the below errors:
```
======================================================================
ERROR: testParse (parsers.winfirewall.WinFirewallParserTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/winfirewall.py", line 34, in testParse
    self.assertEqual(event.source_ip, '123.45.78.90')
AttributeError: 'DateTimeValuesEvent' object has no attribute 'source_ip'
======================================================================
FAIL: testParse (parsers.syslog_plugins.ssh.SSHSyslogPluginTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/syslog_plugins/ssh.py", line 38, in testParse
    self.assertEqual(event.address, '192.168.0.1')
AssertionError: [u'192.168.0.1'] != u'192.168.0.1'
======================================================================
FAIL: testParse (parsers.apache_access.ApacheAccessUnitTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/apache_access.py", line 36, in testParse
    self.assertEqual(event.ip_address, '192.168.0.2')
AssertionError: ([u'192.168.0.2'], {}) != u'192.168.0.2'
```

**Comment by Onager** [comment]
All these parsers are text parsers, and the pyparsing version is different from Tox (2.3.1) to non-Tox (2.3.0)

**Comment by Onager** [comment]
From https://github.com/pyparsing/pyparsing/blob/master/CHANGES: 
- POSSIBLE API CHANGE: this release fixes a bug when results names were
  attached to a MatchFirst or Or object containing an And object.
  Previously, a results name on an And object within an enclosing MatchFirst
  or Or could return just the first token in the And. Now, all the tokens
  matched by the And are correctly returned. This may result in subtle
  changes in the tokens returned if you have this condition in your pyparsing
  scripts.

I upgraded from 2.3.0 to 2.3.1 on my dev machine, and have the same crashes.

**Comment by Onager** [comment]
Identified a fix, that also resolves some other Todos around IP address parsing.
