### ISSUE TITLE
20190131 RunTimeError: Ordered Dict mutated during iteration

### ISSUE THREAD

**Issue by dougkoster** [log2timeline/plaso#2362]
Attempting to test fresh install of Plaso v. 20190131 on a new SIFT 16.04 .ova install. Running against xpdblake.dd image from SANS. I get the following error:

plaso - log2timeline version 20190131

Source path	: /mnt/hgfs/D_Drive/Test Images/xp dblake.dd
Source type	: storage media image
Processing time	: 01:07:04

Tasks:          Queued  Processing      Merging         Abandoned       Total
                1708    179             0               0               9758

Identifier      PID     Status          Memory          Sources         Events          File
Main            9452    running         432.9 MiB       9758 (0)        149150 (0)      
Worker_00       9460    idle            266.0 MiB       4842 (0)        49544 (4)       TSK:/WINDOWS/pchealth/helpctr/OfflineCache/Professional_32#0409/00000274.query
Worker_01       9462    idle            336.1 MiB       4915 (0)        100346 (4)      TSK:/WINDOWS/pchealth/helpctr/OfflineCache/Professional_32#0409/00000273.query

Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/log2timeline_tool.py", line 458, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_engine.py", line 828, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_engine.py", line 346, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_engine.py", line 420, in _ScheduleTasks
    while event_source or self._task_manager.HasPendingTasks():
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_manager.py", line 472, in HasPendingTasks
    self._AbandonQueuedTasks()
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_manager.py", line 203, in _AbandonQueuedTasks
    for task_identifier, task in iter(self._tasks_queued.items()):
RuntimeError: OrderedDict mutated during iteration

This is the contents of the plaso log file:
2019-02-20 20:07:41,408 [INFO] (MainProcess) PID:9452 <engine> Preprocessing detected operating systems: Windows NT
2019-02-20 20:07:41,411 [INFO] (MainProcess) PID:9452 <extraction_tool> Parser filter expression set to: win7,winxp

**Comment by Onager** [comment]
Thanks for the report, this should be pretty straightforward to fix.
