### ISSUE TITLE
ValueError: Invalid size value exceeds maximum value 16777216

### ISSUE THREAD

**Issue by soundwave01** [log2timeline/plaso#2365]
**Description of problem:**

Log2timeline appears to be unable to process large files, like the output from analyzeMFT.   The following error is thrown  "ValueError: Invalid size value exceeds maximum value 16777216."

The error is being thrown on the MAXIMUM_READ_BUFFER_SIZE checks in the readline function of line_reader_file.py  which is called by dsv-parser.pv.

Having checked the files that log2timeline is processing, the first lines are not bigger than 16777216 in size.

I'm struggling to understand where the value for size is getting set (see debug output), it does not appear to correlate to the size of any of the lines or the size of the file.

While in this example I have just shown the error from processing the output from analyzeMFT, I have the same error on around 80 different files.

**Command line and arguments:**

```
analyzeMFT.py -f $MFT --bodyfull -p -b -c mft.csv
log2timeline.py --no_dependencies_check --logfile out.txt --single_process -d test-out MFTbody
```

**Plaso version:**

plaso - log2timeline version 20190131

**Operating system Plaso is running on:**

Ubuntu 16.04.5 LTS

**Installation method:**

apt-get

**Debug output/tracebacks:**

stack trace

```
2019-02-21 14:17:56,340 [ERROR] (MainProcess) PID:7156 <single_process> Invalid size value exceeds maximum value 16777216.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 48, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 818, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 641, in _ProcessFileEntry
    self._ProcessFileEntryDataStream(mediator, file_entry, data_stream)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 733, in _ProcessFileEntryDataStream
    mediator, file_entry, data_stream.name)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 329, in _ExtractContentFromDataStream
    mediator, file_entry, data_stream_name)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 323, in ParseDataStream
    file_object=file_object)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 283, in _ParseFileEntryWithParsers
    parser_mediator, parser, file_entry, file_object=file_object)
  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 211, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "/usr/local/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "/usr/local/lib/python2.7/dist-packages/plaso/parsers/dsv_parser.py", line 209, in ParseFileObject
    if not self._HasExpectedLineLength(file_object):
  File "/usr/local/lib/python2.7/dist-packages/plaso/parsers/dsv_parser.py", line 176, in _HasExpectedLineLength
    sample_line = line_reader.readline(self._maximum_line_length + 1)
  File "/usr/local/lib/python2.7/dist-packages/plaso/lib/line_reader_file.py", line 89, in readline
    self._MAXIMUM_READ_BUFFER_SIZE))
ValueError: Invalid size value exceeds maximum value 16777216.
2019-02-21 14:30:57,364 [DEBUG] (MainProcess) PID:7156 <single_process> Processing completed.

```

Debugger

```
(Pdb) l
 84           raise ValueError('Invalid size value smaller than zero.')
 85  
 86         if size is not None and size > self._MAXIMUM_READ_BUFFER_SIZE:
 87           raise ValueError(
 88               'Invalid size value exceeds maximum value {0:d}.'.format(
 89  ->               self._MAXIMUM_READ_BUFFER_SIZE))
 90  
 91         if not self._lines:
 92           if self._lines_buffer_offset >= self._file_object_size:
 93             return b''
 94  
(Pdb) a
self = <plaso.lib.line_reader_file.BinaryLineReader object at 0x7f05db552ad0>
size = 553402322211286548482
(Pdb) 
```

first 20 lines of the file it is processing

```
0|\$MFT|0|0|0|0|16384|1549931883|1549931883|1549931883|1549931883
0|\$MFTMirr|0|0|0|0|4096|1549931883|1549931883|1549931883|1549931883
0|\$LogFile|0|0|0|0|67108864|1549931883|1549931883|1549931883|1549931883
0|\$Volume|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$AttrDef|0|0|0|0|36000|1549931883|1549931883|1549931883|1549931883
0|\.|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$Bitmap|0|0|0|0|15262016|1549931883|1549931883|1549931883|1549931883
0|\$Boot|0|0|0|0|8192|1549931883|1549931883|1549931883|1549931883
0|\$BadClus|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$BadClus:$Bad|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$Secure|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$Secure:$SDS|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|\$UpCase|0|0|0|0|131072|1549931883|1549931883|1549931883|1549931883
0|\$UpCase:$Info|0|0|0|0|131072|1549931883|1549931883|1549931883|1549931883
0|\$Extend|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|No FN Record|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|No FN Record|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|No FN Record|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|No FN Record|0|0|0|0|0|1549931883|1549931883|1549931883|1549931883
0|Corrupt Record|0|0|0|0|0|0|0|0|0
```
size of the file being processed

`-rw-rw-r--  1 xxxx xxxx 33673110 Feb 21 13:42 MFTbody`

**Comment by Onager** [comment]
The size that's being read here is the maximum length of a line that we'd expect to see in the file: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/dsv_parser.py#L69

My guess is that csv.field_size_limit() is very large in the version of Python you're using, or one of the parsers for some reason expects a very large number of fields.

**Comment by Onager** [comment]
The fix for this will be to check the maximum line length we set in the DSV parser against the maximum read buffer of the underlying reader.

**Comment by Onager** [comment]
Since you have the debugger open, could you let me know which parser is actually causing this call? There's probably a bug to fix in that too. If you can look up the type of `parser` in `  File "/usr/local/lib/python2.7/dist-packages/plaso/engine/extractors.py", line 211, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)` that would do it.

**Comment by soundwave01** [comment]
looks like symantec_scanlog

```
    parser_mediator.SampleStartTiming(parser.NAME)

    print("parser : %s" % (parser.NAME)) 

    try:
      if isinstance(parser, parsers_interface.FileEntryParser):
        parser.Parse(parser_mediator)
      elif isinstance(parser, parsers_interface.FileObjectParser):
        parser.Parse(parser_mediator, file_object)
      result = self._PARSE_RESULT_SUCCESS

```

```
plaso - log2timeline version 20190131

Source path     : /tmp/xxxxxxx/MFTbody
Source type     : single file
Processing time : 00:00:00

Identifier      PID     Status          Memory          Sources         Events          File
Main            7773    running         118.2 MiB       1 (1)           0 (0)           OS:/tmp/xxxxxxxx/MFTbody

parser : filestat
parser : chrome_preferences
parser : syslog
parser : android_app_usage
parser : selinux
parser : recycle_bin
parser : pls_recall
parser : sccm
parser : amcache
parser : winiis
parser : xchatscrollback
parser : dockerjson
parser : symantec_scanlog
> /usr/local/lib/python2.7/dist-packages/plaso/lib/line_reader_file.py(89)readline()
-> self._MAXIMUM_READ_BUFFER_SIZE))
(Pdb) 
```

**Comment by soundwave01** [comment]
got it to run with the following

`log2timeline.py --no_dependencies_check --parser '!symantec_scanlog,!trendmicro_vd,!mactime,!trendmicro_url,!mcafee_protection' --logfile out.txt --single_process -d test-out MFTbody
`
each of those disabled parsers produced the same error.
