### ISSUE TITLE
pinfo is missing parser counter

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#237]
The parser counter is no longer in the pinfo output

**Comment by kiddinn** [comment]
Also an issue in psort, parsing the evil dataset:

    $ psort.py test-1.plaso > /tmp/evil.txt

    [INFO] Data files will be loaded from /Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/share/plaso by default.
    Traceback (most recent call last):
      File "/usr/local/bin/psort.py", line 5, in <module>
        pkg_resources.run_script('plaso==1.3.0-20150610', u'psort.py')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
        execfile(script_filename, namespace, namespace)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 638, in <module>
        if not Main():
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 633, in Main
        tool.ProcessStorage()
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 585, in ProcessStorage
        self._ProcessStorage()
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 231, in _ProcessStorage
        time_slice=time_slice, use_time_slicer=self._use_time_slicer)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/frontend/psort.py", line 423, in ProcessStorage
        analysis_queues=event_queue_producers)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 239, in __exit__
        self.End()
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 231, in End
        self.Flush()
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 198, in Flush
        self._output_module.WriteEvent(event_object)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 55, in WriteEvent
        self.WriteEventBody(event_object)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/dynamic.py", line 355, in WriteEventBody
        row.append(callback_function(event_object))
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/dynamic.py", line 140, in _FormatMessage
        message, _ = self._output_mediator.GetFormattedMessages(event_object)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/mediator.py", line 122, in GetFormattedMessages
        return event_formatter.GetMessages(self._formatter_mediator, event_object)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/winevt.py", line 110, in GetMessages
        source_name, message_identifier)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/mediator.py", line 79, in GetWindowsEventMessage
        log_source, self.DEFAULT_LCID, message_identifier)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/winevt_rc.py", line 303, in GetMessage
        event_log_provider_key = self._GetEventLogProviderKey(log_source)
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/winevt_rc.py", line 192, in _GetEventLogProviderKey
        table_names, column_names, condition))
      File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/winevt_rc.py", line 82, in GetValues
        raise RuntimeError(u'Cannot retrieve values database not opened.')
    RuntimeError: Cannot retrieve values database not opened.

**Comment by kiddinn** [comment]
another issue here is that once a dynamic filter is used but no fields set no output is written

**Comment by kiddinn** [comment]
the database error is due to the fact that sqlite is unable to open the databse due to permissions errors.... 

so find a way to fix those permissions and have a better detection of that.

**Comment by kiddinn** [comment]
This error is raised:

     *** OperationalError: unable to open database file

**Comment by kiddinn** [comment]
pinfo does not provide counter information due to the JSON serializer not properly de-serializing the counter:

```
In [1]: from plaso.lib import event

In [2]: from plaso.serializer import json_serializer

In [3]: p = event.PreprocessObject()

In [4]: import collections

In [5]: p.windows = 'os'

In [6]: p.os = 'windows'

In [7]: p.counter = collections.Counter()

In [8]: p.counter['foobar'] = 324

In [9]: p.counter['foobar_asdf'] = 324

In [10]: pj = json_serializer.JSONPreprocessObjectSerializer.WriteSerialized(p)

In [11]: pj
Out[11]: '{"windows": {"__type__": "bytes", "stream": "os"}, "os": {"__type__": "bytes", "stream": "windows"}, "counter": {"foobar": 324, "__type__": "collections.Counter", "foobar_asdf": 324}, "__type__": "PreprocessObject", "zone": {"__type__": "timezone", "zone": "UTC"}}'
```

Counter is in there, and seems to be properly defined. So we can write the serialized version.

```
In [16]: p2 = json_serializer.JSONPreprocessObjectSerializer.ReadSerialized(pj)

In [17]: p2.counter
Out[17]: Counter()
```

However we cannot read the serialized version and get the proper counter out.

This needs to be fixed and a test added

**Comment by kiddinn** [comment]
Fixed the serializer issue and the permission on the Event Log db, now resulting in

```
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.3.0-20150610', u'psort.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 638, in <module>
    if not Main():
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 633, in Main
    tool.ProcessStorage()
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 585, in ProcessStorage
    self._ProcessStorage()
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/EGG-INFO/scripts/psort.py", line 231, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/frontend/psort.py", line 423, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 239, in __exit__
    self.End()
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 231, in End
    self.Flush()
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 198, in Flush
    self._output_module.WriteEvent(event_object)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/interface.py", line 55, in WriteEvent
    self.WriteEventBody(event_object)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/dynamic.py", line 357, in WriteEventBody
    row.append(callback_function(event_object))
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/dynamic.py", line 140, in _FormatMessage
    message, _ = self._output_mediator.GetFormattedMessages(event_object)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/output/mediator.py", line 122, in GetFormattedMessages
    return event_formatter.GetMessages(self._formatter_mediator, event_object)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150610-py2.7.egg/plaso/formatters/winevt.py", line 112, in GetMessages
    event_values[u'message_string'] = message_string.format(*strings)
IndexError: tuple index out of range
```

**Comment by kiddinn** [comment]
In this case the line is: ```message_string.format(*strings)``` and the line that triggers the condition:

```
(Pdb) strings
[u'rundll32.exe', u'5.1.2600.0', u'hungapp', u'0.0.0.0', u'00000000']
```

With the following ```message_string``` attribute:

```
u'The program {0:s} version {1:s} stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.\\nProcess ID: {2:s}\\nStart Time: {3:s}\\nTermination Time: {4:s}\\nApplication Path: {5:s}\\nReport Id: {6:s}\\n'
```

So strings with length of five and message string requiring length of six.

Event coming from: **AppEvent.Evt**
event_category: **event_category**
event_identifier: **1002**
message_identifier: **1002**
source_name: **Application Hang**

Looking at [eventid.net](http://www.eventid.net/display.asp?eventid=1002&source=Application+Hang) it looks like there may be more than a single message string for this particular event.

for now adding a try/except to catch this.

**Comment by kiddinn** [comment]
This is part of #218

**Comment by kiddinn** [comment]
CL: http://codereview.appspot.com/248750043

Fixes:

 - [x] Check if Winevt RC database successfully opened
 - [x] JSON serializer for the counter object (and thus pinfo starts displaying counter information again)
 - [x] Dynamic output module not having empty output if filter is set and no fields

**Comment by kiddinn** [comment]
Closing this one down now, since all fixes are in.
