### ISSUE TITLE
I installed Yara amd later I unistall it but cuckoo rooter still not working 

### ISSUE THREAD

**Issue by ammarahmad93** [log2timeline/plaso#2386]
Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin;/usr/lib
Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 7, in <module>
    from cuckoo.main import main
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/main.py", line 15, in <module>
    from cuckoo.apps import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/__init__.py", line 5, in <module>
    from .apps import (
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/apps/apps.py", line 34, in <module>
    from cuckoo.core.startup import init_console_logging
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/startup.py", line 11, in <module>
    import yara
  File "/usr/local/lib/python2.7/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python2.7/dist-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory

**Comment by Onager** [comment]
Hey @ammarahmad93 - what does this have to do with Plaso? We don't develop Yara or cuckoo sandbox.

**Comment by joachimmetz** [comment]
No response from reporter and not plaso related based on the description. Closing issue.
