### ISSUE TITLE
psteal fails with format error

### ISSUE THREAD

**Issue by jsolderitsch** [log2timeline/plaso#2392]
**Description of problem:**

psteal reports format error

```
plaso - psteal version 20181219

Storage file	: 20190315T172059-nps-2008-jean.e01.plaso

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    19943   exporting       518.8 MiB       0 (0)           0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 78, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 64, in Main
    tool.AnalyzeEvents()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/psteal_tool.py", line 229, in AnalyzeEvents
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 1021, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 538, in _ExportEvents
    output_module, event, deduplicate_events=deduplicate_events)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 435, in _ExportEvent
    output_module, deduplicate_events=deduplicate_events)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 598, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/lib/python2.7/dist-packages/plaso/output/l2t_csv.py", line 214, in WriteEventMACBGroup
    output_values = self._GetOutputValues(event_macb_group[0])
  File "/usr/lib/python2.7/dist-packages/plaso/output/l2t_csv.py", line 165, in _GetOutputValues
    date_string = '{0:02d}/{1:02d}/{2:04d}'.format(month, day_of_month, year)
ValueError: Unknown format code 'd' for object of type 'unicode'
```

**Command line and arguments:**

`psteal.py --source /cases/nps-2008-jean.e01 -o l2tcsv -w /cases/nps-jean-1.csv`

**Source data:**

This is nps-jean-2008.e01 and .e02 image from the Digital Corpora site:
[https://digitalcorpora.org/corpora/disk-images](https://digitalcorpora.org/corpora/disk-images)

**Plaso version:**

plaso - psteal version 20181219

**Operating system Plaso is running on:**

Sift 3.0 installation

**Installation method:**

plaso pre-installed in the Sift mage

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html#producing-debug-logs]

For more information see the [troubleshooting
guide][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html].

**Comment by jsolderitsch** [comment]
The same error occurs with psort when I don't specify a date range but I do give an output format:
`-o l2tcsv`

If I run psort with a date range expression, the error does not occur.

**Comment by joachimmetz** [comment]
Thx for the report, having a look.

link to images https://digitalcorpora.org/corpora/scenarios/m57-jean

**Comment by jsolderitsch** [comment]
Yes, that is the source of the images: the nps-2008 E01 and E02 files. Some poorly formed datetimes from plaso apparently.

**Comment by joachimmetz** [comment]
> Some poorly formed datetimes from plaso apparently.

where do you base this on?

> ValueError: Unknown format code 'd' for object of type 'unicode'

Could have multiple reasons

**Comment by jsolderitsch** [comment]
Just that the error appears almost immediately when psort is run without a date range so I was assuming records from the dump that have non-normal timestamps might be un-format-able with the current logic. Just a novice guess, with no real evidence.

**Comment by joachimmetz** [comment]
I see, in that case I'll have a look as soon as the download of the image completes

**Comment by joachimmetz** [comment]
The date and time value is out of bound: -9223372036854775808, which results in `date_time.GetDate()` returning None values

```
2019-03-17 11:09:43,372 [ERROR] (MainProcess) PID:10968 <interface> Event: event.956335 data type: firefox:places:bookmark display name: TSK:/Documents and Settings/Jean/Application Data/Mozilla/Firefox/Profiles/c3xj7bxx.default/places.sqlite parser chain: sqlite/firefox_history with error: unable to copy timestamp: -9223372036854775808 to a human readable date. Defaulting to: "00/00/0000"
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2394

**Comment by joachimmetz** [comment]
Changes merged, closing issue

**Comment by jsolderitsch** [comment]
Thanks for the quick turn on this issue!
