### ISSUE TITLE
Preprocess error in log2timeline on VSS

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#243]
Haven't investigated yet:
```
Processing started.
Traceback (most recent call last):
  File "./tools/log2timeline.py", line 696, in <module>
    if not Main():
  File "./tools/log2timeline.py", line 682, in Main
    tool.ProcessSources()
  File "./tools/log2timeline.py", line 624, in ProcessSources
    timezone=self._timezone)
  File "/home/onager/code/plaso/frontend/extraction_frontend.py", line 456, in ProcessSources
    self._PreprocessSetTimezone(pre_obj, timezone=timezone)
  File "/home/onager/code/plaso/frontend/extraction_frontend.py", line 322, in _PreprocessSetTimezone
    pre_obj.zone = timezone
AttributeError: 'NoneType' object has no attribute 'zone'
```

Log2timeline completed OK with no VSS turned on, this exception was raised with all VSS enabled.

**Comment by Onager** [comment]
Error is here: https://github.com/log2timeline/plaso/blob/master/plaso/frontend/extraction_frontend.py#L186

If we have an I/O error we return none instead of a blank preprocess. Will fix in https://codereview.appspot.com/246320043/

**Comment by Onager** [comment]
Additionally, IO error looks interesting: [ERROR] (MainProcess) PID:4182 <extraction_frontend> Unable to preprocess with error: Directory_Con: (tsk3.c:361) Unable to open directory: Error in metadata structure (Extension record 113332 (file ref = 0) is not for attribute list of 108821)
