### ISSUE TITLE
file_entry can be None and raises exception

### ISSUE THREAD

**Issue by bodik** [log2timeline/plaso#2456]
https://github.com/log2timeline/plaso/blob/bc6314896bb2f5cfa4c319972abfadfef3f9c441/plaso/preprocessors/linux.py#L194
```
Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 83, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 69, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 415, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/extraction_tool.py", line 188, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 273, in PreprocessSources
    self.knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 311, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 149, in CollectFromFileSystem
    knowledge_base, artifact_definition, searcher, file_system)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 82, in Collect
    source.separator)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 135, in _ParsePathSpecification
    self._ParseFileEntry(knowledge_base, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/linux.py", line 194, in _ParseFileEntry
    if file_entry.link:
AttributeError: 'NoneType' object has no attribute 'link'
```

**Comment by Onager** [comment]
Thanks for the report!

**Comment by joachimmetz** [comment]
Merged changes
