### ISSUE TITLE
Unable to stat file on mounted Windows drive possibly with file system in unclean state 

### ISSUE THREAD

**Issue by utkonos** [log2timeline/plaso#2461]
**Description of problem:**

Trying to create a timeline from a windows drive that was not shutdown properly.

**Command line and arguments:**

`psteal.py --source=/mnt/evidence --write=/home/user/drive.csv`

**Plaso version:**

plaso 20190331

**Operating system Plaso is running on:**

Ubuntu 18.10

**Installation method:**

Python 3.7.3 with virtual environment. Requirements installed via pip from the requirements.txt file.

**Debug output/tracebacks:**

```
2019-04-17 00:00:00,623 [INFO] (MainProcess) PID:21537 <data_location> Determined data location: /home/user/log2timeline/venv/share/plaso
2019-04-17 00:00:00,654 [INFO] (MainProcess) PID:21537 <artifact_definitions> Determined artifact definitions path: /home/user/log2timeline/venv/share/artifacts
 
Source path             : /mnt/evidence
Source type             : directory
Processing time         : 00:00:00
 
Processing started.
Traceback (most recent call last):
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/vfs/os_file_entry.py", line 103, in __init__
    stat_info = os.lstat(location)
OSError: [Errno 5] Input/output error: '/mnt/evidence/Windows/System32/aadtb.dll'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/user/log2timeline/venv/bin/psteal.py", line 78, in <module>
    if not Main():
  File "/home/user/log2timeline/venv/bin/psteal.py", line 63, in Main
    tool.ExtractEventsFromSources()
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/cli/psteal_tool.py", line 307, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/cli/extraction_tool.py", line 188, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/engine/engine.py", line 273, in PreprocessSources
    self.knowledge_base)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/preprocessors/manager.py", line 328, in RunPlugins
    artifacts_registry, knowledge_base, searcher)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/preprocessors/manager.py", line 196, in CollectFromWindowsRegistry
    preprocess_plugin.Collect(knowledge_base, artifact_definition, searcher)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/preprocessors/interface.py", line 234, in Collect
    for key_path in searcher.Find(find_specs=[find_spec]):
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry_searcher.py", line 265, in Find
    for matching_path in self._FindInKey(registry_key, find_specs, 0):
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry_searcher.py", line 248, in _FindInKey
    sub_registry_key, sub_find_specs, search_depth):
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry_searcher.py", line 248, in _FindInKey
    sub_registry_key, sub_find_specs, search_depth):
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry_searcher.py", line 246, in _FindInKey
    for sub_registry_key in registry_key.GetSubkeys():
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/virtual.py", line 225, in GetSubkeys
    self._GetKeyFromRegistry()
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/virtual.py", line 100, in _GetKeyFromRegistry
    self._registry_key = self._registry.GetKeyByPath(self._key_path)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry.py", line 387, in GetKeyByPath
    key_path_prefix_upper, registry_file = self._GetFileByPath(key_path_upper)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry.py", line 297, in _GetFileByPath
    registry_file = self._OpenFile(mapping.windows_path)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfwinreg/registry.py", line 347, in _OpenFile
    path, ascii_codepage=self._ascii_codepage)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/plaso/preprocessors/manager.py", line 109, in Open
    path_specification = self._path_resolver.ResolvePath(path)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/helpers/windows_path_resolver.py", line 243, in ResolvePath
    path, expand_variables=expand_variables)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/helpers/windows_path_resolver.py", line 179, in _ResolvePath
    path_segment, case_sensitive=False)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/vfs/file_entry.py", line 408, in GetSubFileEntryByName
    for sub_file_entry in self.sub_file_entries:
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/vfs/os_file_entry.py", line 206, in _GetSubFileEntries
    yield OSFileEntry(self._resolver_context, self._file_system, path_spec)
  File "/home/user/log2timeline/venv/lib/python3.7/site-packages/dfvfs/vfs/os_file_entry.py", line 107, in __init__
    exception))
dfvfs.lib.errors.BackEndError: Unable to retrieve stat object with error: [Errno 5] Input/output error: '/mnt/evidence/Windows/System32/aadtb.dll'
```

**Comment by joachimmetz** [comment]
Any indication in your system logs why the operating system cannot stat the file in the mounted file system? Have you tried running plaso directly on the device?

**Comment by utkonos** [comment]
I will check both of those. Thanks for the quick reply. The write blocker is occupied at the moment, but I will work this drive again next.

**Comment by utkonos** [comment]
Working off the /dev works. It's processing. Thanks. I will look at the system logs to see what I can add to this issue about the other way.

**Comment by joachimmetz** [comment]
Great, I'll consider if we should make plaso more resilient for this error scenario. Then again a stat failing is quite a relevant issue to be aware of.

**Comment by utkonos** [comment]
Working directly on the device from /dev is slow. For a drive size that took a couple of hours, using /dev is three days and counting. I have also tried operating on a dd image file. Is there any other options that may provide the same speed as mounting the drive via write blocker?

There are two drives that exhibit this problem, and both were not shutdown properly by windows. This appears to be related to or causing the errors seen.

**Comment by joachimmetz** [comment]
The speed highly depends on many factors e.g. what parsers you've enabled, the speed of your input device/disk, the speed of your output disk, the speed of your temporary data disk, number of workers, etc.

You'll need to be more specific for us to give any useful input on speed

**Comment by joachimmetz** [comment]
No update from reporter, closing issue.
