### ISSUE TITLE
Crash in image_export.py with missing file_entry

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2469]
Traceback, from an older version of Plaso:
```
Traceback (most recent call last):
  File "/usr/bin/image_export.py", line 57, in <module>
    if not Main():
  File "/usr/bin/image_export.py", line 36, in Main
    tool.ProcessSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/image_export_tool.py", line 770, in ProcessSources
    skip_duplicates=self._skip_duplicates)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/image_export_tool.py", line 338, in _ExtractWithFilter
    skip_duplicates=skip_duplicates)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/image_export_tool.py", line 279, in _ExtractFileEntry
    for data_stream in file_entry.data_streams:
AttributeError: 'NoneType' object has no attribute 'data_streams'
```

This looks to be because OpenFileEntry in dfvfs can return None.

**Comment by Onager** [comment]
Also an issue in https://github.com/log2timeline/plaso/blob/master/plaso/filters/file_entry.py#L398 as we check for False in the results, and not for None.

**Comment by Onager** [comment]
Ran into another crash while trying to debug this:

```
Traceback (most recent call last):
  File "./tools/image_export.py", line 57, in <module>
    if not Main():
  File "./tools/image_export.py", line 36, in Main
    tool.ProcessSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/image_export_tool.py", line 791, in ProcessSources
    skip_duplicates=self._skip_duplicates)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/image_export_tool.py", line 350, in _ExtractWithFilter
    extraction_engine.knowledge_base, artifact_filters, filter_file)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 328, in BuildFilterFindSpecs
    artifact_filter_names, environment_variables=environment_variables)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/artifact_filters.py", line 97, in BuildFindSpecs
    definition, environment_variables)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/artifact_filters.py", line 129, in _BuildFindSpecsFromArtifact
    self._knowledge_base.user_accounts)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/artifact_filters.py", line 218, in _BuildFindSpecsFromFileSourcePath
    path_glob, path_separator, user_accounts):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/path_helper.py", line 232, in ExpandUsersVariablePath
    path_segments, path_separator, user_accounts)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/path_helper.py", line 99, in _ExpandUsersVariablePathSegments
    path_segments, path_separator, user_accounts)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/path_helper.py", line 64, in _ExpandUsersHomeDirectoryPathSegments
    if cls._IsWindowsDrivePathSegment(user_path_segments[0]):
IndexError: list index out of range
```

**Comment by Onager** [comment]
It turns out the file causing the original crash is a broken symbolic link, so this was probably triggered by the behavior changed in https://github.com/log2timeline/dfvfs/issues/388

**Comment by joachimmetz** [comment]
Changes merged, closing issue.
