### ISSUE TITLE
Improve handling of error in collector

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#250]
```
Unhandled exception in collector (PID: 11193).

FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
Traceback (most recent call last):
  File "Projects/plaso/plaso/multi_processing/multi_process.py", line 278, in _Main
    self._collector.Collect(self._source_path_specs)
  File "Projects/plaso/plaso/engine/collector.py", line 113, in Collect
    source_path_spec, find_specs=self._filter_find_specs)
  File "Projects/plaso/plaso/engine/collector.py", line 77, in _ProcessPathSpec
    path_spec, resolver_context=self._resolver_context)
  File "Projects/dfvfs/dfvfs/resolver/resolver.py", line 53, in OpenFileEntry
    path_spec, resolver_context=resolver_context)
  File "Projects/dfvfs/dfvfs/resolver/resolver.py", line 163, in OpenFileSystem
    file_system.Open(path_spec=path_spec)
  File "Projects/dfvfs/dfvfs/vfs/file_system.py", line 229, in Open
    self._Open(path_spec=path_spec, mode=mode)
  File "Projects/dfvfs/dfvfs/vfs/tsk_file_system.py", line 67, in _Open
    tsk_file_system = pytsk3.FS_Info(tsk_image_object)
IOError: FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/254880043/

**Comment by Onager** [comment]
Is this fixed now?

**Comment by joachimmetz** [comment]
Yes, this should be fixed by the CL, closing issue.
