### ISSUE TITLE
IO ERRNO 13

### ISSUE THREAD

**Issue by ChopOMatic** [log2timeline/plaso#2517]
**Description of problem:**

log2timeline fails with IO ERRNO 13 

**Command line and arguments:**
```
log2timeline --no-dependencies-check --status_view window "F:\CASE 20190510\Timeline\doe.plaso" "F:\CASE 20190510\ER\TD-doe-LT\TD-doe-LT.E01"
```

**Source data:**
E01 image of a logical NTFS volume

**Plaso version:**
20190429

**Operating system Plaso is running on:**

Win10

**Installation method:**

* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch

**Debug output/tracebacks:**
```
C:\Users\chop\AppData\Local\Programs\Python\Python37-32\plaso-20190429-amd64>log2timeline --no-dependencies-check --status_view window "F:\CASE 20190510\Timeline\doe.plaso" "F:\CASE 20190510\ER\TD-doe-LT\TD-doe-LT.E01"
C:\Users\chop\AppData\Local\Programs\Python\PYTHON~1\PLASO-~1\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
2019-05-11 03:34:32,250 [INFO] (MainProcess) PID:24312 <data_location> Determined data location: C:\Users\chop\AppData\Local\Programs\Python\PYTHON~1\PLASO-~1\data
2019-05-11 03:34:32,262 [INFO] (MainProcess) PID:24312 <artifact_definitions> Determined artifact definitions path: C:\Users\chop\AppData\Local\Programs\Python\PYTHON~1\PLASO-~1\artifacts
The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2019-04-05 16:40:20.1997052
vss2            2019-04-09 14:38:04.4244283
vss3            2019-04-15 01:20:13.5097648
vss4            2019-04-22 22:15:57.7546316

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores
can be defined as: 1,3,5 (a list of comma separated values). Ranges
and lists can also be combined as: 1,3..5. The first store is 1. All
stores can be defined as "all". If no stores are specified none will
be processed. You can abort with Ctrl^C.

VSS identifiers: 1,2

Source path             : F:\CASE 20190510\ER\TD-doe-LT\TD-doe-LT.E01
Source type             : storage media image
Processing time         : 00:00:00

Processing started.
Traceback (most recent call last):
  File "tools\log2timeline.py", line 83, in <module>
  File "tools\log2timeline.py", line 69, in Main
  File "plaso\cli\log2timeline_tool.py", line 415, in ExtractEventsFromSources
  File "plaso\cli\extraction_tool.py", line 191, in _PreprocessSources
  File "logging\__init__.py", line 1200, in error
  File "logging\__init__.py", line 1293, in _log
  File "logging\__init__.py", line 1303, in handle
  File "logging\__init__.py", line 1343, in callHandlers
  File "logging\__init__.py", line 766, in handle
  File "logging\__init__.py", line 963, in emit
  File "plaso\lib\loggers.py", line 40, in _open
  File "gzip.py", line 34, in open
  File "gzip.py", line 94, in __init__
IOError: [Errno 13] Permission denied: u'C:\\Users\\chop\\AppData\\Local\\Programs\\Python\\Python37-32\\plaso-20190429-amd64\\log2timeline-20190511T033432.log.gz'
[24312] Failed to execute script log2timeline
```

**Comment by joachimmetz** [comment]
You cannot write the log file set the location with `--logfile`

**Comment by ChopOMatic** [comment]
It didn't generate the error this time, but returned to the command prompt after about 10 seconds. It generated this in the logfile I specified:

**2019-05-11 04:36:13,618 [INFO] (MainProcess) PID:2180 <engine> Preprocessing detected operating systems: Windows NT, Windows NT, Windows NT
2019-05-11 04:36:13,618 [INFO] (MainProcess) PID:2180 <extraction_tool> Parser filter expression set to: win7**

**Comment by joachimmetz** [comment]
Please provide debug output. Have a look at https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html for troubleshooting tips

**Comment by ChopOMatic** [comment]
C:\Users\chop\AppData\Local\Programs\Python\Python37-32\plaso-20190429-amd64>log2timeline --troubles
C:\Users\chop\AppData\Local\Programs\Python\PYTHON~1\PLASO-~1\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
2019-05-11 05:01:27,871 [INFO] (MainProcess) PID:25904 <data_location> Determined data location: C:\Users\chop\AppData\Local\Programs\Python\PYTHON~1\PLASO-~1\data
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

Path: C:\Users\chop\AppData\Local\Programs\Python\Python37-32\plaso-20190429-amd64\log2timeline.py

plaso - log2timeline version 20190429

Checking availability and versions of dependencies.
[OK]            Crypto version: 2.6.1
[OK]            artifacts version: 20190320
[OK]            bencode
[OK]            biplist
[OK]            certifi version: 2019.03.09
[OK]            chardet version: 3.0.4
[OK]            dateutil version: 2.8.0
[OK]            dfdatetime version: 20190116
[OK]            dfvfs version: 20190421
[OK]            dfwinreg version: 20190329
[OK]            dtfabric version: 20190120
[OK]            elasticsearch version: 6.3.1
[OK]            future version: 0.17.1
[OK]            idna
[OK]            lz4
[OPTIONAL]      missing: lzma.
[OK]            pefile version: 2019.4.18
[OK]            psutil version: 5.6.2
[OK]            pybde version: 20190317
[OK]            pyesedb version: 20181229
[OK]            pyevt version: 20181227
[OK]            pyevtx version: 20181227
[OK]            pyewf version: 20140807
[OK]            pyfsapfs version: 20190210
[OK]            pyfsntfs version: 20190104
[OK]            pyfvde version: 20190104
[OK]            pyfwnt version: 20181227
[OK]            pyfwsi version: 20181227
[OK]            pylnk version: 20181227
[OK]            pymsiecf version: 20181227
[OK]            pyolecf version: 20181231
[OK]            pyparsing version: 2.4.0
[OK]            pyqcow version: 20181227
[OK]            pyregf version: 20190303
[OK]            pyscca version: 20181227
[OK]            pysigscan version: 20190103
[OK]            pysmdev version: 20190315
[OK]            pysmraw version: 20181227
[OK]            pytsk3 version: 20190121
[OK]            pytz
[OK]            pyvhdi version: 20181227
[OK]            pyvmdk version: 20181227
[OK]            pyvshadow version: 20190323
[OK]            pyvslvm version: 20181227
[OK]            requests version: 2.21.0
[OK]            six version: 1.12.0
[OK]            sqlite3
[OK]            urllib3 version: 1.25.2
[OK]            xlsxwriter version: 1.1.7
[OK]            yaml version: 5.1
[OK]            yara version: 3.8.1
[OK]            zmq version: 18.0.1
[OK]            pysqlite2.dbapi2 version: 3.19.2

--------------------------------------------------------

2019-05-11 05:12:40,697 [DEBUG] (MainProcess) PID:1604 <extraction_tool> Starting preprocessing.
2019-05-11 05:12:54,589 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxPasswdFile
2019-05-11 05:12:54,617 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSUserPasswordHashesPlistFiles
2019-05-11 05:12:54,619 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLSBRelease
2019-05-11 05:12:54,621 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxSystemdOSRelease
2019-05-11 05:12:54,624 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxIssueFile
2019-05-11 05:12:54,627 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLocalTime
2019-05-11 05:12:54,628 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableWinDir
2019-05-11 05:12:54,630 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: windir to: "\Windows"
2019-05-11 05:12:54,634 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemConfigurationPreferencesPlistFile
2019-05-11 05:12:54,635 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxDistributionRelease
2019-05-11 05:12:54,641 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSLocalTime
2019-05-11 05:12:54,642 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSKeyboardLayoutPlistFile
2019-05-11 05:12:54,644 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableSystemRoot
2019-05-11 05:12:54,645 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: systemroot to: "\Windows"
2019-05-11 05:12:54,650 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxHostnameFile
2019-05-11 05:12:54,651 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemVersionPlistFile
2019-05-11 05:12:54,653 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCodePage
2019-05-11 05:12:55,302 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramData
2019-05-11 05:12:56,621 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:12:56,631 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsProductName
2019-05-11 05:12:56,663 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsComputerName
2019-05-11 05:12:56,665 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFilesX86
2019-05-11 05:12:56,671 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfilesx86 to: "C:\Program Files (x86)"
2019-05-11 05:12:56,671 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCurrentVersion
2019-05-11 05:12:56,676 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsTimezone
2019-05-11 05:12:56,680 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFiles
2019-05-11 05:12:56,684 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfiles to: "C:\Program Files"
2019-05-11 05:12:56,684 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableAllUsersProfile
2019-05-11 05:12:56,690 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsRegistryProfiles
2019-05-11 05:12:56,697 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppDataKnowledgeBasePlugin
2019-05-11 05:12:56,697 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: allusersappdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:12:56,697 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsProgramDataKnowledgeBasePlugin
2019-05-11 05:12:56,697 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppProfileKnowledgeBasePlugin
2019-05-11 05:12:56,697 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: allusersprofile to: "%SystemDrive%\ProgramData"
2019-05-11 05:13:05,954 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxPasswdFile
2019-05-11 05:13:05,980 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSUserPasswordHashesPlistFiles
2019-05-11 05:13:05,983 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLSBRelease
2019-05-11 05:13:05,983 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxSystemdOSRelease
2019-05-11 05:13:05,986 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxIssueFile
2019-05-11 05:13:05,989 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLocalTime
2019-05-11 05:13:05,990 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableWinDir
2019-05-11 05:13:05,992 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: windir to: "\Windows"
2019-05-11 05:13:05,996 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemConfigurationPreferencesPlistFile
2019-05-11 05:13:05,996 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxDistributionRelease
2019-05-11 05:13:06,003 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSLocalTime
2019-05-11 05:13:06,005 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSKeyboardLayoutPlistFile
2019-05-11 05:13:06,006 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableSystemRoot
2019-05-11 05:13:06,007 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: systemroot to: "\Windows"
2019-05-11 05:13:06,012 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxHostnameFile
2019-05-11 05:13:06,013 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemVersionPlistFile
2019-05-11 05:13:06,015 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCodePage
2019-05-11 05:13:06,684 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramData
2019-05-11 05:13:08,059 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:13:08,069 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsProductName
2019-05-11 05:13:08,098 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsComputerName
2019-05-11 05:13:08,101 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFilesX86
2019-05-11 05:13:08,105 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfilesx86 to: "C:\Program Files (x86)"
2019-05-11 05:13:08,108 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCurrentVersion
2019-05-11 05:13:08,111 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsTimezone
2019-05-11 05:13:08,115 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFiles
2019-05-11 05:13:08,118 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfiles to: "C:\Program Files"
2019-05-11 05:13:08,119 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableAllUsersProfile
2019-05-11 05:13:08,125 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsRegistryProfiles
2019-05-11 05:13:08,131 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppDataKnowledgeBasePlugin
2019-05-11 05:13:08,131 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: allusersappdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:13:08,131 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsProgramDataKnowledgeBasePlugin
2019-05-11 05:13:08,131 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppProfileKnowledgeBasePlugin
2019-05-11 05:13:13,769 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxPasswdFile
2019-05-11 05:13:13,782 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSUserPasswordHashesPlistFiles
2019-05-11 05:13:13,785 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLSBRelease
2019-05-11 05:13:13,786 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxSystemdOSRelease
2019-05-11 05:13:13,788 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxIssueFile
2019-05-11 05:13:13,790 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxLocalTime
2019-05-11 05:13:13,792 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableWinDir
2019-05-11 05:13:13,792 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: windir to: "\Windows"
2019-05-11 05:13:13,796 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemConfigurationPreferencesPlistFile
2019-05-11 05:13:13,798 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxDistributionRelease
2019-05-11 05:13:13,802 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSLocalTime
2019-05-11 05:13:13,805 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSKeyboardLayoutPlistFile
2019-05-11 05:13:13,806 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableSystemRoot
2019-05-11 05:13:13,808 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: systemroot to: "\Windows"
2019-05-11 05:13:13,812 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: LinuxHostnameFile
2019-05-11 05:13:13,812 [DEBUG] (MainProcess) PID:1604 <manager> Running file system preprocessor plugin: MacOSSystemVersionPlistFile
2019-05-11 05:13:13,813 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCodePage
2019-05-11 05:13:14,279 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramData
2019-05-11 05:13:15,243 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:13:15,250 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsProductName
2019-05-11 05:13:15,266 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsComputerName
2019-05-11 05:13:15,269 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFilesX86
2019-05-11 05:13:15,273 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfilesx86 to: "C:\Program Files (x86)"
2019-05-11 05:13:15,275 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsCurrentVersion
2019-05-11 05:13:15,279 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsTimezone
2019-05-11 05:13:15,280 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableProgramFiles
2019-05-11 05:13:15,285 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: programfiles to: "C:\Program Files"
2019-05-11 05:13:15,285 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableAllUsersProfile
2019-05-11 05:13:15,289 [DEBUG] (MainProcess) PID:1604 <manager> Running Windows Registry preprocessor plugin: WindowsRegistryProfiles
2019-05-11 05:13:15,295 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppDataKnowledgeBasePlugin
2019-05-11 05:13:15,295 [DEBUG] (MainProcess) PID:1604 <windows> setting environment variable: allusersappdata to: "%SystemDrive%\ProgramData"
2019-05-11 05:13:15,295 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsProgramDataKnowledgeBasePlugin
2019-05-11 05:13:15,295 [DEBUG] (MainProcess) PID:1604 <manager> Running knowledge base preprocessor plugin: WindowsAllUsersAppProfileKnowledgeBasePlugin
2019-05-11 05:13:15,301 [INFO] (MainProcess) PID:1604 <engine> Preprocessing detected operating systems: Windows NT, Windows NT, Windows NT
2019-05-11 05:13:15,301 [DEBUG] (MainProcess) PID:1604 <extraction_tool> Preprocessing done.
2019-05-11 05:13:15,301 [INFO] (MainProcess) PID:1604 <extraction_tool> Parser filter expression set to: win7
2019-05-11 05:13:15,302 [DEBUG] (MainProcess) PID:1604 <log2timeline_tool> Starting extraction in multi process mode.
2019-05-11 05:13:15,302 [DEBUG] (MainProcess) PID:1604 <zeromq_queue> Creating socket for main_task_queue
2019-05-11 05:13:15,315 [DEBUG] (MainProcess) PID:1604 <zeromq_queue> main_task_queue bound to random port 6344
2019-05-11 05:13:15,316 [DEBUG] (MainProcess) PID:1604 <zeromq_queue> main_task_queue responder thread started

**Comment by joachimmetz** [comment]
Any entry in your Application EventLog that (one of the dependencies of) log2timeline has segfaulted?

**Comment by ChopOMatic** [comment]
I'll take a look after some sleep. Thanks.

**Comment by ChopOMatic** [comment]
Can't find anything referencing log2timeline or recognizable dependencies in the Application event log.

**Comment by joachimmetz** [comment]
> Can't find anything referencing log2timeline or recognizable dependencies in the Application event log.

any application crashes around the time you start log2timeline?

**Comment by ChopOMatic** [comment]
Nope, here's the only events being generated from the time the command is entered until it errors out:

![image](https://user-images.githubusercontent.com/8518789/57579084-9f4dcc80-745c-11e9-90b3-8e2c4d17677e.png)

**Comment by joachimmetz** [comment]
> Nope, here are the only events being generated from the time the command is entered until it errors out:

Unfortunately , except for the permission issue, I see no indication of any error in the information you've sent me.

**Comment by joachimmetz** [comment]
could you explain if "Python37-32" in "Python37-32\plaso-20190429-amd64" is 32-bit

Note that amd64 is 64-bit

**Comment by ChopOMatic** [comment]
Well, big DUH on me. Lemme fix that. I'll be back.

**Comment by ChopOMatic** [comment]
Still no go. Uninstalled Python. Reinstalled 64-bit version. It doesn't generate the error dialog anymore. It says PROCESSING STARTED and after a minute or so returns to the command prompt without having generated anything.

**Comment by joachimmetz** [comment]
If you're using the packaged windows release you don't need to install Python separately see:
https://github.com/log2timeline/plaso/wiki/Windows-Packaged-Release

(this seems to be missing from the documentation on readthedocs https://github.com/log2timeline/plaso/issues/2468)

A typical issue for the packaged release is missing Visual C++ Redistributable libraries

As I said unfortunately, except for the permission issue, I see no indication of any error in the information you've sent me. The abrupt end hints to a segfault in one of the core components to me, such as python or pyzmq.

* see if changing destination / source locations helps
* see if there is any information hinting to a segfault
* run a tracing tool (Process Monitor) to see that indicates what might be going on

**Comment by ChopOMatic** [comment]
Thanks. I'll try uninstalling Python and see how that goes. You happen to know which of the Visual C++ libraries it needs?

I have it working now in both a SIFT VM and on a Mac Mini. Really wanted to run it on my native iron, but it's about to wear me out.

**Comment by joachimmetz** [comment]
VS2017 for the Python 3.7 and VS2008 for Python 2.7

Also see: https://github.com/log2timeline/l2tbinaries/blob/master/README.md

**Comment by ChopOMatic** [comment]
Roger roger.

**Comment by joachimmetz** [comment]
@ChopOMatic any luck with the VS runtime?

**Comment by ChopOMatic** [comment]
Nope. I stubbornly continue trying, running it from different drives, etc., but the result is the same: No more error messages, but after a few seconds it just returns to the command prompt.

Getting what I need done by generating the timelines in a SIFT VM.

**Comment by ChopOMatic** [comment]
BTW, psort works fine.

**Comment by joachimmetz** [comment]
The packed Windows version is no longer provided/supported due to PyInstaller continuity. Closing issue as obsolete.
