### ISSUE TITLE
Set default encoding to 'undefined' to catch implicit conversions between byte and unicode strings

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#252]
Ref https://docs.python.org/2/library/codecs.html

**Comment by joachimmetz** [comment]
@Onager let's look into this after the 1.5.0 release

**Comment by joachimmetz** [comment]
```
PYTHONIOENCODING="undefined" ./run_tests.py 
Traceback (most recent call last):
  File "./run_tests.py", line 24, in <module>
    if not dependency_helper.CheckTestDependencies():
  File "./utils/dependencies.py", line 322, in CheckTestDependencies
    if not self.CheckDependencies(verbose_output=verbose_output):
  File "./utils/dependencies.py", line 292, in CheckDependencies
    print('Checking availability and versions of dependencies.')
  File "/usr/lib64/python2.7/encodings/undefined.py", line 19, in encode
    raise UnicodeError("undefined encoding")
UnicodeError: undefined encoding
```

**Comment by joachimmetz** [comment]
```
diff --git a/run_tests.py b/run_tests.py
index f2ecb460..0606f14d 100755
--- a/run_tests.py
+++ b/run_tests.py
@@ -24,6 +24,11 @@ if __name__ == '__main__':
   if not dependency_helper.CheckTestDependencies():
     sys.exit(1)
 
+  # Set default encoding to undefined to detect missing string
+  # decoding/encoding.
+  reload(sys)
+  sys.setdefaultencoding('undefined')
+
   test_suite = unittest.TestLoader().discover('tests', pattern='*.py')
   test_results = unittest.TextTestRunner(verbosity=2).run(test_suite)
   if not test_results.wasSuccessful():
```

```
Traceback (most recent call last):
  File "./run_tests.py", line 32, in <module>
    test_suite = unittest.TestLoader().discover('tests', pattern='*.py')
  File "/usr/lib64/python2.7/unittest/loader.py", line 176, in discover
    if not top_level_dir in sys.path:
  File "/usr/lib64/python2.7/encodings/undefined.py", line 22, in decode
    raise UnicodeError("undefined encoding")
UnicodeError: undefined encoding
```

**Comment by joachimmetz** [comment]
After adding `from __future__ import unicode_literals`

```
Traceback (most recent call last):
  File "./run_tests.py", line 34, in <module>
    test_suite = unittest.TestLoader().discover('tests', pattern='*.py')
  File "/usr/lib64/python2.7/unittest/loader.py", line 174, in discover
    top_level_dir = os.path.abspath(top_level_dir)
  File "/usr/lib64/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/usr/lib64/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
  File "/usr/lib64/python2.7/encodings/undefined.py", line 22, in decode
    raise UnicodeError("undefined encoding")
UnicodeError: undefined encoding
```

**Comment by joachimmetz** [comment]
@Onager removing this from the milestone, this seems to require more research

**Comment by joachimmetz** [comment]
Also this change https://github.com/log2timeline/plaso/issues/1268 will force all strings to be unicode and Python 3 is more strict in checking for string to byte stream conversions.

**Comment by Onager** [comment]
This is no longer needed - with the migration to Python3 we'll run into these conversions any way.
