### ISSUE TITLE
Error specifying --credential key_data

### ISSUE THREAD

**Issue by aarontp** [log2timeline/plaso#2527]
**Description of problem:**

When specifying a bitlocker key I get a python traceback error:
$ log2timeline.py --partitions 4 --credential key_data:<long string of hex digits> my-image.plaso  my-image.dd

2019-05-14 23:15:10,625 [INFO] (MainProcess) PID:51700 <data_location> Determined data location: /usr/share/plaso
2019-05-14 23:15:10,638 [INFO] (MainProcess) PID:51700 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 83, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 24, in Main
    if not tool.ParseArguments():
  File "/usr/lib/python3/dist-packages/plaso/cli/log2timeline_tool.py", line 264, in ParseArguments
    self.ParseOptions(options)
  File "/usr/lib/python3/dist-packages/plaso/cli/log2timeline_tool.py", line 329, in ParseOptions
    self._ParseStorageMediaOptions(options)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 405, in _ParseStorageMediaOptions
    self._ParseCredentialOptions(options)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 371, in _ParseCredentialOptions
    credential_data = credential_data.decode('hex')
AttributeError: 'str' object has no attribute 'decode'

**Command line and arguments:**

$ log2timeline.py --partitions 4 --credential key_data:<long string of hex digits> my-image.dd my-image.plaso

**Source data:**

Windows disk image.

**Plaso version:**

plaso - log2timeline version 20190429

**Operating system Plaso is running on:**

Debian

**Comment by joachimmetz** [comment]
Which python version are you using 2 or 3?

**Comment by joachimmetz** [comment]
Assuming Python 3 as a temporary work around you can try changing `credential_data = credential_data.decode('hex')` into `credential_data = codecs.decode(credential_data, 'hex')` in plaso/cli/storage_media_tool.py

**Comment by joachimmetz** [comment]
Changes to fix python3 support https://github.com/log2timeline/plaso/pull/2528

**Comment by joachimmetz** [comment]
changes merged, closing issue

**Comment by aarontp** [comment]
Awesome, thanks for the fast response! :)
