### ISSUE TITLE
exception in plistlib

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#254]
```
2015-07-07 14:29:16,852 [ERROR] (Worker_00 ) PID:6798 <worker> list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/engine/worker.py", line 447, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/engine/worker.py", line 404, in _ProcessFileEntry
    self._ParseFileEntryWithParser(parser_object, file_entry)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/engine/worker.py", line 200, in _ParseFileEntryWithParser
    parser_object.UpdateChainAndParse(self._parser_mediator)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/parsers/interface.py", line 289, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/parsers/plist.py", line 112, in ParseFileObject
    top_level_object = self.GetTopLevel(file_object, file_entry.name)
  File "/usr/lib/python2.7/site-packages/plaso-1.3.0_20150701-py2.7.egg/plaso/parsers/plist.py", line 54, in GetTopLevel
    top_level_object = binplist.readPlist(file_object)
  File "/usr/lib/python2.7/site-packages/binplist/binplist.py", line 902, in readPlist
    return plistlib.readPlist(file_obj)
  File "/usr/lib64/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/usr/lib64/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
  File "/usr/lib64/python2.7/plistlib.py", line 418, in handleEndElement
    handler()
  File "/usr/lib64/python2.7/plistlib.py", line 466, in end_integer
    self.addObject(int(self.getData()))
  File "/usr/lib64/python2.7/plistlib.py", line 425, in addObject
    self.stack[-1][self.currentKey] = value
TypeError: list indices must be integers, not str
```

**Comment by joachimmetz** [comment]
The question here is "is this a plaso bug" or something in plistlib

**Comment by kiddinn** [comment]
this is an issue with plistlib, but the question is whether or not the tool was actually parsing a plist file or if it was parsing something completely different. In the latter case we should add an exception handling in plaso for TypeError and then raise unable to parse file.

@rodgermoore can you still reproduce this issue? Do you know what file caused this exception to be raised? It would probably be enough to know the filename itself.

Reading over the issue #251 it seems like this came up while trying to parse a NTFS volume, so I'm assuming it's most likely that this got raised when the plist library attempted to open up a file that is not a plist file.

**Comment by Onager** [comment]
@rodgermoore Are you able to reproduce this still?

**Comment by Onager** [comment]
Removing as a 1.4 release blocker, as we don't have data to reproduce this at present.

**Comment by Onager** [comment]
Closing out this stale issue.
