### ISSUE TITLE
Handle CacheFullError more elegantly

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#257]
Handle CacheFullError more elegantly

* [x] add file system cache reference checking - not applicable
* [x] stop the worker when this error occurs

**Comment by joachimmetz** [comment]
Add file system cache reference checking.

```
2015-07-13 13:16:57,177 [ERROR] (Worker_00 ) PID:6164 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso/engine/worker.py", line 439, in _ProcessPathSpec
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 53, in OpenFileEntry
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 166, in OpenFileSystem
    file_system.Open(path_spec=path_spec)
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/file_system.py", line 234, in Open
    self._resolver_context.CacheFileSystem(path_spec, self)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/context.py", line 62, in CacheFileSystem
    self._file_system_cache.CacheObject(identifier, file_system)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.
```

**Comment by joachimmetz** [comment]
The issue seems to happen when there is an error while processing a gzip compressed files. Could it be that the file entry is not dereferenced?

**Comment by joachimmetz** [comment]
It seems a file_entry reference is kept around on the local frames f_locals, explicitly forcing file_entry = None triggers deference.

**Comment by joachimmetz** [comment]
Work around: https://codereview.appspot.com/257800043/
