### ISSUE TITLE
Running against a test image fails

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#262]
The following run shows how the tool does not start processing:

**$ log2timeline.py /tmp/foobar.plaso syn_null2014ctf.dd**

```
The following Volume Shadow Snapshots (VSS) were found:
Identifier	VSS store identifier			Creation Time
vss1		6101d464-812d-11e3-9952-40f02f0e6321	2014-01-19T17:45:46.579218+00:00

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores can
be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can
also be combined as: 1,3..5. The first store is 1. All stores can be defined
as "all". If no stores are specified none will be processed. You
can abort with Ctrl^C.

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.3.0-20150715', u'log2timeline.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 676, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 662, in Main
    tool.ProcessSources()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 558, in ProcessSources
    scan_context = self.ScanSource()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/plaso/cli/storage_media_tool.py", line 974, in ScanSource
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/plaso/cli/storage_media_tool.py", line 659, in _ScanVolume
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/plaso/cli/storage_media_tool.py", line 694, in _ScanVolumeScanNode
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.0_20150715-py2.7.egg/plaso/cli/storage_media_tool.py", line 763, in _ScanVolumeScanNodeVSS
AttributeError: 'unicode' object has no attribute 'reverse'
```

Specifying "--vss_stores=1" makes the tool run properly. same with vss_stores all

**Comment by kiddinn** [comment]
added a CL: http://codereview.appspot.com/254170043

**Comment by kiddinn** [comment]
CL submitted, this is fixed
