### ISSUE TITLE
Minor issues with preg

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#264]
When running:

$ preg.py -p userassist test_data/NTUSER.DAT 

I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/preg.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.3.0-20150715', u'preg.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/preg.py", line 1711, in <module>
    if not Main():
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/preg.py", line 1700, in Main
    tool.RunModeRegistryPlugin()
  File "/Library/Python/2.7/site-packages/plaso-1.3.0_20150715-py2.7.egg/EGG-INFO/scripts/preg.py", line 865, in RunModeRegistryPlugin
    plugin_list = self.plugin_names.split(u',')
AttributeError: 'list' object has no attribute 'split'
```

CL already out to fix it: https://codereview.appspot.com/253200043/

**Comment by kiddinn** [comment]
CL pushed in, confirmed works now.
