### ISSUE TITLE
BDE: Handle unsupported credentials

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#268]
When running:

```
$ log2timeline.py foobar.plaso bde_enabled_windows.dd 
[INFO] Data files will be loaded from /usr/share/plaso by default.
The following partitions were found:
Identifier      Offset (in bytes)       Size (in bytes)
p1              1048576 (0x00100000)    350.0MiB / 367.0MB (367001600 B)
p2              368050176 (0x15f00000)  148.7GiB / 159.7GB (159671910400 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
p2
Found a BitLocker encrypted volume.
Supported credentials:

  0. startup_key
  1. recovery_password
  2. password
  3. skip

Note that you can abort with Ctrl^C.

Select a credential to unlock the volume: 2
Enter credential data: 
```

And when entering the wrong user password on the prompt, leads to:

```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 676, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 662, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 558, in ProcessSources
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 974, in ScanSource
    self._ScanVolume(scan_context, sub_scan_node)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 659, in _ScanVolume
    self._ScanVolumeScanNode(scan_context, sub_scan_node)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 691, in _ScanVolumeScanNode
    self._ScanVolumeScanNodeEncrypted(scan_context, scan_node)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 731, in _ScanVolumeScanNodeEncrypted
    scan_context, volume_scan_node, credentials)
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 465, in _PromptUserForEncryptedVolumeCredential
    credential_data)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 726, in Unlock
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 63, in _Open
    self._file_object = self._OpenFileObject(path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/bde_file_io.py", line 39, in _OpenFileObject
    bde_volume, path_spec, file_object, resolver.Resolver.key_chain)
  File "/usr/lib/python2.7/dist-packages/dfvfs/lib/bde.py", line 26, in BdeVolumeOpen
    bde_volume.open_file_object(file_object)
IOError: pybde_volume_open_file_object: unable to open volume. libbde_metadata_read_volume_master_key: invalid metadata - missing password volume master key. libbde_volume_open_read_keys_from_metadata: unable to read volume master key from metadata. libbde_volume_open_read: unable to read keys from primary metadata. libbde_volume_open_file_io_handle: unable to read from file IO handle.
```

**Comment by joachimmetz** [comment]
This error is not due to a wrong password, but due to the password credential not supported by the volume. This is work in progress.

**Comment by kiddinn** [comment]
ok, but can we have a more graceful way of handling it to notify the end user?

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/302200043/
