### ISSUE TITLE
Log2timeline exception in the Status View when handling filenames with non-ASCII characters

### ISSUE THREAD

**Issue by Mustachu** [log2timeline/plaso#2704]
**Description of problem:**

log2timeline status windows is throwing an exception when trying to display a filename with non-ascii characters. The following exception happens when processing the file: `/ProgramData/Modèles`

```
Identifier      PID     Status          Memory          Sources         Events          File
Main            106051  running         264.1 MiB       359 (76)        724 (60)        
Worker_00       106056  collecting      196.4 MiB       25 (0)          13 (0)          TSK:/ProgramData/Bureau
Worker_01       106058  collecting      188.4 MiB       24 (3)          22 (4)          TSK:/ProgramData/Microsoft
Worker_02       106060  collecting      179.3 MiB       58 (35)         21 (4)          TSK:/ProgramData/Favorites
Worker_03       106062  collecting      196.4 MiB       1 (0)           20 (0)          TSK:/Program Files (x86)/Windows NT
Worker_04       106064  collecting      178.7 MiB       41 (0)          21 (4)          TSK:/ProgramData/Start Menu
Worker_05       106066  collecting      188.4 MiB       25 (23)         28 (4)          TSK:/ProgramData/VMware
Worker_06       106068  collecting      180.6 MiB       2 (0)           21 (0)          TSK:/ProgramData/Favoris
Worker_07       106070  collecting      181.8 MiB       5 (0)           21 (0)          TSK:/ProgramData/Documents
Worker_08       106072  collecting      196.4 MiB       18 (0)          21 (0)          TSK:/Program Files (x86)/Uninstall Information
Worker_09       106074  collecting      188.4 MiB       4 (3)           25 (4)          TSK:/ProgramData/Templates
Worker_10       106076  idle            189.0 MiB       0 (0)           123 (4)         TSK:/ProgramData/Application Data
Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/task_engine.py", line 560, in _StatusUpdateThreadMain
    self._status_update_callback(self._processing_status)
  File "/usr/lib/python3/dist-packages/plaso/cli/status_view.py", line 300, in _PrintExtractionStatusUpdateWindow
    table_view.Write(self._output_writer)
  File "/usr/lib/python3/dist-packages/plaso/cli/views.py", line 301, in Write
    self._WriteRow(output_writer, values)
  File "/usr/lib/python3/dist-packages/plaso/cli/views.py", line 252, in _WriteRow
    output_writer.Write(row_strings)
  File "/usr/lib/python3/dist-packages/plaso/cli/tools.py", line 572, in Write
    sys.stdout.write(string)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 108: ordinal not in range(128)
```

log2timeline continues to run after throwing the error, but:
1. there is no more update in the status view (the screen stays the same until the end)
2. I had to manually `Ctrl+C` log2tmeline to get my screen again, even though log2timeline correctly finished to parse the image (I assumed that from seeing no more workers when running `top`)

**Command line and arguments:**

`log2timeline.py <OUTPUT_FILE.plaso> <INPUT_FILE_flat.vmdk>` (and a second time with -d)

**Source data:**

Unfortunately, I can't share the source.

**Plaso version:**

plaso - log2timeline version 20190429

**Operating system Plaso is running on:**

Ubuntu 18.04

**Installation method:**

Installed from [GiFT PPA](https://launchpad.net/~gift) stable track

**Debug output/tracebacks:**

The debug logs does not show any related ERROR (but again, parsing seems to work fine). Debug log from the `/ProgramData/Modèles` file

```
2019-07-08 14:02:42,898 [DEBUG] (MainProcess) PID:7219 <task_manager> Created task: bd0d12de08a441af908f1c4ea44cf89f.
2019-07-08 14:02:42,899 [DEBUG] (MainProcess) PID:7219 <task_engine> Scheduled task bd0d12de08a441af908f1c4ea44cf89f for path specification type: OS, location: <PATH>-flat.vmdk
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00100000
type: TSK, inode: 66897, location: /ProgramData/Modèles
```

**Comment by joachimmetz** [comment]
What is your LANG environment variable set to?

`echo $LANG`

**Comment by Mustachu** [comment]
`$LANG` is correctly set to `fr_FR.utf8`.  `LC_ALL` was set to `C` but changing it did not change the results, still getting the same exception. I have no problems to print the character is my terminal: 
```
$ echo "èé" 
èé
```

**Comment by joachimmetz** [comment]
Based on the trace back:
`UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 108: ordinal not in range(128)`

For some reason "string" appears to be a byte string instead of a Unicode string on your configuration. I'll see if I can reproduce it

**Comment by joachimmetz** [comment]
Python 3.3 changed Unicode handling significantly, closing this one as obsolete. Reopen if still and issue.
