### ISSUE TITLE
Elasticsearch errors when storage file contains bytes

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2706]
**Description of problem:**
Timesketch/elasticsearch export fails when there's a byte string in the storage file

**Command line and arguments:**

Using the elasticsearch output modules

**Source data:**

N/A

**Plaso version:**

20190708

**Operating system Plaso is running on:**

N/A

**Installation method:**

Timesketch/docker

**Debug output/tracebacks:**

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 83, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 69, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 563, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1032, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 549, in _ExportEvents
    deduplicate_events=deduplicate_events)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 451, in _ExportEvent
    deduplicate_events=deduplicate_events)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 598, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 125, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 78, in WriteEvent
    self.WriteEventBody(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 342, in WriteEventBody
    self._InsertEvent(event, event_data, event_tag)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 227, in _InsertEvent
    self._FlushEvents()
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 114, in _FlushEvents
    index=self._index_name, request_timeout=self._DEFAULT_REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 1165, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 195, in _bulk_body
    body = '\n'.join(map(self.transport.serializer.dumps, body))
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/serializer.py", line 50, in dumps
    raise SerializationError(data, e)
elasticsearch.exceptions.SerializationError: ({'data_type': 'syslog:line', 'offset': 0, 'body': 'Started Virtual filesystem service - Media Transfer Protocol monitor.', 'sha256_hash': '5ffa867ed64c6279a875b59b517d7306a40d2e02b87ff44a1adf63d76485e828', 'display_name': 'TSK:/var/log/installer/syslog', 'severity': b'', 'reporter': 'systemd', 'pid': 1382, 'parser': 'syslog', 'filename': '/var/log/installer/syslog', 'pathspec': '{"__type__": "PathSpec", "location": "/var/log/installer/syslog", "inode": 262666, "parent": {"__type__": "PathSpec", "location": "/p1", "start_offset": 1048576, "part_index": 2, "parent": {"__type__": "PathSpec", "parent": {"__type__": "PathSpec", "location": "/home/jbn/codelab.dd", "type_indicator": "OS"}, "type_indicator": "RAW"}, "type_indicator": "TSK_PARTITION"}, "type_indicator": "TSK"}', 'inode': 262666, 'hostname': 'ubuntu', 'datetime': '2018-11-29T12:26:54+00:00', 'timestamp': 1543494414000000, 'timestamp_desc': 'Content Modification Time', 'message': '[systemd, pid: 1382] Started Virtual filesystem service - Media Transfer Protocol monitor.', 'tag': [], 'source_short': 'LOG', 'source_long': 'Log File'}, TypeError("Unable to serialize b'' (type: <class 'bytes'>)",))
```

**Comment by joachimmetz** [comment]
Per conversation add a safe guard to catch bytes attributes in the output module and think about catching events that define bytes attributes earlier.

**Comment by joachimmetz** [comment]
Some change to force byte values to empty strings https://github.com/log2timeline/plaso/pull/2707
