### ISSUE TITLE
Winlnk formatter issue

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2720]
Crashing on end-to-end tests:

```
2019-07-15 08:04:01,957 [INFO] (MainProcess) PID:5499 <data_location> Determined data location: /tmp/workspace/plaso-ubuntu-e2e-registrar-py3/data
Traceback (most recent call last):
  File "./tools/psort.py", line 85, in <module>
    if not Main():
  File "./tools/psort.py", line 67, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/cli/psort_tool.py", line 568, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/multi_processing/psort.py", line 1007, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/multi_processing/psort.py", line 542, in _ExportEvents
    deduplicate_events=deduplicate_events)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/multi_processing/psort.py", line 444, in _ExportEvent
    deduplicate_events=deduplicate_events)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/multi_processing/psort.py", line 591, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/interface.py", line 125, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_tag)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/interface.py", line 78, in WriteEvent
    self.WriteEventBody(event, event_data, event_tag)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/dynamic.py", line 439, in WriteEventBody
    event, event_data, event_tag, field_name)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/dynamic.py", line 360, in GetFormattedField
    output_value = callback_function(event, event_data)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/dynamic.py", line 163, in _FormatMessage
    message, _ = self._output_mediator.GetFormattedMessages(event_data)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/output/mediator.py", line 90, in GetFormattedMessages
    return event_formatter.GetMessages(self._formatter_mediator, event)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/formatters/winlnk.py", line 85, in GetMessages
    event_values['linked_path'] = self._GetLinkedPath(event_data)
  File "/tmp/workspace/plaso-ubuntu-e2e-registrar-py3/plaso/formatters/winlnk.py", line 57, in _GetLinkedPath
    linked_path = '\\'.join([working_directory, linked_path])
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by joachimmetz** [comment]
could be introduced by https://github.com/log2timeline/plaso/commit/606c54f3eb8e7ec7f14102404037865cccf09206

having a look later

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2721
