### ISSUE TITLE
latest 64-bit pyinstaller build has an issue with pyzmq

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2722]
latest 64-bit pyinstaller build has an issue with pyzmq

```
.\log2timeline.exe : Traceback (most recent call last):
At line:1 char:1
+ .\log2timeline.exe --status-view=linear test.plaso ..\plaso\test_data ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "tools\log2timeline.py", line 14, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "plaso\cli\log2timeline_tool.py", line 30, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "plaso\multi_processing\task_engine.py", line 19, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "plaso\engine\zeromq_queue.py", line 17, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\zmq\__init__.py", line 47, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\zmq\backend\__init__.py", line 40, in <module>
  File "site-packages\zmq\backend\__init__.py", line 27, in <module>
  File "site-packages\zmq\backend\select.py", line 28, in select_backend
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script log2timeline
```

To do:

* rebuild 64-bit pyinstaller build
* check why test script is not returning an error

**Comment by joachimmetz** [comment]
Pushed new build
