### ISSUE TITLE
Fix: uncaught AttributeError

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#276]
* [ ] Determine which path spec is causing this

```
Traceback (most recent call last):
  File "plaso/engine/worker.py", line 169, in _ParseFileEntryWithParser
    parser_object.UpdateChainAndParse(self._parser_mediator)
  File "plaso/parsers/interface.py", line 72, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "plaso/parsers/interface.py", line 256, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "plaso/parsers/custom_destinations.py", line 142, in ParseFileObject
    lnk_file_object = resolver.Resolver.OpenFileObject(path_spec)
  File "dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "dfvfs/file_io/data_range_io.py", line 90, in _Open
    path_spec.parent, resolver_context=self._resolver_context)
  File "dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "dfvfs/file_io/file_io.py", line 75, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "dfvfs/file_io/tsk_file_io.py", line 62, in _Open
    self._tsk_file = file_entry.GetTSKFile()
AttributeError: 'NoneType' object has no attribute 'GetTSKFile'
```

So file entry is None here.
```
    file_entry = self._file_system.GetFileEntryByPathSpec(path_spec)
    self._tsk_file = file_entry.GetTSKFile()
```

**Comment by joachimmetz** [comment]
Error path is now handled: https://github.com/log2timeline/dfvfs/blob/master/dfvfs/file_io/tsk_file_io.py#L62

Closing issue.
