### ISSUE TITLE
pyewf issues when reading E01 file.

### ISSUE THREAD

**Issue by Mozunu** [log2timeline/plaso#2761]
**Description of problem:**

When trying to parse E01 images all plaso tools fail after printing just 2 lines - details below.

**Command line and arguments:**

```
alex@frostmourne:~$ image_export.py -f /mnt/c/DFIR/windows_artifacts.txt  -w /mnt/d/artifacts/ /mnt/d/frostmourne.E01
2019-10-19 18:22:47,888 [INFO] (MainProcess) PID:13561 <data_location> Determined data location: /usr/share/plaso
2019-10-19 18:22:47,889 [INFO] (MainProcess) PID:13561 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
```

**Source data:**

I am using an E01 disk image from a drive on my laptop; approximate size ~ 380GB.

**Plaso version:**

Tested the issue with two different versions:
20190916
20190708

**Operating system Plaso is running on:**
I can repro this on:
- WSL 1804 & 1604 running on Win10 1903.
- Ubuntu 18.04 fresh installed VM.
- Windows 10 1903.

**Installation method:**

1/ Installed from [GiFT PPA][https://launchpad.net/~gift] stable track
2/ Using the pre-compiled Windows EXE binary files.

**Debug output/tracebacks:**
```

2019-10-19 18:08:50,788 [WARNING] (MainProcess) PID:21044 <image_export> Unable to scan for a supported filesystem with error: Unable to scan source with error: Unable to process source path specification with error: pyewf_handle_open_file_objects: unable to open file. libcdata_internal_array_resize: invalid entries size value exceeds maximum.
 libcdata_array_resize: unable to resize array.
 libmfdata_list_resize: unable to resize elements array.
 libewf_segment_file_read_volume_section: unable to resize chunk table list.
 libewf_handle_open_read_segment_files: unable to read section: volume.
 libewf_handle_open_file_io_pool: unable to read segment files..
Most likely the image format is not supported by the tool.
```

**Comment by joachimmetz** [comment]
which version of libewf/pyewf are you using?

**Comment by Mozunu** [comment]
Thank you for your fast reply! The image was taken with FTK Imager v4.2.1.4. The libewf version seems to be 2.0.0 (in WSL Ubuntu 1804).

I did a few more tests and I cannot repro the issue anymore for:
- raw images
- E01 with no compression
- E01 with compression but under 100GB (resulting image).

Strange enough I can open without any issues that image (of 380GB) in FTK and extract anything I want from it.
Also the header seems correctly formatted (when compared to other E01 images with compression). 
I will redo the image and I think we can close this one. 

Thanks again!

**Comment by joshlemon** [comment]
Just wanted to relight this thread as it looks like this is still an issue. I haven't managed to figure out why this is occurring, however, it does in both the installed and docker version for 20200717.

Initially, I was using E01 images that were broken into 100Gb sizes with the total expanded size ~1Tb. I've tried re-capturing the image as a single E01 and still had the same issue.

Using the Docker version log2timeline just fails early on with:
```
Unable to scan source with error: Unable to process source path specification with error: pyewf_handle_open_file_objects: unable to open file. libcdata_internal_array_resize: invalid entries size value exceeds maximum. libcdata_array_resize: unable to resize array. libmfdata_list_resize: unable to resize elements array. libewf_segment_file_read_volume_section: unable to resize chunk table list. libewf_handle_open_read_segment_files: unable to read section: volume. libewf_handle_open_file_io_pool: unable to read segment files..
```

Using an installed version it gets a little further, it'll read the VSS information, then as it starts to process files it fails with the following output:
```
Traceback (most recent call last):
  File "/Users/useraccount/plaso_env/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20200717', 'log2timeline.py')
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/log2timeline.py", line 97, in <module>
    if not Main():
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/log2timeline.py", line 72, in Main
    tool.ExtractEventsFromSources()
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/cli/log2timeline_tool.py", line 445, in ExtractEventsFromSources
    processing_status = extraction_engine.ProcessSources(
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 817, in ProcessSources
    extraction_process = self._StartWorkerProcess('', storage_writer)
  File "/Users/useraccount/plaso_env/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 572, in _StartWorkerProcess
    process.start()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
^CException ignored in: <module 'threading' from '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
```
I suspect this is something related to libewf, using ewfverify throws this error:
```
ewfverify 20140808

Unable to open EWF image file(s).
libcdata_internal_array_resize: invalid entries size value exceeds maximum.
libcdata_array_resize: unable to resize array.
libmfdata_list_resize: unable to resize elements array.
libewf_segment_file_read_volume_section: unable to resize chunk table list.
libewf_handle_open_read_segment_files: unable to read section: volume.
libewf_handle_open_file_io_pool: unable to read segment files.
libewf_handle_open: unable to open handle using a file IO pool.
verification_handle_open_input: unable to open files.
```

I've also tested the above on different OSs and still run into the same issues.

Loading the same E01's in Arsenal Image Mounter or FTK works perfectly fine. I'm not sure if this is a size issue with the E01's and libewf.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libewf-legacy/issues/9
