### ISSUE TITLE
PyInstaller build raises exception in pyzmq

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2778]
Running make_check.bat with PyInstaller plaso-20190916-py3.7-amd64.zip build raises exception in pyzmq

```
Exception ignored in: <function Socket.__del__ at 0x000001D4F7201488>
Traceback (most recent call last):
  File "site-packages\zmq\sugar\socket.py", line 67, in __del__
  File "site-packages\zmq\sugar\socket.py", line 105, in close
  File "site-packages\zmq\sugar\context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Processing completed.
```

**Comment by joachimmetz** [comment]
Looks like this is mainly informative

**Comment by joachimmetz** [comment]
Closing issue, since plaso will discontinue pyinstaller support. Also see: https://github.com/log2timeline/l2tdevtools/issues/760
