### ISSUE TITLE
Preprocessing fails with WindowsHostnamePlugin

### ISSUE THREAD

**Issue by stbe** [log2timeline/plaso#2819]
I got a Win2k image that fails to process with the following exception:

```shell

root@7e56f81805b2:/tmp# log2timeline.py -d --status_view linear test.plaso /tmp/image.vmdk
2020-02-06 09:45:05,255 [INFO] (MainProcess) PID:69 <data_location> Determined data location: /usr/share/plaso
2020-02-06 09:45:05,282 [INFO] (MainProcess) PID:69 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]


Source path		: /tmp/image.vmdk
Source type		: storage media image
Processing time		: 00:00:00

Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 87, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 67, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/log2timeline_tool.py", line 414, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 218, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/lib/python3/dist-packages/plaso/engine/engine.py", line 272, in PreprocessSources
    self.knowledge_base)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/manager.py", line 328, in RunPlugins
    artifacts_registry, knowledge_base, searcher)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/manager.py", line 196, in CollectFromWindowsRegistry
    preprocess_plugin.Collect(knowledge_base, artifact_definition, searcher)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/interface.py", line 243, in Collect
    self._ParseKey(knowledge_base, registry_key, value_name)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/interface.py", line 276, in _ParseKey
    self._ParseValueData(knowledge_base, value_object)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/windows.py", line 266, in _ParseValueData
    type(value_data), self.ARTIFACT_DEFINITION_NAME))
TypeError: unsupported format string passed to type.__format__

root@7e56f81805b2:/tmp# zcat log2timeline-20200206T095205.log.gz
2020-02-06 09:52:05,465 [DEBUG] (MainProcess) PID:101 <extraction_tool> Starting preprocessing.
2020-02-06 09:52:07,699 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxHostnameFile
2020-02-06 09:52:07,705 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxDistributionRelease
2020-02-06 09:52:07,714 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxIssueFile
2020-02-06 09:52:07,719 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxLSBRelease
2020-02-06 09:52:07,721 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxSystemdOSRelease
2020-02-06 09:52:07,727 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxLocalTime
2020-02-06 09:52:07,730 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: LinuxPasswdFile
2020-02-06 09:52:07,733 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: MacOSSystemConfigurationPreferencesPlistFile
2020-02-06 09:52:07,737 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: MacOSKeyboardLayoutPlistFile
2020-02-06 09:52:07,739 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: MacOSSystemVersionPlistFile
2020-02-06 09:52:07,742 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: MacOSLocalTime
2020-02-06 09:52:07,747 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: MacOSUserPasswordHashesPlistFiles
2020-02-06 09:52:07,755 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableSystemRoot
2020-02-06 09:52:07,763 [DEBUG] (MainProcess) PID:101 <windows> setting environment variable: systemroot to: "\WINNT"
2020-02-06 09:52:07,769 [DEBUG] (MainProcess) PID:101 <manager> Running file system preprocessor plugin: WindowsEnvironmentVariableWinDir
2020-02-06 09:52:07,773 [DEBUG] (MainProcess) PID:101 <windows> setting environment variable: windir to: "\WINNT"
2020-02-06 09:52:07,778 [DEBUG] (MainProcess) PID:101 <manager> Running Windows Registry preprocessor plugin: WindowsEnvironmentVariableAllUsersProfile
2020-02-06 09:52:08,449 [DEBUG] (MainProcess) PID:101 <windows> setting environment variable: allusersprofile to: "All Users"
2020-02-06 09:52:08,451 [DEBUG] (MainProcess) PID:101 <manager> Running Windows Registry preprocessor plugin: WindowsAvailableTimeZones
2020-02-06 09:52:08,492 [DEBUG] (MainProcess) PID:101 <manager> Running Windows Registry preprocessor plugin: WindowsCodePage
2020-02-06 09:52:09,203 [DEBUG] (MainProcess) PID:101 <manager> Running Windows Registry preprocessor plugin: WindowsComputerName

root@7e56f81805b2:/tmp# log2timeline.py --version
plaso - log2timeline version 20200121

```

If it helps, `type(value_data)` at this point is `pyregf.multi_string`

Environment is the `log2timeline/plaso:20200121` docker image.

**Comment by joachimmetz** [comment]
@stbe interesting, I would be interested in the contents of the Registry value as well

to see how we should handle the multi string hostname, if it contains sensitive information feel free to sanitize the actual strings but I would like to know where individual strings start and stop.

**Comment by joachimmetz** [comment]
Note to self for context:
* https://github.com/ForensicArtifacts/artifacts/blob/f4efd6845feda4d96399025bba5ef60df57bf4b5/data/windows.yaml#L329
* capture this info in https://github.com/libyal/winreg-kb

**Comment by stbe** [comment]
@joachimmetz Indeed, the REG_MULTI_SZ is quite odd. It contains just one entry - the hostname of the machine (terminated by an empty string).

I've got a vanilla Win2k VM that I just checked. From a first glance, it does not look like there is a legitimate way of making this a multi string. It also does not seem to have any issues with that value being a REG_MULTI_SZ instead of a REG_SZ - it reboots fine without issues when I edit it by hand. It appears to take the first one as ActiveComputer name in case there are more listed in ComputerName. Setting the hostname via normal means (GUI) changes the type of the key back to REG_SZ. 

So I suspect that the system was provisioned by some sort of bootstrapping script that set the hostname via editing the registry and chose the wrong type for it, but that's just a wild guess.

**Comment by joachimmetz** [comment]
Thx for that context, I'll make some changes to support the first string in a multi string value.

**Comment by joachimmetz** [comment]
I've made some changes https://github.com/log2timeline/plaso/pull/2820

**Comment by joachimmetz** [comment]
Changes merged, closing issue
