### ISSUE TITLE
Ubuntu stable install provides me older versions?

### ISSUE THREAD

**Issue by apapadop** [log2timeline/plaso#282]
Following https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release appears to install everything as needed, but trying to use the tool complains about pyregf being too old:

```
alex@gtw:~$ psort.py -h
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 24, in <module>
    from plaso.frontend import psort
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 22, in <module>
    from plaso.multi_processing import multi_process
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 18, in <module>
    from plaso.engine import engine
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 11, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/macosx.py", line 12, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/__init__.py", line 49, in <module>
    from plaso.parsers import winreg
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/winreg.py", line 10, in <module>
    from plaso.winreg import winregistry
  File "/usr/lib/python2.7/dist-packages/plaso/winreg/winregistry.py", line 4, in <module>
    from plaso.winreg import winpyregf
  File "/usr/lib/python2.7/dist-packages/plaso/winreg/winpyregf.py", line 14, in <module>
    dependencies.CheckModuleVersion(u'pyregf')
  File "/usr/lib/python2.7/dist-packages/plaso/dependencies.py", line 403, in CheckModuleVersion
    module_name, module_version))
**ImportError: Module pyregf is too old, minimum required version 20141030**
alex@gtw:~$ apt-cache policy python-plaso
python-plaso:
  Installed: 1.3.0-2ppa1~trusty
  Candidate: 1.3.0-2ppa1~trusty
  Version table:
 *** 1.3.0-2ppa1~trusty 0
        500 http://ppa.launchpad.net/gift/stable/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
alex@gtw:~$ 
```

This may be a leftover from previous installations on people's environments that's not cleanly taken care of by following the wiki documentation.

I've found that
```
sudo apt-get remove libregf libsigscan && sudo apt-get install python-plaso 
```

pulled down the right versions of the above dependencies and appears to allow plaso to work as expected.

Hope this helps.

**Comment by kiddinn** [comment]
Did you note what the following command indicated:

apt-cache policy libregf-python

Also were you just using the GIFT repo or did you have SIFT installed as well?

**Comment by apapadop** [comment]
I do not have the historical (i.e. before the changes) information, sorry. I had enabled the SIFT repo on this machine months ago, and enabled GIFT today.

**Comment by joachimmetz** [comment]
Check the [pinning priority](http://www.argon.org/~roderick/apt-pinning.html) of the GIFT and SIFT repo. SIFT (hopefully removed now) contained various out dated versions.

**Comment by joachimmetz** [comment]
Closing issue, created https://github.com/log2timeline/plaso/issues/291 to give people some pointers on troubleshooting installation issues. It is impossible to create documentation that will cover every edge case.
