### ISSUE TITLE
Parser attribute not serialized

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2889]
Debug log line:
`2020-04-15 07:26:43,455 [DEBUG] (MainProcess) PID:4299 <json_serializer> [ConvertDictToObject] unsupported attribute name: event.parser`

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "plaso/tools/log2timeline.py", line 97, in <module>
    if not Main():
  File "plaso/tools/log2timeline.py", line 72, in Main
    tool.ExtractEventsFromSources()
  File "plaso/plaso/cli/log2timeline_tool.py", line 448, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "plaso/plaso/multi_processing/task_engine.py", line 812, in ProcessSources
    self._ProcessSources(source_path_specs, storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 343, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 449, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 256, in _MergeTaskStorage
    maximum_number_of_containers=self._MAXIMUM_NUMBER_OF_CONTAINERS)
  File "plaso/plaso/storage/sqlite/merge_reader.py", line 278, in MergeAttributeContainers
    self._active_container_type, serialized_data)
  File "plaso/plaso/storage/interface.py", line 600, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "plaso/plaso/serializer/json_serializer.py", line 404, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "plaso/plaso/serializer/json_serializer.py", line 423, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "plaso/plaso/serializer/json_serializer.py", line 252, in _ConvertDictToObject
    'supported.').format(attribute_name))
ValueError: Event data attribute value: return_value of type dict is not supported.
```

**Comment by joachimmetz** [comment]
The psort-linux-hashes end to end test seems to be passing again. Can you indicate if this log statement was possibly due to an older storage file? We can update the storage file format version number.
