### ISSUE TITLE
End-to-end tests failing on MacOS image due to increased strictness of serializer

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2890]
```
Traceback (most recent call last):
  File "plaso/tools/log2timeline.py", line 97, in <module>
    if not Main():
  File "plaso/tools/log2timeline.py", line 72, in Main
    tool.ExtractEventsFromSources()
  File "plaso/plaso/cli/log2timeline_tool.py", line 448, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "plaso/plaso/multi_processing/task_engine.py", line 812, in ProcessSources
    self._ProcessSources(source_path_specs, storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 343, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 449, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 256, in _MergeTaskStorage
    maximum_number_of_containers=self._MAXIMUM_NUMBER_OF_CONTAINERS)
  File "plaso/plaso/storage/sqlite/merge_reader.py", line 278, in MergeAttributeContainers
    self._active_container_type, serialized_data)
  File "plaso/plaso/storage/interface.py", line 600, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "plaso/plaso/serializer/json_serializer.py", line 404, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "plaso/plaso/serializer/json_serializer.py", line 423, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "plaso/plaso/serializer/json_serializer.py", line 252, in _ConvertDictToObject
    'supported.').format(attribute_name))
ValueError: Event data attribute value: return_value of type dict is not supported.
```

**Comment by joachimmetz** [comment]
Looks like related to bsm parser https://github.com/log2timeline/plaso/blob/3c128a329e820b7b4d0ef6f78f09d32e732273e0/plaso/parsers/bsm.py#L36

**Comment by joachimmetz** [comment]
`ValueError: Event data attribute value: return_value of type dict is not supported: {'error': 'Success', 'token_status': 0, 'call_status': 0}.`

**Comment by Onager** [comment]
@joachimmetz Shouldn't the mediator check for this, if we know what types are allowed in containers? Do we have these types documented somewhere, perhaps in the serializer?

**Comment by Onager** [comment]
Also, I don't think this sort of crash should lead to the whole processing hanging. It looks we should catch that ValueError somewhere.

**Comment by joachimmetz** [comment]
> Do we have these types documented somewhere, perhaps in the serializer?

@Onager regarding documentation I thought you were working on that given https://github.com/log2timeline/plaso/issues/2129. There are some notes in that issue why dicts were prohibited.

> Shouldn't the mediator check for this, if we know what types are allowed in containers?

We could add a check to the mediator as well, but will need to make sure the serializer handles them appropriately as well when reading. 

> Also, I don't think this sort of crash should lead to the whole processing hanging.

Ack good point.

**Comment by joachimmetz** [comment]
Added https://github.com/log2timeline/plaso/pull/2893 to make the storage merge reader error tollerant to serialization issues. I'll give this a test on the test image as well, after testing the bsm changes.

**Comment by joachimmetz** [comment]
Removing this from the April milestone. Basic issues have been addressed. Keep this issue for now as reminder to address some of the TODOs
