### ISSUE TITLE
tests failing on Fedora 32, Python 3.8 

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2899]
```
======================================================================
ERROR: testStartStopTiming (engine.profilers.SerializersProfilerTest)
Tests the StartTiming and StopTiming functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "plaso/tests/engine/profilers.py", line 140, in testStartStopTiming
    test_profiler.StartTiming('test_profile')
  File "./plaso/engine/profilers.py", line 118, in StartTiming
    self._profile_measurements[profile_name].SampleStart()
  File "./plaso/engine/profilers.py", line 29, in SampleStart
    self._start_cpu_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

Per https://www.webucator.com/blog/2015/08/python-clocks-explained/ looks like `time.perf_counter()` is the function that we want to replace `time.clock()` with.

**Comment by joachimmetz** [comment]
```
======================================================================
ERROR: testParse (parsers.winfirewall.WinFirewallParserTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "plaso/tests/parsers/winfirewall.py", line 20, in testParse
    storage_writer = self._ParseFile(['firewall.log'], parser)
  File "./tests/parsers/test_lib.py", line 151, in _ParseFile
    return self._ParseFileByPathSpec(
  File "./tests/parsers/test_lib.py", line 184, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "./plaso/parsers/interface.py", line 272, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "./plaso/parsers/text_parser.py", line 427, in ParseFileObject
    self.ParseRecord(parser_mediator, use_key, parsed_structure)
  File "./plaso/parsers/winfirewall.py", line 211, in ParseRecord
    self._ParseLogLine(parser_mediator, structure)
  File "./plaso/parsers/winfirewall.py", line 188, in _ParseLogLine
    parser_mediator.ProduceEventWithEventData(event, event_data)
  File "./plaso/parsers/mediator.py", line 502, in ProduceEventWithEventData
    event_data = copy.deepcopy(event_data)
  File "/usr/lib64/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
TypeError: 'str' object is not callable
```

**Comment by joachimmetz** [comment]
Issues addressed in plaso
