### ISSUE TITLE
Elasticsearch output error: Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by utkonos** [log2timeline/plaso#2926]
**Description of problem:**

According to the commit logs, elasticsearch 7 is supported, but after running with a fresh install, the output plugin fails with an error.

**Command line and arguments:**

```
psteal.py -o elastic --server localhost --port 9200 --index_name test1 --raw_fields --source image.img -w test1.plaso
```

**Source data:**

I used a VirtualBox VM with a fresh install of windows 7 32bit. Drive size 16GB. Converted vdi image to raw with this command:
```
VBoxManage clonehd Win7x32.vdi image.img --format raw
```

**Plaso version:**

plaso-20200430 installed from GIFT PPA
Elasticsearch 7.7.0

**Operating system Plaso is running on:**

Ubuntu Server 20.04

**Installation method:**

```
#!/bin/bash
## Set environment
export DEBIAN_FRONTEND=noninteractive

## Update Ubuntu
apt-get update
apt-get upgrade -y
apt-get autoremove -y
apt-get autoclean -y

## Install Plaso
add-apt-repository ppa:gift/stable
apt-get update
apt-get install -y plaso-tools
apt-get upgrade -y

## Add Plaso user
adduser --gecos '' --disabled-password plaso
```
Elasticsearch installed like this:
```
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
apt-get update
apt-get install -y elasticsearch
apt-get install -y kibana
service elasticsearch start
service kibana start
systemctl enable elasticsearch
systemctl enable kibana
```

**Debug output/tracebacks:**

```
Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 110, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 87, in Main
    tool.AnalyzeEvents()
  File "/usr/lib/python3/dist-packages/plaso/cli/psteal_tool.py", line 218, in AnalyzeEvents
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 997, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python3/dist-packages/plaso/output/elastic.py", line 72, in WriteHeader
    self._CreateIndexIfNotExists(self._index_name, mappings)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 98, in _CreateIndexIfNotExists
    self._client.indices.create(
  File "/usr/lib/python3/dist-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/indices.py", line 103, in create
    return self.transport.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/base.py", line 243, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [plaso_event : {dynamic_templates=[{strings={mapping={fields={raw={ignore_above=10922, index=false, type=keyword}}}, match_mapping_type=string}}]}]')
```

**Comment by joachimmetz** [comment]
What is your version of elasticsearch-py ?

**Comment by joachimmetz** [comment]
@berggren any thoughts?

**Comment by utkonos** [comment]
> What is your version of elasticsearch-py ?

elasticsearch      7.6.0         7.7.0    wheel

**Comment by utkonos** [comment]
```
python3-elasticsearch:
  Installed: 7.6.0-1ppa1~focal
  Candidate: 7.6.0-1ppa1~focal
  Version table:
 *** 7.6.0-1ppa1~focal 500
        500 http://ppa.launchpad.net/gift/stable/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

It's the one installed from the PPA

**Comment by utkonos** [comment]
I have just updated this python package using pip and I'm rerunning the image analysis. I'll let you know if this solves it.

**Comment by utkonos** [comment]
Updated elasticsearch python package to 7.7.0

```
elasticsearch          7.7.0
```

```
Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 110, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 87, in Main
    tool.AnalyzeEvents()
  File "/usr/lib/python3/dist-packages/plaso/cli/psteal_tool.py", line 218, in AnalyzeEvents
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 997, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python3/dist-packages/plaso/output/elastic.py", line 72, in WriteHeader
    self._CreateIndexIfNotExists(self._index_name, mappings)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 98, in _CreateIndexIfNotExists
    self._client.indices.create(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/indices.py", line 102, in create
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 281, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [plaso_event : {dynamic_templates=[{strings={mapping={fields={raw={ignore_above=10922, index=false, type=keyword}}}, match_mapping_type=string}}]}]')
```

**Comment by utkonos** [comment]
Clean install, but using 7.6.2 and marking the packages with hold so they're the older version. Still have the same error.

```
$ apt-cache policy elasticsearch
elasticsearch:
  Installed: 7.6.2
  Candidate: 7.7.0
```

```
Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 110, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 87, in Main
    tool.AnalyzeEvents()
  File "/usr/lib/python3/dist-packages/plaso/cli/psteal_tool.py", line 218, in AnalyzeEvents
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 997, in ExportEvents
    output_module.WriteHeader()
  File "/usr/lib/python3/dist-packages/plaso/output/elastic.py", line 72, in WriteHeader
    self._CreateIndexIfNotExists(self._index_name, mappings)
  File "/usr/lib/python3/dist-packages/plaso/output/shared_elastic.py", line 98, in _CreateIndexIfNotExists
    self._client.indices.create(
  File "/usr/lib/python3/dist-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/lib/python3/dist-packages/elasticsearch/client/indices.py", line 103, in create
    return self.transport.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/transport.py", line 355, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3/dist-packages/elasticsearch/connection/base.py", line 243, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [plaso_event : {dynamic_templates=[{strings={mapping={fields={raw={ignore_above=10922, index=false, type=keyword}}}, match_mapping_type=string}}]}]')
```

**Comment by utkonos** [comment]
Starting with a fresh install of Ubuntu 20.04, then running the following two scripts to install and the error happens.

```
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
apt-get update
apt-get install -y elasticsearch=7.6.2
apt-mark hold elasticsearch
apt-get install -y kibana=7.6.2
apt-mark hold kibana
service elasticsearch start
systemctl enable elasticsearch
service kibana start
systemctl enable kibana
```

```
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade -y
apt-get autoremove -y
apt-get autoclean -y
apt-get install -y jq
apt-get install -y python3-pip
add-apt-repository ppa:gift/stable
apt-get update
apt-get install -y plaso-tools
apt-get upgrade -y
adduser --gecos '' --disabled-password plaso
```

command line used was:

```
psteal.py -o elastic --server localhost --port 9200 --index_name test1 --raw_fields --source image.img -w test1.plaso
```

**Comment by joachimmetz** [comment]
Thx, for the additional context. We'll have a closer look as soon as time permits, a first assumption is that might be related to the `--raw_fields` option.

**Comment by utkonos** [comment]
This is what was causing the problem. Thanks!

`--raw_fields` is not compatible with elasticsearch output. Is this expected behavior?

**Comment by joachimmetz** [comment]
> Is this expected behavior?

ES keeps changing version by version, this might have been supported in the past. @berggren might know from the top of his head.

**Comment by joachimmetz** [comment]
While working on https://github.com/log2timeline/plaso/issues/2931 I was able to reproduce `--raw_fields` failing on Elasticsearch 7.

**Comment by joachimmetz** [comment]
Changes in https://github.com/log2timeline/plaso/pull/2953 which seem to do the trick on test system

**Comment by joachimmetz** [comment]
Changes merged
