### ISSUE TITLE
Unittests fail when running with Python 3.8 on Windows

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2945]
```
======================================================================
ERROR: testSampleStartStop (engine.profilers.CPUTimeMeasurementTest)
Tests the SampleStart and SampleStop functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "plaso\tests\engine\profilers.py", line 25, in testSampleStartStop
    cpu_measurement.SampleStart()
  File ".\plaso\engine\profilers.py", line 29, in SampleStart
    self._start_cpu_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by joachimmetz** [comment]
Duplicate of https://github.com/log2timeline/plaso/issues/2899, likely stale test environment

**Comment by joachimmetz** [comment]
issue due to stale test environment closing
