### ISSUE TITLE
Add Timesketch end-to-end test coverage

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2955]
With timesketch now in GIFT PPA dev track add Timesketch end-to-end test coverage that uses the PPA build.

* [x] Add output to timesketch end-to-end test configuration https://github.com/log2timeline/plaso/pull/2954
* [x] Add TS test system configuration
* [x] Fix TS package in GIFT PPA (https://github.com/google/timesketch/issues/1211, https://github.com/google/timesketch/issues/1210)
* [x] Change test system configuration after merge https://github.com/log2timeline/plaso/pull/2954
* [ ] ~~Add ubuntu_install_timesketch.sh script to l2tdevtools~~
  * this is a Plaso specific script, let's not add it for now

**Comment by joachimmetz** [comment]
```
psort.py -o timesketch test.plaso 
2020-05-25 14:29:19,777 [INFO] (MainProcess) PID:4723 <data_location> Determined data location: /usr/share/plaso
Config file /etc/timesketch/timesketch.conf does not exist.
```

```
ls /etc/timesketch/timesketch.conf
/etc/timesketch/timesketch.conf
```

**Comment by joachimmetz** [comment]
Issue causing the test to stall https://github.com/log2timeline/plaso/issues/2975

Need to make sure to create a TS user first
```
2020-05-25 15:42:37,061 [INFO] (MainProcess) PID:15326 <data_location> Determined data location: /tmp/workspace/plaso-linux-output-timesketch/data
2020-05-25 15:42:37,799 [INFO] (MainProcess) PID:15326 <timesketch_out> Timeline name: test
2020-05-25 15:42:37,799 [INFO] (MainProcess) PID:15326 <timesketch_out> Owner of the timeline: test
Traceback (most recent call last):
  File "./tools/psort.py", line 95, in <module>
    if not Main():
  File "./tools/psort.py", line 72, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/plaso-linux-output-timesketch/plaso/cli/psort_tool.py", line 571, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/tmp/workspace/plaso-linux-output-timesketch/plaso/multi_processing/psort.py", line 996, in ExportEvents
    output_module.WriteHeader()
  File "/tmp/workspace/plaso-linux-output-timesketch/plaso/output/timesketch_out.py", line 122, in WriteHeader
    'Unknown Timesketch user: {0:s}'.format(self._timeline_owner))
RuntimeError: Unknown Timesketch user: test
```

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/tsctl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tabulate==0.8.6' distribution was not found and is required by timesketch
```

**Comment by joachimmetz** [comment]
Added tabulate 0.8.7, and tweaks to timesketch rules file to include:

```
.PHONY: override_dh_auto_install
override_dh_auto_install:
        dh_auto_install
        rm -f debian/tmp/usr/lib/python3*/dist-packages/timesketch-*.egg-info/requires.txt
```
