### ISSUE TITLE
request for required input unclear because question is not yet printed to output

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2975]
```
psort.py -o timesketch test.plaso
2020-05-25 16:03:38,542 [INFO] (MainProcess) PID:6164 <data_location> Determined data location: /usr/share/plaso
2020-05-25 16:03:42,081 [INFO] (MainProcess) PID:6164 <timesketch_out> Timeline name:
2020-05-25 16:03:42,082 [INFO] (MainProcess) PID:6164 <timesketch_out> Owner of the timeline: None
^CMissing parameter timeline_name for output module: Traceback (most recent call last):
  File "/usr/bin/psort.py", line 95, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 30, in Main
    if not tool.ParseArguments(sys.argv[1:]):
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 405, in ParseArguments
    self.ParseOptions(options)
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 494, in ParseOptions
    self._output_module = self._CreateOutputModule(options)
  File "/usr/lib/python3/dist-packages/plaso/cli/tool_options.py", line 200, in _CreateOutputModule
    'Missing parameter {0:s} for output module'.format(parameter))
  File "/usr/lib/python3/dist-packages/plaso/cli/tools.py", line 194, in _PromptUserForInput
    return self._input_reader.Read()
  File "/usr/lib/python3/dist-packages/plaso/cli/tools.py", line 495, in Read
    encoded_string = self._file_object.readline()
KeyboardInterrupt
```

**Comment by joachimmetz** [comment]
Looks like output might need to be flushed before reading input.

**Comment by joachimmetz** [comment]
Note to self: make sure there is a call to flush before every call for user input.

**Comment by joachimmetz** [comment]
Note to self: check if the changes in https://github.com/log2timeline/plaso/pull/3037 solve the issue for all reads from stdin.
