### ISSUE TITLE
Why does psort.py errors with regvalue of type dict is not supported?

### ISSUE THREAD

**Issue by Kn0wl3dge** [log2timeline/plaso#3013]
**Description of problem:**

So I have generated the plaso file using log2timeline.py. Then I wanted to put this file in timesketch, so I set up a timesktech development docker environment. After uploading the plaso file I got the error below.
So I tried putting the data in an ELK stack with a psort (not in the docker container this time) installed from Github sources and I got the same error.
I also tried outputing this into a csv file and... same error.

**Command line and arguments:**

```
log2timeline.py --partitions 1 --single_process full_timeline.plaso disk.raw
psort.py -o l2tcsv -w full_timeline.plaso.csv full_timeline.plaso
```

**Source data:**

The data come from an NTFS disk used to analyze a malware. If needed, I can upload the plaso file.

**Plaso version:**

20200430

**Operating system Plaso is running on:**

Parrot Security 5.4.19-4 and Docker (Timesketch dev Docker image)

**Installation method:**

I tried 2 installations methods of Plaso :
* From the latest release on Github (20200430)
* From [GiFT PPA][https://launchpad.net/~gift] stable track (for the docker image of timesketch)

**Debug output/tracebacks:**
```
plaso - psort version 20200430

Storage file		: full_timeline.plaso
Processing time		: 00:00:15

Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               79              12811           1991661

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    3554    exporting       118.9 MiB       13306 (440)     0 (0)           0 (0)

Traceback (most recent call last):
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/interface.py", line 518, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/serializer/json_serializer.py", line 400, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/serializer/json_serializer.py", line 419, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/serializer/json_serializer.py", line 246, in _ConvertDictToObject
    raise ValueError((
ValueError: Event data attribute value: regvalue of type dict is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/knowledge/plaso_env/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20200430', 'psort.py')
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/EGG-INFO/scripts/psort.py", line 95, in <module>
    if not Main():
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/EGG-INFO/scripts/psort.py", line 72, in Main
    tool.ProcessStorage()
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/cli/psort_tool.py", line 566, in ProcessStorage
    analysis_engine.ExportEvents(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/multi_processing/psort.py", line 1004, in ExportEvents
    self._ExportEvents(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/multi_processing/psort.py", line 487, in _ExportEvents
    event_data = storage_reader.GetEventDataByIdentifier(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/file_interface.py", line 308, in GetEventDataByIdentifier
    return self._storage_file.GetEventDataByIdentifier(identifier)
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/interface.py", line 261, in GetEventDataByIdentifier
    return self._GetAttributeContainerByIdentifier(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/sqlite/sqlite_file.py", line 257, in _GetAttributeContainerByIdentifier
    return self._GetAttributeContainerByIndex(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/sqlite/sqlite_file.py", line 298, in _GetAttributeContainerByIndex
    attribute_container = self._DeserializeAttributeContainer(
  File "/home/knowledge/plaso_env/lib/python3.8/site-packages/plaso-20200430-py3.8.egg/plaso/storage/interface.py", line 525, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: Event data attribute value: regvalue of type dict is not supported.
```

**Comment by joachimmetz** [comment]
This is because the plaso file was created with a plaso version that is no longer supported (too old)

**Comment by joachimmetz** [comment]
What version of plaso did you use to create the plaso file? `pyinfo.py` should be able to tell you what version was used to generate the file

**Comment by Kn0wl3dge** [comment]
```
(plaso_env) ➜  case pinfo.py full_timeline.plaso

************************** Plaso Storage Information ***************************
            Filename : full_timeline.plaso
      Format version : 20180101
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
9e62740a-a607-4371-9813-d7ac1aa91ae7 : 2020-06-03T18:09:07.756069Z
d520ed72-41ad-454c-b924-b67a828a5e2b : 2020-06-06T07:37:34.193922Z
--------------------------------------------------------------------------------

**************** Session: 9e62740a-a607-4371-9813-d7ac1aa91ae7 *****************
                Start time : 2020-06-03T18:09:07.756069Z
           Completion time : 2020-06-03T18:46:57.798188Z
              Product name : plaso
           Product version : 20190131
    Command line arguments : /usr/bin/log2timeline.py-python3 --partitions 1
                             --data plaso/data --no_dependencies_check
                             --single_process --no_vss full_timeline.plaso
                             disk.raw
[...]

**************** Session: d520ed72-41ad-454c-b924-b67a828a5e2b *****************
                Start time : 2020-06-06T07:37:34.193922Z
           Completion time : 2020-06-06T08:19:38.179470Z
              Product name : plaso
           Product version : 20200430
    Command line arguments : /home/knowledge/plaso_env/bin/log2timeline.py
                             --partitions 1 --single_process
                             full_timeline.plaso disk.raw

```

I thought that plaso files where storing only one session. So I firstly tried an older version and then updated to the 20200430. Howerver I didn't removed the plaso file, so the format used was to old I guess.
I am going to try out with a new plaso file and see what happen.
Thanks for the help !

**Comment by joachimmetz** [comment]
Plaso files support multiple sessions, so you can add events from multiple sources and to store analysis results.

> Howerver I didn't removed the plaso file, so the format used was to old I guess.

The data that was stored was still in the old format. Regvalue had been deprecated for approx a year, but now will no longer be backwards supported.

I know this can be annoying but we strongly encourage people to run the latest Plaso release. Issues get addressed continuously in Plaso and its dependencies.

I'll close the issue since your question seems to be addressed.
