### ISSUE TITLE
Issue with dfwinreg/regf.py 

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#311]
After the Registry commit: 4f3a85fbea10637c1cdbf0cde9fc539fdcea9c47

things started to fail:

```
2015-08-26 10:45:34,469 [WARNING] (Worker_04 ) PID:21019 <worker> Unhandled exception while processing path spec: type: OS, location: <PATH>/test.dd
type: VHDI
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00007e00
type: TSK, inode: 377, location: /Documents and Settings/NetworkService/ntuser.dat.LOG
.
2015-08-26 10:45:34,470 [ERROR] (Worker_04 ) PID:21019 <worker> 'NoneType' object has no attribute 'values'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/engine/worker.py", line 471, in _ProcessPathSpec
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/engine/worker.py", line 430, in _ProcessFileEntry
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/engine/worker.py", line 213, in _ParseFileEntryWithParser
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/winreg.py", line 318, in Parse
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/winreg.py", line 264, in _ParseRegistryFile
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/plugins.py", line 85, in UpdateChainAndProcess
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/winreg_plugins/mrulist.py", line 192, in Process
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/parsers/winreg_plugins/interface.py", line 211, in Process
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.3.1_20150826-py2.7.egg/plaso/dfwinreg/regf.py", line 166, in GetValues
AttributeError: 'NoneType' object has no attribute 'values'
```

This gets repeated very frequently in the logs.

**Comment by kiddinn** [comment]
The issue here is that this is coming from: **ntuser.dat.LOG** but it is detected as a SOFTWARE hive.

```
(Pdb) parser_mediator.GetDisplayName(file_entry)
u'TSK:/Documents and Settings/NetworkService/ntuser.dat.LOG'
```

And 
```
(Pdb) root_key_stuff = winreg_file.GetRootKey()
(Pdb) root_key_stuff.__dict__
{'_pyregf_key': None, '_path': u'\\'}
```

The pyregf_key is not set for this Registry file and thus we can't recurse the keys.

**Comment by kiddinn** [comment]
The main problem here is the edge case where GetRootKey returns and effectively empty key, that is when there is no root key the interface returns back a root key that doesn't have a corresponding REGF key.

**Comment by kiddinn** [comment]
added: http://codereview.appspot.com/264900043

**Comment by joachimmetz** [comment]
Also please add a test for this scenario.

**Comment by kiddinn** [comment]
Removed the fix from the previous CL and added a new one: http://codereview.appspot.com/259610043

**Comment by kiddinn** [comment]
CL submitted, fixed
