### ISSUE TITLE
OS X Yosemite Install Issue Plaso 1.3

### ISSUE THREAD

**Issue by rayschippers** [log2timeline/plaso#312]
I am running OS X 10.10.5, I downloaded Plaso 1.3, mounted the DMG then in terminal ran:
sudo ./install.sh 

Last lines of the installer output was: 
installer: The install was successful.
Done.
Two versions of the pyparsing module exist. Deleting the system provided one.

Then I ran:
```
MacBook-Pro:plaso-1.3.0 raymond$ log2timeline.py -h
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 7, in <module>
    from plaso.engine import engine
  File "/Library/Python/2.7/site-packages/plaso/engine/engine.py", line 11, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/macosx.py", line 12, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 37, in <module>
    from plaso.parsers import skydrivelogerr
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelogerr.py", line 40, in <module>
    class SkyDriveLogErrorParser(text_parser.PyparsingMultiLineTextParser):
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelogerr.py", line 89, in SkyDriveLogErrorParser
    pyparsing.lineEnd())
TypeError: __call__() takes exactly 2 arguments (1 given)
```

Has anyone seen something similar?

**Comment by joachimmetz** [comment]
What you are seeing is a bug in pyparsing

So do as the script indicates:
```
Two versions of the pyparsing module exist. Deleting the system provided one.
```
And delete the old version of pyparsing

**Comment by Onager** [comment]
So should this be an instruction "Delete the system provided one"? From reading this message, I thought the installer had already done this.

@rayschippers Try the workaround on https://github.com/log2timeline/plaso/wiki/Development-release-Mac-OS-X to get the right pyparsing loaded.

**Comment by joachimmetz** [comment]
So judging from: https://github.com/log2timeline/plaso/blob/master/config/macosx/install.sh.in#L60 it does. However if an old version of pyparsing is installed in another location this does not work.

**Comment by joachimmetz** [comment]
No update from OP closing issue.
