### ISSUE TITLE
psort-studentpc1-services end-to-end test failing with QueueFull

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3145]
a previous instance of this issue https://github.com/log2timeline/plaso/issues/3001

```
2020-06-28 00:54:56,187 [INFO] (MainProcess) PID:4328 <data_location> Determined data location: /tmp/workspace/psort-linux-services/data
Traceback (most recent call last):
  File "./tools/psort.py", line 99, in <module>
    if not Main():
  File "./tools/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/psort-linux-services/plaso/cli/psort_tool.py", line 556, in ProcessStorage
    worker_memory_limit=self._worker_memory_limit)
  File "/tmp/workspace/psort-linux-services/plaso/multi_processing/psort.py", line 947, in AnalyzeEvents
    storage_writer, analysis_plugins, event_filter=event_filter)
  File "/tmp/workspace/psort-linux-services/plaso/multi_processing/psort.py", line 308, in _AnalyzeEvents
    event_queue.PushItem((event, event_data, event_data_stream))
  File "/tmp/workspace/psort-linux-services/plaso/engine/zeromq_queue.py", line 457, in PushItem
    raise errors.QueueFull
plaso.lib.errors.QueueFull
```

* [x] fix issue https://github.com/log2timeline/plaso/pull/3146
* [x] add end-to-end test that can be run on CI https://github.com/log2timeline/plaso/pull/3148
  * ~~reduce analysis module (worker process) time out, default is 15 mins~~

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "plaso/multi_processing/analysis_process.py", line 246, in _ProcessEvent
    self._analysis_plugin.ExamineEvent(
  File "plaso/analysis/windows_services.py", line 281, in ExamineEvent
    service = WindowsService.FromEventData(event_data, event_data_stream)
  File "plaso/analysis/windows_services.py", line 137, in FromEventData
    event_data.start_type, event_data.object_name, source,
AttributeError: 'EventData' object has no attribute 'object_name'
```
