### ISSUE TITLE
nsrlsvr analysis plugin end to end tests failing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3158]
```
2020-07-13 13:03:56,615 [INFO] (MainProcess) PID:4081 <data_location> Determined data location: /tmp/workspace/psort-linux-nsrlsvr/data
Traceback (most recent call last):
  File "./tools/psort.py", line 99, in <module>
    if not Main():
  File "./tools/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/psort-linux-nsrlsvr/plaso/cli/psort_tool.py", line 558, in ProcessStorage
    worker_memory_limit=self._worker_memory_limit)
  File "/tmp/workspace/psort-linux-nsrlsvr/plaso/multi_processing/psort.py", line 944, in AnalyzeEvents
    storage_writer, analysis_plugins, event_filter=event_filter)
  File "/tmp/workspace/psort-linux-nsrlsvr/plaso/multi_processing/psort.py", line 306, in _AnalyzeEvents
    event_queue.PushItem((event, event_data, event_data_stream))
  File "/tmp/workspace/psort-linux-nsrlsvr/plaso/engine/zeromq_queue.py", line 457, in PushItem
    raise errors.QueueFull
plaso.lib.errors.QueueFull
```

**Comment by joachimmetz** [comment]
the analysis module process gets kill about 4 mins into processing

**Comment by joachimmetz** [comment]
Side note current nsrlsvr test not representative since events do not contain md5 hash.

**Comment by joachimmetz** [comment]
Additional changes: https://github.com/log2timeline/plaso/pull/3160/files#diff-39fc108fa49cdaba64e67431651b99abL250

removed SignalAbort since exception can be safely handled and analysis can continue

**Comment by joachimmetz** [comment]
end to end tests passing again
