### ISSUE TITLE
Unable to run psteal 20200717 in vitualenv on MacOS Catalina

### ISSUE THREAD

**Issue by Sh0ckFR** [log2timeline/plaso#3164]
**Description of problem:**

Hello,

I'm unable to use psteal with the last version of the repository, I have an error about multiprocessing

Thank you for your help

**Command line and arguments:**

/usr/local/bin/psteal.py --source /Users/user/Desktop/timesketch/art --additional_fields "data_type, strings, event_type" -w /Users/user/Desktop/timesketch/extract.csv

**Source data:**

This is a CyLR output, I can't share it sorry

**Plaso version:**

plaso 20200717 (git clone on it)

**Operating system Plaso is running on:**

MacOS 10.15.6 (Catalina)

**Installation method:**

In a virtualenv;

```
pip3 install -r requirements.txt
python3 setup.py install
```

**Debug output/tracebacks:**

```
2020-07-21 16:03:50,352 [INFO] (MainProcess) PID:4045 <data_location> Determined data location: /usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/share/plaso
2020-07-21 16:03:50,545 [INFO] (MainProcess) PID:4045 <artifact_definitions> Determined artifact definitions path: /Users/user/Desktop/Files/Tools/plaso/plaso/share/artifacts
Checking availability and versions of dependencies.
[OK]


Source path     : /Users/user/Desktop/timesketch/art
Source type     : directory
Processing time     : 00:00:00

Processing started.
Traceback (most recent call last):
  File "/usr/local/bin/psteal.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20200717', 'psteal.py')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/psteal.py", line 110, in <module>
    if not Main():
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/psteal.py", line 86, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/cli/psteal_tool.py", line 388, in ExtractEventsFromSources
    processing_status = extraction_engine.ProcessSources(
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 817, in ProcessSources
    extraction_process = self._StartWorkerProcess('', storage_writer)
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 572, in _StartWorkerProcess
    process.start()
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```

**Comment by joachimmetz** [comment]
> This is a CyLR output, I can't share it sorry

What we mainly need to know if this is an image, which image format, or directory or single file.

> File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
> AttributeError: module '__main__' has no attribute '__spec__'

This hints the error is within python3.8 multiprocessing module.

Google searching for `AttributeError: module '__main__' has no attribute '__spec__'` most of the hits refer to Spyder being the culprit. Are you using that by any chance?

Otherwise I would recommend using the Docker image/container instead.

**Comment by Sh0ckFR** [comment]
> > This is a CyLR output, I can't share it sorry
> 
> What we mainly need to know if this is an image, which image format, or directory or single file.
> 
> > File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
> > main_mod_name = getattr(main_module.**spec**, "name", None)
> > AttributeError: module '**main**' has no attribute '**spec**'
> 
> This hints the error is within python3.8 multiprocessing module.
> 
> Google searching for `AttributeError: module '__main__' has no attribute '__spec__'` most of the hits refer to Spyder being the culprit. Are you using that by any chance?
> 
> Otherwise I would recommend using the Docker image/container instead.

This is a directory, I don't use Spyder, I used a clean virtualenv

I think I will use docker instead tomorrow like you said

**Comment by joachimmetz** [comment]
> This is a directory, I don't use Spyder, I used a clean virtualenv

Ack, I'll see if I can reproduce this on Travis, we currently run with 10.14 in virtualenv https://travis-ci.com/github/log2timeline/plaso/jobs/362180258

**Comment by joachimmetz** [comment]
Created https://github.com/log2timeline/plaso/pull/3165, test ran and completed successfully https://travis-ci.com/github/log2timeline/plaso/jobs/363406599#L17

So I'm not sure what is different on your configuration.

> I think I will use docker instead tomorrow like you said

Docker will provide you the most hermetic build, which should minimize most system specific deployment issues.

**Comment by Sh0ckFR** [comment]
Thank you, it worked with docker:

```
docker pull log2timeline/plaso
docker run -v `pwd`:`pwd` -w `pwd` log2timeline/plaso psteal --source artifcacts -w output.csv
```

artifacts is my directory of the different artifacts collected from CyLR

Have a good day !

**Comment by jeffg2k** [comment]
I'm also having this issue.. hope there is something that can be tweaked to fix it.
```
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20200717', 'log2timeline.py')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/log2timeline.py", line 97, in <module>
    if not Main():
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/EGG-INFO/scripts/log2timeline.py", line 72, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/cli/log2timeline_tool.py", line 445, in ExtractEventsFromSources
    processing_status = extraction_engine.ProcessSources(
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 817, in ProcessSources
    extraction_process = self._StartWorkerProcess('', storage_writer)
  File "/usr/local/lib/python3.8/site-packages/plaso-20200717-py3.8.egg/plaso/multi_processing/task_engine.py", line 572, in _StartWorkerProcess
    process.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```
