### ISSUE TITLE
development version: Elasticsearch end-to-end tests failing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3212]
```
2020-08-24 22:46:10,835 [INFO] (MainProcess) PID:5516 <data_location> Determined data location: /tmp/workspace/plaso-linux-output-elastic6/data
Traceback (most recent call last):
  File "./tools/psort.py", line 99, in <module>
    if not Main():
  File "./tools/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/cli/psort_tool.py", line 598, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/multi_processing/psort.py", line 1045, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/multi_processing/psort.py", line 590, in _ExportEvents
    deduplicate_events=deduplicate_events)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/multi_processing/psort.py", line 483, in _ExportEvent
    storage_reader, output_module, deduplicate_events=deduplicate_events)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/multi_processing/psort.py", line 640, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/output/interface.py", line 126, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/output/interface.py", line 76, in WriteEvent
    self.WriteEventBody(event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/output/shared_elastic.py", line 471, in WriteEventBody
    self._InsertEvent(event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/output/shared_elastic.py", line 327, in _InsertEvent
    event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-output-elastic6/plaso/output/shared_elastic.py", line 290, in _GetSanitizedEventValues
    for attribute_name, attribute_value in sorted(event_attributes):
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by joachimmetz** [comment]
```
[('datetime', None), ('display_name', None), ('message', None), ('source_long', None), ('source_short', None), ('tag', None), ('timestamp', None), ('timestamp_desc', None), ('data_type', 'fs:stat'), ('parser', 'filestat'), ('display_name', 'NTFS:\\Users\\gold_administrator\\AppData\\Local\\Microsoft\\Windows\\Temporary Internet Files\\Content.IE5\\5ZBG4UOD\\Windows6.1-KB2729094-v2-x64[1].msu'), ('file_entry_type', 'file'), ('file_size', 1663018), ('file_system_type', 'NTFS'), ('filename', '\\Users\\gold_administrator\\AppData\\Local\\Microsoft\\Windows\\Temporary Internet Files\\Content.IE5\\5ZBG4UOD\\Windows6.1-KB2729094-v2-x64[1].msu'), ('inode', 69499), ('is_allocated', True), ('hostname', 'STUDENT-PC1'), ('md5_hash', '55ee29b470da7cf9313ebe73ffdd48c2'), ('sha256_hash', '5aa9d02ef6464a136ad3e74692d43734c186c3dbaa492b37e6f69d75faaeead4')]
```

**Comment by joachimmetz** [comment]
so technically the sort is not needed here since a dict is being filled.

**Comment by joachimmetz** [comment]
Re-running end-to-end tests

**Comment by joachimmetz** [comment]
end-to-end tests pass again, closing issue
