### ISSUE TITLE
dependency check failing on Fedora 33, Python 3.9 test

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3231]
https://travis-ci.com/github/log2timeline/l2tbinaries/jobs/388969239

```
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 97, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 67, in Main
    if tool.dependencies_check and not dependencies.CheckDependencies(
  File "/usr/lib/python3.9/site-packages/plaso/dependencies.py", line 211, in CheckDependencies
    if not _CheckPythonModule(
  File "/usr/lib/python3.9/site-packages/plaso/dependencies.py", line 138, in _CheckPythonModule
    module_version_map = list(
ValueError: invalid literal for int() with base 10: 'rc1'
```

**Comment by joachimmetz** [comment]
This has been addressed, tests are now passing
