### ISSUE TITLE
timesketch end-to-end test failing: No module named 'vine.five'

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3254]
timesketch end-to-end test is failing

```
Traceback (most recent call last):
  File "/usr/bin/tsctl", line 11, in <module>
    load_entry_point('timesketch==20200710', 'console_scripts', 'tsctl')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/dist-packages/timesketch/tsctl.py", line 41, in <module>
    from timesketch.app import create_app
  File "/usr/lib/python3.6/dist-packages/timesketch/app.py", line 24, in <module>
    from celery import Celery
  File "/usr/lib/python3/dist-packages/celery/__init__.py", line 19, in <module>
    from . import local  # noqa
  File "/usr/lib/python3/dist-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/lib/python3/dist-packages/celery/five.py", line 7, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'
```

Related https://github.com/log2timeline/l2tdevtools/issues/904

**Comment by joachimmetz** [comment]
@berggren could you make a new Timesketch pre-release?

**Comment by joachimmetz** [comment]
Pushed celery 5 to GIFT dev track and tests passing again. IMHO we should still make a new TS pre-release and test latest Plaso against that. Closing this issue.
