### ISSUE TITLE
Error "regvalue of type dict is not supported" despite an up-to-date version

### ISSUE THREAD

**Issue by RHormiere** [log2timeline/plaso#3274]
**Description of problem:**

Hello,
I am facing the very same issue as #3013 when trying to use psort.py on a plaso storage file.
I tried to redo everything multiple times (generating and parsing), without success.
I found nothing useful in the logs.

**Command line and arguments:**

log2timeline.py STORAGE_FILE /path/to/collected/data
psort.py -o l2tcsv -w TIMELINE STORAGE_FILE

**Source data:**

log2timeline.py has been used on a bunch of collected data from a single server (EVTX, Registry hives, $MFT, ...). This is a standard procedure and I have done this multiple times, using the same type of data (collected by the same tool), without any issue.

**Plaso version:**

I tried this morning with version 20200717 (for both psort and l2t). Facing the issue, I decided to update both (version 20201007) but this didn't fix the error even after redoing everything.

**Operating system Plaso is running on:**

Linux 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Debug output/tracebacks:**

Here is the full output (with --debug) :
```
plaso - psort version 20201007

Storage file            : ../plaso/STORAGE.plaso
Processing time         : 00:00:53

Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               0               150359          11562844

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    2184108 exporting       118.7 MiB       150389 (1442)   0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 643, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 427, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 446, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 273, in _ConvertDictToObject
    raise ValueError((
ValueError: Event data attribute value: regvalue of type dict is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 99, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 593, in ProcessStorage
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1042, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 526, in _ExportEvents
    event_data = storage_reader.GetEventDataByIdentifier(
  File "/usr/lib/python3/dist-packages/plaso/storage/file_interface.py", line 309, in GetEventDataByIdentifier
    return self._storage_file.GetEventDataByIdentifier(identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 904, in GetEventDataByIdentifier
    event_data = self._GetAttributeContainerByIndex(
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 336, in _GetAttributeContainerByIndex
    attribute_container = self._DeserializeAttributeContainer(
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 650, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: Event data attribute value: regvalue of type dict is not supported.
```

Thanks for your help !

**Comment by joachimmetz** [comment]
From: https://github.com/log2timeline/plaso/issues/3013

The data that was stored was still in the old format. Regvalue had been deprecated for approx a year, but now will no longer be backwards supported.

I know this can be annoying but we strongly encourage people to run the latest Plaso release. Issues get addressed continuously in Plaso and its dependencies.

**Comment by RHormiere** [comment]
I may be dumb, but I don't understand your sentence "The data that was stored was still in the old format".
Since I started log2timeline.py again in version 20201007 to get the most recent format, how can it still be in the old one ?
Unless I'm missing something ?

**Comment by joachimmetz** [comment]
> Since I started log2timeline.py again in version 20201007 to get the most recent format, how can it still be in the old one ?

Since that is how it was stored. log2timeline.py will not update an old storage file for you.

You can get more information about which version of log2timeline.py was used to create the Plaso storage file with:

```
pinfo.py --sections sessions file.plaso
```

**Comment by RHormiere** [comment]
Oh I see, just restarting log2timeline.py was not sufficient.
I get in fact two sessions, and the first one is in an old format.

Thanks !
