### ISSUE TITLE
handle "sqlite3.OperationalError: database or disk is full" more graceful

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3390]
handle sqlite3.OperationalError more graceful

```
Traceback (most recent call last):
  File "plaso/tools/log2timeline.py", line 97, in <module>
    if not Main():
  File "plaso/tools/log2timeline.py", line 72, in Main
    tool.ExtractEventsFromSources()
  File "plaso/plaso/cli/log2timeline_tool.py", line 448, in ExtractEventsFromSources
    processing_status = extraction_engine.ProcessSources(
  File "plaso/plaso/multi_processing/task_engine.py", line 837, in ProcessSources
    self._ProcessSources(source_path_specs, storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 398, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 504, in _ScheduleTasks
    self._MergeTaskStorage(storage_writer)
  File "plaso/plaso/multi_processing/task_engine.py", line 311, in _MergeTaskStorage
    fully_merged = self._storage_merge_reader.MergeAttributeContainers(
  File "plaso/plaso/storage/sqlite/merge_reader.py", line 396, in MergeAttributeContainers
    self._add_active_container_method(
  File "plaso/plaso/storage/sqlite/merge_reader.py", line 189, in _AddEventData
    self._storage_writer.AddEventData(
  File "plaso/plaso/storage/file_interface.py", line 638, in AddEventData
    self._storage_file.AddEventData(event_data, serialized_data=serialized_data)
  File "plaso/plaso/storage/sqlite/sqlite_file.py", line 767, in AddEventData
    self._AddAttributeContainer(self._CONTAINER_TYPE_EVENT_DATA, event_data)
  File "plaso/plaso/storage/sqlite/sqlite_file.py", line 131, in _AddAttributeContainer
    self._WriteSerializedAttributeContainerList(container_type)
  File "plaso/plaso/storage/sqlite/sqlite_file.py", line 694, in _WriteSerializedAttributeContainerList
    self._cursor.executemany(query, values_tuple_list)
sqlite3.OperationalError: database or disk is full
```

**Comment by joachimmetz** [comment]
Related issue https://github.com/log2timeline/plaso/issues/2265

**Comment by joachimmetz** [comment]
Changes in https://github.com/log2timeline/plaso/pull/3743
