### ISSUE TITLE
Fix issue with archive end-to-end test

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3413]
One of the end-to-end tests introduced in https://github.com/log2timeline/plaso/pull/3393 is failing with:

```
2021-01-04 19:32:28,553 [INFO] (MainProcess) PID:4932 <data_location> Determined data location: plaso-linux-e2e-dean_mac-with_archives/data
Traceback (most recent call last):
  File "./tools/psort.py", line 99, in <module>
    if not Main():
  File "./tools/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/cli/psort_tool.py", line 593, in ProcessStorage
    analysis_engine.ExportEvents(
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/multi_processing/psort.py", line 1041, in ExportEvents
    self._ExportEvents(
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/multi_processing/psort.py", line 588, in _ExportEvents
    self._ExportEvent(
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/multi_processing/psort.py", line 482, in _ExportEvent
    self._FlushExportBuffer(
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/multi_processing/psort.py", line 640, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/output/interface.py", line 117, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_data_stream, event_tag)
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/output/interface.py", line 78, in WriteEvent
    self.WriteEventBody(event, event_data, event_data_stream, event_tag)
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/output/interface.py", line 194, in WriteEventBody
    self.WriteLine(output_text)
  File "plaso-linux-e2e-dean_mac-with_archives/plaso/output/interface.py", line 202, in WriteLine
    self._file_object.write('{0:s}\n'.format(text))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 104-110: surrogates not allowed
```

**Comment by joachimmetz** [comment]
Looks this is cause by a path within a tar that contain Unicode surrogates

**Comment by joachimmetz** [comment]
Looks like the PR fixes the issue on the failing end-to-end test

**Comment by joachimmetz** [comment]
Similar issue when looking at the resulting Plaso storage file in pinfo
