### ISSUE TITLE
ImportError: cannot import name 'YaraError' from 'yara'

### ISSUE THREAD

**Issue by ragehead** [log2timeline/plaso#3453]
I'm using Python3.8 and I downloaded Plaso and installed all the requirements (yara module is included). However, when I try to run the `python3.8 log2timeline.py` I get an error message.

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/plaso/analyzers/yara_analyzer.py", line 9, in <module>
    from yara import Error as YaraError
ImportError: cannot import name 'Error' from 'yara' (/home/user/.local/lib/python3.8/site-packages/yara/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/home/user/.local/lib/python3.8/site-packages/plaso/cli/log2timeline_tool.py", line 18, in <module>
    from plaso.analyzers.hashers import manager as hashers_manager
  File "/home/user/.local/lib/python3.8/site-packages/plaso/analyzers/__init__.py", line 5, in <module>
    from plaso.analyzers import yara_analyzer
  File "/home/user/.local/lib/python3.8/site-packages/plaso/analyzers/yara_analyzer.py", line 11, in <module>
    from yara import YaraError
ImportError: cannot import name 'YaraError' from 'yara' (/home/user/.local/lib/python3.8/site-packages/yara/__init__.py)
```

Could anyone help me with it? Thnx

**Comment by joachimmetz** [comment]
Did you install [yara-python](https://github.com/VirusTotal/yara-python) and not some other yara variant ? If so which version ?

**Comment by ragehead** [comment]
> Did you install [yara-python](https://github.com/VirusTotal/yara-python) and not some other yara variant ? If so which version ?

it seems the issue was from having another yara module but I still get an error message, not sure if it's related to this issue or not.


```
Failed to import '/usr/local/lib/libyara.so'
PATH = /home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rekall/bin:/home/user/.fzf/bin;/usr/local/lib
Traceback (most recent call last):
  File "log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/home/user/.local/lib/python3.8/site-packages/plaso/cli/log2timeline_tool.py", line 18, in <module>
    from plaso.analyzers.hashers import manager as hashers_manager
  File "/home/user/.local/lib/python3.8/site-packages/plaso/analyzers/__init__.py", line 5, in <module>
    from plaso.analyzers import yara_analyzer
  File "/home/user/.local/lib/python3.8/site-packages/plaso/analyzers/yara_analyzer.py", line 6, in <module>
    import yara
  File "/home/user/.local/lib/python3.8/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/home/user/.local/lib/python3.8/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/home/user/.local/lib/python3.8/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libyara.so: cannot open shared object file: No such file or directory
```

**Comment by joachimmetz** [comment]
This is another issue. Your yara Python module cannot find libyara.

**These are not Plaso issues!**

These are libyara installation issues. I would strongly recommend to follow one of the recommended installation methods, if you are not comfortable with debugging installation issues https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html.

**Comment by joachimmetz** [comment]
Closing issue, no updated from reporter assuming question has been addressed.
