### ISSUE TITLE
Pre-processing failing on decrypted volume image

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3488]
```
Traceback (most recent call last):
File "/usr/bin/log2timeline.py", line 97, in <module>
if not Main():
File "/usr/bin/log2timeline.py", line 72, in Main
tool.ExtractEventsFromSources()
File "plaso/cli/log2timeline_tool.py", line 414, in ExtractEventsFromSources
self._PreprocessSources(extraction_engine)
File "plaso/cli/extraction_tool.py", line 322, in _PreprocessSources
extraction_engine.PreprocessSources(
File "plaso/engine/engine.py", line 278, in PreprocessSources
operating_system = self._DetermineOperatingSystem(searcher)
File "plaso/engine/engine.py", line 91, in _DetermineOperatingSystem
for path_spec in searcher.Find(find_specs=find_specs):
File "dfvfs/helpers/file_system_searcher.py", line 592, in Find
for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
File "dfvfs/helpers/file_system_searcher.py", line 566, in _FindInFileEntry
for matching_path_spec in self._FindInFileEntry(
File "dfvfs/helpers/file_system_searcher.py", line 566, in _FindInFileEntry
for matching_path_spec in self._FindInFileEntry(
File "dfvfs/helpers/file_system_searcher.py", line 551, in _FindInFileEntry
location_match = find_spec.CompareLocation(
File "dfvfs/helpers/file_system_searcher.py", line 384, in CompareLocation
raise ValueError(
ValueError: File entry path specification and mount point type indicators do not match.
```

**Comment by joachimmetz** [comment]
* the mount point path spec is OS
* the file entry path spec is OS -> NTFS (no additional RAW layer)

**Comment by joachimmetz** [comment]
Change dfVFS to be less strict https://github.com/log2timeline/dfvfs/pull/552
