### ISSUE TITLE
Image export unexpected none

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#350]
Traceback only for now:
```
 image_export.py --names known_hosts mac.dd
[INFO] Data files will be loaded from /usr/share/plaso by default.
Filters:
        names: known_hosts
The following partitions were found:
Identifier      Offset (in bytes)       Size (in bytes)
p1              20480 (0x00005000)      200.0MiB / 209.7MB (209715200 B)
p2              209735680 (0x0c805000)  112.2GiB / 120.5GB (120473067520 B)
p3              120682803200 (0x1c19417000)     619.9MiB / 650.0MB (650002432 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
p2
2015-09-29 14:23:05,741 [INFO] Processing started.
Traceback (most recent call last):
  File "/usr/bin/image_export.py", line 309, in <module>
    if not Main():
  File "/usr/bin/image_export.py", line 292, in Main
    tool.ProcessSources()
  File "/usr/bin/image_export.py", line 270, in ProcessSources
    remove_duplicates=self._remove_duplicates)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/image_export.py", line 931, in ProcessSources
    remove_duplicates=remove_duplicates)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/image_export.py", line 614, in _Extract
    input_queue_consumer.ConsumeItems()
  File "/usr/lib/python2.7/dist-packages/plaso/engine/queue.py", line 132, in ConsumeItems
    self._ConsumeItem(item, **kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/image_export.py", line 578, in _ConsumeItem
    path_spec, self._destination_path, filename_prefix=filename_prefix)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/image_export.py", line 518, in WriteFile
    file_object.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by Onager** [comment]
Just tried to reproduce this and couldn't - looking at the traceback, this issue may no longer be applicable for HEAD.

**Comment by kiddinn** [comment]
let's make sure this is not an issue before closing

**Comment by Onager** [comment]
It's not an issue.
