### ISSUE TITLE
preprocessing: failing on RHEL6 image due to symbolic link

### ISSUE THREAD

**Issue by knsankar** [log2timeline/plaso#3519]
**Description of problem:**

I am trying to create plaso from vmdk with the following command line and it throws an error.

**Command line and arguments:**

log2timeline.py --partitions all --volumes all /data/server.plaso /data/server.vmdk

**Source data:**

# Disk DescriptorFile
version=3
encoding="UTF-8"
CID=577c21a4
parentCID=ffffffff
createType="vmfs"

**Plaso version:**

20210213

**Operating system Plaso is running on:**

CentOS 7

**Installation method:**

Plaso installed from pip3.

All the dependencies are met. 

`# log2timeline.py --troubles
2021-03-06 22:50:11,972 [INFO] (MainProcess) PID:10756 <data_location> Determined data location: /usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/share/plaso
Using Python version 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Path: /usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/EGG-INFO/scripts/log2timeline.py

plaso - log2timeline version 20210213

Checking availability and versions of dependencies.
[OK]		artifacts version: 20200515
[OK]		bencode
[OK]		certifi version: 2019.11.28
[OK]		chardet version: 3.0.4
[OK]		cryptography version: 3.3.2
[OK]		dateutil version: 2.8.1
[OK]		defusedxml version: 0.5.0
[OK]		dfdatetime version: 20200824
[OK]		dfvfs version: 20210213
[OK]		dfwinreg version: 20201006
[OK]		dtfabric version: 20200621
[OK]		elasticsearch version: 7.5.1
[OK]		future version: 0.18.2
[OK]		idna version: 3.1
[OK]		lz4 version: 3.0.2
[OK]		pefile version: 2019.4.18
[OK]		psutil version: 5.7.0
[OK]		pybde version: 20191221
[OK]		pycreg version: 20200725
[OK]		pyesedb version: 20200418
[OK]		pyevt version: 20200418
[OK]		pyevtx version: 20200419
[OK]		pyewf version: 20140806
[OK]		pyfsapfs version: 20201107
[OK]		pyfsext version: 20210129
[OK]		pyfshfs version: 20201104
[OK]		pyfsntfs version: 20201115
[OK]		pyfsxfs version: 20201117
[OK]		pyfvde version: 20191221
[OK]		pyfwnt version: 20191222
[OK]		pyfwsi version: 20191221
[OK]		pylnk version: 20191221
[OK]		pyluksde version: 20200205
[OK]		pymsiecf version: 20191221
[OK]		pyolecf version: 20191221
[OK]		pyparsing version: 2.4.7
[OK]		pyqcow version: 20191221
[OK]		pyregf version: 20201007
[OK]		pyscca version: 20191222
[OK]		pysigscan version: 20191221
[OK]		pysmdev version: 20200210
[OK]		pysmraw version: 20191221
[OK]		pytsk3 version: 20200117
[OK]		pytz
[OK]		pyvhdi version: 20191221
[OK]		pyvmdk version: 20191221
[OK]		pyvsgpt version: 20210207
[OK]		pyvshadow version: 20191221
[OK]		pyvslvm version: 20200102
[OK]		redis version: 3.5.3
[OK]		requests version: 2.25.0
[OK]		six version: 1.12.0
[OK]		urllib3 version: 1.25.8
[OK]		xlsxwriter version: 1.2.8
[OK]		yaml version: 5.4.1
[OK]		yara version: 3.11.0
[OK]		zmq version: 14.7.0`

**Debug output/tracebacks:**

`Processing started.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dfvfs/resolver/resolver.py", line 109, in OpenFileObject
    file_object.Open()
  File "/usr/local/lib/python3.6/site-packages/dfvfs/file_io/file_io.py", line 89, in Open
    self._Open(mode=mode)
  File "/usr/local/lib/python3.6/site-packages/dfvfs/file_io/tsk_file_io.py", line 117, in _Open
    raise IOError('Not a regular file.')
OSError: Not a regular file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20210213', 'log2timeline.py')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/EGG-INFO/scripts/log2timeline.py", line 94, in <module>
    if not Main():
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/EGG-INFO/scripts/log2timeline.py", line 69, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/cli/log2timeline_tool.py", line 414, in ExtractEventsFromSources
    self._PreprocessSources(extraction_engine)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/cli/extraction_tool.py", line 331, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/engine/engine.py", line 287, in PreprocessSources
    self.knowledge_base)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/preprocessors/manager.py", line 317, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/preprocessors/manager.py", line 155, in CollectFromFileSystem
    knowledge_base, artifact_definition, searcher, file_system)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/preprocessors/interface.py", line 78, in Collect
    source.separator)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/preprocessors/interface.py", line 132, in _ParsePathSpecification
    self._ParseFileEntry(knowledge_base, file_entry)
  File "/usr/local/lib/python3.6/site-packages/plaso-20210213-py3.6.egg/plaso/preprocessors/interface.py", line 166, in _ParseFileEntry
    file_object = file_entry.GetFileObject()
  File "/usr/local/lib/python3.6/site-packages/dfvfs/vfs/tsk_file_entry.py", line 804, in GetFileObject
    path_spec, resolver_context=self._resolver_context)
  File "/usr/local/lib/python3.6/site-packages/dfvfs/resolver/resolver.py", line 112, in OpenFileObject
    'Unable to open file object with error: {0!s}'.format(exception))
dfvfs.lib.errors.BackEndError: Unable to open file object with error: Not a regular file.`

**Comment by joachimmetz** [comment]
This looks like preprocessing is trying to read a file which is not a file.
Can you provide more info what operating system is in server.vmdk

If you can please attach debug log, also see https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html

**Comment by knsankar** [comment]
server.vmdk is a RHEL6 harddisk.

**Comment by joachimmetz** [comment]
Ack, I'll see if I can dig up a stock RHEL6 image from somewhere. I assume that preprocessing encounters a symbolic link where it expects a regular file.

**Comment by joachimmetz** [comment]
Was able to reproduce with the RedHat's official RHEL 6.10 KVM image (rhel-server-6.10-update-11-x86_64-kvm.qcow2)
