### ISSUE TITLE
Fix failing end-to-end tests

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3560]
```
2021-04-17 08:57:31,305 [INFO] (MainProcess) PID:7953 <data_location> Determined data location: /tmp/workspace/plaso-linux-e2e-dc1-greendale3/data
Traceback (most recent call last):
  File "./tools/psort.py", line 101, in <module>
    if not Main():
  File "./tools/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/cli/psort_tool.py", line 598, in ProcessStorage
    analysis_engine.ExportEvents(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/multi_processing/psort.py", line 1056, in ExportEvents
    self._ExportEvents(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/multi_processing/psort.py", line 590, in _ExportEvents
    self._ExportEvent(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/multi_processing/psort.py", line 484, in _ExportEvent
    self._FlushExportBuffer(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/multi_processing/psort.py", line 642, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/interface.py", line 115, in WriteEventMACBGroup
    self.WriteEvent(event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/interface.py", line 76, in WriteEvent
    self.WriteEventBody(event, event_data, event_data_stream, event_tag)
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/interface.py", line 189, in WriteEventBody
    output_text = self._event_formatting_helper.GetFormattedEvent(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/shared_dsv.py", line 56, in GetFormattedEvent
    field_value = self._field_formatting_helper.GetFormattedField(
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/formatting_helper.py", line 549, in GetFormattedField
    output_value = callback_function(event, event_data, event_data_stream)
  File "/tmp/workspace/plaso-linux-e2e-dc1-greendale3/plaso/output/formatting_helper.py", line 79, in _FormatDateTime
    if iso8601_string[10] == 'T' and iso8601_string[-1] == 'Z':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by joachimmetz** [comment]
Issue introduced by https://github.com/log2timeline/plaso/commit/cd7bde44b2028de091193ead2bb6d870f8b832d8
