### ISSUE TITLE
pefile 2021.5.13 causes unit tests to fail

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3591]
Seen on the CI tests https://github.com/log2timeline/plaso/runs/2581908094?check_suite_focus=true

```
pefile==2021.5.13
```

```
======================================================================
FAIL: testParseFileObjectOnDriver (parsers.pe.PECOFFTest)
Tests the ParseFileObject on a PE driver (SYS) file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/plaso/plaso/tests/parsers/pe.py", line 62, in testParseFileObjectOnDriver
    self.CheckEventValues(storage_writer, events[0], expected_event_values)
  File "./tests/parsers/test_lib.py", line 198, in CheckEventValues
    self.assertEqual(value, expected_value, error_message)
AssertionError: 'Executable (EXE)' != 'Driver (SYS)'
- Executable (EXE)
+ Driver (SYS)
 : event value: "pe_type" does not match expected value
```

**Comment by joachimmetz** [comment]
Set a maximum version for the time being https://github.com/log2timeline/plaso/pull/3593

**Comment by joachimmetz** [comment]
Changing the test for now, have filed an issue with upstream to see what is the root cause https://github.com/erocarrera/pefile/issues/322
