### ISSUE TITLE
Serializer: exception when deserializing pathspec

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#371]
```
» PYTHONPATH=. ./tools/psort.py --output_format=dynamic /tmp/test.plaso
[INFO] Data files will be loaded from /home/onager/code/plaso/data by default.
datetime,timestamp_desc,source,source_long,message,parser,display_name,tag,store_number,store_index
Traceback (most recent call last):
  File "./tools/psort.py", line 676, in <module>
    if not Main():
  File "./tools/psort.py", line 671, in Main
    tool.ProcessStorage()
  File "./tools/psort.py", line 623, in ProcessStorage
    self._ProcessStorage()
  File "./tools/psort.py", line 252, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/home/onager/code/plaso/plaso/frontend/psort.py", line 403, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/home/onager/code/plaso/plaso/frontend/psort.py", line 556, in ProcessEventsFromStorage
    event_object = storage_file.GetSortedEntry()
  File "/home/onager/code/plaso/plaso/lib/storage.py", line 1071, in GetSortedEntry
    event_object = self.GetEventObject(store_number)
  File "/home/onager/code/plaso/plaso/lib/storage.py", line 1131, in GetEventObject
    event_object_data)
  File "/home/onager/code/plaso/plaso/serializer/json_serializer.py", line 799, in ReadSerialized
    return json_decoder.decode(json_string)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/onager/code/plaso/plaso/serializer/json_serializer.py", line 249, in _ConvertDictToObject
    return self._ConvertDictToPathSpec(json_dict)
  File "/home/onager/code/plaso/plaso/serializer/json_serializer.py", line 211, in _ConvertDictToPathSpec
    type_indicator, **json_dict)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/factory.py", line 107, in NewPathSpec
    return path_spec_type(**kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/os_path_spec.py", line 42, in __init__
    super(OSPathSpec, self).__init__(location=location, parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/location_path_spec.py", line 26, in __init__
    super(LocationPathSpec, self).__init__(parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/path_spec.py", line 25, in __init__
    raise ValueError(u'Unused keyword arguments.')
ValueError: Unused keyword arguments.


 » ./utils/check_dependencies.py
 <snip>
 [OK]		dfvfs version: 20151008
 <snip>
```

**Comment by kiddinn** [comment]
if you run debugger on this you'll see:

```
(Pdb) kwargs
{u'data_stream': u''}
```

And if you go a bit up:

```
> ... dfvfs/path/factory.py(107)NewPathSpec()
-> return path_spec_type(**kwargs)
Pdb) kwargs
{u'data_stream': u'', u'location': u'/.../Users/provision/Library/Preferences/com.apple.scheduler.plist'}
```

(or whatever file of the day is)

And if you read the actual serialized object:
```
(Pdb) json_string
'{"username": "-", "inode": <REDACTED>, "display_name": "OS:...Users/provision/Library/Preferences/com.apple.scheduler.plist", "uuid": "<REDACTED>", "timestamp_desc": "Content Modification Time", "timestamp": 978336000000000, "parser": "plist/plist_default", "__type__": "EventObject", "filename": "/.../provision/Library/Preferences/com.apple.scheduler.plist", "data_type": {"__type__": "bytes", "stream": "plist:key"}, "key": {"__type__": "bytes", "stream": "date"}, "pathspec": {"data_stream": "", "type_indicator": "OS", "__type__": "PathSpec", "location": "...Library/Preferences/com.apple.scheduler.plist"}, "root": "/AbsoluteSchedule/com.apple.SoftwareUpdate/SUCheckSchedulerTag/Timer"}'
```

**Comment by joachimmetz** [comment]
With which version of dfvfs was the plaso storage file created?

```
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/factory.py", line 107, in NewPathSpec
    return path_spec_type(**kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/os_path_spec.py", line 42, in __init__
    super(OSPathSpec, self).__init__(location=location, parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/location_path_spec.py", line 26, in __init__
    super(LocationPathSpec, self).__init__(parent=parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/path_spec.py", line 25, in __init__
    raise ValueError(u'Unused keyword arguments.')
```

Indicates an OS path spec with data stream is defined.

**Comment by rgayon** [comment]
Stumbled upon the same error. It happens when launching l2t on a directory with 1 file inside but everything's fine when when running it on said file
