### ISSUE TITLE
Winrestore: exception parsing data stream

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#372]
```
2015-10-13 16:22:39,294 [ERROR] (Worker_09 ) PID:8326 <worker> ParseFileObject() got multiple values for keyword argument 'file_object'
Traceback (most recent call last):
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 535, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry, data_stream_name=data_stream_name)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 488, in _ProcessFileEntry
    self._ProcessDataStream(file_entry, data_stream_name=data_stream_name)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 430, in _ProcessDataStream
    parser_object, file_entry, file_object=file_object)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 236, in _ParseFileEntryWithParser
    self._parser_mediator, file_object=file_object)
  File "/home/onager/code/plaso/plaso/parsers/interface.py", line 212, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "/home/onager/code/plaso/plaso/parsers/winrestore.py", line 115, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
TypeError: ParseFileObject() got multiple values for keyword argument 'file_object'
```

Looks to be related to the recent changes to file_object handling in the worker/parser interface.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/267420043/

**Comment by joachimmetz** [comment]
@Onager the CL is in can you confirm it fixes the issue.

**Comment by Onager** [comment]
This is now fixed.
