### ISSUE TITLE
end-to-end tests failing with: KeyError: 'Date and time values type: WebKitTime not set.'

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3994]
```
2021-12-19 17:20:18,301 [INFO] (MainProcess) PID:5409 <data_location> Determined data location: /tmp/workspace/plaso-linux-e2e-dean-macbook/data
Traceback (most recent call last):
  File "./tools/psort.py", line 101, in <module>
    if not Main():
  File "./tools/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/multi_process/output_engine.py", line 491, in ExportEvents
    self._ExportEvents(
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/multi_process/output_engine.py", line 295, in _ExportEvents
    for event in storage_reader.GetSortedEvents(time_range=time_slice_range):
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/storage/sqlite/sqlite_file.py", line 401, in _GetAttributeContainersWithFilter
    container = self._CreatetAttributeContainerFromRow(
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/storage/sqlite/sqlite_file.py", line 333, in _CreatetAttributeContainerFromRow
    attribute_value = self._serializer.ReadSerialized(attribute_value)
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/serializer/json_serializer.py", line 493, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/serializer/json_serializer.py", line 517, in ReadSerializedDict
    json_object = cls._ConvertJSONToValue(json_dict)
  File "/tmp/workspace/plaso-linux-e2e-dean-macbook/plaso/serializer/json_serializer.py", line 294, in _ConvertJSONToValue
    return convert_function(json_dict)
  File "/usr/lib/python3/dist-packages/dfdatetime/serializer.py", line 48, in ConvertDictToDateTimeValues
    date_time = factory.Factory.NewDateTimeValues(class_name, **json_dict)
  File "/usr/lib/python3/dist-packages/dfdatetime/factory.py", line 42, in NewDateTimeValues
    raise KeyError('Date and time values type: {0:s} not set.'.format(
KeyError: 'Date and time values type: WebKitTime not set.'
```

**Comment by joachimmetz** [comment]
Looks like an issue in dfDateTime 20211113 pre-release

**Comment by joachimmetz** [comment]
Issue addressed
