### ISSUE TITLE
macOS: AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by mhansen** [log2timeline/plaso#4020]
Hi there! Having some troubles on macOS, thought it might be useful to report in case anyone else is seeing this. The error looks pretty deep in your dependencies (multiprocessing) though, perhaps it isn't your problem?

**Description of problem:**

I'm trying to run log2timeline:

Here's my commands, and the error I get:
```
$ git clone https://github.com/log2timeline/plaso.git
$ cd plaso
$ python3 -m virtualenv -p python3 venv
$ . venv/bin/activate.fish
$ pip3 install -r requirements.txt
$  python3 setup.py build
$ python3 setup.py install
$ venv/bin/log2timeline.py --storage-file timeline.plaso /Volumes/dell/sda2 --process_memory_limit 0
2022-01-05 10:32:14,774 [INFO] (MainProcess) PID:51768 <data_location> Determined data location: /Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/share/plaso
2022-01-05 10:32:14,781 [INFO] (MainProcess) PID:51768 <artifact_definitions> Determined artifact definitions path: /Users/mark/projects/plaso/venv/share/artifacts
Checking availability and versions of dependencies.
[OK]


Source path             : /Volumes/dell/sda2
Source type             : storage media image
Processing time         : 00:00:00

Processing started.
Traceback (most recent call last):
  File "/Users/mark/projects/plaso/venv/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20211229', 'log2timeline.py')
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 73, in Main
    tool.ExtractEventsFromSources()
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/cli/extraction_tool.py", line 730, in ExtractEventsFromSources
    processing_status = self._ProcessSources(session, storage_writer)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/cli/extraction_tool.py", line 583, in _ProcessSources
    processing_status = extraction_engine.ProcessSources(
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/multi_process/extraction_engine.py", line 993, in ProcessSources
    worker_process = self._StartWorkerProcess(process_name)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/multi_process/extraction_engine.py", line 765, in _StartWorkerProcess
    process.start()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```

Then it hangs, using no CPU. I think it's wedged.

**Source data:**

The source is a windows XP disk partition, sorry, can't share it. Hopefully it's clear enough from the error message above what's happening without it?

**Plaso version:**

`fb0762bd996abc31872b9c212f31d7d3007e2d0f` (top of tree)

**Operating system Plaso is running on:**

macOS on M1
```
$ python3 -V
Python 3.9.9
```

**Installation method:**

git clone, see above

**Debug output/tracebacks:**

```
2022-01-05 10:30:13,055 [WARNING] (MainProcess) PID:51674 <extraction_tool> Appending to an already existing storage file.
2022-01-05 10:30:14,511 [INFO] (MainProcess) PID:51674 <engine> Preprocessing detected operating systems: Windows NT
```

**Comment by joachimmetz** [comment]
Based on the last part of the output and a couple of web searches, this does **not** look Plaso related 

```
 File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
```

**Comment by joachimmetz** [comment]
Some context https://stackoverflow.com/questions/45720153/python-multiprocessing-error-attributeerror-module-main-has-no-attribute

**Comment by mhansen** [comment]
I'm not running from a python shell. I'm running from fish, a normal-ish shell, inside tmux, inside Terminal.app terminal emulator. No Spyder or pdb or anaconda or notebook wrapper.

**Comment by joachimmetz** [comment]
As stated in #3164, we've not been able to reproduce this. So you'll need to track down what is different on your installation to determine if this is something that Plaso can address. Or use the Docker build since that is not affected by such these kind of installation specific issues.

**Comment by mhansen** [comment]
Am I perhaps invoking the script wrong? (venv/bin/log2timeline.py)? Do I need to invoke a script with a __main__ if-statement in it instead perhaps?

**Comment by joachimmetz** [comment]
> Am I perhaps invoking the script wrong? (venv/bin/log2timeline.py)?

doesn't `venv/bin/log2timeline.py` contain a main statement? if not, something went wrong in your installation

**Comment by mhansen** [comment]
I think my venv/bin/log2timeline.py just imports and delegates unconditionally to another file. I'll check tomorrow.

**Comment by mhansen** [comment]
There's no `if __name__ == "__main__" in here.

```
$ cat venv/bin/log2timeline.py
#!/Users/mark/projects/plaso/venv/bin/python3
# EASY-INSTALL-SCRIPT: 'plaso==20211229','log2timeline.py'
__requires__ = 'plaso==20211229'
__import__('pkg_resources').run_script('plaso==20211229', 'log2timeline.py')
```

Maybe that run_script function is resetting __main__ because it's running with run_script, not as main. Not sure. I'll investigate further.

**Comment by mhansen** [comment]
Hmm, no, `__name__ == "__main__"` in `scripts/log2timeline.py` as indicated by this stack frame:

```
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
```
That line of code is inside the if-statement checking `__name__ == "__main__"`

**Comment by mhansen** [comment]
Trying upgrading to python 3.10 (as the spawn function and `__spec__` stuff is inside python.

I still get the same (ish) error message:

```
Processing started.
Traceback (most recent call last):
  File "/Users/mark/projects/plaso/venv/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20211229', 'log2timeline.py')
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py", line 73, in Main
    tool.ExtractEventsFromSources()
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/plaso/cli/extraction_tool.py", line 730, in ExtractEventsFromSources
    processing_status = self._ProcessSources(session, storage_writer)
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/plaso/cli/extraction_tool.py", line 583, in _ProcessSources
    processing_status = extraction_engine.ProcessSources(
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/plaso/multi_process/extraction_engine.py", line 993, in ProcessSources
    worker_process = self._StartWorkerProcess(process_name)
  File "/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/plaso/multi_process/extraction_engine.py", line 765, in _StartWorkerProcess
    process.start()
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'. Did you mean: '__doc__'?
```

**Comment by mhansen** [comment]
I'm binary searching through the stack to find where `__spec__` was removed from the main module.

At the root of the stack trace, in `venv/bin/log2timeline.py`, it's present, if I change the file to add `import pdb; pdb. set_trace()` at the top of the file, I see in the debugger that `__spec__` is present:

```
> /Users/mark/projects/plaso/venv/bin/log2timeline.py(4)<module>()
-> __requires__ = 'plaso==20211229'
(Pdb) import sys
(Pdb) main_module = sys.modules['__main__']
(Pdb) dir(main_module)
['__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'main_module', 'pdb', 'sys']
(Pdb) main_module
<module '__main__' from '/Users/mark/projects/plaso/venv/bin/log2timeline.py'>
(Pdb) main_module.__file__
'/Users/mark/projects/plaso/venv/bin/log2timeline.py'
(Pdb) getattr(main_module.__spec__, "name", None)
(Pdb)
```

At the leaf of the stack trace, in `multi_process/extraction_engine.py:765`, I see that `__spec__` is gone, and the `main_module.__file__` has changed to `venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py`:

```
(Pdb) import sys
(Pdb) main_module = sys.modules['__main__']
(Pdb) main_module
<module '__main__' from '/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py'>
(Pdb) dir(main_module)
['Main', '__builtins__', '__doc__', '__file__', '__name__', 'dependencies', 'errors', 'log2timeline_tool', 'logging', 'multiprocessing', 'os', 'sys']
(Pdb) main_module.__file__
'/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py'
```

**Comment by mhansen** [comment]
The `__main__` is reset to remove `__spec__` very early on, before the call to `venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py`:

```
> /Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py(98)<module>()
-> multiprocessing.freeze_support()
(Pdb) import sys
(Pdb) main_module = sys.modules['__main__']
(Pdb) dir(main_module)
['Main', '__builtins__', '__doc__', '__file__', '__name__', 'dependencies', 'errors', 'log2timeline_tool', 'logging', 'main_module', 'multiprocessing', 'os', 'pdb', 'sys']
(Pdb) main_module.__file__
'/Users/mark/projects/plaso/venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py'
(Pdb) getattr(main_module.__spec__, "name", None)
*** AttributeError: module '__main__' has no attribute '__spec__'
```

So it must be removed by `pkg_resources`

**Comment by mhansen** [comment]
Somewhat confirming the hypothesis above, if I run `venv/lib/python3.10/site-packages/plaso-20211229-py3.10.egg/EGG-INFO/scripts/log2timeline.py` directly, not via `venv/bin/log2timeline.py`, then I'm able to proceed past the error and the scan commences:

```
plaso - log2timeline version 20211229

Source path             : /Volumes/dell/sda2
Source type             : storage media image
Processing time         : 00:00:16
```

**Comment by mhansen** [comment]
`pkg_resources` seems to be part of `setuptools`, which isn't part of the python distribution.

`pkg_resources` is calling `exec` (a python built-in function) which is probably doing the work of re-setting main.

I'm not sure if I should chase this up with setuptools or with Python.

**Comment by joachimmetz** [comment]
@mhansen what version of setuptools and pkg_resources are you using? have you tried their latest versions or default versions?

**Comment by mhansen** [comment]
I think (but not sure) that `pkg_resources` is distributed with setuptools. I think the way to tell what `setuptools` is `pip list`:

```
$ pip list
pip                21.3.1
setuptools         60.2.0
```

That seems to be the latest version on pypi: https://pypi.org/project/setuptools/

**Comment by mhansen** [comment]
Just to close this out; I've moved on from this problem and probably won't
have time to investigate further. Thanks for the help! Wonder what was
going on but the workaround solved my problem and now my forensics are
solved :-)
