### ISSUE TITLE
macOS: ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by mhansen** [log2timeline/plaso#4021]
**Description of problem:**

I'm trying to run log2timeline on macOS, and getting this error. I have a workaround (set `--process_memory_limit 0`), but I thought I'd report it all the same.

**Command line and arguments:**

```
$ venv/bin/log2timeline.py --storage-file timeline.plaso /Volumes/dell/sda2
2022-01-05 10:19:29,351 [INFO] (MainProcess) PID:51457 <data_location> Determined data location: /Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg
/share/plaso
2022-01-05 10:19:29,357 [INFO] (MainProcess) PID:51457 <artifact_definitions> Determined artifact definitions path: /Users/mark/projects/plaso/venv/share/artifacts
Traceback (most recent call last):
  File "/Users/mark/projects/plaso/venv/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20211229', 'log2timeline.py')
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 19, in Main
    if not tool.ParseArguments(sys.argv[1:]):
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/cli/log2timeline_tool.py", line 245, in ParseArguments
    self.ParseOptions(options)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/cli/log2timeline_tool.py", line 337, in ParseOptions
    self._EnforceProcessMemoryLimit(self._process_memory_limit)
  File "/Users/mark/projects/plaso/venv/lib/python3.9/site-packages/plaso-20211229-py3.9.egg/plaso/cli/tools.py", line 137, in _EnforceProcessMemoryLimit
    resource.setrlimit(resource.RLIMIT_DATA, (memory_limit, memory_limit))
ValueError: current limit exceeds maximum limit
```
**Source data:**

Can't share sorry. It's an NTFS drive image. I think the error happens before reading the disk data.

**Plaso version:**

Top of tree. `fb0762bd996abc31872b9c212f31d7d3007e2d0f`

**Operating system Plaso is running on:**

macOS. Python 3.9

**Installation method:**

git clone

**Comment by joachimmetz** [comment]
> Can't share sorry. It's an NTFS drive image. I think the error happens before reading the disk data.

That is fine, the script is trying to set the memory resource limit https://github.com/log2timeline/plaso/blob/fb0762bd996abc31872b9c212f31d7d3007e2d0f/plaso/cli/tools.py#L137, which for some reason is failing on your system.

**Comment by joachimmetz** [comment]
Note to self, might be good to add a more explanatory error message

**Comment by studiawan** [comment]
Hi, I am trying to develop a parser on MacOS and having the same issue. I hope the July release will solve this issue.

**Comment by joachimmetz** [comment]
@studiawan if you want to develop for Plaso use HEAD, in which this issue should be resolved.

**Comment by studiawan** [comment]
Thanks @joachimmetz I will try it.
