### ISSUE TITLE
ValueError: Number of produced sources smaller than previous update.

### ISSUE THREAD

**Issue by duckexmachina** [log2timeline/plaso#4041]
Status thread crashes (?) with error
```
ValueError: Number of produced sources smaller than previous update.
```
**Command line and arguments:**
```
psteal.py  -d --process_archives --source ./timeline/ -w ./timeline.debug.csv
```
**Source data:**

Windows 10.0.18362SP0 user profile acquired with GRR, extracted to a directory

**Plaso version:**

plaso - psteal version 20211229

**Operating system Plaso is running on:**

```Ubuntu 20.04.3 LTS \n \l```
```5.4.0-99-generic #112-Ubuntu```

**Installation method:**
 installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Debug output/tracebacks:**
```
Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 103, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 79, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 730, in ExtractEventsFromSources
    processing_status = self._ProcessSources(session, storage_writer)
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 583, in _ProcessSources
    processing_status = extraction_engine.ProcessSources(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/extraction_engine.py", line 1017, in ProcessSources
    self._StopStatusUpdateThread()
  File "/usr/lib/python3/dist-packages/plaso/multi_process/engine.py", line 400, in _StopStatusUpdateThread
    self._UpdateStatus()
  File "/usr/lib/python3/dist-packages/plaso/multi_process/extraction_engine.py", line 927, in _UpdateStatus
    self._CheckStatusWorkerProcess(pid)
  File "/usr/lib/python3/dist-packages/plaso/multi_process/engine.py", line 156, in _CheckStatusWorkerProcess
    self._UpdateProcessingStatus(pid, process_status, used_memory)
  File "/usr/lib/python3/dist-packages/plaso/multi_process/extraction_engine.py", line 903, in _UpdateProcessingStatus
    self._processing_status.UpdateWorkerStatus(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 390, in UpdateWorkerStatus
    self._UpdateProcessStatus(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 272, in _UpdateProcessStatus
    process_status.UpdateNumberOfEventSources(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 165, in UpdateNumberOfEventSources
    raise ValueError(
ValueError: Number of produced sources smaller than previous update.
```

**Comment by duckexmachina** [comment]
Thanks @joachimmetz 
No, this doesn't happen without the ```--process_archives``` option. 

Anecdotally, whenever I've seen this happen, I always seem to see Teams.exe in the status output, and it seems to hang the worker... :
```Worker_01       48237   extracting      181.7 MiB       2220 (0)        9539 (0)        ZIP:/lib/net45/Teams.exe
Worker_02       48239   not responding  177.1 MiB       2415 (0)        16032 (0)       ZIP:/lib/net45/Teams.exe
Worker_03       48241   idle            140.6 MiB       9301 (0)        36071 (5)       ZIP:/themeVariants/variant4/theme/theme/auxiliaryThemeThumbnail.jpeg
Worker_04       48243   extracting      197.5 MiB       4035 (0)        5547 (0)        ZIP:/lib/net45/Teams.exe
```
and shows up in the logs thusly:
```
2022-02-10 16:47:58,699 [DEBUG] (MainProcess) PID:48230 <task_manager> Abandoned queued task: c17f29f91f904511a6fe3ac805f36b11.
2022-02-10 16:47:58,699 [DEBUG] (MainProcess) PID:48230 <task_manager> Abandoned queued task: c7a415fd2c2c49c3bf82503dcacc861d.
2022-02-10 16:47:58,699 [DEBUG] (MainProcess) PID:48230 <task_manager> Abandoned queued task: 165bd7fa849a411dacd2f4512cf16a85.
2022-02-10 16:47:58,699 [DEBUG] (MainProcess) PID:48230 <extraction_engine> Task scheduler stopped
2022-02-10 16:47:58,704 [ERROR] (MainProcess) PID:48230 <extraction_engine> Process Worker_01 (PID: 48237) has not reported activity within the timeout period.
2022-02-10 16:47:58,704 [DEBUG] (MainProcess) PID:48230 <task_manager> Task b59b047021d74242b0f260e654d023b6 was abandoned, but now processing.
2022-02-10 16:47:58,705 [ERROR] (MainProcess) PID:48230 <engine> Process Worker_01 (PID: 48237) is not functioning correctly. Status code: not responding.
2022-02-10 16:47:58,705 [WARNING] (MainProcess) PID:48230 <engine> Terminating process: (PID: 48237).
2022-02-10 16:48:03,708 [WARNING] (MainProcess) PID:48230 <engine> Killing process: (PID: 48237).
2022-02-10 16:48:03,709 [DEBUG] (MainProcess) PID:48230 <engine> Stopped monitoring process: Worker_01 (PID: 48237)
2022-02-10 16:48:03,709 [INFO] (MainProcess) PID:48230 <engine> Attempt: 1 to start replacement worker process for Worker_01
2022-02-10 16:48:03,710 [DEBUG] (MainProcess) PID:48230 <extraction_engine> Starting worker process Worker_01
2022-02-10 16:48:03,824 [ERROR] (MainProcess) PID:48230 <extraction_engine> Process Worker_04 (PID: 48243) has not reported activity within the timeout period.
2022-02-10 16:48:03,824 [DEBUG] (MainProcess) PID:48230 <task_manager> Task 35e98b45188b41159451600c9000ca2d was abandoned, but now processing.
2022-02-10 16:48:03,824 [ERROR] (MainProcess) PID:48230 <engine> Process Worker_04 (PID: 48243) is not functioning correctly. Status code: not responding.
2022-02-10 16:48:03,825 [WARNING] (MainProcess) PID:48230 <engine> Terminating process: (PID: 48243).
2022-02-10 16:48:08,828 [WARNING] (MainProcess) PID:48230 <engine> Killing process: (PID: 48243).
2022-02-10 16:48:08,828 [DEBUG] (MainProcess) PID:48230 <engine> Stopped monitoring process: Worker_04 (PID: 48243)
2022-02-10 16:48:08,829 [INFO] (MainProcess) PID:48230 <engine> Attempt: 1 to start replacement worker process for Worker_04
2022-02-10 16:48:08,829 [DEBUG] (MainProcess) PID:48230 <extraction_engine> Starting worker process Worker_04
2022-02-10 16:48:08,952 [DEBUG] (MainProcess) PID:48230 <task_manager> Task c17f29f91f904511a6fe3ac805f36b11 was abandoned, but now processing.
2022-02-10 16:48:08,957 [DEBUG] (MainProcess) PID:48230 <task_manager> Task 165bd7fa849a411dacd2f4512cf16a85 was abandoned, but now processing.
2022-02-10 16:48:08,958 [DEBUG] (MainProcess) PID:48230 <task_manager> Task c7a415fd2c2c49c3bf82503dcacc861d was abandoned, but now processing.
```
digging a little deeper, I found the archive containing Teams.exe ```~/AppData/Local/Microsoft/Teams/packages/Teams-1.4.00.7174-full.nupkg```  and removed it from the source data. 
**Re-runnnig the timeline with the same options (with the problem archive removed) log2timeline completes and exits normally** !!! 💯 

Running ```psteal.py  -d --process_archives --source ./Teams-1.4.00.7174-full.nupkg  -w ./Teams.nupkg.debug.csv```

against just the single file, it eventually just hangs on extracting Teams.exe and after a few minutes throws the same error as before.

```
Source path             : /data/localfast//Teams-1.4.00.7174-full.nupkg
Source type             : single file
Processing time         : 00:12:19

Tasks:          Queued  Processing      Merging         Abandoned       Total
                0       3               0               0               4110

Identifier      PID     Status          Memory          Sources         Events          File
Main            61887   running         156.1 MiB       4110 (0)        6233 (0)
Worker_00       61892   idle            161.9 MiB       983 (0)         389 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RTMPLTFM.dll
Worker_01       61894   idle            156.2 MiB       167 (0)         598 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/slimcore.node
Worker_02       61896   extracting      175.4 MiB       381 (0)         171 (0)         ZIP:/lib/net45/Teams.exe
Worker_03       61898   idle            144.8 MiB       208 (0)         369 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/adal34-win/build/Release/adal.dll
Worker_04       61900   idle            158.4 MiB       172 (0)         279 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/slimcore.node
Worker_05       61902   idle            135.5 MiB       107 (0)         742 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/@microsoft/fasttext-languagedetector/build/Release/fastText-languagedetector.node
Worker_06       61904   extracting      152.4 MiB       298 (0)         185 (0)         ZIP:/lib/net45/Teams.exe
Worker_07       61908   extracting      181.6 MiB       99 (0)          10 (0)          ZIP:/lib/net45/Teams.exe
Worker_08       61910   idle            121.0 MiB       378 (0)         542 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/@msteams/node-locale-info-provider/build/Release/node-locale-info-provider.node
Worker_09       61912   idle            156.4 MiB       129 (0)         444 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/skypert.dll
Worker_10       61914   idle            138.1 MiB       70 (0)          466 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/@msteams/electron-modules-package-utils/build/Release/package-utils.node
Worker_11       61916   idle            126.5 MiB       328 (0)         269 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RtmCodecs.dll
Worker_12       61918   idle            155.6 MiB       221 (0)         623 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RTMPLTFM.dll
Worker_13       61922   idle            138.8 MiB       304 (0)         432 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/adal3-win/build/Release/adal.dll
Worker_14       61926   idle            143.3 MiB       264 (0)         717 (0)         ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RTMPLTFM.dll


Exception in thread Status update:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/plaso/multi_process/engine.py", line 347, in _StatusUpdateThreadMain
    self._UpdateStatus()
  File "/usr/lib/python3/dist-packages/plaso/multi_process/extraction_engine.py", line 927, in _UpdateStatus
    self._CheckStatusWorkerProcess(pid)
  File "/usr/lib/python3/dist-packages/plaso/multi_process/engine.py", line 156, in _CheckStatusWorkerProcess
    self._UpdateProcessingStatus(pid, process_status, used_memory)
  File "/usr/lib/python3/dist-packages/plaso/multi_process/extraction_engine.py", line 903, in _UpdateProcessingStatus
    self._processing_status.UpdateWorkerStatus(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 390, in UpdateWorkerStatus
    self._UpdateProcessStatus(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 272, in _UpdateProcessStatus
    process_status.UpdateNumberOfEventSources(
  File "/usr/lib/python3/dist-packages/plaso/engine/processing_status.py", line 156, in UpdateNumberOfEventSources
    raise ValueError(
ValueError: Number of consumed sources smaller than previous update.
```
I can provide a copy of the troublesome archive if needed. 

Teams-1.4.00.7174-full.nupkg
Sha256 | dd307f81878d210b41335d24ed0bf20446287f284deb7b6d5214f1f089f40241

**Comment by joachimmetz** [comment]
> I can provide a copy of the troublesome archive if needed.

Thx, that would be useful to determine what is triggering the exception

**Comment by duckexmachina** [comment]
sent to your email

**Comment by joachimmetz** [comment]
received it, thx, having a look at this shortly when time permits

**Comment by joachimmetz** [comment]
Name of the file "Teams-1.4.00.7174-full.nupkg.zip"

**Comment by joachimmetz** [comment]
```
plaso - log2timeline version 20220129

Source path		: Teams-1.4.00.7174-full.nupkg.zip
Source type		: single file
Processing time		: 00:16:59

Tasks:          Queued  Processing      Merging         Abandoned       Total
                781     7               0               0               990

Identifier      PID     Status          Memory          Sources         Events          File
Main            4178363 running         157.3 MiB       990 (0)         331 (0)         
Worker_00       4178367 extracting      161.2 MiB       832 (0)         73 (0)          ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/platform.node
Worker_01       4178369 not responding  219.9 MiB       0 (0)           23 (0)          ZIP:/lib/net45/Teams.exe
Worker_02       4178371 extracting      192.2 MiB       7 (0)           69 (0)          ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RtmMediaManager.dll
Worker_03       4178373 extracting      211.1 MiB       9 (0)           30 (0)          ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/onnxruntime.dll
Worker_04       4178375 not responding  187.4 MiB       1 (0)           21 (0)          ZIP:/lib/net45/ucrtbase.dll
Worker_05       4178377 extracting      212.8 MiB       7 (0)           62 (0)          ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RtmControl.dll
Worker_06       4178379 extracting      194.4 MiB       133 (0)         60 (0)          ZIP:/lib/net45/resources/app.asar.unpacked/node_modules/slimcore/bin/RtmCodecs.dll
```

**Comment by joachimmetz** [comment]
Current assumption cause of the exception, for some reason the "not responding" path produces 0 "produced sources" where this should be none.

**Comment by joachimmetz** [comment]
Looks like Worker is "restarted" and log flushed

```
2022-02-12 15:32:49,253 [ERROR] (Worker_05 ) PID:658146 <extraction_process> S: {'display_name': 'ZIP:/lib/net45/ucrtbase.dll', 'identifier': 'Worker_05', 'last_activity_timestamp': 1644679068.8214629, 'number_of_consumed_event_tags': None, 'number_of_consumed_events': 0, 'number_of_consumed_sources': 8, 'number_of_produced_event_tags': None, 'number_of_produced_events': 21, 'number_of_produced_sources': 61, 'processing_status': 'extracting', 'task_identifier': '003bb54f6bfa4b71a936ae108e04a957', 'used_memory': '196956160'}
tail: Worker_05_ziptest.log: file truncated
2022-02-12 15:32:54,316 [DEBUG] (Worker_05 ) PID:745152 <base_process> Process: Worker_05 (PID: 745152) started
2022-02-12 15:32:54,331 [DEBUG] (Worker_05 ) PID:745152 <base_process> Process: Worker_05 process status RPC server started
2022-02-12 15:32:54,331 [DEBUG] (Worker_05 ) PID:745152 <base_process> Process: Worker_05 (PID: 745152) enter main
2022-02-12 15:32:54,949 [ERROR] (Worker_05 ) PID:745152 <extraction_process> S: {'display_name': '', 'identifier': 'Worker_05', 'last_activity_timestamp': 0.0, 'number_of_consumed_event_tags': None, 'number_of_consumed_events': 0, 'number_of_consumed_sources': 0, 'number_of_produced_event_tags': None, 'number_of_produced_events': 0, 'number_of_produced_sources': 0, 'processing_status': 'initialized', 'task_identifier': '', 'used_memory': '125898752'}
```

**Comment by joachimmetz** [comment]
Looks like the dfVFS ZipFile work-around for ZipExtFile not being seekable can be solved differently.
