### ISSUE TITLE
Volumeshadow parsing is not diabled even if --no-vss is used

### ISSUE THREAD

**Issue by tkessels** [log2timeline/plaso#4059]
**Description of problem:**

Parsing of Image fails due to Problem with libvshadow even if the command line option --no-vss is used. I would expect libvshadow to be skip-able entirely when working with an potential damaged Filesystem.
Processing of the image content works fine if manually mounted filesystem is provided to log2timeline in "directory" mode.

**Command line and arguments:**
--no-vss

**Source data:**

Image of a Windows Server 2008

**Plaso version:**

20211229

**Operating system Plaso is running on:**

Using  the official docker container with ubuntu 20.04

**Installation method:**
docker pull log2timeline/plaso

**Debug output/tracebacks:**

2022-02-22 11:17:34,032 [INFO] (MainProcess) PID:9 <data_location> Determined data location: /usr/share/plaso
2022-02-22 11:17:34,054 [INFO] (MainProcess) PID:9 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 165, in OpenFileSystem
    file_system.Open()
  File "/usr/lib/python3/dist-packages/dfvfs/vfs/file_system.py", line 257, in Open
    self._Open(mode=mode)
  File "/usr/lib/python3/dist-packages/dfvfs/vfs/vshadow_file_system.py", line 63, in _Open
    vshadow_volume.open_file_object(file_object)
OSError: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_data: invalid volume system signature. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header. libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 99, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 73, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 690, in ExtractEventsFromSources
    self.ScanSource(self._source_path)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 642, in ScanSource
    base_path_specs = volume_scanner_object.GetBasePathSpecs(
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 680, in GetBasePathSpecs
    return self._GetBasePathSpecs(scan_context, options)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 224, in _GetBasePathSpecs
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 600, in _ScanVolume
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 575, in _ScanVolume
    self._ScanVolumeSystemRoot(
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 309, in _ScanVolumeSystemRoot
    volume_system.Open(scan_node.path_spec)
  File "/usr/lib/python3/dist-packages/dfvfs/volume/volume_system.py", line 290, in Open
    self._file_system = resolver.Resolver.OpenFileSystem(path_spec)
  File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 167, in OpenFileSystem
    raise errors.BackEndError(
dfvfs.lib.errors.BackEndError: Unable to open file system with error: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_data: invalid volume system signature. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header. libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.

**Comment by joachimmetz** [comment]
```
OSError: pyvshadow_volume_open_file_object: unable to open volume.
libvshadow_ntfs_volume_header_read_data: invalid volume system signature.
libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header.
libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header.
libvshadow_volume_open_read: unable to read NTFS volume headers.
libvshadow_volume_open_file_io_handle: unable to read from file IO handle.
```

**Comment by joachimmetz** [comment]
@tkessels can you provide more information about your source image. Possibly you're running into the following issue https://github.com/libyal/libbfoverlay/wiki/Examples#correcting-truncated-windows-live-volume-images

**Comment by joachimmetz** [comment]
> I would expect libvshadow to be skip-able entirely when working with an potential damaged Filesystem.

This is debatable, it is very easy to state, but hard to do in a way that correctly and transparently deals with the corruption.

**Comment by joachimmetz** [comment]
Duplicate of: https://github.com/log2timeline/plaso/issues/3592

**Comment by tkessels** [comment]
Thank you for your quick response.

> @tkessels can you provide more information about your source image. Possibly you're running into the following issue https://github.com/libyal/libbfoverlay/wiki/Examples#correcting-truncated-windows-live-volume-images

You are right, the image was created from a live system with FTK-Imager 4.7.1 and therefore it is likely that the same corruption as in #3592 is present.

I agree with you that a corrupted Image should fail loudly even though in this case the EWF-Format would provide proof that the image itself wasn't damaged in transit but rather the filesystem is "damaged".
I was hoping (while totally oblivious to the inner workings of log2timeline) that there was an easy fix for the issue by simply skipping failing parser thus enabling us to process corrupted filesystems. 

I'll try to fix the image as suggested in https://github.com/libyal/libbfoverlay/wiki/Examples#correcting-truncated-windows-live-volume-images as soon as possible.
Thanks again for this awesome tool. I
