### ISSUE TITLE
json serializer raises TypeError in _ConvertEventTagToDict

### ISSUE THREAD

**Issue by vdsilva** [log2timeline/plaso#407]
This stack trace was generated while running psort on the Plaso file below that is part of the Greendale test data. The storage file was generated by an older version of Plaso and the error below occurs using the version of psort from head.

```
vdsilva@vdsilva:plaso-data$ ../plaso/tools/psort.py -o json_line ./dean-mac.plaso -w /tmp/dean-mac.json
[INFO] Data files will be loaded from /vdsilva/plaso/data by default.
Traceback (most recent call last):
  File "../plaso/tools/psort.py", line 684, in <module>
    if not Main():
  File "../plaso/tools/psort.py", line 679, in Main
    tool.ProcessStorage()
  File "../plaso/tools/psort.py", line 631, in ProcessStorage
    self._ProcessStorage()
  File "../plaso/tools/psort.py", line 258, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/vdsilva/plaso/plaso/frontend/psort.py", line 548, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/vdsilva/plaso/plaso/output/interface.py", line 241, in __exit__
    self.End()
  File "/vdsilva/plaso/plaso/output/interface.py", line 233, in End 
    self.Flush()
  File "/vdsilva/plaso/plaso/output/interface.py", line 198, in Flush
    self._output_module.WriteEvent(event_object)
  File "/vdsilva/plaso/plaso/output/interface.py", line 55, in WriteEvent
    self.WriteEventBody(event_object)
  File "/vdsilva/plaso/plaso/output/json_line.py", line 35, in WriteEventBody
    event_object))
  File "/vdsilva/plaso/plaso/serializer/json_serializer.py", line 812, in WriteSerialized
    return json.dumps(event_object, cls=_EventObjectJSONEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/vdsilva/plaso/plaso/serializer/json_serializer.py", line 596, in default
    attribute_value = self._ConvertEventTagToDict(attribute_value)
  File "/vdsilva/plaso/plaso/serializer/json_serializer.py", line 491, in _ConvertEventTagToDict
    raise TypeError
TypeError


[ERROR] 
> /vdsilva/plaso/plaso/serializer/json_serializer.py(491)_ConvertEventTagToDict()
> -> raise TypeError
> (Pdb) event_tag
> '{"comment": "Tag applied by tagging analysis plugin.", "event_uuid": "b33c3600aa75407fae09f0c31a9cf3a7", "tags": ["File Downloaded"]}'
> (Pdb) event_tag.__class__
> <type 'str'>
> (Pdb) 
> 
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/master/plaso/serializer/json_serializer.py#L491

```
    if not isinstance(event_tag, event.EventTag):
      raise TypeError
```

https://github.com/log2timeline/plaso/blob/master/plaso/serializer/json_serializer.py#L595

```
      elif attribute_name == u'tag':
        attribute_value = self._ConvertEventTagToDict(attribute_value)
```

```
> (Pdb) event_tag.__class__
> <type 'str'>
```

We need to figure out why event_object.tag is set to something other than an EventTag object.

**Comment by joachimmetz** [comment]
I've not been able to reproduce this with HEAD on the dean-mac image.

**Comment by Onager** [comment]
This is an incompatibility with storage files generated with Plaso 1.3, not going to fix.
