### ISSUE TITLE
MacOS: ImportError: cannot import name 'fvde_analyzer_helper' from 'dfvfs.analyzer'

### ISSUE THREAD

**Issue by studiawan** [log2timeline/plaso#4094]
**Description of problem:**

Getting error `ImportError: cannot import name 'fvde_ analyzer_helper' from 'dfvfs.analyzer'` after installing on a fresh Anaconda virtual environment. I just type the command `log2timeline.py` and the error message appeared.

**Command line and arguments:**

$ log2timeline.py
Traceback (most recent call last):
  File "/Users/hudan/opt/anaconda3/envs/plaso/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20211229', 'log2timeline.py')
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1459, in run_script
    exec(code, namespace, namespace)
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/plaso-20211229-py3.8.egg/EGG-INFO/scripts/log2timeline.py", line 11, in <module>
    from plaso.cli import log2timeline_tool
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/plaso-20211229-py3.8.egg/plaso/cli/log2timeline_tool.py", line 15, in <module>
    from plaso.cli import extraction_tool
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/plaso-20211229-py3.8.egg/plaso/cli/extraction_tool.py", line 22, in <module>
    from plaso.cli import storage_media_tool
  File "/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/plaso-20211229-py3.8.egg/plaso/cli/storage_media_tool.py", line 8, in <module>
    from dfvfs.analyzer import fvde_analyzer_helper
ImportError: cannot import name 'fvde_analyzer_helper' from 'dfvfs.analyzer' (/Users/hudan/opt/anaconda3/envs/plaso/lib/python3.8/site-packages/dfvfs/analyzer/__init__.py)

**Source data:**

No data used yet.

**Plaso version:**

plaso-20211229

**Operating system Plaso is running on:**

- macOS Monterey Version 12.1 (Apple M1)
- Python 3.8
- Anaconda virtual environment

**Installation method:**

For example:
* installed from https://github.com/log2timeline/plaso/releases/tag/20211229
* installation steps: https://plaso.readthedocs.io/en/latest/sources/user/MacOS-Source-Release.html

**Debug output/tracebacks:**

the same output as section **Command line and arguments:**

**Comment by joachimmetz** [comment]
This is because you are installing a newer dfVFS version, revert to an older version of dfVFS compatible with the Plaso version (https://github.com/log2timeline/dfvfs/releases/tag/20211228).

Strongly encourage to use the provided Docker images instead.

**Comment by studiawan** [comment]
Hi @joachimmetz, I can confirm that I have successfully installed plaso using dfvfs version 20211228. Thank you.
