### ISSUE TITLE
Windows: datetime module throws an unexpected OSError exception

### ISSUE THREAD

**Issue by sin4ts** [log2timeline/plaso#4095]
**Description of problem:**
When exporting results, Plaso crash with the following  error:
```
Traceback (most recent call last):
  File "\\VBoxSvr\share\dev\plaso\psteal.py", line 103, in <module>
  File "\\VBoxSvr\share\dev\plaso\psteal.py", line 80, in Main
  File "plaso\cli\psteal_tool.py", line 355, in ProcessStorage
  File "plaso\multi_process\output_engine.py", line 491, in ExportEvents
  File "plaso\multi_process\output_engine.py", line 359, in _ExportEvents
  File "plaso\multi_process\output_engine.py", line 253, in _ExportEvent
  File "plaso\multi_process\output_engine.py", line 402, in _FlushExportBuffer
  File "plaso\output\interface.py", line 84, in WriteEvent
  File "plaso\output\interface.py", line 197, in WriteEventBody
  File "plaso\output\shared_dsv.py", line 56, in GetFormattedEvent
  File "plaso\output\formatting_helper.py", line 623, in GetFormattedField
  File "plaso\output\formatting_helper.py", line 154, in _FormatDateTime
OSError: [Errno 22] Invalid argument
[16392] Failed to execute script 'psteal' due to unhandled exception!
```
After digging into this error, it looks like the issue come from this instruction ("plaso\output\formatting_helper.py", line 154, in _FormatDateTime) : 
```
        datetime_object = datetime_object.astimezone(
            self._output_mediator.timezone) 
```
Further debugging indicate the datetime_object which caused plaso to crashed is "1601-01-01 01:01:01" and the timezone UTC.
I managed to reproduced the bug outside of Plaso : 
```
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime_object = datetime.datetime.strptime('1601-01-01 01:01:01', '%Y-%m-%d %H:%M:%S')
>>> timezone_object = datetime.timezone(datetime.timedelta())
>>> datetime_object.astimezone(timezone_object)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```
Please note the bug only occurs on Windows. Could not reproduce it on Linux. It actually looks like any date before 1970-01-01 would cause this bug to happen.

I managed to get Plaso working by catching OSError in the same function, line 162: 
```
-      except (OverflowError, TypeError, ValueError) as exception:
+      except (OverflowError, TypeError, ValueError, OSError) as exception:

```

**Command line and arguments:**

psteal.py --source IMAGE_PATH -o dynamic -w output.csv

**Source data:**
Source image was a Windows E01 image

**Plaso version:**

Latest version fetched via "git clone" and manually installed on Windows

**Operating system Plaso is running on:**

Windows 10

**Installation method:**
Manual installation

**Debug output/tracebacks:**
```
Traceback (most recent call last):
  File "\\VBoxSvr\share\dev\plaso\psteal.py", line 103, in <module>
  File "\\VBoxSvr\share\dev\plaso\psteal.py", line 80, in Main
  File "plaso\cli\psteal_tool.py", line 355, in ProcessStorage
  File "plaso\multi_process\output_engine.py", line 491, in ExportEvents
  File "plaso\multi_process\output_engine.py", line 359, in _ExportEvents
  File "plaso\multi_process\output_engine.py", line 253, in _ExportEvent
  File "plaso\multi_process\output_engine.py", line 402, in _FlushExportBuffer
  File "plaso\output\interface.py", line 84, in WriteEvent
  File "plaso\output\interface.py", line 197, in WriteEventBody
  File "plaso\output\shared_dsv.py", line 56, in GetFormattedEvent
  File "plaso\output\formatting_helper.py", line 623, in GetFormattedField
  File "plaso\output\formatting_helper.py", line 154, in _FormatDateTime
OSError: [Errno 22] Invalid argument
[16392] Failed to execute script 'psteal' due to unhandled exception!
```

**Comment by joachimmetz** [comment]
thx for the report, I'll add OSError to the catch list.

For context there is nothing in the Python documentation about OSError https://docs.python.org/3/library/datetime.html

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/4096 should address the issue

**Comment by sin4ts** [comment]
> thx for the report, I'll add OSError to the catch list.
> 
> For context there is nothing in the Python documentation about OSError https://docs.python.org/3/library/datetime.html

Yes it looks like it's a bug from the datetime library... Thanks for fixing it quickly !
