### ISSUE TITLE
Issue running Plaso on WIndows 10

### ISSUE THREAD

**Issue by cipherz404** [log2timeline/plaso#4107]
**Description of problem:**

I am trying to run log2timeline in WIndows but I am getting an error. 

log2timeline.py --help

Please provide the command with arguments you ran when you experienced
the problem.

log2timeline.py --help

**Plaso version:**

plaso-20220428 Latest

**Operating system Plaso is running on:**

Windows 10

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

Downloaded from Github https://github.com/log2timeline/plaso

Please run the tool with "-d" to generate debug output, and include anything relevant.
Traceback (most recent call last):
  File "C:\cyber\dfir\tools\plaso-main\tools\log2timeline.py", line 11, in <module>
    from plaso.cli import log2timeline_tool
  File "C:\Users\lapen\AppData\Local\Programs\Python\Python39\lib\site-packages\plaso-20220501-py3.9.egg\plaso\cli\log2timeline_tool.py", line 12, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "C:\Users\lapen\AppData\Local\Programs\Python\Python39\lib\site-packages\plaso-20220501-py3.9.egg\plaso\output\__init__.py", line 4, in <module>
    from plaso.output import dynamic
  File "C:\Users\lapen\AppData\Local\Programs\Python\Python39\lib\site-packages\plaso-20220501-py3.9.egg\plaso\output\dynamic.py", line 5, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

**Comment by joachimmetz** [comment]
@cipherz404 please read the documentation https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#how-to-get-started and use a preferred installation method if you're not familiar with debugging Python installation issues. You are missing a dependency.
