### ISSUE TITLE
psort: TypeError raised on storage file without events

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4119]
Storage file created with `log2timeline.py --parsers "mactime" --storage_file plaso.db image.E01`

Presumably no bodyfile in the image

```
2022-05-29 23:21:34,095 [INFO] (MainProcess) PID:210944 <data_location> Determined data location: /usr/local/lib/python3.8/dist-packages/plaso-20220428-py3.8.egg/share/plaso
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20220428', 'psort.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/plaso-20220428-py3.8.egg/EGG-INFO/scripts/psort.py", line 101, in <module>
    if not Main():
  File "/usr/local/lib/python3.8/dist-packages/plaso-20220428-py3.8.egg/EGG-INFO/scripts/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python3.8/dist-packages/plaso-20220428-py3.8.egg/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/local/lib/python3.8/dist-packages/plaso-20220428-py3.8.egg/plaso/multi_process/output_engine.py", line 480, in ExportEvents
    total_number_of_events += stored_session.parsers_counter['total'] or 0
TypeError: 'NoneType' object is not subscriptable
```

**Comment by joachimmetz** [comment]
Was able to reproduce this on an empty storage file.
