### ISSUE TITLE
ConfluenceAccessParser raises AttributeError with pyparsing 2.4.7

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4137]
```
Traceback (most recent call last):
  File "/home/test/plaso/./tools/log2timeline.py", line 11, in <module>
    from plaso.cli import log2timeline_tool
  File "/home/test/plaso/plaso/cli/log2timeline_tool.py", line 15, in <module>
    from plaso.cli import extraction_tool
  File "/home/test/plaso/plaso/cli/extraction_tool.py", line 18, in <module>
    from plaso import parsers  # pylint: disable=unused-import
  File "/home/test/plaso/plaso/parsers/__init__.py", line 15, in <module>
    from plaso.parsers import confluence_access
  File "/home/test/plaso/plaso/parsers/confluence_access.py", line 57, in <module>
    class ConfluenceAccessParser(text_parser.PyparsingSingleLineTextParser):
  File "/home/test/plaso/plaso/parsers/confluence_access.py", line 100, in ConfluenceAccessParser
    _USER_AGENT = pyparsing.rest_of_line.setResultsName('user_agent')
AttributeError: module 'pyparsing' has no attribute 'rest_of_line'. Did you mean: 'restOfLine'?
```

**Comment by joachimmetz** [comment]
Same for `one_of` instead of `oneOf`
