### ISSUE TITLE
Registry parser raises format handling related exception while processing test file

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#416]
I'm not sure where the best place for a fix is - libregf, dfwinreg or plaso:
```
2015-11-27 16:57:21,504 [WARNING] (Worker_01 ) PID:10600 <worker> Unhandled exception while processing path spec: type: OS, location: /home/onager/code/plaso/test_data/SOFTWARE-RunTests
2015-11-27 16:57:21,504 [ERROR] (Worker_01 ) PID:10600 <worker> Unable to read data from value: lParam with error: pyregf_value_get_data_as_integer: unable to retrieve integer value. libregf_value_type_copy_to_32bit: invalid value data size value out of bounds. libregf_value_get_value_32bit: unable to set 32-bit value.
Traceback (most recent call last):
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 570, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry, data_stream_name=data_stream_name)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 523, in _ProcessFileEntry
    self._ProcessDataStream(file_entry, data_stream_name=data_stream_name)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 464, in _ProcessDataStream
    parser_object, file_entry, file_object=file_object)
  File "/home/onager/code/plaso/plaso/engine/worker.py", line 261, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_mediator, file_object)
  File "/home/onager/code/plaso/plaso/parsers/interface.py", line 288, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/home/onager/code/plaso/plaso/parsers/winreg.py", line 119, in ParseFileObject
    parser_mediator, registry_key)
  File "/home/onager/code/plaso/plaso/parsers/winreg_plugins/interface.py", line 280, in UpdateChainAndProcess
    self.Process(parser_mediator, registry_key, **kwargs)
  File "/home/onager/code/plaso/plaso/parsers/winreg_plugins/interface.py", line 265, in Process
    self.GetEntries(parser_mediator, registry_key, **kwargs)
  File "/home/onager/code/plaso/plaso/parsers/winreg_plugins/default.py", line 50, in GetEntries
    registry_value.data_type_string, registry_value.GetData())
  File "/home/onager/code/plaso/plaso/dfwinreg/regf.py", line 175, in GetData
    self._pyregf_value.name, exception))
WinRegistryValueError: Unable to read data from value: lParam with error: pyregf_value_get_data_as_integer: unable to retrieve integer value. libregf_value_type_copy_to_32bit: invalid value data size value out of bounds. libregf_value_get_value_32bit: unable to set 32-bit value.
```

Actions:

* [x] analyze the root cause of the issue, maybe it is an unknown part of the format
* [x] Have the winreg parser catch WinRegistryValueError and continue processing the Registry file

**Comment by joachimmetz** [comment]
This is likely working as intended and the WinRegistryValueError is raised because the input data is not what it is that is expected:

* [ ] analyze the root cause of the issue, maybe it is an unknown part of the format
* [ ] Have the winreg parser catch WinRegistryValueError and continue processing the Registry file

**Comment by joachimmetz** [comment]
hexdump -Cv "fuse/Software/Microsoft/Windows/CurrentVersion/Group Policy/History/{35378EAC-683F-11D2-A89A-00C04FBBCFA2}/0/(values)/lParam"
```
00000000  00 00 00 00 00 00 00 00                           |........|
00000008
```
