### ISSUE TITLE
look into failing test on Fedora 36

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4249]
determine why this test is failing on Fedora 36

```
======================================================================
ERROR: testParse (parsers.viminfo.ViminfoParserTest)
Tests the Parse function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/parsers/viminfo.py", line 21, in testParse
    storage_writer = self._ParseFile(['.viminfo'], parser)
  File "tests/parsers/test_lib.py", line 134, in _ParseFile
    return self._ParseFileByPathSpec(
  File "tests/parsers/test_lib.py", line 166, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "plaso/parsers/interface.py", line 288, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "plaso/parsers/text_parser.py", line 587, in ParseFileObject
    raise errors.WrongParser(
plaso.lib.errors.WrongParser: more than 20 consecutive failures to parse lines.

----------------------------------------------------------------------
```

@sydp FYI

**Comment by joachimmetz** [comment]
Looks like this might be happening here:

```
1	CHAR	0
	test multiline register1
	test multiline register2

|3,0,1,0,34,0,1234567895,"test multiline register1","test multiline register2"
...
```

**Comment by sydp** [comment]
Ack, will see if I can replicate locally and fix.

**Comment by joachimmetz** [comment]
So the first failure seems to be on line `# hlsearch on (H) or off (h):` if I remove https://github.com/log2timeline/plaso/blob/main/plaso/parsers/viminfo.py#L83 the parser continues to `# Last Substitute Search Pattern:`

**Comment by joachimmetz** [comment]
Removed the line start statement and added a couple of more line end statements and got the parser working on F36. Also cleaned up the text parser a bit.
