### ISSUE TITLE
chrome_preferences: raises MemoryError on large files

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#4279]
**Description of problem:**

Trying to parse a 3Tb jsonl log file works correctly when l2t is started with:

```
log2timeline.py --single_process -d --parsers jsonl,jsonl/docker_container_log --hashers none /mnt/sdb1/var/lib/docker/containers/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07-json.log
```
But is not being processed at all by docker_container_log plugin if all parsers are enabled (removing `--parsers jsonl,jsonl/docker_container_log`)

Debugging shows that a MemoryError is raised when previous parsers try to call read() on the opened file:

```
2022-09-28 14:30:53,163 [DEBUG] (MainProcess) PID:48742 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/mnt/sdb1/var/lib/docker/containers/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07-json.log with parser: chrome_preferences
2022-09-28 14:30:53,548 [WARNING] (MainProcess) PID:48742 <extraction_engine> Unhandled exception while processing path spec: OS:/mnt/sdb1/var/lib/docker/containers/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07/ee8ffeddfd0e17c4ba0f312c81c57ffd919e5e7f56ff5dd5e51f705e8764ba07-json.log.
2022-09-28 14:30:53,548 [ERROR] (MainProcess) PID:48742 <extraction_engine> 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/single_process/extraction_engine.py", line 95, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(
  File "/usr/lib/python3/dist-packages/plaso/engine/worker.py", line 876, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/usr/lib/python3/dist-packages/plaso/engine/worker.py", line 679, in _ProcessFileEntry
    self._ProcessFileEntryDataStream(mediator, file_entry, data_stream)
  File "/usr/lib/python3/dist-packages/plaso/engine/worker.py", line 771, in _ProcessFileEntryDataStream
    self._ExtractContentFromDataStream(
  File "/usr/lib/python3/dist-packages/plaso/engine/worker.py", line 364, in _ExtractContentFromDataStream
    self._event_extractor.ParseDataStream(
  File "/usr/lib/python3/dist-packages/plaso/engine/extractors.py", line 293, in ParseDataStream
    self._ParseFileEntryWithParsers(
  File "/usr/lib/python3/dist-packages/plaso/engine/extractors.py", line 255, in _ParseFileEntryWithParsers
    parse_result = self._ParseFileEntryWithParser(
  File "/usr/lib/python3/dist-packages/plaso/engine/extractors.py", line 193, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "/usr/lib/python3/dist-packages/plaso/parsers/interface.py", line 288, in Parse
    self.ParseFileObject(parser_mediator, file_object)
  File "/usr/lib/python3/dist-packages/plaso/parsers/chrome_preferences.py", line 208, in ParseFileObject
    file_content = file_object.read()
  File "/usr/lib/python3/dist-packages/dfvfs/file_io/os_file_io.py", line 143, in read
    return self._file_object.read(size)
MemoryError
```

Disabling the chrome_preferences parser (by commenting the relevant line in `/usr/lib/python3/dist-packages/plaso/parsers/__init__.py`, because of https://github.com/log2timeline/plaso/issues/4278) makes the file being parsed again.

I think parsers shouldn't call read() on the opened file_object, but also plaso should maybe catch the MemoryError and move forward to trying another parser.

**Source data:**

This can be reproduced with 
```
yes '{"log":"I","stream":"s","time":"2021-02-02T22:16:21.930612511Z"}'|pv > /tmp/a
```
Letting this fill a more than 10G file

and then running `log2timeline.py --single_process -d  --hashers none /tmp/a`

**Plaso version:**

```
# log2timeline.py -V
plaso - log2timeline version 20220724
```

**Operating system Plaso is running on:**

Ubuntu 20.04 x86_64

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

* installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Comment by joachimmetz** [comment]
```
grep -r 'file_object.read()' *
...
plaso/parsers/firefox_cache.py:    header_data = file_object.read()
plaso/parsers/chrome_preferences.py:    file_content = file_object.read()
plaso/parsers/plist.py:    plist_data = file_object.read()
...
```

**Comment by joachimmetz** [comment]
plist.py has a maximum file size check
