### ISSUE TITLE
Gzip uncompress failed

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#433]
Hi guys,

I have an issue with log2timeline 1.3.1 when i a generate a timeline as follow :

```
worker_14 (PID: 19170) - events extracted: 18968 - file: GZIP:/Users/nangadef/AppData/Local/Mozilla/Firefox/Profiles/bxr.default/cache2/entries/36BD4932652E5947AF173A95C80094A06A79CF39 - running: True <running>
2015-12-09 14:33:19,304 [WARNING] (Worker_11 ) PID:19164 <worker> Unhandled exception while processing path spec: type: OS, location: /srv/niamaniama/2015-12-08_11-07-16/image.001
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x20100000
type: BDE
type: VSHADOW, location: /vss4, store index: 3
type: TSK, inode: 224342, location: /Users/nangadef/AppData/Local/Mozilla/Firefox/Profiles/bxr.default/cache2/entries/7DFDE765B249F91EDFC2037C176FF104772423DD
type: GZIP
.
2015-12-09 14:33:19,304 [ERROR] (Worker_11 ) PID:19164 <worker> Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid block type.
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 562, in _ProcessPathSpec
self._ProcessFileEntry(file_entry, data_stream_name=data_stream_name)
File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 497, in _ProcessFileEntry
self._HashDataStream(file_entry, data_stream_name=data_stream_name)
File "/usr/local/lib/python2.7/dist-packages/plaso/engine/worker.py", line 198, in _HashDataStream
buffer_size=self._DEFAULT_HASH_READ_SIZE)
File "/usr/local/lib/python2.7/dist-packages/plaso/hashers/manager.py", line 161, in HashFileObject
data = file_object.read(buffer_size)
File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 103, in read
return self._file_object.read(size=size)
File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 216, in read
self._AlignUncompressedDataOffset(self._current_offset)
File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 145, in _AlignUncompressedDataOffset
read_count = self._ReadCompressedData(self._COMPRESSED_DATA_BUFFER_SIZE)
File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 173, in _ReadCompressedData
self._decompressor.Decompress(self._compressed_data))
File "/usr/lib/python2.7/dist-packages/dfvfs/compression/zlib_decompressor.py", line 50, in Decompress
u'{0:s}.').format(exception))
BackEndError: Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid block type.
```

Thanks

**Comment by joachimmetz** [comment]
```
/Users/nangadef/AppData/Local/Mozilla/Firefox/Profiles/bxr.default/cache2/entries/7DFDE765B249F91EDFC2037C176FF104772423DD
```

Is this a full gzip file or gzip data inside a larger cache file. In case of the latter this is expected and this is an error to be expected. We'll look if we can make the error handling a bit more graceful but ideally we get the compressed file check to ignore known gzip cache files.

**Comment by joachimmetz** [comment]
This is working as intended, but I've created https://github.com/log2timeline/plaso/issues/467 to stop trying to process these files.
