### ISSUE TITLE
Zero MQ likely causing unstable interpreter state

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#441]
On Mac OS X with pyzmq 15.1.0 
```
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
```

On Linux with unknown version pyzmq (likely related)
```
File "/usr/lib64/python2.7/traceback.py", line 241, in format_exc
  etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

Zero MQ still experimental thus not a release show stopper

**Comment by Onager** [comment]
This might have been because we were closing some of the queues properly (for the first exception, anyway). Please retry after https://codereview.appspot.com/281870043/

**Comment by joachimmetz** [comment]
Note to self: test with changes on PR

**Comment by joachimmetz** [comment]
@Onager the CL fixes the issue on OSX for me

**Comment by gregfreemyer** [comment]
Assuming this is related:

openSUSE Leap 42.1
plaso 1.4 rc1 (pulled from git on Dec 20)
self-built via specfile
python-pyzmq-14.7.0-3.1.x86_64
libzmq5-4.1.3-18.1.x86_64

When running "./run_tests.py" one of the 2 Unhandled Exceptions I was seeing on openSUSE is gone.  One remains:

> ./run_tests.py
<snip>
OK
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-9, stopped daemon 140568290121472)>>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib64/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'

removing "tests/engine/zeromq_queue.py*" causes the Unhandled Exception to go away.

**Comment by joachimmetz** [comment]
https://travis-ci.org/log2timeline/plaso/builds/99617968

```
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "./plaso/engine/zeromq_queue.py", line 751, in _ZeroMQResponder
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "./plaso/engine/zeromq_queue.py", line 751, in _ZeroMQResponder
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

**Comment by joachimmetz** [comment]
```
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-5, stopped daemon 139974498572032)>>
```

**Comment by Onager** [comment]
This looks to be because we're setting the zeromq responder threads to be daemons, so python shuts down with them still running. One solution is to mark them as non-daemon.

**Comment by joachimmetz** [comment]
Closing issue because of significant changes in multi processing: https://github.com/log2timeline/plaso/issues/338
