### ISSUE TITLE
Bitlocker selection: Must be char not unicode error.

### ISSUE THREAD

**Issue by vnoxygen** [log2timeline/plaso#446]
Currently using plaso-1.3.0-win-amd64-vs2010.zip. However when selecting input, the tool rejected the selection with the following "TypeError: must be char, not unicode" error.

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
p1
Found a BitLocker encrypted volume.
Supported credentials:

  0. startup_key
  1. recovery_password
  2. password
  3. skip

Note that you can abort with Ctrl^C.

Select a credential to unlock the volume: 1
Traceback (most recent call last):
  File "<string>", line 676, in <module>
  File "<string>", line 662, in Main
  File "<string>", line 558, in ProcessSources
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.cli.storage_med
ia_tool", line 974, in ScanSource
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.cli.storage_med
ia_tool", line 659, in _ScanVolume
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.cli.storage_med
ia_tool", line 691, in _ScanVolumeScanNode
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.cli.storage_med
ia_tool", line 731, in _ScanVolumeScanNodeEncrypted
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.cli.storage_med
ia_tool", line 453, in _PromptUserForEncryptedVolumeCredential
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\getpass", line 95, in
 win_getpass
TypeError: must be char, not unicode

**Comment by joachimmetz** [comment]
This is an issue specific to Python 2 on Windows, pending fix: http://codereview.appspot.com/279640043
