### ISSUE TITLE
psort fail to export dfdatetime.DateTimeValues to json and OpenSearch 

### ISSUE THREAD

**Issue by william-billaud** [log2timeline/plaso#4526]
**Description of problem:**

Psort fail to export in json values of type `dfdatetime.DateTimeValues` when the value is an attribute of an event (eg. previous_run_times in [winprefetch](https://github.com/log2timeline/plaso/blob/53f532a3e066dc0269aa7e748737b4c50944abc4/plaso/parsers/winprefetch.py#L27)

For opensearch no crashes occur but the bulk export fails if the bulk contains an event that could not be serialized.

**Command line and arguments:**

```
log2timeline.py --partition all --hashers sha1  ~/Downloads/HP-Final/Laptop1Final.E01
# jsonl
./psort.py -o json_line -w fail.jsonl 20221228T162736-Laptop1Final.E01.plaso  "parser is 'prefetch' and timestamp_desc is not 'Creation Time'" 
# opensearch
./psort.py -o opensearch --opensearch-user admin --opensearch-server "localhost" --use_ssl --opensearch-port 9200 20221228T162736-Laptop1Final.E01.plaso "parser is 'prefetch'"
```

**Source data:**

https://cfreds.nist.gov/all/MagnetForensics/2022WindowsMagnetCTF (but any windows image with prefetch should cause the crash).

**Plaso version:**

20221227

**Operating system Plaso is running on:**

Tested on MacOS and Ubuntu 20.04

**Installation method:**

* manually (pip from source)

**Debug output/tracebacks:**

Stack trace : 

```
Traceback (most recent call last):
  File "<REDACTED>/./psort.py", line 101, in <module>
    if not Main():
  File "<REDACTED>/./psort.py", line 74, in Main
    tool.ProcessStorage()
  File "<REDACTED>/plaso/cli/psort_tool.py", line 536, in ProcessStorage
    output_engine.ExportEvents(
  File "<REDACTED>/plaso/multi_process/output_engine.py", line 596, in ExportEvents
    self._ExportEvents(
  File "<REDACTED>/plaso/multi_process/output_engine.py", line 416, in _ExportEvents
    self._ExportEvent(
  File "<REDACTED>/plaso/multi_process/output_engine.py", line 311, in _ExportEvent
    self._FlushExportBuffer(
  File "<REDACTED>/plaso/multi_process/output_engine.py", line 458, in _FlushExportBuffer
    output_module.WriteEvent(
  File "<REDACTED>/plaso/output/interface.py", line 75, in WriteEvent
    self.WriteEventBody(
  File "<REDACTED>/plaso/output/json_line.py", line 36, in WriteEventBody
    output_text = self._event_formatting_helper.GetFormattedEvent(
  File "<REDACTED>/plaso/output/shared_json.py", line 143, in GetFormattedEvent
    return json.dumps(json_dict, sort_keys=True)
  File "<REDACTED>/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "<REDACTED>/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "<REDACTED>/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "<REDACTED>/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Filetime is not JSON serializable
```

For opensearch :  

```
2022-12-28 20:33:29,776 [WARNING] (MainProcess) PID:23514 <shared_opensearch> Unable to bulk insert with error: ({'data_type': 'windows:prefetch:execution', 'parser': 'prefetch', 'executable': 'SVCHOST.EXE', 'mapped_files': <REDACTED>], 'prefetch_hash': 1206935246, 'previous_run_times': [<dfdatetime.filetime.Filetime object at 0x112a4cbe0>, <dfdatetime.filetime.Filetime object at 0x112a4c460>, <dfdatetime.filetime.Filetime object at 0x112a4ccd0>],
 'run_count': 4, 'version': 30, 'volume_device_paths': ['\\VOLUME{01d8067502ac9764-1002c20a}'], 'volume_serial_numbers': [268616202], 'path_spec': '{"__type__": "PathSpec", "mft_attribute": 2, "location": "\\\\Windows.old\\\
\Windows\\\\Prefetch\\\\SVCHOST.EXE-47F05ECE.pf", "mft_entry": 96839, "parent": {"__type__": "PathSpec", "location": "/p3", "parent": {"__type__": "PathSpec", "parent": {"__type__": "PathSpec", "location": "<REDACTES>/Laptop1Final.E01", "type_indicator": "OS"}, "type_indicator": "EWF"}, "type_indicator": "GPT"}, "type_indicator": "NTFS"}', 'sha1_hash': '0730b065ae2015712c14f76675c073682212661f', 'datetime': '2022-01-10T2
3:03:48.076395+00:00', 'display_name': 'NTFS:\\Windows.old\\Windows\\Prefetch\\SVCHOST.EXE-47F05ECE.pf', 'message': 'Prefetch [SVCHOST.EXE] was executed - run count 4 path hints: \\WINDOWS\\SYSTEM32\\SVCHOST.EXE hash: 0x47F0
5ECE volume: 1 [serial number: 0x1002C20A, device path: \\VOLUME{01d8067502ac9764-1002c20a}]', 'source_long': 'WinPrefetch', 'source_short': 'LOG', 'tag': [], 'timestamp': 1641855828076395, 'timestamp_desc': 'Previous Last T
ime Executed'}, TypeError("Unable to serialize <dfdatetime.filetime.Filetime object at 0x112a4cbe0> (type: <class 'dfdatetime.filetime.Filetime'>)"))
```

**Comment by joachimmetz** [comment]
@william-billaud thx for the report, annoying that the tests did not catch this, I'll have a look
