### ISSUE TITLE
AttributeError in psort when formatting message

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#4640]
**Describe the problem:**

Crash in psort when exporting events

**To Reproduce:**

Run psort on a plaso file - I'm not immediately sure what event is causing this.

At the moment I've only seen this error with the opensearch output module.

Plaso version  20230311

**Expected behavior:**

No crash

**Debug output/tracebacks:**

```
2023-04-27 11:50:38,929 [INFO] (MainProcess) PID:157 <data_location> Determined data location: /usr/share/plaso
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 487, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 301, in _ExportEvents
    self._ExportEvent(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 196, in _ExportEvent
    self._FlushExportBuffer(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 351, in _FlushExportBuffer
    output_module.WriteFieldValuesOfMACBGroup(
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 127, in WriteFieldValuesOfMACBGroup
    self.WriteFieldValues(
  File "/usr/lib/python3/dist-packages/plaso/output/text_file.py", line 234, in WriteFieldValues
    super(SortedTextFileOutputModule, self).WriteFieldValues(
  File "/usr/lib/python3/dist-packages/plaso/output/interface.py", line 106, in WriteFieldValues
    field_values = self._GetFieldValues(
  File "/usr/lib/python3/dist-packages/plaso/output/text_file.py", line 184, in _GetFieldValues
    return self._event_formatting_helper.GetFieldValues(
  File "/usr/lib/python3/dist-packages/plaso/output/shared_dsv.py", line 64, in GetFieldValues
    field_value = self._field_formatting_helper.GetFormattedField(
  File "/usr/lib/python3/dist-packages/plaso/output/formatting_helper.py", line 564, in GetFormattedField
    output_value = callback_function(
  File "/usr/lib/python3/dist-packages/plaso/output/formatting_helper.py", line 317, in _FormatMessage
    return message_formatter.GetMessage(event_values)
  File "/usr/lib/python3/dist-packages/plaso/formatters/interface.py", line 405, in GetMessage
    return self._FormatMessage(self._format_string, event_values)
  File "/usr/lib/python3/dist-packages/plaso/formatters/interface.py", line 240, in _FormatMessage
    message_string = format_string.format(**event_values)
AttributeError: 'list' object has no attribute 'format'
```
**Additional context**

N/A

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/main/plaso/formatters/interface.py#L240

**Comment by joachimmetz** [comment]
I assume this might be the culprit https://github.com/log2timeline/plaso/commit/4656497775912bf9fb8ffb9f94915270810232fd

**Comment by Onager** [comment]
Another issue related to the same .plaso file:

```
pinfo.py /Users/onager/disk.plaso 

************************** Plaso Storage Information ***************************
            Filename : disk.plaso
      Format version : 20230107
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
bbdd6bd9-aae1-4a8b-b0c2-81a907c5df79 : 2023-04-28T11:50:16.857555+00:00
--------------------------------------------------------------------------------
2023-05-12 13:15:10,312 [WARNING] (MainProcess) PID:78955 <tools> Unable to set memory limit to 4294967296 current limit is 9223372036854775807.
Traceback (most recent call last):
  File "/Users/onager/code/plaso/tools/pinfo.py", line 85, in <module>
    if not Main():
  File "/Users/onager/code/plaso/tools/pinfo.py", line 62, in Main
    tool.PrintStorageInformation()
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1682, in PrintStorageInformation
    self._PrintStorageInformation(storage_reader)
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1135, in _PrintStorageInformation
    self._PrintSourcesOverview(storage_reader)
  File "/Users/onager/code/plaso/plaso/cli/pinfo_tool.py", line 1203, in _PrintSourcesOverview
    for source_index, source in enumerate(generator):
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 499, in _GetAttributeContainersWithFilter
    container = self._CreatetAttributeContainerFromRow(
  File "/Users/onager/code/plaso/plaso/storage/sqlite/sqlite_file.py", line 89, in _CreatetAttributeContainerFromRow
    return super(SQLiteStorageFile, self)._CreatetAttributeContainerFromRow(
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 383, in _CreatetAttributeContainerFromRow
    attribute_value = self._schema_helper.DeserializeValue(
  File "/Users/onager/.virtualenvs/plaso/lib/python3.9/site-packages/acstore/sqlite_store.py", line 125, in DeserializeValue
    value = serializer.DeserializeValue(value)
  File "/Users/onager/code/plaso/plaso/storage/serializers.py", line 65, in DeserializeValue
    json_dict['parent'] = self.DeserializeValue(json_dict['parent'])
  File "/Users/onager/code/plaso/plaso/storage/serializers.py", line 58, in DeserializeValue
    json_dict = json.loads(value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

It looks like a parent pathspec is being deserialized first. The json_dict on line 65 of serializers.py is:
`{'__type__': 'PathSpec', 'parent': {'__type__': 'PathSpec', 'location': '/media/disk/boot/symvers-3.10.0-1160.el7.x86_64.gz', 'type_indicator': 'OS'}}`

Containing a dict, not a string as apparently expected

**Comment by Onager** [comment]
After some investigation, it turned out to be the updatedb formatter from #4395 where more message strings were added, but the type didn't change from 'basic' to 'conditional'.

**Comment by joachimmetz** [comment]
looks like an edge case that no longer surfaced, closing issue, reopen if issue still persist
