### ISSUE TITLE
Unable to use dates in event filters

### ISSUE THREAD

**Issue by miketweaver** [log2timeline/plaso#4646]
**Describe the problem:**

I am unable to use dates in psort's filters.

**To Reproduce:**

The version of Plaso you used:

`plaso - psort version 20230311`

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

`Docker`

------------

I'm following the documentation here:
https://plaso.readthedocs.io/en/latest/sources/user/Using-psort.html#filters
And I'm using psort.py

```
$ alias psort.py='docker run -v $(pwd):/data log2timeline/plaso psort.py'
$ psort -V
plaso - psort version 20230311
$ psort -w /data/timeline.log -q /data/E01-timeline.plaso "date > '2020-09-18 02:00:00' AND date < '2020-09-20 03:00:00'"
```

And I'm getting an error. I'm assuming I'm doing something wrong.
```
Main                    7       exporting       63.2 MiB        0 (0)           0 (0)           0 (0)

    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 487, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 257, in _ExportEvents
    filter_match = event_filter.Match(
  File "/usr/lib/python3/dist-packages/plaso/filters/event_filter.py", line 48, in Match
    return self._event_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 90, in Matches
    match = sub_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 300, in Matches
    value = self._GetValue(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 261, in _GetValue
    attribute_value = value_types.DateTimeValueType(attribute_value)
  File "/usr/lib/python3/dist-packages/plaso/filters/value_types.py", line 39, in __init__
    raise ValueError('Unsupported date time string value: {0!s}'.format(
ValueError: Unsupported date time string value: None
```

After reading this page:
https://plaso.readthedocs.io/en/latest/sources/user/Event-filters.html#value-type-helpers
I tried using `date > '2020-09-18T02:00:00.000' AND date < '2020-09-20T03:00:00.000'` instead, since it talked about the "Date and time value helper"
```
psort -w /data/timeline.log -q /data/E01-timeline.plaso "date > DATETIME('2020-09-18T02:00:00.000') AND date < DATETIME('2020-09-20T03:00:00.000')"

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/filters/value_types.py", line 37, in __init__
    self.CopyFromDateTimeString(value)
  File "/usr/lib/python3/dist-packages/dfdatetime/posix_time.py", line 289, in CopyFromDateTimeString
    date_time_values = self._CopyDateTimeFromString(time_string)
  File "/usr/lib/python3/dist-packages/dfdatetime/interface.py", line 357, in _CopyDateTimeFromString
    raise ValueError('Invalid time string.')
ValueError: Invalid time string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 522, in ProcessStorage
    output_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 487, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_process/output_engine.py", line 257, in _ExportEvents
    filter_match = event_filter.Match(
  File "/usr/lib/python3/dist-packages/plaso/filters/event_filter.py", line 48, in Match
    return self._event_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 90, in Matches
    match = sub_filter.Matches(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 300, in Matches
    value = self._GetValue(
  File "/usr/lib/python3/dist-packages/plaso/filters/filters.py", line 261, in _GetValue
    attribute_value = value_types.DateTimeValueType(attribute_value)
  File "/usr/lib/python3/dist-packages/plaso/filters/value_types.py", line 39, in __init__
    raise ValueError('Unsupported date time string value: {0!s}'.format(
ValueError: Unsupported date time string value: None
```

**Expected behavior:**

I would expect it to allow us to use dates in filters like described in the documentation.

**Debug output/tracebacks:**

I ran with `-d` and it didn't produce any log files

**Comment by joachimmetz** [comment]
> I would expect it to allow us to use dates in filters like described in the documentation.

They do, the following event filter is working fine for me:
```
"date >= DATETIME('2013-03-10T09:00:00.000') AND date <= DATETIME('2013-03-11T09:00:00.000')"
```

Even your filters works on my iinstallation:
```
"date > '2020-09-18 02:00:00' AND date < '2020-09-20 03:00:00'"
"date > DATETIME('2020-09-18T02:00:00.000') AND date < DATETIME('2020-09-20T03:00:00.000')"
```

So let's figure out what is different about your configuration that causes the filter to fail

**Comment by joachimmetz** [comment]
Per https://github.com/log2timeline/plaso/blob/main/plaso/filters/filters.py#L261 for some reason there could be event without a timestamp in your extracted data. Could you describe to me what input data you are processing and what extraction warnings log2timeline.py yielded?

**Comment by miketweaver** [comment]
Sure. I was testing on a public image file for my testing. Here's what I did:

Aquire Image:
```
wget https://dfirmadness.com/case001/DC01-E01.zip
unzip DC01-E01.zip
```

Setup Docker:
```
docker run log2timeline/plaso log2timeline.py --version
alias log2timeline='docker run --rm -v $(pwd):/data log2timeline/plaso log2timeline.py'
alias psort='docker run --rm -v $(pwd):/data log2timeline/plaso psort.py'
```

Create Timeline:
```
cd E01-DC01/
log2timeline --storage-file /data/E01-timeline.plaso --partition all -z UTC /data/20200918_0347_CDrive.E01
```

PSORT:
```
psort -w /data/timeline.log -q /data/E01-timeline.plaso "date > DATETIME('2020-09-18T02:00:00.000') AND date < DATETIME('2020-09-20T03:00:00.000')"
```

**Comment by miketweaver** [comment]
I went ahead and ran log2timeline with the debug logging:
```
$ log2timeline --storage-file /data/E01-timeline.plaso --log-file=/data/log2timeline_problem.log.gz --debug --partition all -z UTC /data/20200918_0347_CDrive.E01
```
[log2timeline_problem.log.gz](https://github.com/log2timeline/plaso/files/11409599/log2timeline_problem.log.gz)

**Comment by joachimmetz** [comment]
Thanks that is useful info to find a root cause. I've been able to reproduce with the same source data. Looks like a 'windows:registry:network' event is generated with a timestamp of None, which the filter does not like.

**Comment by joachimmetz** [comment]
Either try rerunning log2timeline with https://github.com/log2timeline/dfdatetime/releases/tag/20230225 or psort with the changes in https://github.com/log2timeline/plaso/commit/9f612d9a6da2cc92479f714bcd96424f3772cb50.
