### ISSUE TITLE
Unable to preprocess with error: FS_Info_open_meta

### ISSUE THREAD

**Issue by CdtDelta** [log2timeline/plaso#466]
Plaso Version: 1.4.0-rc2
Installed by downloading binary and extracting files

Windows 10 64-bit

```
W:\CASE\WorkingCopy\DiskImage>c:\Tools\plaso-1.4.0-rc2\log2timeline.exe ..\..\Admin\Timeline\WORKSTATION.dump WORKSTATION_C_drive.E01
WARNING: unable to determine location of data files.
Checking availability and versions of plaso dependencies.
[OK]            artifacts version: 20151105
[OK]            bencode
[OK]            binplist version: 0.1.5
[OK]            construct version: 2.5.2
[OK]            dateutil version: 2.4.2
[OK]            dfvfs version: 20151216
[OK]            dpkt version: 1.8.6
[OK]            google.protobuf
[OK]            IPython version: 1.2.1
[OK]            pefile version: 1.2.10-139
[OK]            psutil version: 1.2.1
[OK]            pyparsing version: 2.0.6
[OK]            pytz
[OK]            requests version: 2.9.0
[OK]            six version: 1.9.0
[OK]            xlsxwriter version: 0.7.7
[OK]            yaml version: 3.10
[OK]            zmq version: 15.1.0
[OK]            SleuthKit version: 4.2.0
[OK]            pytsk3 version: 20150406
[OK]            libbde (pybde) version: 20150204
[OK]            libesedb (pyesedb) version: 20151213
[OK]            libevt (pyevt) version: 20151206
[OK]            libevtx (pyevtx) version: 20151206
[OK]            libewf (pyewf) version: 20140608
[OK]            libfsntfs (pyfsntfs) version: 20151205
[OK]            libfwsi (pyfwsi) version: 20150701
[OK]            liblnk (pylnk) version: 20151205
[OK]            libmsiecf (pymsiecf) version: 20151205
[OK]            libolecf (pyolecf) version: 20151205
[OK]            libqcow (pyqcow) version: 20151219
[OK]            libregf (pyregf) version: 20151205
[OK]            libsigscan (pysigscan) version: 20151205
[OK]            libsmdev (pysmdev) version: 20151219
[OK]            libsmraw (pysmraw) version: 20151219
[OK]            libvhdi (pyvhdi) version: 20151205
[OK]            libvmdk (pyvmdk) version: 20150516
[OK]            libvshadow (pyvshadow) version: 20150106


Source path     : W:\CASE\WorkingCopy\DiskImage\WORKSTATION_C_drive.E01
Source type     : storage media image

Processing started.
2015-12-24 19:20:41,509 [ERROR] (MainProcess) PID:6568 <__init__> Unable to preprocess with error: FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
WARNING:root:Unhandled exception in collector (PID: 8576).
ERROR:root:FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
Traceback (most recent call last):
  File "plaso\multi_processing\multi_process.py", line 287, in _Main
  File "plaso\engine\collector.py", line 126, in Collect
  File "plaso\engine\collector.py", line 106, in _ProcessPathSpec
  File "plaso\engine\collector.py", line 62, in _ProcessFileSystem
  File "plaso\engine\collector.py", line 324, in Collect
  File "plaso\engine\collector.py", line 257, in _ProcessDirectory
  File "site-packages\dfvfs\vfs\file_entry.py", line 329, in IsAllocated
  File "site-packages\dfvfs\vfs\tsk_file_entry.py", line 323, in _GetStat
  File "site-packages\dfvfs\vfs\tsk_file_entry.py", line 542, in GetTSKFile
IOError: FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
Worker_00 (PID: 11788) - events extracted: 4 - file: TSK:/Documents and Settings - running: True <running>
Worker_01 (PID: 4772) - events extracted: 0 - file: TSK:/$AttrDef - running: True <running>
Worker_02 (PID: 7232) - events extracted: 0 - file:  - running: True <running>
Worker_03 (PID: 12164) - events extracted: 0 - file:  - running: True <running>
Worker_04 (PID: 1012) - events extracted: 0 - file:  - running: True <running>
Worker_05 (PID: 8468) - events extracted: 0 - file:  - running: True <running>
2015-12-24 19:20:58,688 [ERROR] (MainProcess) PID:6568 <__init__> Process Collector (PID: 8576) is not functioning correctly. Status code killed.
2015-12-24 19:20:58,688 [WARNING] (MainProcess) PID:6568 <__init__> Processing aborted with engine error: Collector unexpectedly terminated.
2015-12-24 19:20:58,688 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_02 (PID: 7232).
2015-12-24 19:20:58,688 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_03 (PID: 12164).
2015-12-24 19:20:58,688 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_05 (PID: 8468).
2015-12-24 19:20:58,704 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_00 (PID: 11788).
2015-12-24 19:20:58,704 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: StorageWriter (PID: 5204).
2015-12-24 19:20:58,704 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_01 (PID: 4772).
2015-12-24 19:20:58,704 [WARNING] (MainProcess) PID:6568 <__init__> Terminating process: Worker_04 (PID: 1012).
Processing completed with errors.
```

**Comment by joachimmetz** [comment]
```
ERROR:root:FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) ( - proc_attrseq)
Traceback (most recent call last):
```

**Comment by joachimmetz** [comment]
```
WARNING: unable to determine location of data files.
```

Note to self check if data location detection can be improved for PyInstaller build

**Comment by CdtDelta** [comment]
Issue is still present in 1.4.0

Y:\Archive\12_22_2015_CASE_NAME\WorkingCopy>c:\Tools\plaso\log2timeline.exe ..\Admin\Timeline\COMPUTER_NAME.dump DiskImage\COMPUTER_NAME_C_drive.E01
Checking availability and versions of plaso dependencies.
[OK]


Source path     : Y:\Archive\12_22_2015_CASE_NAME\WorkingCopy\DiskImage\COMPUTER_NAME_C_drive.E01
Source type     : storage media image

Processing started.
2016-01-23 20:44:32,687 [ERROR] (MainProcess) PID:9464 <extraction_frontend> Unable to preprocess with error: FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
WARNING:root:Unhandled exception in collector (PID: 5692).
ERROR:root:FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
Traceback (most recent call last):
  File "plaso\multi_processing\multi_process.py", line 286, in _Main
  File "plaso\engine\collector.py", line 124, in Collect
  File "plaso\engine\collector.py", line 105, in _ProcessPathSpec
  File "plaso\engine\collector.py", line 61, in _ProcessFileSystem
  File "plaso\engine\collector.py", line 327, in Collect
  File "plaso\engine\collector.py", line 260, in _ProcessDirectory
  File "site-packages\dfvfs\vfs\file_entry.py", line 336, in IsAllocated
  File "site-packages\dfvfs\vfs\tsk_file_entry.py", line 321, in _GetStat
  File "site-packages\dfvfs\vfs\tsk_file_entry.py", line 540, in GetTSKFile
IOError: FS_Info_open_meta: (tsk3.c:291) Unable to open file: Error in metadata structure (ntfs_make_run: Run length is larger than file system) (  - proc_attrseq)
2016-01-23 20:44:44,957 [ERROR] (MainProcess) PID:9464 <multi_process> Process Collector (PID: 5692) is not functioning correctly. Status code killed.
2016-01-23 20:44:44,971 [WARNING] (MainProcess) PID:9464 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.
2016-01-23 20:44:44,987 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: StorageWriter (PID: 10372).
2016-01-23 20:44:44,987 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_00 (PID: 6044).
2016-01-23 20:44:45,003 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_02 (PID: 8092).
2016-01-23 20:44:45,003 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_05 (PID: 1220).
2016-01-23 20:44:45,019 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_04 (PID: 2296).
2016-01-23 20:44:45,019 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_01 (PID: 10724).
2016-01-23 20:44:45,035 [WARNING] (MainProcess) PID:9464 <multi_process> Terminating process: Worker_03 (PID: 6148).
Processing completed with errors.

**Comment by joachimmetz** [comment]
Thanks for the confirmation but yes this is libtsk issue. This means that the issue is not within plaso but in one of its dependencies and needs fixing there.

Can you do the following:
* try to isolate the mft entry index of the file with e.g. fls
* compile libfsntfs with verbose and debug output (https://github.com/libyal/libfsntfs/wiki/Troubleshooting#verbose-and-debug-output)
* provide me with the debug output of `fsntfsinfo -v -E ENTRY VOLUME` where entry is the MFT entry number and VOLUME the volume in which the file system is stored

Without more detailed information we are not able to get this issue fixed.

**Comment by joachimmetz** [comment]
No update from reporter, unable to fix without additional information.
