### ISSUE TITLE
Exporting Plaso to Elasticsearch Failure "strings_parsed of type dict is not supported"

### ISSUE THREAD

**Issue by djantoxz** [log2timeline/plaso#4663]
I am building super timeline, running plaso to Windows evidences (e.g. event logs, registry, mft, and so forth), plaso file generated. However when I use psort, error occurred. The following are details of my environment.

```
$ log2timeline.py -V
plaso - log2timeline version 20210606
$ psort.py -V
plaso - psort version 20210606
$ pip3 show elasticsearch
Name: elasticsearch
Version: 7.9.1
Summary: Python client for Elasticsearch
Home-page: https://github.com/elastic/elasticsearch-py
Author: Honza Král, Nick Lang
Author-email: honza.kral@gmail.com, nick@nicklang.com
License: Apache-2.0
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
$ python -V
Python 3.8.5
$ dpkg --list|grep elasticsearch
ii  elasticsearch                                 7.9.1                                amd64        Distributed RESTful search engine built for the cloud
ii  python3-elasticsearch                         7.9.1-1ppa1~focal                    all          Python client for Elasticsearch

```
The following are the error messages:

```
Storage file            : ./Windows.plaso
Processing time         : 00:05:27

Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               191             288770          18467478

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    4559    exporting       217.5 MiB       289398 (153)    0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 732, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 566, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 585, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 287, in _ConvertDictToObject
    raise ValueError((
ValueError: Event data attribute value: strings_parsed of type dict is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 547, in ProcessStorage
    analysis_engine.ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1043, in ExportEvents
    self._ExportEvents(
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 513, in _ExportEvents
    event_data = storage_reader.GetEventDataByIdentifier(
  File "/usr/lib/python3/dist-packages/plaso/storage/file_interface.py", line 299, in GetEventDataByIdentifier
    return self._storage_file.GetEventDataByIdentifier(identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 943, in GetEventDataByIdentifier
    event_data = self._GetAttributeContainerByIndex(
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 365, in _GetAttributeContainerByIndex
    attribute_container = self._DeserializeAttributeContainer(
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 739, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: Event data attribute value: strings_parsed of type dict is not supported.


```

Found similar issue https://github.com/google/timesketch/issues/1402 - no solution there.

Thanks.

**Comment by joachimmetz** [comment]
The version of Plaso you are using is no longer supported (older than 6 months). Also in the mean time we moved to Open Search. I recommend trying a newer version of Plaso first.

**Comment by djantoxz** [comment]
On progress installing plaso-20230311

**Comment by joachimmetz** [comment]
FYI Using the Docker image might be quicker.

**Comment by djantoxz** [comment]
Problem solved with this:

```
sansforensics@siftworkstation: ~
$ dpkg --list|grep opensearch
ii  opensearch                                    2.7.0                                amd64        An open source distributed and RESTful search engine
ii  opensearch-dashboards                         2.7.0                                amd64        Open source visualization dashboards for OpenSearch
ii  python3-opensearch                            2.0.0-1ppa1~focal                    all          OpenSearch Python Client
sansforensics@siftworkstation: ~
$ log2timeline.py -V
plaso - log2timeline version 20221229
sansforensics@siftworkstation: ~
$ psort.py -V
plaso - psort version 20221229
```
