### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4883]
CI tests are failing with:

```
======================================================================
ERROR: storage.redis.reader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: storage.redis.reader
Traceback (most recent call last):
  File "/__w/plaso/plaso/.tox/py310/lib/python3.10/site-packages/fakeredis/_server.py", line 13, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/__w/plaso/plaso/tests/storage/redis/reader.py", line 9, in <module>
    import fakeredis
  File "/__w/plaso/plaso/.tox/py310/lib/python3.10/site-packages/fakeredis/__init__.py", line 1, in <module>
    from ._server import (
  File "/__w/plaso/plaso/.tox/py310/lib/python3.10/site-packages/fakeredis/_server.py", line 15, in <module>
    from typing import Self
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)
```

**Comment by joachimmetz** [comment]
Changes in https://github.com/log2timeline/plaso/commit/217a1c486614959639f1ced35ce79d91324ce251 for now use older version of fakeredis
