### ISSUE TITLE
log2timeline.py: workers remain alive

### ISSUE THREAD

**Issue by gregfreemyer** [log2timeline/plaso#49]
RE: Git head 20141124

I initiated log2timeline.py yesterday against a partition.  I just checked its progress and it seems to be in an infinite loop.  I invoked log2timeline via:

> log2timeline.py -d --logfile plaso-debug.log --workers 4 --offset 411648 cu01c1.plasodb /mnt/imageCU01/ewf1

For the last 12+ hours I'm getting this in the debug output every 10 seconds:

> 2014-11-26 15:26:48,732 [WARNING] (MainProcess) PID:11761 <foreman> Unable to connect to RPC socket to: Worker_0 at http://localhost:11784
2014-11-26 15:26:48,733 [ERROR] (MainProcess) PID:11761 <foreman> Process Worker_0 [11784] is not functioning when it should be. Terminating it and removing from list.
2014-11-26 15:26:48,734 [WARNING] (MainProcess) PID:11761 <foreman> Process Worker_0 [11784] is still alive.
2014-11-26 15:26:48,736 [WARNING] (MainProcess) PID:11761 <foreman> Unable to connect to RPC socket to: Worker_1 at http://localhost:11786
2014-11-26 15:26:48,737 [ERROR] (MainProcess) PID:11761 <foreman> Process Worker_1 [11786] is not functioning when it should be. Terminating it and removing from list.
2014-11-26 15:26:48,738 [WARNING] (MainProcess) PID:11761 <foreman> Process Worker_1 [11786] is still alive.
2014-11-26 15:26:48,740 [WARNING] (MainProcess) PID:11761 <foreman> Unable to connect to RPC socket to: Worker_2 at http://localhost:11788
2014-11-26 15:26:48,740 [ERROR] (MainProcess) PID:11761 <foreman> Process Worker_2 [11788] is not functioning when it should be. Terminating it and removing from list.
2014-11-26 15:26:48,742 [WARNING] (MainProcess) PID:11761 <foreman> Process Worker_2 [11788] is still alive.
2014-11-26 15:26:48,743 [WARNING] (MainProcess) PID:11761 <foreman> Unable to connect to RPC socket to: Worker_3 at http://localhost:11790
2014-11-26 15:26:48,744 [ERROR] (MainProcess) PID:11761 <foreman> Process Worker_3 [11790] is not functioning when it should be. Terminating it and removing from list.
2014-11-26 15:26:48,745 [WARNING] (MainProcess) PID:11761 <foreman> Process Worker_3 [11790] is still alive.

I went back and looked at the first occurrence and I don't see any relevant logs just before it started but I don't really know what I'm looking for.

I have the full debug.log, so let me know what I can provide.  

Likely an unrelated issue but before the infinite loop started I was getting this "ERROR" by the 10,000s of thousands, but it was more or less continuous for the whole time the image was processing:

> 2014-11-25 20:32:21,290 [ERROR] (Worker_2  ) PID:11788 <worker> 'ascii' codec can't decode byte 0xf9 in position 1: ordinal not in range(128)

Here it is with some context:

> 2014-11-25 20:32:21,290 [DEBUG] (Worker_2  ) PID:11788 <worker> Trying to parse: f_000022 with parser: skydrive_log_error
2014-11-25 20:32:21,290 [WARNING] (Worker_2  ) PID:11788 <worker> [skydrive_log_error] Unable to process file: type: OS, location: /mnt/imageCU01/ewf1
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x0c900000
type: VSHADOW, store index: 0
type: TSK, inode: 114343, location: /Users/bbenisrael/AppData/Local/Google/Chrome/User Data/Default/Media Cache/f_000022
 with error: 'ascii' codec can't decode byte 0xf9 in position 1: ordinal not in range(128).
2014-11-25 20:32:21,290 [DEBUG] (Worker_2  ) PID:11788 <worker> The path specification that caused the error: type: OS, location: /mnt/imageCU01/ewf1
type: RAW
type: TSK_PARTITION, location: /p2, part index: 3, start offset: 0x0c900000
type: VSHADOW, store index: 0
type: TSK, inode: 114343, location: /Users/bbenisrael/AppData/Local/Google/Chrome/User Data/Default/Media Cache/f_000022
2014-11-25 20:32:21,290 [ERROR] (Worker_2  ) PID:11788 <worker> 'ascii' codec can't decode byte 0xf9 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/site-packages/plaso/parsers/text_parser.py", line 1032, in Parse
    self._text_reader.ReadLines(file_object)
  File "/usr/lib/python2.7/site-packages/plaso/parsers/text_parser.py", line 970, in ReadLines
    self.lines = u''.join([self.lines, line])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf9 in position 1: ordinal not in range(128)

If that is unrelated and worthy of its own issue, let me know.

**Comment by joachimmetz** [comment]
The issue mentioned by florian-eichelberger@ looks more like: https://github.com/log2timeline/plaso/issues/71

**Comment by joachimmetz** [comment]
Can you try again the latest dev version. Issue #71 seems to have been fixed by it. Feel free to reopen the issue if it is not fixed.
