### ISSUE TITLE
Unhandled exception in skype sqlite plugin

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#498]
Encountered in one of the test images.
```
Traceback (most recent call last):
  File "plaso\engine\worker.py", line 684, in _ProcessPathSpec
  File "plaso\engine\worker.py", line 636, in _ProcessFileEntry
  File "plaso\engine\worker.py", line 555, in _ProcessDataStream
  File "plaso\engine\worker.py", line 353, in _ParseFileEntryWithParser
  File "plaso\parsers\interface.py", line 288, in Parse
  File "plaso\parsers\sqlite.py", line 268, in ParseFileObject
  File "plaso\parsers\plugins.py", line 88, in UpdateChainAndProcess
  File "plaso\parsers\sqlite_plugins\interface.py", line 89, in Process
  File "plaso\parsers\sqlite_plugins\interface.py", line 52, in GetEntries
  File "plaso\parsers\sqlite_plugins\skype.py", line 299, in ParseSMS
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/281190043/

**Comment by joachimmetz** [comment]
```
sqlite> .schema SMSes
CREATE TABLE "SMSes" (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, outgoing_reply_type INTEGER, status INTEGER, failurereason INTEGER, is_failed_unseen INTEGER, timestamp INTEGER, price INTEGER, price_precision INTEGER, price_currency TEXT, reply_to_number TEXT, target_numbers TEXT, target_statuses BLOB, body TEXT, chatmsg_id INTEGER, identity TEXT, notification_id INTEGER, event_flags INTEGER, reply_id_number TEXT, convo_name TEXT);
```

```
SELECT * FROM SMSes;
121|1|2|1|3|||0|0|3|EUR||||||||||
125|1|2|1|3|||0|0|3|EUR||||||||||
```
