### ISSUE TITLE
Refactor CUPS IPP parser

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#538]
Refactor to match include more defined tag types, more closely match current control file format.

**Comment by Onager** [comment]
This is currently crashing, too:
```
2016-05-18 20:03:44,008 [ERROR] (Worker_02 ) PID:4129 <worker> 'utf8' codec can't decode byte 0x98 in position 28: invalid start byte
Traceback (most recent call last):
  File "/plaso/engine/worker.py", line 728, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry, data_stream_name=data_stream_name)
  File "/plaso/engine/worker.py", line 680, in _ProcessFileEntry
    file_entry, data_stream_name=data_stream_name)
  File "/plaso/engine/worker.py", line 559, in _ProcessDataStream
    parser_object, file_entry, file_object=file_object)
  File "/plaso/engine/worker.py", line 358, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_mediator, file_object)
  File "/plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/plaso/parsers/cups_ipp.py", line 240, in ParseFileObject
    name, value = self.ReadPair(parser_mediator, file_object)
  File "/plaso/parsers/cups_ipp.py", line 329, in ReadPair
    name = self.PAIR_NAME.parse_stream(file_object).text
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/lib/python2.7/dist-packages/construct/adapters.py", line 158, in _decode
    obj = obj.decode(self.encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 28: invalid start byte
```

**Comment by joachimmetz** [comment]
@Onager should we fix this bug as part of 1.5 ?

**Comment by joachimmetz** [comment]
Pending refactor for dtFabric https://codereview.appspot.com/347800043/

**Comment by joachimmetz** [comment]
@Onager "This is currently crashing, too:" do you recall which test image / file this is?

**Comment by Onager** [comment]
No, I don't remember which test file that was. 

Is this issue fixed with https://github.com/log2timeline/plaso/commit/8a275cb6ecb75dcecbbc7446c6766672a0ae7488 ?

**Comment by joachimmetz** [comment]
This particular issue (maybe not the root cause) is no longer applicable.

**Comment by joachimmetz** [comment]
Will need test file to reproduce and improve parser. Closing issue seeing parser has been rewritten.
