### ISSUE TITLE
The check of dependencies fails with non numerical versions.

### ISSUE THREAD

**Issue by 2xyo** [log2timeline/plaso#567]
### Description

log2timeline.py  looks not happy with non numerical versioning of some python packages even if it's not a mandatory dependency.

```
$ log2timeline.py  -f filter myfile.plaso  /dev/vg_myserver/lv_root
Checking availability and versions of plaso dependencies.
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/local/bin/log2timeline.py", line 798, in Main
    verbose_output=False):
  File "/usr/local/lib/python2.7/dist-packages/plaso/dependencies.py", line 453, in CheckDependencies
    verbose_output=verbose_output):
  File "/usr/local/lib/python2.7/dist-packages/plaso/dependencies.py", line 310, in _CheckPythonModule
    map(int, _VERSION_SPLIT_REGEX.split(module_version)))
ValueError: invalid literal for int() with base 10: '0rc2'

$ pip freeze |grep 0rc2
ipython==4.1.0rc2

$ pip uninstall ipython

$ log2timeline.py  -f filter myfile.plaso  /dev/vg_myserver/lv_root
Checking availability and versions of plaso dependencies.
[OK]
...
```
### Dirty fix

Quick and dirty fix taking into account alpha, beta, release candidate: 

```
diff --git a/plaso/dependencies.py b/plaso/dependencies.py
index 2bc1817..c39eb52 100644
--- a/plaso/dependencies.py
+++ b/plaso/dependencies.py
@@ -74,7 +74,7 @@ PYTHON_DEPENDENCIES = [
 PYTHON_TEST_DEPENDENCIES = [
     (u'mock', u'__version__', u'0.7.1', None)]

-_VERSION_SPLIT_REGEX = re.compile(r'\.|\-')
+_VERSION_SPLIT_REGEX = re.compile(r'\.|\-|a|b|rc')


 def _DownloadPageContent(download_url):

```

Not really tested.
### Installed version

Plaso 

```
# cd /opt/plaso
# git rev-parse HEAD
ebb77482ee2b3ed9a7e5607e2a6fd6748585a423
#  pip install -U .
Successfully installed plaso-1.4.1.post20160130
# /usr/local/bin/log2timeline.py -V
plaso - log2timeline version 1.4.1_20160130
```

Dependencies : 

```
# cat /etc/apt/sources.list.d/gift-dev-trusty.list
deb http://ppa.launchpad.net/gift/dev/ubuntu trusty main
```

**Comment by joachimmetz** [comment]
Thanks for reporting. We'll gradually look to improve the dependency check. For now you can disable it with `--no-dependencies-check` if it gets in your way.

**Comment by joachimmetz** [comment]
ipython is no longer a dependency, closing issue. Reopen if this surfaces a again with a different dependency.
