### ISSUE TITLE
Latest IPython breaks tests on Travis

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#591]
* [x] [Use IPython provided by Ubuntu 14.04](https://codereview.appspot.com/297710043/)

```
/usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
```

**Comment by mark-hallman** [comment]
Hello all,

I am getting the same error trying to preg.py  other modules are working.  Thoughts?

**Comment by mark-hallman** [comment]
Here is the entire message received...

preg.py -q NTUSER.DAT
/usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/preg.py", line 1717, in <module>
    if not Main():
  File "/usr/bin/preg.py", line 1708, in Main
    tool.RunModeRegistryFile()
  File "/usr/bin/preg.py", line 838, in RunModeRegistryFile
    registry_helper.Open()
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/preg.py", line 1076, in Open
    self._registry_file = win_registry_reader.Open(file_object)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/winreg.py", line 31, in Open
    registry_file.Open(file_object)
  File "/usr/lib/python2.7/dist-packages/plaso/dfwinreg/regf.py", line 266, in Open
    self._regf_file.open_file_object(self._file_object)
IOError: pyregf_file_open_file_object: unable to open file. libregf_io_handle_read_file_header: invalid file signature. libregf_file_open_read: unable to read file header. libregf_file_open_file_io_handle: unable to read from file handle.

**Comment by joachimmetz** [comment]
@mark-hallman please don't hijack issues that are not related. I'll remove your comments form this issue and move this elsewhere.

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "./run_tests.py", line 15, in <module>
    if not plaso.dependencies.CheckTestDependencies():
  File "./plaso/dependencies.py", line 517, in CheckTestDependencies
    if not CheckDependencies(latest_version_check=latest_version_check):
  File "./plaso/dependencies.py", line 453, in CheckDependencies
    verbose_output=verbose_output):
  File "./plaso/dependencies.py", line 290, in _CheckPythonModule
    module_object = _ImportPythonModule(module_name)
  File "./plaso/dependencies.py", line 110, in _ImportPythonModule
    module_object = list(map(__import__, [module_name]))[0]
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 77, in <module>
    _is_tty = (sys.stdin.isatty()) and (sys.stdout.isatty()) and  (sys.stderr.isatty())
AttributeError: 'UnicodeStdout' object has no attribute 'isatty'
```
