### ISSUE TITLE
Issues installing Plaso 1.4.0 on Macosx 

### ISSUE THREAD

**Issue by odelamp** [log2timeline/plaso#593]
Hi, 
I'm trying to install plaso 1.4.0 on my Mac and check_dependencies.py script keep saying that Construct 2.5.1 and pyparsing 2.0.1 are too old.
I have manually installed the newer versions from https://github.com/log2timeline/l2tbinaries/tree/master/macosx

Regards,
Olivier.

**Comment by joachimmetz** [comment]
This is a known issue with Mac OS X see: https://github.com/log2timeline/plaso/wiki/Dependencies-Mac-OS-X#pyparsing

I see that https://github.com/log2timeline/plaso/wiki/Mac-OS-X-Packaged-Release was not updated to reflect this as well.

**Comment by odelamp** [comment]
Hi Joachim,
thanks for this prompt response.
I'm running EL Capitan and tried already to force the PYTHONPATH but I'm still getting the same error when launching log2timeline.
According to my understanding this issue is due to a conflict of version.
/usr/local/bin/log2timeline.py --help
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 22, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 6, in <module>
    from plaso.cli import storage_media_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/storage_media_tool.py", line 10, in <module>
    from dfvfs.helpers import source_scanner
  File "/Library/Python/2.7/site-packages/dfvfs/helpers/source_scanner.py", line 20, in <module>
    from dfvfs.analyzer import analyzer
  File "/Library/Python/2.7/site-packages/dfvfs/analyzer/__init__.py", line 3, in <module>
    from dfvfs.analyzer import bde_analyzer_helper
  File "/Library/Python/2.7/site-packages/dfvfs/analyzer/bde_analyzer_helper.py", line 4, in <module>
    from dfvfs.analyzer import analyzer
  File "/Library/Python/2.7/site-packages/dfvfs/analyzer/analyzer.py", line 9, in <module>
    from dfvfs.resolver import resolver
  File "/Library/Python/2.7/site-packages/dfvfs/resolver/__init__.py", line 18, in <module>
    from dfvfs.resolver import gzip_resolver_helper
  File "/Library/Python/2.7/site-packages/dfvfs/resolver/gzip_resolver_helper.py", line 5, in <module>
    import dfvfs.file_io.gzip_file_io
  File "/Library/Python/2.7/site-packages/dfvfs/file_io/gzip_file_io.py", line 15, in <module>
    class GzipFile(file_object_io.FileObjectIO):
  File "/Library/Python/2.7/site-packages/dfvfs/file_io/gzip_file_io.py", line 22, in GzipFile
    construct.ULInt16(u'signature'),
  File "/Library/Python/2.7/site-packages/construct-2.5.1-py2.7.egg/construct/macros.py", line 160, in ULInt16
    return FormatField(name, "<", "H")
  File "/Library/Python/2.7/site-packages/construct-2.5.1-py2.7.egg/construct/core.py", line 352, in __init__
    StaticField.__init__(self, name, self.packer.size)
  File "/Library/Python/2.7/site-packages/construct-2.5.1-py2.7.egg/construct/core.py", line 324, in __init__
    Construct.__init__(self, name)
  File "/Library/Python/2.7/site-packages/construct-2.5.1-py2.7.egg/construct/core.py", line 103, in __init__
    raise TypeError("name must be a string or None", name)
TypeError: ('name must be a string or None', u'signature')

**Comment by odelamp** [comment]
ok find my way, the issue was with a version conflict of construct.
/Library/Python/2.7/site-packages/construct-2.5.1-py2.7.egg:
total 0
drwxr-xr-x    4 root  wheel   136 Jan 30  2015 .
drwxr-xr-x  150 root  wheel  5100 Feb 16 13:35 ..
drwxr-xr-x    8 root  wheel   272 Jan 30  2015 EGG-INFO
drwxr-xr-x   17 root  wheel   578 Jan 30  2015 construct

/Library/Python/2.7/site-packages/construct-2.5.2-py2.7.egg-info:
total 56
drwxr-xr-x    8 root  wheel   272 Feb 16 13:35 .
drwxr-xr-x  150 root  wheel  5100 Feb 16 13:35 ..
-rw-r--r--    1 root  wheel  1136 Dec  6  2014 LICENSE
-rw-rw-r--    1 root  wheel  4982 Dec  6  2014 PKG-INFO
-rw-rw-r--    1 root  wheel  1840 Dec  6  2014 SOURCES.txt
-rw-rw-r--    1 root  wheel     1 Dec  6  2014 dependency_links.txt
-rw-rw-r--    1 root  wheel     3 Dec  6  2014 requires.txt
-rw-rw-r--    1 root  wheel    10 Dec  6  2014 top_level.txt

Removing the 2.5.1 solved the issue.

**Comment by joachimmetz** [comment]
Great. Plaso needs 2.5.2 since we ran into some show stopper bugs in 2.5.1 in the past.

I've also updated https://github.com/log2timeline/plaso/wiki/Mac-OS-X-Packaged-Release and will close this issue.
