### ISSUE TITLE
preg: warning?

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#611]
From @mark-hallman Here is the entire message received...

```
preg.py -q NTUSER.DAT
/usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/preg.py", line 1717, in <module>
    if not Main():
  File "/usr/bin/preg.py", line 1708, in Main
    tool.RunModeRegistryFile()
  File "/usr/bin/preg.py", line 838, in RunModeRegistryFile
    registry_helper.Open()
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/preg.py", line 1076, in Open
    self._registry_file = win_registry_reader.Open(file_object)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/winreg.py", line 31, in Open
    registry_file.Open(file_object)
  File "/usr/lib/python2.7/dist-packages/plaso/dfwinreg/regf.py", line 266, in Open
    self._regf_file.open_file_object(self._file_object)
IOError: pyregf_file_open_file_object: unable to open file. libregf_io_handle_read_file_header: invalid file signature. libregf_file_open_read: unable to read file header. libregf_file_open_file_io_handle: unable to read from file handle.
```

**Comment by joachimmetz** [comment]
@mark-hallman the deprecation warning is not related to the error. If you look at the error:
```
IOError: pyregf_file_open_file_object: unable to open file.
libregf_io_handle_read_file_header: invalid file signature.
libregf_file_open_read: unable to read file header.
libregf_file_open_file_io_handle: unable to read from file handle.
```

`libregf_io_handle_read_file_header: invalid file signature.` indicates that the file being opened does not appears to be a REGF file. Can you add a hexdump of the first 32 bytes of NTUSER.DAT e.g.
```
hexdump -Cv NTUSER.DAT | head -n2
```

**Comment by joachimmetz** [comment]
No update from OP, closing issue.
