### ISSUE TITLE
Adding missing preferred_encoding attribute to test classes

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#616]
Filing so I don't forget:

```
======================================================================
ERROR: testParseStringOption (cli.tools.CLIToolTest)
Tests the ParseStringOption function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/plaso/tests/cli/tools.py", line 141, in testParseStringOption
    encoding = self.preferred_encoding
AttributeError: 'CLIToolTest' object has no attribute 'preferred_encoding'

======================================================================
ERROR: testParseStringOption (cli.helpers.interface.HelperManagerTest)
Tests the _ParseStringOption function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/plaso/tests/cli/helpers/interface.py", line 49, in testParseStringOption
    encoding = self.preferred_encoding
AttributeError: 'HelperManagerTest' object has no attribute 'preferred_encoding'

----------------------------------------------------------------------
```

**Comment by Onager** [comment]
Some other encoding issues:

```
======================================================================
ERROR: testParseStringOption (cli.tools.CLIToolTest)
Tests the ParseStringOption function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/Plaso unit tests/tests/cli/tools.py", line 168, in testParseStringOption
    if not sys.stdin.encoding and sys.stdin.encoding.upper() == u'UTF-8':
AttributeError: 'NoneType' object has no attribute 'upper'

======================================================================
ERROR: testParseStringOption (cli.helpers.interface.HelperManagerTest)
Tests the _ParseStringOption function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/Plaso unit tests/tests/cli/helpers/interface.py", line 76, in testParseStringOption
    if not sys.stdin.encoding and sys.stdin.encoding.upper() == u'UTF-8':
AttributeError: 'NoneType' object has no attribute 'upper'

----------------------------------------------------------------------
```
