### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#625]
I get an UTF8 error when using the current docker image with log2timeline version 1.4.0:

` docker run -v /data:/data -v /run/media/targetdir:/drive e687ba2cd049 log2timeline.py /data/l2t.dump /drive --parsers "winevtx,lnk,winreg,webhist,skype,winxp,win7" --workers 6`

```
Processing started.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 802, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 735, in ProcessSources
    timezone=self._timezone)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 471, in ProcessSources
    pre_obj = self._PreprocessSources(source_path_specs, source_type)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 191, in _PreprocessSources
    source_path_specs, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 103, in PreprocessSources
    platform = preprocess_interface.GuessOS(searcher)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 203, in GuessOS
    for path_spec in searcher.Find(find_specs=find_specs):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 410, in Find
    for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/file_system_searcher.py", line 379, in _FindInFileEntry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 228, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 67, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 45, in _EntriesGenerator
    location, directory_entry])
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_system.py", line 191, in JoinPath
    segment.split(self.PATH_SEPARATOR) for segment in path_segments]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

The /run/media/targetdir is a windows C: partition with the following mount params: 

`/dev/sdc2 on /run/media/targetdir type fuseblk (ro,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)`

I suppose my LANG and LC_ALL environment variables are of no help here because the command is run within docker environment.

I could provide a list of files and directories for reproduction purposes.

```
docker run e687ba2cd049 log2timeline.py  --version
> plaso - log2timeline version 1.4.0
```

I also reported this bug in #351 but I am not sure if this one is really command-line related.

**Comment by bf** [comment]
Processing works when I use the hard disk image and specify the volume using the `--partition` command line parameter.

**Comment by Onager** [comment]
This might be due to the LANG and LC_ALL settings inside the container - by default, they're ascii, not unicode. I'll take a look at this.

**Comment by Onager** [comment]
Could you try adding the following to your dockerfile:
```
# Set terminal to UTF-8 by default
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
ENV LANG en_US.UTF-8  
ENV LC_ALL en_US.UTF-8 
```

Then rebuild the docker image, start a new container, and try again?

**Comment by bf** [comment]
Thanks for the immediate reponse! I will do so and report back after the currently running extraction task is finished.

**Comment by bf** [comment]
Thanks Onager, this fixed my issue. I've created a pull request to add these changes to the plaso docker file :+1:
