### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by yani1shu** [log2timeline/plaso#669]
**Plaso version:**

plaso - log2timeline version 1.4.0

**Operating system Plaso is running on:**

Windows 10 x64

Trying to process raw image consisting of 435 image file segments. It opens the image and shows the partitions and restore points, when it starts trying to process I get the following error:

2016-04-14 15:18:47,364 [ERROR] (MainProcess) PID:4204 <engine> Unable to open file system with error: [Errno 24] Too many open files: u'E:\\case\\case001\\FILE.072'
Traceback (most recent call last):
  File "<string>", line 816, in <module>
  File "<string>", line 802, in Main
  File "<string>", line 735, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 564, in ProcessSources
  File "plaso\multi_processing\multi_process.py", line 1077, in ProcessSources
  File "plaso\multi_processing\multi_process.py", line 1391, in __init__
  File "plaso\multi_processing\multi_process.py", line 59, in __init__
  File "multiprocessing\__init__.py", line 252, in Value
  File "c:\Projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 315, in load_module
  File "c:\Projects\pyinstaller\PyInstaller\loader\pyimod02_archive.py", line 321, in extract
  File "c:\Projects\pyinstaller\PyInstaller\loader\pyimod02_archive.py", line 73, in __enter__
  File "c:\Projects\pyinstaller\PyInstaller\loader\pyimod02_archive.py", line 69, in __open
IOError: [Errno 24] Too many open files: 'C:\\Users\\examiner\\Desktop\\Forensic Apps\\plaso\\log2timeline.exe'
log2timeline returned -1

I don't have the image files open any where else.

**Comment by joachimmetz** [comment]
Solution for now:

Increase the maximum number of open file handles on you system or separately mount the storage media image.

**Comment by yani1shu** [comment]
How do I Increase the maximum number of open file handles on you system?

On Thursday, April 14, 2016, Joachim Metz <notifications@github.com> wrote:

> Solution for now:
>
> Increase the maximum number of open file handles on you system or
> separately mount the storage media image.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/log2timeline/plaso/issues/669#issuecomment-210280617>
>


-- 
Sent from Gmail Mobile

**Comment by joachimmetz** [comment]
> How do I Increase the maximum number of open file handles on you system?

Seeing you're running Windows it is likely a combination of non-obvious limitations. Also see: http://stackoverflow.com/questions/870173/is-there-a-limit-on-number-of-open-files-in-windows

I've opened: https://github.com/log2timeline/dfvfs/issues/120 to see if that might provide solution to the issue.

**Comment by fbruzzaniti** [comment]
I was getting this error when running psort.py against a 3 gig plaso file (tagging).
A quick fix for anyone who is having this problem on Ubuntu (well it worked for me).
In the same user session that you plan to run psort.py type:

ulimit -Sn 4096 then run psort

4096 was enough for what I was doing it is the soft limit for my system. You could change the hard limit for the entire system via sysctl then rerun ulimit.  FYI the line to add to /etc/sysctl.conf would be something like:

fs.file-max = 8192
sysctl -p

**Comment by Onager** [comment]
@fbruzzaniti that sounds like a completely different issue, as the original report was Windows and Log2timeline, and your report is Linux and Psort.

I'll move this to another issue, and I'd like to know more about what's happening here.
