### ISSUE TITLE
linux preprocessor raises exception when analyzing a partition, if /etc/passwd is badly formatted

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#678]
**Plaso version:**

1.3.0

dpkg -l | grep plaso
ii  python-plaso                        1.3.0-2ppa1~trusty                          all          Plaso Log2Timeline

**Operating system Plaso is running on:**

Ubuntu trusty 64b / 3.13.0-74-generic

**Installation method:**

ppa/GIFT

**Description of problem:**

Log2timeline's linux preprocessor crashes when analyzing a partition, if /etc/passwd is badly formatted.

**Debug output/tracebacks:**

log2timeline.py -d disk.plaso /dev/sdb1
[INFO] Data files will be loaded from /usr/share/plaso by default.

Source path     : /dev/sdb1
Source type     : storage media image

Processing started.
2016-04-25 11:12:19,256 [DEBUG] (MainProcess) PID:28115 <extraction_frontend> Starting preprocessing.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 676, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 662, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 604, in ProcessSources
    timezone=self._timezone)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 450, in ProcessSources
    pre_obj = self._PreprocessSource(source_path_specs, source_type)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 189, in _PreprocessSource
    resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 97, in PreprocessSource
    platform, searcher, self.knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 117, in RunPlugins
    plugin_object.Run(searcher, knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 113, in Run
    value = self.GetValue(searcher, knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/linux.py", line 87, in GetValue
    for row in reader:
_csv.Error: line contains NULL byte

**Source data:**

Disk image.

**Comment by rgayon** [comment]
Same issue with 1.4.0 

 log2timeline.py -d disk.plaso /dev/sdb1
Checking availability and versions of plaso dependencies.
[OK]


Source path     : /dev/sdb1
Source type     : storage media device

Processing started.
2016-04-26 10:46:33,999 [DEBUG] (MainProcess) PID:21512 <extraction_frontend> Starting preprocessing.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 802, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 735, in ProcessSources
    timezone=self._timezone)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 471, in ProcessSources
    pre_obj = self._PreprocessSources(source_path_specs, source_type)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 191, in _PreprocessSources
    source_path_specs, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 108, in PreprocessSources
    platform, file_system, mount_point, self.knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/manager.py", line 232, in RunPlugins
    plugin_object.Run(searcher, knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/interface.py", line 131, in Run
    value = self.GetValue(searcher, knowledge_base)
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/linux.py", line 87, in GetValue
    for row in reader:
_csv.Error: line contains NULL byte

**Comment by joachimmetz** [comment]
So this would mean the file contains 0-byte values, any example we can use as a test file?

**Comment by joachimmetz** [comment]
Changes pending in https://codereview.appspot.com/305820043/diff/100001/plaso/preprocessors/linux.py
