### ISSUE TITLE
psort.py -slice: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by NZC-2270116** [log2timeline/plaso#679]
**Plaso version:**

plaso - psort version 1.4.1_20160414

Current code from git clone, deps from ppa:gift/dev.

[OK]		artifacts version: 20160114
[OK]		bencode
[OK]		binplist version: 0.1.5
[OK]		construct version: 2.5.2
[OK]		dateutil version: 2.5.3
[OK]		dfdatetime version: 20160323
[OK]		dfvfs version: 20160330
[OK]		dfwinreg version: 20160320
[OK]		dpkt version: 1.8.7
[OK]		google.protobuf
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
[OK]		hachoir_metadata version: 1.3.3
[OK]		IPython version: 2.4.1
[OK]		pefile version: 1.2.10-139
[OK]		psutil version: 4.1.0
[OK]		pyparsing version: 2.1.1
[OK]		pytz
[OK]		requests version: 2.9.1
[OK]		six version: 1.10.0
[OK]		xlsxwriter version: 0.7.3
[OK]		yaml version: 3.11
[OK]		zmq version: 15.2.0
[OK]		sqlite3 version: 3.11.0
[OK]		SleuthKit version: 4.2.0
[OK]		pytsk3 version: 20160111
[OK]		libbde (pybde) version: 20160418
[OK]		libesedb (pyesedb) version: 20151213
[OK]		libevt (pyevt) version: 20160421
[OK]		libevtx (pyevtx) version: 20160421
[INFO]		libewf (pyewf) version: 20140608 installed, version: 20160424 available.
[OK]		libfsntfs (pyfsntfs) version: 20160418
[OK]		libfwsi (pyfwsi) version: 20160110
[OK]		liblnk (pylnk) version: 20160420
[OK]		libmsiecf (pymsiecf) version: 20160421
[OK]		libolecf (pyolecf) version: 20160423
[OK]		libqcow (pyqcow) version: 20160123
[OK]		libregf (pyregf) version: 20160424
[OK]		libscca (pyscca) version: 20160108
[OK]		libsigscan (pysigscan) version: 20160312
[OK]		libsmdev (pysmdev) version: 20160320
[INFO]		libsmraw (pysmraw) version: 20160108 installed, version: 20160424 available.
[INFO]		libvhdi (pyvhdi) version: 20160108 installed, version: 20160424 available.
[OK]		libvmdk (pyvmdk) version: 20160119
[OK]		libvshadow (pyvshadow) version: 20160110

**Operating system Plaso is running on:**

Ubuntu 16.04LTS

Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Installation method:**

Added ppa:gift/dev, manually installed deps (some deps are broken so fully automatic install does not work).  git clone, manually changed one line to work around https://github.com/log2timeline/plaso/issues/673 then build & install.  log2timeline.py and psort.py has worked OK until this issue.

**Description of problem:**

 % psort.py -o xlsx -w a.xlsx  --slice '...' --slice-size 240 a.plaso 
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.1.post20160414', 'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 693, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 688, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 637, in ProcessStorage
    self._ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 261, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/plaso/frontend/psort.py", line 530, in ProcessStorage
    counter[u'Stored Events'] += information.counter[u'total']
TypeError: 'NoneType' object has no attribute '__getitem__'

% psort.py --slice '2011-03-10 03:00:00' --slice-size 600 x.plaso > x.csv
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.1.post20160414', 'psort.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 693, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 688, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 637, in ProcessStorage
    self._ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/EGG-INFO/scripts/psort.py", line 261, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160414-py2.7.egg/plaso/frontend/psort.py", line 530, in ProcessStorage
    counter[u'Stored Events'] += information.counter[u'total']
TypeError: 'NoneType' object has no attribute '__getitem__'

Problem occurs when --slice is used.  Output format does not matter (tried default, xlsx).

**Comment by joachimmetz** [comment]
Thanks for the report, we'll try to have a look at the issue as soon time permits.

**Comment by joachimmetz** [comment]
Might have reproduced a similar issue in the recent refactoring. I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/296240043/

**Comment by joachimmetz** [comment]
Should be fixed now
