### ISSUE TITLE
Issue with preprocess for /etc/passwd

### ISSUE THREAD

**Issue by chaoticmachinery** [log2timeline/plaso#699]
**Plaso version: 1.4.0 Release
**Operating system Plaso is running on: Fedora 23
**Installation method: Used 1.4.0 source code release and built  
**Description of problem:**
Get a "IndexError: list index out of range" error when /usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/preprocessors/linux.py encounters a blank line in the /etc/passwd file.

**Debug output/tracebacks:**
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.0', 'log2timeline.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 802, in Main
    tool.ProcessSources()
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 735, in ProcessSources
    timezone=self._timezone)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/frontend/extraction_frontend.py", line 471, in ProcessSources
    pre_obj = self._PreprocessSources(source_path_specs, source_type)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/frontend/extraction_frontend.py", line 191, in _PreprocessSources
    source_path_specs, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/engine/engine.py", line 108, in PreprocessSources
    platform, file_system, mount_point, self.knowledge_base)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/preprocessors/manager.py", line 232, in RunPlugins
    plugin_object.Run(searcher, knowledge_base)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/preprocessors/interface.py", line 131, in Run
    value = self.GetValue(searcher, knowledge_base)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.0-py2.7.egg/plaso/preprocessors/linux.py", line 91, in GetValue
    'uid': row[2],
IndexError: list index out of range

**Source data:**
```
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin

sync:x:5:0:sync:/sbin:/bin/sync
```

**The Fix**
The following edit to the block of code addresses the issue:
```
    users = []
    for row in reader:
      try:
      # TODO: as part of artifacts, create a proper object for this.
         user = {
             'uid': row[2],
             'gid': row[3],
             'name': row[0],
             'path': row[5],
             'shell': row[6]}
         users.append(user)
      except IndexError:
         print 'Bad line in passwd file'

    file_object.close()

```

**Comment by joachimmetz** [comment]
Thanks for the report, think this is related to https://github.com/log2timeline/plaso/issues/678 and is on our 1.5.0 to fix list.

**Comment by joachimmetz** [comment]
Added a fix to https://codereview.appspot.com/305820043/
