### ISSUE TITLE
Openxml / Zip Handling Bug ? 

### ISSUE THREAD

**Issue by florian-eichelberger** [log2timeline/plaso#72]
Hi Guys

I tried to use log2timeline / plaso and it seems to be somehow tripping over this: (in addition to another bug as it seems).

Vers. used: plaso-backend 1.1.1_20141103   (using the SANS SIFT Workstation 3)  on Debian Wheezy/Sid 
Python 2.7.3

Started it using this cmd-line:
log2timeline.py -o 32 -i /mnt/hgfs/TARGET/image_dump /mnt/hgfs/TARGET/image.dd 

It seems to start correctly, but after some time those messages show up and in the end I seem to run into this bug ( https://github.com/log2timeline/plaso/issues/49 )  and am left with a 409 bytes dump file .... 

2014-12-17 17:15:30,717 [WARNING] (Worker_0  ) PID:26039 <worker> [openxml] Unable to process file: type: OS, location: /mnt/hgfs/TARGET/image.dd
type: RAW
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00004000
type: TSK, inode: 28766, location: /Program Files/CA/SharedComponents/iTechnology/Spin/baseSpindle.spar
 with error: unpack requires a string argument of length 22.
2014-12-17 17:15:30,718 [ERROR] (Worker_0  ) PID:26039 <worker> unpack requires a string argument of length 22
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 151, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/oxml.py", line 96, in Parse
    if not zipfile.is_zipfile(file_object):
  File "/usr/lib/python2.7/zipfile.py", line 149, in is_zipfile
    result = _check_zipfile(fp=filename)
  File "/usr/lib/python2.7/zipfile.py", line 135, in _check_zipfile
    if _EndRecData(fp):
  File "/usr/lib/python2.7/zipfile.py", line 238, in _EndRecData
    endrec = list(struct.unpack(structEndArchive, recData))
error: unpack requires a string argument of length 22
2014-12-17 17:15:31,269 [WARNING] (Worker_0  ) PID:26039 <worker> [openxml] Unable to process file: type: OS, location: /mnt/hgfs/TARGET/image.dd
type: RAW
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00004000
type: TSK, inode: 29018, location: /Program Files/CA/SharedComponents/iTechnology/Spin/itmClient.spar
 with error: unpack requires a string argument of length 22.
2014-12-17 17:15:31,270 [ERROR] (Worker_0  ) PID:26039 <worker> unpack requires a string argument of length 22
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 151, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/oxml.py", line 96, in Parse
    if not zipfile.is_zipfile(file_object):
  File "/usr/lib/python2.7/zipfile.py", line 149, in is_zipfile
    result = _check_zipfile(fp=filename)
  File "/usr/lib/python2.7/zipfile.py", line 135, in _check_zipfile
    if _EndRecData(fp):
  File "/usr/lib/python2.7/zipfile.py", line 238, in _EndRecData
    endrec = list(struct.unpack(structEndArchive, recData))
error: unpack requires a string argument of length 22

**Comment by kiddinn** [comment]
This was fixed quite some time ago, closing this one down since I haven't received any update in quite some time.

IF this is really still an issue, could you re-open the bug?
