### ISSUE TITLE
Question: How to analyse a whole drive

### ISSUE THREAD

**Issue by m-terlinde** [log2timeline/plaso#736]
**Plaso version:**
1.4.0

**Operating system Plaso is running on:**

Windows 7 x64, run the exes in Cygwin

**Installation method:**
The Windows .zip file

**Description of problem:**

I really don't know how to analyse a whole windows drive.
I tried many combinations and different versions of how to write a drive letter. PhysicalDriveX didn't worked either.

I hope you can help me?

**Debug output/tracebacks:**

```
localuser@Computername /cygdrive/d/Software/loganalyse
$ ./log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest4.palso" H:
2016-06-21 09:00:14,198 [DEBUG] (MainProcess) PID:4064 <extraction_frontend> Starting preprocessing.
2016-06-21 09:00:14,209 [DEBUG] (MainProcess) PID:4064 <extraction_frontend> Preprocessing done.
2016-06-21 09:00:14,209 [DEBUG] (MainProcess) PID:4064 <extraction_frontend> Starting extraction in multi process mode.
'2016-06-21 09:00:14,209 [DEBUG] (MainProcess) PID:4064 <multi_process> Starting processes.'
'WARNING:root:Unhandled exception in collector (PID: 6356).
ERROR:root:'ascii' codec can't decode byte 0xe4 in position 53: ordinal not in range(128)'
Traceback (most recent call last):
  File "plaso\multi_processing\multi_process.py", line 286, in _Main
  File "plaso\engine\collector.py", line 124, in Collect
  File "plaso\engine\collector.py", line 105, in _ProcessPathSpec
  File "plaso\engine\collector.py", line 61, in _ProcessFileSystem
  File "plaso\engine\collector.py", line 327, in Collect
  File "plaso\engine\collector.py", line 260, in _ProcessDirectory
  File "site-packages\dfvfs\vfs\file_entry.py", line 336, in IsAllocated
  File "site-packages\dfvfs\vfs\os_file_entry.py", line 147, in _GetStat
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 53: ordinal not in range(128)
2016-06-21 09:00:18,229 [DEBUG] (MainProcess) PID:4064 <multi_process> Processing started.
2016-06-21 09:00:21,739 [ERROR] (MainProcess) PID:4064 <multi_process> Process Collector (PID: 6356) is not functioning correctly. Status code killed.
2016-06-21 09:00:21,739 [WARNING] (MainProcess) PID:4064 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Stopping extraction processes.
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Process: StorageWriter (PID: 824) has been removed from the monitoring list.
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Process: Worker_00 (PID: 8784) has been removed from the monitoring list.
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Process: Collector (PID: 6356) has been removed from the monitoring list.
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Process: Worker_01 (PID: 2812) has been removed from the monitoring list.
2016-06-21 09:00:21,739 [WARNING] (MainProcess) PID:4064 <multi_process> Terminating process: StorageWriter (PID: 824).
2016-06-21 09:00:21,739 [WARNING] (MainProcess) PID:4064 <multi_process> Terminating process: Worker_00 (PID: 8784).
2016-06-21 09:00:21,739 [WARNING] (MainProcess) PID:4064 <multi_process> Terminating process: Worker_01 (PID: 2812).
2016-06-21 09:00:21,739 [DEBUG] (MainProcess) PID:4064 <multi_process> Emptying queues.
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Waiting for process: StorageWriter (PID: 824).
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Process StorageWriter (PID: 824) stopped.
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Waiting for process: Worker_00 (PID: 8784).
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Process Worker_00 (PID: 8784) stopped.
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Waiting for process: Collector (PID: 6356).
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Process Collector (PID: 6356) stopped.
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Waiting for process: Worker_01 (PID: 2812).
2016-06-21 09:00:21,789 [DEBUG] (MainProcess) PID:4064 <multi_process> Process Worker_01 (PID: 2812) stopped.
Checking availability and versions of plaso dependencies.
[OK]


Source path     : H:\
Source type     : directory

Processing started.
Processing completed with errors.

```

**Source data:**

A mounted e01 file with FTK Imager.

**Comment by Onager** [comment]
This looks like a dfVFS issue - I assume you can't process the .e01 directly, because there are two many segments, is that correct?  If you haven't tried running directly on the .e01 though, you should give that a try.

**Comment by Onager** [comment]
It looks like dfVFS is crashing here: https://github.com/log2timeline/dfvfs/blob/20160108/dfvfs/vfs/os_file_entry.py#L147 which is when it's trying to report an un-recoverable error stat'ing the target directory. Given this is a mounted file system, there could be a few different reasons why there's an error trying to stat the file, permissions being my first guess. Are you running as administrator?

When you say that "PhysicalDriveX didn't work either", what exactly, happened, and what command were you running? Were you running that command as administrator?

**Comment by m-terlinde** [comment]
I'll give it a try later or tomorrow with the PhysicalDrive, so I can prompt the output here.
The .e01 file is compressed and ~26 GB. We tried to process it directly, mostly it works.
We got a few errors parsing some of the .evtx files, but I think this is stuff for a new issue. log2timeline is working on the e01 in this moment, so I've to wait for the errors.
There wasn't any outpunt with "segments" as far as I saw last time I checked.

**Comment by joachimmetz** [comment]
> This looks like a dfVFS issue - I assume you can't process the .e01 directly, because there are two many segments, is that correct?

Based on the following output I would say that is not the issue:

```
Source path     : H:\
Source type     : directory
```

I'm wondering if you running under CygWin might confuse the Python interpreter and indicate the wrong file system encoding. Try running log2timeline.exe from a regular command prompt (cmd.exe).

**Comment by m-terlinde** [comment]
If I run it in the cmd.exe I'll get this:

```
D:\Software\loganalyse>log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest7.palso" H:
Checking availability and versions of plaso dependencies.
[OK]


Source path     : H:\
Source type     : directory

Processing started.
2016-06-22 10:16:58,454 [DEBUG] (MainProcess) PID:8000 <extraction_frontend> Starting preprocessing.
2016-06-22 10:16:58,494 [DEBUG] (MainProcess) PID:8000 <extraction_frontend> Preprocessing done.
2016-06-22 10:16:58,494 [DEBUG] (MainProcess) PID:8000 <extraction_frontend> Starting extraction in multi process mode.
2016-06-22 10:16:58,494 [DEBUG] (MainProcess) PID:8000 <multi_process> Starting processes.
WARNING:root:Unhandled exception in collector (PID: 7872).
ERROR:root:'ascii' codec can't decode byte 0xe4 in position 53: ordinal not in range(128)
Traceback (most recent call last):
  File "plaso\multi_processing\multi_process.py", line 286, in _Main
  File "plaso\engine\collector.py", line 124, in Collect
  File "plaso\engine\collector.py", line 105, in _ProcessPathSpec
  File "plaso\engine\collector.py", line 61, in _ProcessFileSystem
  File "plaso\engine\collector.py", line 327, in Collect
  File "plaso\engine\collector.py", line 260, in _ProcessDirectory
  File "site-packages\dfvfs\vfs\file_entry.py", line 336, in IsAllocated
  File "site-packages\dfvfs\vfs\os_file_entry.py", line 147, in _GetStat
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 53: ordinal not in range(128)
2016-06-22 10:17:02,224 [DEBUG] (MainProcess) PID:8000 <multi_process> Processing started.
2016-06-22 10:17:07,755 [DEBUG] (MainProcess) PID:8000 <processing_status> Processing incomplete - extraction still in p
rogress.
Worker_00 (PID: 6620) - events extracted: 36 - file: OS:H:\Config.Msi - running: True <running>
Worker_01 (PID: 6544) - events extracted: 0 - file:  - running: True <running>
2016-06-22 10:17:09,255 [ERROR] (MainProcess) PID:8000 <multi_process> Process Collector (PID: 7872) is not functioning
correctly. Status code killed.
2016-06-22 10:17:09,255 [WARNING] (MainProcess) PID:8000 <multi_process> Processing aborted with engine error: Collector
 unexpectedly terminated.
2016-06-22 10:17:09,255 [DEBUG] (MainProcess) PID:8000 <multi_process> Stopping extraction processes.
2016-06-22 10:17:09,255 [DEBUG] (MainProcess) PID:8000 <multi_process> Process: Collector (PID: 7872) has been removed f
rom the monitoring list.
2016-06-22 10:17:09,255 [DEBUG] (MainProcess) PID:8000 <multi_process> Process: Worker_00 (PID: 6620) has been removed f
rom the monitoring list.
2016-06-22 10:17:09,255 [DEBUG] (MainProcess) PID:8000 <multi_process> Process: Worker_01 (PID: 6544) has been removed f
rom the monitoring list.
2016-06-22 10:17:09,255 [DEBUG] (MainProcess) PID:8000 <multi_process> Process: StorageWriter (PID: 5980) has been remov
ed from the monitoring list.
2016-06-22 10:17:09,255 [WARNING] (MainProcess) PID:8000 <multi_process> Terminating process: Worker_00 (PID: 6620).
2016-06-22 10:17:09,255 [WARNING] (MainProcess) PID:8000 <multi_process> Terminating process: Worker_01 (PID: 6544).
2016-06-22 10:17:09,255 [WARNING] (MainProcess) PID:8000 <multi_process> Terminating process: StorageWriter (PID: 5980).

2016-06-22 10:17:09,265 [DEBUG] (MainProcess) PID:8000 <multi_process> Emptying queues.
2016-06-22 10:17:09,295 [DEBUG] (MainProcess) PID:8000 <multi_process> Waiting for process: Collector (PID: 7872).
2016-06-22 10:17:09,295 [DEBUG] (MainProcess) PID:8000 <multi_process> Process Collector (PID: 7872) stopped.
2016-06-22 10:17:09,295 [DEBUG] (MainProcess) PID:8000 <multi_process> Waiting for process: Worker_00 (PID: 6620).
2016-06-22 10:17:09,305 [DEBUG] (MainProcess) PID:8000 <multi_process> Process Worker_00 (PID: 6620) stopped.
2016-06-22 10:17:09,305 [DEBUG] (MainProcess) PID:8000 <multi_process> Waiting for process: Worker_01 (PID: 6544).
2016-06-22 10:17:09,305 [DEBUG] (MainProcess) PID:8000 <multi_process> Process Worker_01 (PID: 6544) stopped.
2016-06-22 10:17:09,315 [DEBUG] (MainProcess) PID:8000 <multi_process> Waiting for process: StorageWriter (PID: 5980).
2016-06-22 10:17:09,315 [DEBUG] (MainProcess) PID:8000 <multi_process> Process StorageWriter (PID: 5980) stopped.
Processing completed with errors.

```

Recording to [the dfvfs wiki](https://github.com/log2timeline/dfvfs/wiki/Windows-Path-Resolver) I tried the following aswell:

```
D:\Software\loganalyse>log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest7.palso" \.\C:
Checking availability and versions of plaso dependencies.
[OK]

2016-06-22 10:19:34,709 [WARNING] (MainProcess) PID:8032 <<string>> No such device, file or directory: D:\C:.

D:\Software\loganalyse>log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest7.palso" \.\C:\
Checking availability and versions of plaso dependencies.
[OK]

2016-06-22 10:19:42,630 [WARNING] (MainProcess) PID:6536 <<string>> No such device, file or directory: D:\C:.

D:\Software\loganalyse>log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest7.palso" \.\PhysicalDrive0
Checking availability and versions of plaso dependencies.
[OK]

2016-06-22 10:20:13,279 [WARNING] (MainProcess) PID:4760 <<string>> No such device, file or directory: D:\PhysicalDrive0
.
```

**Comment by joachimmetz** [comment]
Try:
```
\\.\PhysicalDrive0
```

**Comment by m-terlinde** [comment]
This works on PhysicalDrive0 (detects all 3 partitions) but not on the mounted E01 image on PhysicalDrive4.
It is mounted with the FTK Imager 3.4.2.2

```
D:\Software\loganalyse>log2timeline.exe -p -d -z "Europe/Berlin" "G:\Log2Timeline\MTE\imagetest7.palso" \\.\PhysicalDriv
e4
Checking availability and versions of plaso dependencies.
[OK]

Traceback (most recent call last):
  File "<string>", line 816, in <module>
  File "<string>", line 802, in Main
  File "<string>", line 691, in ProcessSources
  File "plaso\cli\storage_media_tool.py", line 928, in ScanSource
  File "site-packages\dfvfs\helpers\source_scanner.py", line 564, in Scan
  File "site-packages\dfvfs\helpers\source_scanner.py", line 371, in _ScanNode
  File "site-packages\dfvfs\helpers\source_scanner.py", line 625, in ScanForStorageMediaImage
  File "site-packages\dfvfs\analyzer\analyzer.py", line 324, in GetStorageMediaImageTypeIndicators
  File "site-packages\dfvfs\analyzer\analyzer.py", line 188, in _GetTypeIndicators
  File "site-packages\dfvfs\resolver\resolver.py", line 113, in OpenFileObject
  File "site-packages\dfvfs\file_io\file_io.py", line 73, in open
  File "site-packages\dfvfs\file_io\os_file_io.py", line 100, in _Open
IOError: pysmdev_handle_open: unable to open handle. libsmdev_handle_get_bytes_per_sector: unsupported platform.
log2timeline returned -1
```

Any other ideas to use the drive letter "H" properly for l2t?

**Comment by joachimmetz** [comment]
> IOError: pysmdev_handle_open: unable to open handle. libsmdev_handle_get_bytes_per_sector: unsupported platform.
> log2timeline returned -1

The driver is not behaving like a proper physical drive

> Any other ideas to use the drive letter "H" properly for l2t?

Plaso is not supposed to work with "drive letters", either a proper device or directly on the E01.

You could try use ewfmount to mount the E01 as a RAW image.

**Comment by joachimmetz** [comment]
No update from OP, closing issue.
