### ISSUE TITLE
UnicodeDecodeError in cups parser

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#766]
**Plaso version:** HEAD

```
Traceback (most recent call last):
  File "plaso/multi_processing/multi_process.py", line 1214, in _ProcessTask
    self._parser_mediator, task.path_spec)
  File "plaso/engine/worker.py", line 618, in ProcessPathSpec
    self._ProcessFileEntry(parser_mediator, file_entry)
  File "plaso/engine/worker.py", line 452, in _ProcessFileEntry
    parser_mediator, file_entry, data_stream.name)
  File "plaso/engine/worker.py", line 543, in _ProcessFileEntryDataStream
    parser_mediator, file_entry, data_stream_name=data_stream_name)
  File "plaso/engine/extractors.py", line 252, in ParseDataStream
    parser_mediator, parser, file_entry, file_object=file_object)
  File "plaso/engine/extractors.py", line 187, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "plaso/parsers/cups_ipp.py", line 240, in ParseFileObject
    name, value = self.ReadPair(parser_mediator, file_object)
  File "plaso/parsers/cups_ipp.py", line 329, in ReadPair
    name = self.PAIR_NAME.parse_stream(file_object).text
  File "/usr/lib/python2.7/site-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/lib/python2.7/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/site-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/lib/python2.7/site-packages/construct/adapters.py", line 158, in _decode
    obj = obj.decode(self.encoding)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 28: invalid start byte
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/304720043/
