### ISSUE TITLE
Tests on Travis sometimes failing with zmq.error.Again: Resource temporarily unavailable

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#794]
Might be 2 issues here and seem to be flaky

```
Process Analysis tagging:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/log2timeline/plaso/plaso/analysis/interface.py", line 113, in RunPlugin
    self.ConsumeItems(analysis_mediator=analysis_mediator)
  File "/home/travis/build/log2timeline/plaso/plaso/engine/plaso_queue.py", line 145, in ConsumeItems
    self._ConsumeItem(item, **kwargs)
  File "/home/travis/build/log2timeline/plaso/plaso/analysis/interface.py", line 73, in _ConsumeItem
    self.ExamineEvent(analysis_mediator, item, **kwargs)
  File "/home/travis/build/log2timeline/plaso/plaso/analysis/tagging.py", line 111, in ExamineEvent
    event_tag.AddLabel(matched_tags)
  File "/home/travis/build/log2timeline/plaso/plaso/containers/events.py", line 295, in AddLabel
    if not self._VALID_LABEL_REGEX.match(label):
TypeError: expected string or buffer
```
```
[ERROR] Unnamed unable to push item, raising.
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tools/psort.py", line 676, in <module>
    if not Main():
  File "/home/travis/build/log2timeline/plaso/tools/psort.py", line 671, in Main
    tool.ProcessStorage()
  File "/home/travis/build/log2timeline/plaso/tools/psort.py", line 620, in ProcessStorage
    self._ProcessStorage()
  File "/home/travis/build/log2timeline/plaso/tools/psort.py", line 247, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/home/travis/build/log2timeline/plaso/plaso/frontend/psort.py", line 600, in ProcessStorage
    time_slice=time_slice, use_time_slicer=use_time_slicer)
  File "/home/travis/build/log2timeline/plaso/plaso/frontend/psort.py", line 233, in _ProcessStorage
    time_slice=time_slice)
  File "/home/travis/build/log2timeline/plaso/plaso/frontend/psort.py", line 499, in ProcessEventsFromStorage
    self._AppendEvent(event_object, output_buffer, analysis_queues)
  File "/home/travis/build/log2timeline/plaso/plaso/frontend/psort.py", line 83, in _AppendEvent
    event_queue.ProduceItem(event_object)
  File "/home/travis/build/log2timeline/plaso/plaso/engine/plaso_queue.py", line 180, in ProduceItem
    self._queue.PushItem(item)
  File "/home/travis/build/log2timeline/plaso/plaso/engine/zeromq_queue.py", line 363, in PushItem
    self._zmq_socket.send_pyobj(item)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 329, in send_pyobj
    return self.send(msg, flags)
  File "socket.pyx", line 565, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5263)
  File "socket.pyx", line 612, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5030)
  File "socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2068)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
zmq.error.Again: Resource temporarily unavailable
```

**Comment by joachimmetz** [comment]
Maybe related (during unit tests):
```
ERROR:root:ZMQ syscall interrupted in Worker_00 pathspec. Queue aborting.
ERROR:root:ZMQ syscall interrupted in Worker_01 pathspec. Queue aborting.
ERROR:root:ZMQ syscall interrupted in Worker_02 pathspec. Queue aborting.
ERROR:root:ZMQ syscall interrupted in Worker_03 pathspec. Queue aborting.
```

**Comment by Onager** [comment]
What looks to be happening here is:

- Analysis plugin dies (exception 1)
- Event queue from storage to analysis fills up, and eventually zmq times out trying to add an event to an already full queue (exception 2)

This is looks to be working as intended from a zeromq perspective, but I'm surprised this doesn't crash 100% of the time, and not at all using multiprocessing. We may need to tweak the tests a bit.

**Comment by joachimmetz** [comment]
> This is looks to be working as intended from a zeromq perspective, but I'm surprised this doesn't crash 100% of the time, and not at all using multiprocessing

Might is be related to the blocking behavior of multiprocessing?
