### ISSUE TITLE
Missing protobuf_serializer module ?

### ISSUE THREAD

**Issue by gazbarg** [log2timeline/plaso#803]
**Plaso version:**

1.4.0

**Operating system Plaso is running on:**

Linux Gentoo

**Installation method:**

From ebuilds (and sources). Old ebuilds found and updated to latest releases of plaso and tools.

**Description of problem:**

When starting log2timeline, module protobuf_serializer is not found (from dfvfs).
It is quite possible one of the ebuilds is missing dependencies or such.

**Debug output/tracebacks:**

log2timeline.py -d
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/log2timeline.py", line 25, in <module>
    from plaso.frontend import log2timeline
  File "/usr/lib64/python2.7/site-packages/plaso/frontend/log2timeline.py", line 15, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "/usr/lib64/python2.7/site-packages/plaso/output/__init__.py", line 11, in <module>
    from plaso.output import pstorage
  File "/usr/lib64/python2.7/site-packages/plaso/output/pstorage.py", line 8, in <module>
    from plaso.storage import zip_file
  File "/usr/lib64/python2.7/site-packages/plaso/storage/zip_file.py", line 101, in <module>
    from plaso.serializer import protobuf_serializer
  File "/usr/lib64/python2.7/site-packages/plaso/serializer/protobuf_serializer.py", line 6, in <module>
    from dfvfs.serializer import protobuf_serializer as dfvfs_protobuf_serializer
ImportError: cannot import name protobuf_serializer

**Comment by joachimmetz** [comment]
Protobuf support has been deprecated in dfvfs and in plaso (after 1.4.0)

**Comment by joachimmetz** [comment]
Closing issue no update from OP.

**Comment by gazbarg** [comment]
I'm late in answering. 
Rolling dfvfs back to version 20160108 solved the problem. Thanks.
