### ISSUE TITLE
Zip Storage error: IOError: Permission Denied

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#808]
**Plaso version:**

Plaso: HEAD

Dfvfs: HEAD

**Operating system Plaso is running on:**

64bit Windows 7

**Installation method:**

Development environment

**Description of problem:**

When I run log2timeline I get a Permission Denied Error. This happens consistently on all input I give it.

**Debug output/tracebacks:**

```
(plaso) G:\test_data\Kik>python C:\dev\plaso\tools\log2timeline.py set_3_output2.zip Set_3 -d
Checking availability and versions of plaso dependencies.
[OK]


Source path     : G:\test_data\Kik\Set_3
Source type     : directory

Processing started.
2016-07-15 11:21:51,963 [DEBUG] (MainProcess) PID:4224 <extraction_frontend> Starting preprocessing.
2016-07-15 11:21:52,009 [DEBUG] (MainProcess) PID:4224 <extraction_frontend> Preprocessing done.
2016-07-15 11:21:52,025 [DEBUG] (MainProcess) PID:4224 <extraction_frontend> Starting extraction in multi process mode.
2016-07-15 11:21:52,134 [DEBUG] (MainProcess) PID:4224 <zeromq_queue> Task queue bound to random port 49585
2016-07-15 11:21:52,211 [DEBUG] (MainProcess) PID:4224 <zeromq_queue> ZeroMQ responder thread started
2016-07-15 11:22:05,489 [DEBUG] (MainProcess) PID:4224 <zip_file> Writing to ZIP file with buffer size: 205520896
2016-07-15 11:22:05,536 [DEBUG] (MainProcess) PID:4224 <engine> Task scheduler started
Worker_00 (PID: 348) - events extracted: 76 - file: OS:G:\test_data\Kik\Set_3\Library\Caches\com.kik.chat\com.apple.open
gl - running: True
Worker_01 (PID: 5248) - events extracted: 41 - file: OS:G:\test_data\Kik\Set_3\Documents\smiley_storage\smileys - runnin
g: True
Worker_02 (PID: 5148) - events extracted: 34 - file: OS:G:\test_data\Kik\Set_3\Library\Caches\com.kik.chat\Cache.db - ru
nning: True
Worker_03 (PID: 1552) - events extracted: 3 - file: OS:G:\test_data\Kik\Set_3\Kik-Release-8.7.0.1913.app - running: True

Worker_04 (PID: 224) - events extracted: 59 - file: OS:G:\test_data\Kik\Set_3\Documents\content_manager\data_cache\e5646
50e-b865-402a-9284-22ed16439a35 - running: True
Worker_05 (PID: 5544) - events extracted: 67 - file: OS:G:\test_data\Kik\Set_3\Documents\content_manager\data_cache\8b54
6625-48cd-4ed9-95fa-1d1f51512f9b - running: True
Worker_06 (PID: 6120) - events extracted: 105 - file: OS:G:\test_data\Kik\Set_3\Documents\content_manager\data_cache\5f8
4a69e-1dac-4baa-a781-c33af02c285c - running: True
Traceback (most recent call last):
  File "C:\dev\plaso\tools\log2timeline.py", line 803, in <module>
    if not Main():
  File "C:\dev\plaso\tools\log2timeline.py", line 789, in Main
    tool.ProcessSources()
  File "C:\dev\plaso\tools\log2timeline.py", line 699, in ProcessSources
    timezone=self._timezone)
  File "C:\dev\plaso\plaso\frontend\extraction_frontend.py", line 539, in ProcessSources
    text_prepend=self._text_prepend)
  File "C:\dev\plaso\plaso\multi_processing\engine.py", line 971, in ProcessSources
    filter_find_specs=filter_find_specs)
  File "C:\dev\plaso\plaso\multi_processing\engine.py", line 350, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File "C:\dev\plaso\plaso\multi_processing\engine.py", line 505, in _ScheduleTasks
    if storage_writer.MergeTaskStorage(task_identifier):
  File "C:\dev\plaso\plaso\storage\zip_file.py", line 3343, in MergeTaskStorage
    storage_reader = ZIPStorageFileReader(storage_file_path)
  File "C:\dev\plaso\plaso\storage\zip_file.py", line 3057, in __init__
    self._storage_file.Open(path=input_file)
  File "C:\dev\plaso\plaso\storage\zip_file.py", line 2833, in Open
    self._OpenZIPFile(path, read_only)
  File "C:\dev\plaso\plaso\storage\zip_file.py", line 1742, in _OpenZIPFile
    allowZip64=True)
  File "C:\Python27\Lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 13] Permission denied: u'tmp70uzqj\\merge\\94d6406c81bf42589652b0dc5a2db337.plaso'
```

**Comment by joachimmetz** [comment]
Fix already pending in: https://codereview.appspot.com/307790043/diff/60001/plaso/storage/zip_file.py

**Comment by joachimmetz** [comment]
This is a Windows specific issue BTW.

**Comment by dc3-plaso** [comment]
I figured. Windows get all the fun. :unamused:

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/d2259b9021c6e8d2c3bd5266fa7f19034398d5cb
