### ISSUE TITLE
Knowledge base incorrectly references user_account.name

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#828]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

Dev install

**Description of problem:**

Psort has an unhandled exception when trying to read a systemconfigurationartifact.

**Debug output/tracebacks:**
```
Traceback (most recent call last):
  File "./tools/psort.py", line 675, in <module>
    if not Main():
  File "./tools/psort.py", line 670, in Main
    tool.ProcessStorage()
  File "./tools/psort.py", line 619, in ProcessStorage
    self._ProcessStorage()
  File "./tools/psort.py", line 249, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/tmp/jenkins/workspace/plaso_acserver_end_to_end/plaso/frontend/psort.py", line 540, in ProcessStorage
    time_slice=time_slice, use_time_slicer=use_time_slicer)
  File "/tmp/jenkins/workspace/plaso_acserver_end_to_end/plaso/frontend/psort.py", line 276, in _ProcessStorage
    storage_file.ReadPreprocessingInformation(self._knowledge_base)
  File "/tmp/jenkins/workspace/plaso_acserver_end_to_end/plaso/storage/zip_file.py", line 2940, in ReadPreprocessingInformation
    stream_number, system_configuration)
  File "/tmp/jenkins/workspace/plaso_acserver_end_to_end/plaso/engine/knowledge_base.py", line 266, in ReadSystemConfigurationArtifact
    for user_account in system_configuration.user_accounts}
  File "/tmp/jenkins/workspace/plaso_acserver_end_to_end/plaso/engine/knowledge_base.py", line 266, in <dictcomp>
    for user_account in system_configuration.user_accounts}
AttributeError: 'UserAccountArtifact' object has no attribute 'name'
```

**Source data:**

Linux test image

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/304170043/
