### ISSUE TITLE
Status update thread dies due to produced sources being less than last update.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#830]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

Dev install

**Description of problem:**

Status update thread dies due to produced sources being less than last update.

**Debug output/tracebacks:**
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/multi_processing/engine.py", line 688, in _StatusUpdateThreadMain
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/multi_processing/engine.py", line 225, in _CheckStatusWorkerProcess
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/multi_processing/engine.py", line 865, in _UpdateProcessingStatus
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/engine/processing_status.py", line 321, in UpdateWorkerStatus
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/engine/processing_status.py", line 236, in _UpdateProcessStatus
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1_20160717-py2.7.egg/plaso/engine/processing_status.py", line 166, in UpdateNumberOfEventSources
ValueError: Number of produced sources smaller than previous update.
```
**Source data:**

student-pc1.dd test image

**Comment by joachimmetz** [comment]
Hmm, need to dive into why this is happening. Is this on the same machine as https://github.com/log2timeline/plaso/issues/829 ?

**Comment by Onager** [comment]
No, different machine (and different user, even!)

**Comment by Onager** [comment]
Thought about this - perhaps this occurring due to the items being missing from the status dictionary? Ref: 
https://github.com/log2timeline/plaso/blob/eec5cb44ac7ad232791dba32bb3796384fc2c83e/plaso/multi_processing/engine.py#L858

**Comment by joachimmetz** [comment]
That could very well be.
