### ISSUE TITLE
selinux parser produces unserializable values

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#836]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

Dev install

**Description of problem:**

Worker has an unhandled exception.

**Debug output/tracebacks:**

```
2016-07-21 12:52:47,488 [WARNING] (Worker_01 ) PID:8090 <worker_process> Unhandled exception while processing path spec: OS:/home/onager/code/plaso_onager/test_data/selinux.log.
2016-07-21 12:52:47,489 [ERROR] (Worker_01 ) PID:8090 <worker_process> ([u'UNKNOWN[', u'1323', u']'], {u'key': [(u'type', 0)], u'value': [(u'UNKNOWN[', 0)]}) is not JSON serializable
Traceback (most recent call last):
  File "/home/onager/code/plaso_onager/plaso/multi_processing/worker_process.py", line 245, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/home/onager/code/plaso_onager/plaso/engine/worker.py", line 679, in ProcessPathSpec
    self._ProcessFileEntry(parser_mediator, file_entry)
  File "/home/onager/code/plaso_onager/plaso/engine/worker.py", line 540, in _ProcessFileEntry
    parser_mediator, file_entry, data_stream.name)
  File "/home/onager/code/plaso_onager/plaso/engine/worker.py", line 629, in _ProcessFileEntryDataStream
    parser_mediator, file_entry, data_stream_name)
  File "/home/onager/code/plaso_onager/plaso/engine/extractors.py", line 248, in ParseDataStream
    parser_mediator, parser, file_entry, file_object=file_object)
  File "/home/onager/code/plaso_onager/plaso/engine/extractors.py", line 185, in _ParseFileEntryWithParser
    parser.Parse(parser_mediator, file_object)
  File "/home/onager/code/plaso_onager/plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/home/onager/code/plaso_onager/plaso/parsers/text_parser.py", line 477, in ParseFileObject
    parser_mediator, use_key, parsed_structure)
  File "/home/onager/code/plaso_onager/plaso/parsers/selinux.py", line 151, in ParseRecord
    parser_mediator.ProduceEvent(event_object)
  File "/home/onager/code/plaso_onager/plaso/parsers/mediator.py", line 488, in ProduceEvent
    self._storage_writer.AddEvent(event_object)
  File "/home/onager/code/plaso_onager/plaso/storage/zip_file.py", line 2903, in AddEvent
    self._storage_file.AddEvent(event)
  File "/home/onager/code/plaso_onager/plaso/storage/gzip_file.py", line 110, in AddEvent
    self._WriteAttributeContainer(event)
  File "/home/onager/code/plaso_onager/plaso/storage/gzip_file.py", line 84, in _WriteAttributeContainer
    attribute_container)
  File "/home/onager/code/plaso_onager/plaso/storage/interface.py", line 237, in _SerializeAttributeContainer
    attribute_container)
  File "/home/onager/code/plaso_onager/plaso/serializer/json_serializer.py", line 421, in WriteSerialized
    return json.dumps(json_dict)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ([u'UNKNOWN[', u'1323', u']'], {u'key': [(u'type', 0)], u'value': [(u'UNKNOWN[', 0)]}) is not JSON serializable
```

**Source data:**

selinux.log from test_data

**Comment by joachimmetz** [comment]
```
{'body': u'fd=6 flags=0x802', 'username': u'-', 'audit_type': ([u'UNKNOWN[', u'1323', u']'], {u'key': [(u'type', 0)], u'value': [(u'UNKNOWN[', 0)]}), 'sha256_hash': u'73704381a54be840bdae7866609c36069d3da314f639879dabddb82450c16d4c', 'display_name': u'OS:plaso/test_data/selinux.log', 'uuid': u'567309a64a984a528894f6fbf82b08b1', 'data_type': u'selinux:line', 'timestamp': 1389164020991000, 'parser': u'selinux', 'filename': u'plaso/test_data/selinux.log', 'timestamp_desc': u'Content Modification Time', 'offset': 0, 'pathspec': <dfvfs.path.os_path_spec.OSPathSpec object at 0x7f1dca9f5550>}
```
