### ISSUE TITLE
ZeroMQ on Windows causes pickle error

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#878]
**Plaso version:** HEAD

Windows XP (32-bit) and 7 (64-bit)

pyzqm: 15.3.0

```
TypeError: can't pickle thread.lock objects.
```

**Comment by Onager** [comment]
Any more context on where this is happening? psort, l2t.py? Some time during extraction?

I take it that this doesn't occur with the multiprocessing queue on.

Other references to this error message suggest that this is often raised by multiprocessing. Perhaps a passing a queue with an open thread as an arg to a new process creation?

**Comment by Onager** [comment]
OK, that description is consistent with my theory as to why this happening. Moved synchronization event creation to after queue open.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/301470043/

**Comment by joachimmetz** [comment]
```
Tests the ProcessSources function. ... Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "c:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "c:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "c:\Python27\lib\pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "c:\Python27\lib\pickle.py", line 1130, in find_class
    __import__(module)
  File ".\plaso\multi_processing\worker_process.py", line 11, in <module>
    from plaso.engine import worker
  File ".\plaso\engine\worker.py", line 18, in <module>
    from plaso.engine import extractors
  File ".\plaso\engine\extractors.py", line 19, in <module>
    from plaso.parsers import interface as parsers_interface
  File ".\plaso\parsers\__init__.py", line 52, in <module>
    from plaso.parsers import winreg
  File ".\plaso\parsers\winreg.py", line 6, in <module>
    from dfwinreg import errors as dfwinreg_errors
ImportError: cannot import name errors
WARNING:root:queuestart_ZeroMQBufferedPushBindQueue could not send an item
```

```
======================================================================
ERROR: testProcessSources (multi_processing.task_engine.TaskMultiProcessEngineTest)
Tests the PreprocessSources and ProcessSources function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Projects\plaso\tests\multi_processing\task_engine.py", line 42, in te
stProcessSources
    parser_filter_expression=u'filestat')
  File ".\plaso\multi_processing\task_engine.py", line 649, in ProcessSources
    self._StartMonitoringProcess(extraction_process.pid)
  File ".\plaso\multi_processing\engine.py", line 320, in _StartMonitoringProcess
    pid))
IOError: RPC client unable to determine server (PID: 5108) port.
```
