### ISSUE TITLE
utils/check_dependencies.py raise OSError on yara check if python-yara not installed

### ISSUE THREAD

**Issue by ghost** [log2timeline/plaso#887]
**Plaso version:**

20160731 and HEAD as of now

**Operating system Plaso is running on:**

Ubuntu 16.04LTS

Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Installation method:**

git clone plaso
Install deps via git clone or download source or apt install.

**Description of problem:**

python utils/check_dependencies.py crashes on yara check

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

```
$ python utils/check_dependencies.py 
Checking availability and versions of dependencies.
[OK]        artifacts version: 20160713
[OK]        bencode
[OK]        binplist version: 0.1.5
[OK]        construct version: 2.5.2
[OK]        dateutil version: 2.5.3
[OK]        dfdatetime version: 20160801
[OK]        dfvfs version: 20160803
[OK]        dfwinreg version: 20160801
[OK]        dpkt version: 1.8
[OK]        efilter
[OK]        hachoir_core version: 1.3.3
[OK]        hachoir_metadata version: 1.3.3
[OK]        hachoir_parser version: 1.3.4
[FAILURE]   missing: IPython.
[OK]        pefile version: 2016.3.28
[OK]        psutil version: 4.3.0
[OK]        pyparsing version: 2.1.5
[OK]        pytz
[OK]        requests version: 2.9.1
[OK]        six version: 1.10.0
[OK]        xlsxwriter version: 0.9.3
[OK]        yaml version: 3.11
Failed to import '/usr/lib/libyara.so'
PATH = /home/dfa/bin:/home/dfa/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;/usr/lib
Traceback (most recent call last):
  File "utils/check_dependencies.py", line 15, in <module>
    if not plaso.dependencies.CheckDependencies(latest_version_check=True):
  File "./plaso/dependencies.py", line 440, in CheckDependencies
    verbose_output=verbose_output):
  File "./plaso/dependencies.py", line 195, in _CheckPythonModule
    module_object = _ImportPythonModule(module_name)
  File "./plaso/dependencies.py", line 411, in _ImportPythonModule
    module_object = list(map(__import__, [module_name]))[0]
  File "/usr/local/lib/python2.7/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python2.7/dist-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory

# apt install python-yara
.....

$ python utils/check_dependencies.py 
Checking availability and versions of dependencies.
[OK]        artifacts version: 20160713
[OK]        bencode
[OK]        binplist version: 0.1.5
[OK]        construct version: 2.5.2
[OK]        dateutil version: 2.5.3
[OK]        dfdatetime version: 20160801
[OK]        dfvfs version: 20160803
[OK]        dfwinreg version: 20160801
[OK]        dpkt version: 1.8
[OK]        efilter
[OK]        hachoir_core version: 1.3.3
[OK]        hachoir_metadata version: 1.3.3
[OK]        hachoir_parser version: 1.3.4
[FAILURE]   missing: IPython.
[OK]        pefile version: 2016.3.28
[OK]        psutil version: 4.3.0
[OK]        pyparsing version: 2.1.5
[OK]        pytz
[OK]        requests version: 2.9.1
[OK]        six version: 1.10.0
[OK]        xlsxwriter version: 0.9.3
[OK]        yaml version: 3.11
[FAILURE]   unable to determine version information for: yara
[OK]        zmq version: 15.3.0
[OK]        sqlite3 version: 3.11.0
[OK]        SleuthKit version: 4.3.0
[OK]        pytsk3 version: 20160721
```

**Comment by joachimmetz** [comment]
This looks like an issue caused by the build of yara-python linking to libyara which is not present. How did you build/install yara-python?

**Comment by NZC-2270116** [comment]
After further investigation, it is partially a yara problem but there is still a plaso issue.

This was the PyPi version of yara.  I determined that "yara-ctypes -h" also crashed which obviously wasn't a l2t issue.  Removing the PyPi version of yara and building yara-1.7.7 from source got me a working yara-ctypes.

But now that is fixed utils/check_dependancies.py still fails on yara because it is unable to determine version information:

```
$ yara-ctypes --version
yara-ctypes version 1.7.7

$ python utils/check_dependencies.py 
Checking availability and versions of dependencies.
[OK]		artifacts version: 20160713
[OK]		bencode
[OK]		binplist version: 0.1.5
[OK]		construct version: 2.5.2
[OK]		dateutil version: 2.5.3
[OK]		dfdatetime version: 20160801
[OK]		dfvfs version: 20160803
[OK]		dfwinreg version: 20160801
[OK]		dpkt version: 1.8
[OK]		efilter
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_metadata version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
[OK]		IPython version: 2.4.1
[OK]		pefile version: 2016.3.28
[OK]		psutil version: 4.3.0
[OK]		pyparsing version: 2.1.5
[OK]		pytz
[OK]		requests version: 2.9.1
[OK]		six version: 1.10.0
[OK]		xlsxwriter version: 0.9.3
[OK]		yaml version: 3.11
[FAILURE]	unable to determine version information for: yara
[OK]		zmq version: 15.3.0
[OK]		sqlite3 version: 3.11.0
[OK]		SleuthKit version: 4.3.0
[OK]		pytsk3 version: 20160721
[OK]		libbde (pybde) version: 20160731
[OK]		libesedb (pyesedb) version: 20160622
[OK]		libevt (pyevt) version: 20160421
[OK]		libevtx (pyevtx) version: 20160421
[INFO]		libewf (pyewf) version: 20140608 installed, version: 20160424 available.
[OK]		libfsntfs (pyfsntfs) version: 20160418
[OK]		libfwsi (pyfwsi) version: 20160110
[OK]		liblnk (pylnk) version: 20160420
[OK]		libmsiecf (pymsiecf) version: 20160421
[OK]		libolecf (pyolecf) version: 20160423
[OK]		libqcow (pyqcow) version: 20160123
[OK]		libregf (pyregf) version: 20160424
[OK]		libscca (pyscca) version: 20160108
[OK]		libsigscan (pysigscan) version: 20160312
[OK]		libsmdev (pysmdev) version: 20160320
[OK]		libsmraw (pysmraw) version: 20160424
[OK]		libvhdi (pyvhdi) version: 20160424
[OK]		libvmdk (pyvmdk) version: 20160119
[OK]		libvshadow (pyvshadow) version: 20160110

```

That failure on yara is enough to stop l2t from running at all.  It knows yara is there, otherwise it reports "missing".

**Comment by joachimmetz** [comment]
We don't support yara-ctypes that's the cause of the version check failing. You'll need yara-python from virus total.

L2t has a flag to skip the version check, but that is **only** recommended if you know what you are doing.

Also this is not a crash but an exception raising as expected.

**Comment by Onager** [comment]
Plaso doesn't use Yara-ctypes (https://pypi.python.org/pypi/yara) it uses
Yara-python (https://pypi.python.org/pypi/yara-python).

The name collision is a little unfortunate.

-Daniel

**Comment by boonlia** [comment]
For me "pip install yara-python --upgrade" did the trick. It worked well.
