### ISSUE TITLE
psort.py timesketch output module disable

### ISSUE THREAD

**Issue by Itaykr** [log2timeline/plaso#903]
**Plaso version:**

log2timline 1.4.1_20160719

**Operating system Plaso is running on:**

Ubuntu 15.04

**Installation method:**

git clone and dependencies install.

**Description of problem:**

Hi, I've installed timesketch yesterday and im trying to use psort.py timesketch output module. but after running psory.py -o list, timesketch is under the disabled output modules.
How can i enable the module?

**Comment by Itaykr** [comment]
So i fixed this using pip install timesketch. but now using psory.py -o timesketch plaso.dump i get the following exception:
```
[WARNING] Storage file does not contain a metadata stream.
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.1.post20160719', 'psort.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 675, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 670, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 619, in ProcessStorage
    self._ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 249, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/frontend/psort.py", line 528, in ProcessStorage
    storage_file.Open(path=self._storage_file_path, read_only=read_only)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/storage/zip_file.py", line 2663, in Open
    self._OpenRead()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/storage/zip_file.py", line 1591, in _OpenRead
    stored_serialization_format = self._ReadSerializerStream()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/storage/zip_file.py", line 1776, in _ReadSerializerStream
    serialization_format))
ValueError: Unsupported stored serialization format: proto

```

**Comment by joachimmetz** [comment]
How did you create the plaso file? We removed protobuf support from the 1.4.1 development version and only support JSON now.

**Comment by Itaykr** [comment]
so i used a timeline generated by old version. i've generated new timeline that use JSON and now using psort.py raise the following exception:
```

Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.4.1.post20160719', 'psort.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 675, in <module>
    if not Main():
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 670, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 619, in ProcessStorage
    self._ProcessStorage()
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/EGG-INFO/scripts/psort.py", line 249, in _ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/frontend/psort.py", line 540, in ProcessStorage
    time_slice=time_slice, use_time_slicer=use_time_slicer)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/frontend/psort.py", line 276, in _ProcessStorage
    storage_file.ReadPreprocessingInformation(self._knowledge_base)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/storage/zip_file.py", line 2691, in ReadPreprocessingInformation
    stream_number, system_configuration)
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/engine/knowledge_base.py", line 233, in ReadSystemConfigurationArtifact
    for user_account in system_configuration.user_accounts}
  File "/usr/local/lib/python2.7/dist-packages/plaso-1.4.1.post20160719-py2.7.egg/plaso/engine/knowledge_base.py", line 233, in <dictcomp>
    for user_account in system_configuration.user_accounts}
AttributeError: 'UserAccountArtifact' object has no attribute 'name'
```

while log2timeline analyzed the image there was several errors. this is the output of log2timeline:
```
2016-08-09 17:47:46,360 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_05 (PID: 26722).
2016-08-09 17:47:46,360 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_06 (PID: 26726).
2016-08-09 17:47:46,361 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_00 (PID: 26701).
2016-08-09 17:47:46,361 [ERROR] (Worker_05 ) PID:26722 <zeromq_queue> ZMQ syscall interrupted in Worker_05 pathspec. Queue aborting.
2016-08-09 17:47:46,361 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_01 (PID: 26705).
2016-08-09 17:47:46,361 [ERROR] (Worker_06 ) PID:26726 <zeromq_queue> ZMQ syscall interrupted in Worker_06 pathspec. Queue aborting.
2016-08-09 17:47:46,361 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_02 (PID: 26709).
2016-08-09 17:47:46,361 [ERROR] (Worker_00 ) PID:26701 <zeromq_queue> ZMQ syscall interrupted in Worker_00 pathspec. Queue aborting.
2016-08-09 17:47:46,361 [ERROR] (Worker_01 ) PID:26705 <zeromq_queue> ZMQ syscall interrupted in Worker_01 pathspec. Queue aborting.
2016-08-09 17:47:46,362 [ERROR] (Worker_02 ) PID:26709 <zeromq_queue> ZMQ syscall interrupted in Worker_02 pathspec. Queue aborting.
2016-08-09 17:47:46,362 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_03 (PID: 26713).
2016-08-09 17:47:46,363 [WARNING] (MainProcess) PID:26692 <engine> Terminating process: Worker_04 (PID: 26718).
2016-08-09 17:47:46,363 [ERROR] (Worker_03 ) PID:26713 <zeromq_queue> ZMQ syscall interrupted in Worker_03 pathspec. Queue aborting.
2016-08-09 17:47:46,363 [ERROR] (Worker_04 ) PID:26718 <zeromq_queue> ZMQ syscall interrupted in Worker_04 pathspec. Queue aborting.
Processing completed.
Number of errors encountered while extracting events: 3.

Use pinfo to inspect errors in more detail.
```

**Comment by Itaykr** [comment]
After searching for the exception in the issues section i found you already patch this issue. i manually patch the file according to https://github.com/log2timeline/plaso/issues/828.

now im facing new issue. psort is running and adding events but after 143000 event it freeze and my machine become very slow. there is a log or something i can use?

**Comment by Onager** [comment]
This is https://github.com/log2timeline/plaso/issues/828 which has been fixed.

**Comment by Onager** [comment]
You're using an old version of the Plaso dev version, so there's not much we can do to help here. Notably, psort has been heavily refactor since July. Also, from the psort help output:

```
Informational Arguments:
  --logfile FILENAME, --log_file FILENAME, --log-file FILENAME
                        If defined all log messages will be redirected to this
                        file instead the default STDERR.
  -d, --debug           enable debug output.
```

**Comment by Itaykr** [comment]
1.4.1 is an old version?

**Comment by Onager** [comment]
#828 was fixed 22 days ago, and you can see the commits to master since 2016-07-19 here: https://github.com/log2timeline/plaso/commits/master. There are quite a few, and some large refactors of psort specifically.

You mentioned installing by git clone - pull the latest version, see how that goes. For context, we're currently working towards a 1.5.0 stable release.

**Comment by Itaykr** [comment]
OK, thanks!
