### ISSUE TITLE
Handle absence of -w in psort.py more gracefully

### ISSUE THREAD

**Issue by daniel-ayers** [log2timeline/plaso#919]
1.5 RC1 from GIFT PPA on Ubuntu 14.04LTS 64 bit

Lack of '-w' on psort.py command line is caught late and causes an untidy traceback:

```
root@l2t-test:~# psort.py results/winxp2.plaso 
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 821, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 816, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 691, in ProcessStorage
    u'is no longer supported.').format(self._output_format))
plaso.lib.errors.BadConfigOption: Output format: dynamic requires an output file, output to stdout is no longer supported.
```

Since there is already checking of some/many invalid parameter combinations in the front end, shouldn't this be caught earlier and lead to a tidier error message - something like this:

```
root@l2t-test:~# psort.py --status_view blarg
usage: psort.py [-h] [-V] [--analysis PLUGIN_LIST] [--use_zeromq CHOICE]
                [--logfile FILENAME] [-d] [-q] [--status_view TYPE]
                [--slice DATE] [--slice_size SLICE_SIZE] [--slicer]
                [--data PATH] [-a] [--language LANGUAGE] [-o FORMAT]
                [-w OUTPUTFILE] [-z TIMEZONE]
                [STORAGE_FILE] [FILTER]
psort.py: error: argument --status_view/--status-view: invalid choice: 'blarg' (choose from u'linear', u'none', u'window')
```

Many users are likely to encounter this situation and the traceback may (unfairly) reduce confidence in the tool.

**Comment by joachimmetz** [comment]
Thanks for the feedback, we could catch the BadConfigOption and print the reason as a single line for better UX.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/302510043/
