### ISSUE TITLE
Issues with the Chrome Preferences parser

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#92]
While parsing a test disk image:

    2015-01-21 14:12:27,699 [WARNING] (Worker_1  ) PID:731 <worker> [chrome_preferences] Unable to process file: type: OS, location: /PATHtest_images/win7-64-nfury-10.3.58.6/win7-64-nfury-c-drive/win7-64-nfury-c-drive.E01
    type: EWF
    type: TSK, inode: 80707, location: /Users/nfury/AppData/Local/Google/Chrome/User Data/Default/Preferences
     with error: int() can't convert non-string with explicit base.

    2015-01-21 14:12:27,699 [ERROR] (Worker_1  ) PID:731 <worker> int() can't convert non-string with explicit base
    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/plaso/engine/worker.py", line 126, in _ParseFileEntryWithParser
        parser_object.Parse(self._parser_context, file_entry)
      File "build/bdist.linux-x86_64/egg/plaso/parsers/chrome_preferences.py", line 138, in Parse
        extensions_dict):
      File "build/bdist.linux-x86_64/egg/plaso/parsers/chrome_preferences.py", line 64, in _ExtractExtensionInstallationEvents
        install_time = int(extension.get(u'install_time', 0), 10)
    TypeError: int() can't convert non-string with explicit base

The relevant bit being:

*install_time = int(**extension.get(u'install_time', 0)**, 10)
**TypeError: int() can't convert non-string with explicit base***

This is something I should have caught... if there is no install time you get a 0 (an integer) back from the extension.get call. And the integer 0 cannot be casted to an integer, since it is already an integer.... better approach

install_time = int(extension.get(u'install_time', **u'0'**), 10)

**Comment by kiddinn** [comment]
https://codereview.appspot.com/193410043/
