### ISSUE TITLE
log2timeline.py quits before completion; can't find storage file

### ISSUE THREAD

**Issue by slo-sleuth** [log2timeline/plaso#942]
**Plaso version:**

plaso - log2timeline version 1.4.1_20160809

**Operating system Plaso is running on:**

Platform:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

Image: 
Acquiry information
    Operating system used:  Linux
    Software version used:  20140608
    Password:       N/A

EWF information
    File format:        EnCase 6
    Sectors per chunk:  64
    Error granularity:  64
    Compression method: deflate
    Compression level:  best compression
    Set identifier:     81c7e817-8bfe-7949-ac00-c0ff0e5a47ac

**Installation method:**

ppa:gift/dev

**Description of problem:**

log2timeline.py quits with an unhandled exception before completing processing.

Command line arguments : /usr/bin/log2timeline.py image.plaso 
                             image_153080.E01 --no_vss --partition 4 -d
                             --logfile plaso.log

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

```
2016-08-22 16:42:31,009 [DEBUG] (Worker_00 ) PID:12271 <worker> [ProcessFileEntry] processing file entry: TSK:/ProgramData/ASUS WebStorage
2016-08-22 16:42:31,010 [DEBUG] (Worker_00 ) PID:12271 <worker> [ProcessFileEntry] done processing file entry: TSK:/ProgramData/ASUS WebStorage
2016-08-22 16:42:31,029 [WARNING] (Worker_00 ) PID:12271 <worker_process> Unhandled exception in process: Worker_00 (PID: 12271).
2016-08-22 16:42:31,029 [ERROR] (Worker_00 ) PID:12271 <worker_process> [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/worker_process.py", line 200, in _Main
    self._ProcessTask(task)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/worker_process.py", line 301, in _ProcessTask
    self._storage_writer.PrepareMergeTaskStorage(task.identifier)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 3180, in PrepareMergeTaskStorage
    os.rename(storage_file_path, merge_storage_file_path)
OSError: [Errno 2] No such file or directory
2016-08-22 16:42:31,030 [DEBUG] (Worker_00 ) PID:12271 <worker_process> Worker: Worker_00 (PID: 12271) stopped
2016-08-22 16:42:31,030 [WARNING] (Worker_00 ) PID:12271 <zeromq_queue> Worker_00 task queue queue aborting. Contents may be lost.
2016-08-22 16:42:36,124 [DEBUG] (Worker_00 ) PID:12271 <base_process> Process: Worker_00 process status RPC server stopped
2016-08-22 16:42:36,124 [DEBUG] (Worker_00 ) PID:12271 <base_process> Process: Worker_00 (PID: 12271) stopped
```

**Source data:**

DD image of a Win8 Tablet PC acquired by Linux boot disc.  DD image was converted to EWF.

The following partitions were found:
Identifier  Offset (in bytes)   Size (in bytes)
p1      1048576 (0x00100000)    100.0MiB / 104.9MB (104857600 B)
p2      105906176 (0x06500000)  900.0MiB / 943.7MB (943718400 B)
p3      1049624576 (0x3e900000) 128.0MiB / 134.2MB (134217728 B)
p4      1183842304 (0x46900000) 49.1GiB / 52.8GB (52762247168 B)
p5      53946089472 (0xc8f700000)   8.0GiB / 8.6GB (8589934592 B)

**Comment by joachimmetz** [comment]
Add an exception handler for the OSError but any idea/indication what could be causing the the task file to be missing?

**Comment by joachimmetz** [comment]
Happens in one of the tests as well

```
Tests the PreprocessSources and ProcessSources function. ... Process tagging:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./plaso/multi_processing/base_process.py", line 200, in run
    self._Main()
  File "./plaso/multi_processing/analysis_process.py", line 155, in _Main
    self._storage_writer.PrepareMergeTaskStorage(task.identifier)
  File "./plaso/storage/zip_file.py", line 3214, in PrepareMergeTaskStorage
    u'{1:s}').format(storage_file_path, exception))
IOError: Unable to rename task storage file: /tmp/tmpAmkVpO/tmpgA84vN/tagging.plaso with error: [Errno 2] No such file or directory
```

**Comment by slo-sleuth** [comment]
No, I haven't been able to identify why the task file goes missing.  The error happens after quite a bit of processing, so stepping though pdb is time prohibitive.

**Comment by joachimmetz** [comment]
Can you check with the release 1.5.0, this might have been addressed.

**Comment by slo-sleuth** [comment]
I no longer have access to the device that caused the errors, but I've run
1.4 and now 1.5 on a new device.  1.4 completed with errors, those that I
could observe were gzip compression issues.  1.5 has not completed but is
not throwing the same errors.  Let's assume you got it with this version,
since I can't test, and I'll repost if it occurs again.

**Comment by slo-sleuth** [comment]
Plaso 1.5 halted, writing a dump file and removing one of two temp folders,
but the process did not close and I received the following traceback (not
the same issue, obviously):

Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 767, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 753, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 664, in ProcessSources
    timezone=self._timezone, yara_rules_string=self._yara_rules_string)
  File
"/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py",
line 483, in ProcessSources
    yara_rules_string=yara_rules_string)
  File
"/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py",
line 791, in ProcessSources
    filter_find_specs=filter_find_specs)
  File
"/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py",
line 288, in _ProcessSources
    self._ScheduleTasks(storage_writer)
  File
"/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py",
line 419, in _ScheduleTasks
    self._FillEventSourceHeap(storage_writer, event_source_heap)
  File
"/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py",
line 351, in _FillEventSourceHeap
    event_source = storage_writer.GetNextWrittenEventSource()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line
3175, in GetNextWrittenEventSource
    self._written_event_source_index)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line
2582, in GetEventSourceByIndex
    offset_table = self._GetSerializedEventSourceOffsetTable(stream_number)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line
1443, in _GetSerializedEventSourceOffsetTable
    u'event_source_index', stream_number)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line
1375, in _GetSerializedDataOffsetTable
    lfu_stream_number = self._event_offset_tables_lfu.pop()
IndexError: pop from empty list

I had executed plaso with this command and chose to iterate over three
shadow volumes in a Win 7 system.:

sudo log2timeline.py --parsers webhist plaso.dump /dev/sdk2

**Comment by vonnopsled** [comment]
My coworker ran into a similar error:

```
command: log2timeline.py output.plaso '/mnt/hgfs/GDrive_Forensics_1/test/disk16/test.00001'

Traceback (most recent call last):
 File "/usr/bin/log2timeline.py", line 767, in <module>
   if not Main():
 File "/usr/bin/log2timeline.py", line 753, in Main
   tool.ProcessSources()
 File "/usr/bin/log2timeline.py", line 664, in ProcessSources
   timezone=self._timezone, yara_rules_string=self._yara_rules_string)
 File "/usr/lib/python2.7/dist-packages/plaso/frontend/extraction_frontend.py", line 483, in ProcessSources
   yara_rules_string=yara_rules_string)
 File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/task_engine.py", line 783, in ProcessSources
   storage_writer.Open()
 File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 3203, in Open
   self._storage_file.GetNumberOfEventSources())
 File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 2668, in GetNumberOfEventSources
   offset_table = self._GetSerializedEventSourceOffsetTable(stream_number)
 File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1443, in _GetSerializedEventSourceOffsetTable
   u'event_source_index', stream_number)
 File "/usr/lib/python2.7/dist-packages/plaso/storage/zip_file.py", line 1375, in _GetSerializedDataOffsetTable
   lfu_stream_number = self._event_offset_tables_lfu.pop()
IndexError: pop from empty list
```

test.00001 is a dd raw image of a Mac drive.
plaso -log2timeline version 1.5.0

**Comment by vonnopsled** [comment]
Here's the pinfo with the errors:

```
*********************************** Error: 0 ***********************************
           Message : unable to process path specification with error: Unable
                     to decompress zlib compressed stream with error: Error -3
                     while decompressing: invalid distance too far back.
      Parser chain : 
Path specification : type: OS, location:
                     /mnt/hgfs/GDrive_Forensics_1/test/disk16/test.00001
                   : type: TSK, inode: 107998, location:
                     /Library/Printers/PPDs/Contents/Resources/EPSON FAX.gz
                   : type: GZIP
--------------------------------------------------------------------------------

*********************************** Error: 1 ***********************************
           Message : unable to process path specification with error: Unable
                     to decompress zlib compressed stream with error: Error -3
                     while decompressing: invalid block type.
      Parser chain : 
Path specification : type: OS, location:
                     /mnt/hgfs/GDrive_Forensics_1/test/disk16/test.00001
                   : type: TSK, inode: 107997, location:
                     /Library/Printers/PPDs/Contents/Resources/EPSON FAX A3.gz
                   : type: GZIP
```

**Comment by joachimmetz** [comment]
Closing this issue, due to major overhaul of ZIP-based storage in recent versions. Let us know if this issue persists.
