### ISSUE TITLE
zipfile raises: File name in directory X and header Y differ.

### ISSUE THREAD

**Issue by daniel-ayers** [log2timeline/plaso#943]
**Plaso version:**

1.5RC

**Operating system Plaso is running on:**

Ubuntu 16.04LTS

**Installation method:**

ppa:gift/dev

**Description of problem:**

$ log2timeline.py --hashers sha1 --parsers win7_slow --partitions all -z Pacific/Auckland --vss-stores all --debug --logfile X.log --process_archives --workers 8 X.plaso X.dd

Errors similar to the following are generated:

```
2016-08-22 18:44:48,911 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "bg\AABLoc.resources.dll" and header "bg/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,045 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "da\AABLoc.resources.dll" and header "da/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,130 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "ca\AABLoc.resources.dll" and header "ca/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,126 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "cs\AABLoc.resources.dll" and header "cs/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,345 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "el\AABLoc.resources.dll" and header "el/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,373 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "de\AABLoc.resources.dll" and header "de/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,416 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "es\AABLoc.resources.dll" and header "es/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,483 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "et\AABLoc.resources.dll" and header "et/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,539 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "fi\AABLoc.resources.dll" and header "fi/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,586 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "eu\AABLoc.resources.dll" and header "eu/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,798 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "hr\AABLoc.resources.dll" and header "hr/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,803 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "hu\AABLoc.resources.dll" and header "hu/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,834 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "it\AABLoc.resources.dll" and header "it/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,874 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "id\AABLoc.resources.dll" and header "id/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,922 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "ja\AABLoc.resources.dll" and header "ja/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,984 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "fr\AABLoc.resources.dll" and header "fr/AABLoc.resources.dll" differ.
2016-08-22 18:44:49,999 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "ko\AABLoc.resources.dll" and header "ko/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,064 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "lt\AABLoc.resources.dll" and header "lt/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,166 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "lv\AABLoc.resources.dll" and header "lv/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,187 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "ms\AABLoc.resources.dll" and header "ms/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,256 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "nb-no\AABLoc.resources.dll" and header "nb-no/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,273 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "nl\AABLoc.resources.dll" and header "nl/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,295 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "pl\AABLoc.resources.dll" and header "pl/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,365 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "pt-br\AABLoc.resources.dll" and header "pt-br/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,434 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "pt\AABLoc.resources.dll" and header "pt/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,488 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "ro\AABLoc.resources.dll" and header "ro/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,600 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "sk\AABLoc.resources.dll" and header "sk/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,647 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "ru\AABLoc.resources.dll" and header "ru/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,686 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "sl\AABLoc.resources.dll" and header "sl/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,884 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "tr\AABLoc.resources.dll" and header "tr/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,920 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "sr-cyrl-cs\AABLoc.resources.dll" and header "sr-cyrl-cs/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,921 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "th\AABLoc.resources.dll" and header "th/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,940 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "sv\AABLoc.resources.dll" and header "sv/AABLoc.resources.dll" differ.
2016-08-22 18:44:50,961 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "sr-latn-cs\AABLoc.resources.dll" and header "sr-latn-cs/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,016 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "uk\AABLoc.resources.dll" and header "uk/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,046 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "vi\AABLoc.resources.dll" and header "vi/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,055 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "zh-CN\AABLoc.resources.dll" and header "zh-CN/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,500 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "zh-tw\AABLoc.resources.dll" and header "zh-tw/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,589 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "zh-hk\AABLoc.resources.dll" and header "zh-hk/AABLoc.resources.dll" differ.
2016-08-22 18:44:51,824 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "da\SearchOptionsFlyoutLoc.resources.dll" and header "da/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:51,838 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "ca\SearchOptionsFlyoutLoc.resources.dll" and header "ca/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:51,908 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "cs\SearchOptionsFlyoutLoc.resources.dll" and header "cs/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:51,954 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "bg\SearchOptionsFlyoutLoc.resources.dll" and header "bg/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:51,963 [ERROR] (Worker_06 ) PID:12334 <worker_process> File name in directory "el\SearchOptionsFlyoutLoc.resources.dll" and header "el/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,018 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "de\SearchOptionsFlyoutLoc.resources.dll" and header "de/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,036 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "es\SearchOptionsFlyoutLoc.resources.dll" and header "es/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,095 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "et\SearchOptionsFlyoutLoc.resources.dll" and header "et/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,122 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "eu\SearchOptionsFlyoutLoc.resources.dll" and header "eu/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,170 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "fi\SearchOptionsFlyoutLoc.resources.dll" and header "fi/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,200 [ERROR] (Worker_04 ) PID:12326 <worker_process> File name in directory "fr\SearchOptionsFlyoutLoc.resources.dll" and header "fr/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,229 [ERROR] (Worker_06 ) PID:12334 <worker_process> File name in directory "hr\SearchOptionsFlyoutLoc.resources.dll" and header "hr/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,314 [ERROR] (Worker_01 ) PID:12314 <worker_process> File name in directory "hu\SearchOptionsFlyoutLoc.resources.dll" and header "hu/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,318 [ERROR] (Worker_05 ) PID:12330 <worker_process> File name in directory "id\SearchOptionsFlyoutLoc.resources.dll" and header "id/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,356 [ERROR] (Worker_00 ) PID:12310 <worker_process> File name in directory "it\SearchOptionsFlyoutLoc.resources.dll" and header "it/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,426 [ERROR] (Worker_03 ) PID:12322 <worker_process> File name in directory "ja\SearchOptionsFlyoutLoc.resources.dll" and header "ja/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,510 [ERROR] (Worker_07 ) PID:12338 <worker_process> File name in directory "ko\SearchOptionsFlyoutLoc.resources.dll" and header "ko/SearchOptionsFlyoutLoc.resources.dll" differ.
2016-08-22 18:44:52,529 [ERROR] (Worker_02 ) PID:12318 <worker_process> File name in directory "lt\SearchOptionsFlyoutLoc.resources.dll" and header "lt/SearchOptionsFlyoutLoc.resources.dll" differ.
```

Research indicates this might be an issue extracting ZIP files with directories in Python and the traditional confusion between Windows and *nix style paths.  eg. https://stackoverflow.com/questions/6063910/cant-unzip-archive-built-with-zipfile-python

**Source data:**

DD image of Windows PC.

**Comment by joachimmetz** [comment]
From zipfile.py
```
            if fname != zinfo.orig_filename:
                raise BadZipfile, \
                        'File name in directory "%s" and header "%s" differ.' % (
                            zinfo.orig_filename, fname)
```

**Comment by daniel-ayers** [comment]
I will go find it in the image and confirm there is nothing confidential in it.

**Comment by joachimmetz** [comment]
thx. To be verose I meant just the ZIP file

**Comment by daniel-ayers** [comment]
See email.

**Comment by joachimmetz** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/worker_process.py", line 246, in _ProcessPathSpec
    extraction_worker.ProcessPathSpec(parser_mediator, path_spec)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 741, in ProcessPathSpec
    self._ProcessFileEntry(mediator, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 601, in _ProcessFileEntry
    mediator, file_entry, data_stream.name)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 639, in _ProcessFileEntryDataStream
    self._AnalyzeDataStream(mediator, file_entry, data_stream_name)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 153, in _AnalyzeDataStream
    self._AnalyzeFileObject(mediator, file_object)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 182, in _AnalyzeFileObject
    data = file_object.read(maximum_read_size)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/zip_file_io.py", line 148, in read
    self._AlignUncompressedDataOffset(self._current_offset)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/zip_file_io.py", line 91, in _AlignUncompressedDataOffset
    self._zip_ext_file = self._zip_file.open(self._zip_info, 'r')
  File "/usr/lib/python2.7/zipfile.py", line 980, in open
    zinfo.orig_filename, fname)
```

**Comment by joachimmetz** [comment]
Added changes to dfvfs to raise this as an IOError instead of zipfile.BadZipfile: https://github.com/log2timeline/dfvfs/commit/19cbbd92d9003db4c94bcb4c51d8d51f3086c39f. 

Seeing this error is raised in zipfile, it cannot be fixed without replacing zipfile with a more error tolerant solution, which is not a short term option.

**Comment by joachimmetz** [comment]
Filed: https://github.com/log2timeline/dfvfs/issues/168, closing this issue.
