### ISSUE TITLE
psort.py raises exception when attempting to filter by tag

### ISSUE THREAD

**Issue by daniel-ayers** [log2timeline/plaso#947]
**Plaso version:**

1.5RC

**Operating system Plaso is running on:**

Ubuntu 16.04LTS 64 bit

**Installation method:**

ppa:gift/dev

**Description of problem:**

psort.py crashes when attempting to filter events by tag == 'browser_search'.

```
$ pinfo.py -v X.plaso
************************** Plaso Storage Information ***************************
            Filename : ntfs.plaso
      Format version : 20160715
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
18cf1857-a9e7-4cda-ad82-c1746af2ce2b : 2016-08-23T08:50:26.514530+00:00
ff13ccb8-1c0a-468e-9ce2-1720ed014ed7 : 2016-08-23T09:55:34.709518+00:00
--------------------------------------------------------------------------------


**************** Session: ff13ccb8-1c0a-468e-9ce2-1720ed014ed7 *****************
                Start time : 2016-08-23T09:55:34.709518+00:00
           Completion time : 2016-08-23T09:56:17.269469+00:00
              Product name : plaso
           Product version : 1.4.1_20160809
    Command line arguments : /usr/bin/psort.py -w ntfs-search.txt --analysis
                             browser_search ntfs.plaso
  Parser filter expression : N/A
Enabled parser and plugins : N/A
        Preferred encoding : UTF-8
                Debug mode : False
               Filter file : N/A
         Filter expression : N/A
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

****** Reports generated per plugin: ff13ccb8-1c0a-468e-9ce2-1720ed014ed7 ******
   Plugin name : Number of reports
--------------------------------------------------------------------------------
browser_search : 1
         Total : 1
--------------------------------------------------------------------------------

***** Event tags generated per label: ff13ccb8-1c0a-468e-9ce2-1720ed014ed7 *****
         Label : Number of event tags
--------------------------------------------------------------------------------
browser_search : 332
         Total : 332
--------------------------------------------------------------------------------
```

**Debug output/tracebacks:**

```
$ psort.py --debug --logfile=x.log -w ntfs-search.txt ntfs.plaso "tag is 'browser_search'"
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 821, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 816, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 763, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 285, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 604, in ExportEvents
    time_slice=time_slice, use_time_slicer=use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/psort.py", line 256, in _ExportEvents
    filter_match = event_filter.Match(event)
  File "/usr/lib/python2.7/dist-packages/plaso/filters/event_filter.py", line 42, in Match
    self._decision = self._matcher.Matches(event_object)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 256, in Matches
    if values and self.Operate(values):
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 243, in Operate
    for val in values:
  File "/usr/lib/python2.7/dist-packages/plaso/lib/objectfilter.py", line 537, in Expand
    attr_value = self._GetValue(obj, attr_name)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/pfilter.py", line 125, in _GetValue
    return ret.tags
AttributeError: 'EventTag' object has no attribute 'tags'
```

https://github.com/log2timeline/plaso/blob/master/plaso/lib/pfilter.py#L125 

Looking at the events in JSON format there is an attribute 'tag' but not 'tags'.

**Comment by joachimmetz** [comment]
Thx for the report, I'll have a look. This seems to be some issue with the plaso object filter implementation not entirely being with the times.

**Comment by joachimmetz** [comment]
> Looking at the events in JSON format there is an attribute 'tag' but not 'tags'.

This should be "labels", to reflect changes in the EventTag.

**Comment by joachimmetz** [comment]
BTW the plaso object filter syntax would be `tag contains 'browser_search'` since tag maps to a list of event labels. Note this is a legacy part of plaso that is on the list for an overhaul.

**Comment by joachimmetz** [comment]
Test and fix added. Closing issue.
