### ISSUE TITLE
update_dependencies.py error

### ISSUE THREAD

**Issue by dnides** [log2timeline/plaso#96]
Windows 8.1 x64 trying to run update_dependencies.py I get the following error.
```
c:\plaso build\plaso\plaso\utils>update_dependencies.py

Traceback (most recent call last):
  File "C:\plaso build\plaso\plaso\utils\update_dependencies.py", line 653, in <module>
    if not Main():
  File "C:\plaso build\plaso\plaso\utils\update_dependencies.py", line 266, in Main
    u'{0:s}/3rd%20party/{1:s}'.format(google_drive_url, sub_directory))
  File "C:\plaso build\plaso\plaso\utils\update_dependencies.py", line 132, in GetPackageDownloadUrls
    page_content = self.DownloadPageContent(google_drive_url)
  File "C:\plaso build\plaso\plaso\utils\update_dependencies.py", line 56, in DownloadPageContent
    url_object = urllib2.urlopen(download_url)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 396, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/3rd%20party/win-amd64-vs2010

c:\plaso build\plaso\plaso\utils>
```

**Comment by joachimmetz** [comment]
This script is still work in progress; it is trying to download the pre-built MSI from the plaso google drive folder, but looks like that fails. This has low priority since drive is not the best of binary distribution methods.

**Comment by joachimmetz** [comment]
Moving dependency script to https://github.com/log2timeline/devtools

**Comment by joachimmetz** [comment]
Pending fix for this issue: https://codereview.appspot.com/221100043/
