### ISSUE TITLE
Processing completed with errors

### ISSUE THREAD

**Issue by trietptm** [log2timeline/plaso#973]
**Plaso version:**

plaso - log2timeline version 1.4.0

**Operating system Plaso is running on:**

Updated SANS SIFT Ubuntu 14.04 LTS

**Installation method:**

sift-bootstrap

**Description of problem:**

When the command I use is: log2timeline.py --log-file=log2timeline.log --debug ThepViet_1.dump ThepViet.E01
, I receive the message: "Processing completed with errors." and the tails of the log file is here: https://gist.github.com/trietptm/a4370b59b6582f4610ebec8ad64c22a8
When I run zipinfo against the result Plaso file, it tells me that "End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive." although I can open the Plaso file with 7-Zip as a ZIP file.
**Debug output/tracebacks:**

https://gist.github.com/trietptm/a4370b59b6582f4610ebec8ad64c22a8

**Source data:**

Disk imaging from Windows Server 2012 R2 with FTK Imager 3.4.2.6 in E01 format, Image Fragment Size: do not fragment, Compression: 9 (smallest).

**Comment by trietptm** [comment]
I test with plaso-1.5.0-rc2-win-amd64-vs2010 and get the error: "Unable to close storage file".

```
Worker_00 (PID: 4172) - events produced: 2035348 - file:  - running: False
Worker_01 (PID: 9808) - events produced: 297901 - file: TSK:/Users/adminhq/AppData/Local/Google/Chrome/User Data/Default/Extensions/felcaaldnbdncclmgdcncolpebgiejap/1.1_0/_locales/bg/messages.json.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_02 (PID: 10148) - events produced: 411437 - file: TSK:/Users/adminhq/AppData/Local/Google/Chrome/User Data/Default/Storage/ext/chrome-signin/def/GPUCache/data_2.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_03 (PID: 6792) - events produced: 306886 - file: TSK:/Users/adminhq/AppData/Local/Google/Chrome/User Data/Default/Extensions/ghbmnnjooekpmoecnnnilnnbdlolhkhi/1.4_1/_locales/pt_PT/messages.json.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_00 (PID: 4172) - events produced: 2035348 - file:  - running: False
Worker_01 (PID: 9808) - events produced: 297901 - file: TSK:/Users/adminhq/AppData/Local/Google/Chrome/User Data/Default/Extensions/felcaaldnbdncclmgdcncolpebgiejap/1.1_0/_locales/bg/messages.json.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_02 (PID: 10148) - events produced: 411437 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys - running: True
Worker_03 (PID: 6792) - events produced: 306890 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer - running: True
Worker_00 (PID: 4172) - events produced: 2035348 - file:  - running: False
Worker_01 (PID: 9808) - events produced: 297905 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys/settings.sol.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_02 (PID: 10148) - events produced: 411441 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys - running: True
Worker_03 (PID: 6792) - events produced: 306890 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer - running: True
Worker_00 (PID: 4172) - events produced: 2035348 - file:  - running: False
Worker_01 (PID: 9808) - events produced: 297905 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys/settings.sol.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_02 (PID: 10148) - events produced: 411441 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys - running: True
Worker_03 (PID: 6792) - events produced: 306890 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer - running: True
Worker_00 (PID: 4172) - events produced: 2035348 - file:  - running: False
Worker_01 (PID: 9808) - events produced: 297905 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys/settings.sol.id-FA06CD03.systemdown@india.com.xtbl - running: True
Worker_02 (PID: 10148) - events produced: 411441 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer/sys - running: True
Worker_03 (PID: 6792) - events produced: 306890 - file: TSK:/Users/Administrator/AppData/Local/CocCoc/Browser/User Data/Default/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/H7C3C8YP/macromedia.com/support/flashplayer - running: True
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 754, in ProcessSources
  File "plaso\storage\zip_file.py", line 3066, in Close
  File "plaso\storage\zip_file.py", line 2471, in Close
IOError: Unable to close storage file.
Failed to execute script log2timeline
```

**Comment by Onager** [comment]
This error is raised when Plaso can't rename a file (to mark it as closed) because another process has the file opened. Is there anything else running on the system (anti-virus software?) that might have the file open?

**Comment by trietptm** [comment]
I have already stopped the antivirus before running Plaso - log2timeline. BTW, I see a result file in a folder named tmp_569i_ :) .

**Comment by joachimmetz** [comment]
>  I see a result file in a folder named tmp_569i_ :) .

That is correct the storage file is moved to a temp directory to isolate it for merging serialized data into the zip file, and work around excessive memory usage by the ZIP file Python implementation. This behavior might go away in the future when we change storage implementation.

**Comment by joachimmetz** [comment]
> "Processing completed with errors."

FYI this is as expected if there are extraction errors, they are now stored in the storage file and be listed with pinfo. To be verbose the Traceback is not as expected.

**Comment by Onager** [comment]
Closing, zip storage has been removed.
