### ISSUE TITLE
Travis-CI Linux build failing

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#981]
Travis-CI Linux build failing, likely an issue with an updated dependency.
Recent updates: construct, efilter, libmsiecf, pslist

**Comment by Onager** [comment]
It looks like construct 2.5.4 doesn't like unicode field names:

```
======================================================================
ERROR: engine.path_helper (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: engine.path_helper
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/log2timeline/plaso/tests/engine/path_helper.py", line 10, in <module>
    from plaso.containers import artifacts
  File "./plaso/containers/__init__.py", line 8, in <module>
    from plaso.containers import reports
  File "./plaso/containers/reports.py", line 6, in <module>
    from plaso.lib import timelib
  File "./plaso/lib/timelib.py", line 41, in <module>
    class Timestamp(object):
  File "./plaso/lib/timelib.py", line 109, in Timestamp
    construct.ULInt16(u'year'),
  File "/usr/lib/python2.7/dist-packages/construct/macros.py", line 138, in ULInt16
    return FormatField(name, "<", "H")
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 353, in __init__
    super(FormatField, self).__init__(name, self.packer.size)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 325, in __init__
    super(StaticField, self).__init__(name)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 104, in __init__
    raise TypeError("name must be a string or None", name)
TypeError: ('name must be a string or None', u'year')
```

**Comment by Onager** [comment]
This is also breaking dfvfs:

```
======================================================================
ERROR: engine.path_helper (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: engine.path_helper
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/log2timeline/plaso/tests/engine/path_helper.py", line 13, in <module>
    from tests import test_lib as shared_test_lib
  File "./tests/test_lib.py", line 11, in <module>
    from dfvfs.resolver import resolver as path_spec_resolver
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/__init__.py", line 10, in <module>
    from dfvfs.resolver import cpio_resolver_helper
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/cpio_resolver_helper.py", line 6, in <module>
    import dfvfs.vfs.cpio_file_system
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/cpio_file_system.py", line 7, in <module>
    from dfvfs.lib import cpio
  File "/usr/lib/python2.7/dist-packages/dfvfs/lib/cpio.py", line 38, in <module>
    class CPIOArchiveFile(object):
  File "/usr/lib/python2.7/dist-packages/dfvfs/lib/cpio.py", line 52, in CPIOArchiveFile
    construct.UBInt16(u'signature'),
  File "/usr/lib/python2.7/dist-packages/construct/macros.py", line 112, in UBInt16
    return FormatField(name, ">", "H")
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 353, in __init__
    super(FormatField, self).__init__(name, self.packer.size)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 325, in __init__
    super(StaticField, self).__init__(name)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 104, in __init__
    raise TypeError("name must be a string or None", name)
TypeError: ('name must be a string or None', u'signature')
```

**Comment by joachimmetz** [comment]
https://github.com/construct/construct/issues/87

**Comment by joachimmetz** [comment]
```
======================================================================
ERROR: testMergeFromStorage (storage.zip_file.ZIPStorageFileWriterTest)
Tests the MergeFromStorage function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/storage/zip_file.py", line 1516, in testMergeFromStorage
    storage_writer.Close()
  File "./plaso/storage/zip_file.py", line 3077, in Close
    self._storage_file.Close()
  File "./plaso/storage/zip_file.py", line 2439, in Close
    self.Flush()
  File "./plaso/storage/zip_file.py", line 2497, in Flush
    self._WriteSerializedEventTags()
  File "./plaso/storage/zip_file.py", line 2087, in _WriteSerializedEventTags
    event_tag_index_table.Write()
  File "./plaso/storage/zip_file.py", line 903, in Write
    entry_data = self._TAG_INDEX_STRUCT.build(event_tag_index)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 218, in build
    self.build_stream(obj, stream)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 225, in build_stream
    self._build(obj, stream, Container())
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 709, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 920, in _build
    case._build(obj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 709, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 296, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 296, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 771, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 406, in _build
    _write_stream(stream, self.lengthfunc(context), obj)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 319, in _write_stream
    stream.write(data)
TypeError: 'unicode' does not have the buffer interface
```

**Comment by joachimmetz** [comment]
New construct is "beta" (https://pypi.python.org/pypi/construct/2.6.2) and undergoing API and cores changes (I would argue that more likely experimental state in libyal terms at the moment). Hence switching back to 2.5.3

**Comment by joachimmetz** [comment]
Travis build green again closing issue.
