### ISSUE TITLE
Version Check Failed on pylnk

### ISSUE THREAD

**Issue by dsplice** [log2timeline/plaso#997]
Plaso version: 1.4.1_20160912

Operating system Plaso is running on: Linux, CentOS7, 64 bit

Installation method: git

Description of problem:  When running a command (eg psort.py -o list) a dependancy check for pylnk fails (location:  winlnk.py line 18).  Commenting out the check allows rest of command to run successfully.

Debug output/tracebacks:

[t906518@localhost plaso]$ psort.py -o list
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.4.1-20160912', u'psort.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/EGG-INFO/scripts/psort.py", line 27, in <module>
    from plaso import filters  # pylint: disable=unused-import
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/filters/__init__.py", line 4, in <module>
    from plaso.filters import dynamic_filter
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/filters/dynamic_filter.py", line 4, in <module>
    from plaso.filters import event_filter
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/filters/event_filter.py", line 4, in <module>
    from plaso.filters import interface
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/filters/interface.py", line 7, in <module>
    from plaso.lib import pfilter
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/lib/pfilter.py", line 16, in <module>
    from plaso.parsers import presets
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/parsers/__init__.py", line 11, in <module>
    from plaso.parsers import custom_destinations
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/parsers/custom_destinations.py", line 16, in <module>
    from plaso.parsers import winlnk
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/parsers/winlnk.py", line 18, in <module>
    dependencies.CheckModuleVersion(u'pylnk')
  File "/usr/lib/python2.7/site-packages/plaso-1.4.1_20160912-py2.7.egg/plaso/dependencies.py", line 482, in CheckModuleVersion
    module_version = module_object.get_version()
AttributeError: 'module' object has no attribute 'get_version'

**Comment by joachimmetz** [comment]
You've likely installed the wrong pylnk (https://pypi.python.org/pypi/pylnk/) instead of https://pypi.python.org/pypi/liblnk-python/20160420

**Comment by joachimmetz** [comment]
And if you are wondering why this is https://sourceforge.net/p/pypi/support-requests/527/

**Comment by dsplice** [comment]
Awesome.  Will try again!  Thanks for the speedy response!

Derek
