### ISSUE TITLE
Issue with Plaso 1.4.0 on Ubuntu - Processing

### ISSUE THREAD

**Issue by kmbMA** [log2timeline/plaso#999]
Trying to run log2timeline.py against more than one set of E01 files for Windows 7 OS. The processing starts but almost immediately fails with the following:

2016-09-14 08:36:27,269 [ERROR](MainProcess) PID:3291 <extraction_frontend> Unable to preprocess with error: Directory_Con: (tsk3.c:361) Unable to open directory: General file system error (fs_attr_add_run: error adding additional run (393622): No filler entry for 0. Final: 1) (  - proc_attrseq: put run - proc_attrlist)
2016-09-14 08:36:29,271 [WARNING](Collector) PID:3301 <multi_process> Unhandled exception in collector (PID: 3301).
2016-09-14 08:36:29,271 [ERROR](Collector) PID:3301 <multi_process> Directory_Con: (tsk3.c:361) Unable to open directory: General file system error (fs_attr_add_run: error adding additional run (393622): No filler entry for 0. Final: 1) (  - proc_attrseq: put run - proc_attrlist)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/multi_processing/multi_process.py", line 286, in _Main
    self._collector.Collect(self._source_path_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 124, in Collect
    source_path_spec, find_specs=self._filter_find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 105, in _ProcessPathSpec
    self._ProcessFileSystem(path_spec, find_specs=find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 61, in _ProcessFileSystem
    self._fs_collector.Collect(file_system, path_spec, find_specs=find_specs)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 327, in Collect
    self._ProcessDirectory(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/collector.py", line 255, in _ProcessDirectory
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 439, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 67, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 77, in _EntriesGenerator
    tsk_directory = fs_info.open_dir(path=location)
IOError: Directory_Con: (tsk3.c:361) Unable to open directory: General file system error (fs_attr_add_run: error adding additional run (393622): No filler entry for 0. Final: 1) (  - proc_attrseq: put run - proc_attrlist)
2016-09-14 08:36:32,654 [ERROR](MainProcess) PID:3291 <multi_process> Process Collector (PID: 3301) is not functioning correctly. Status code killed.
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: StorageWriter (PID: 3299).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_00 (PID: 3303).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_01 (PID: 3305).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_02 (PID: 3307).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_03 (PID: 3309).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_04 (PID: 3311).
2016-09-14 08:36:32,655 [WARNING](MainProcess) PID:3291 <multi_process> Terminating process: Worker_05 (PID: 3313).

**Comment by joachimmetz** [comment]
which version of libewf are you using?

**Comment by kmbMA** [comment]
When I run ewfmount –V it says the version is 20140608



Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by joachimmetz** [comment]
thx, then based on the following error I would say this could be a TSK related issue
```
IOError: Directory_Con: (tsk3.c:361) Unable to open directory: General file system error (fs_attr_add_run: error adding additional run (393622): No filler entry for 0. Final: 1) ( - proc_attrseq: put run - proc_attrlist)
```

did you try running with the E01s mounted with ewfmount?

**Comment by kmbMA** [comment]
so when I mount the E01's with EWFMount, it still won't work until I run Mount against the RAW file making the folder structure visible. At that point, log2timeline will run.

**Comment by kmbMA** [comment]
so it looks like sleuthkit 4.2 is what is installed with Plaso but 4.3 is available. Any idea how I could update the install?

**Comment by joachimmetz** [comment]
how did you install pytsk?

**Comment by kmbMA** [comment]
I believe I used the python-plaso to get it installed Joachim

**Comment by joachimmetz** [comment]
Can you be a bit more specific? Which platform I assume Linux but which disto?

Did you get it from the GIFT PPA (https://launchpad.net/~gift), from stable or dev track? Because a while back we started shipping pytsk bundled with TSK (https://github.com/py4n6/pytsk)

**Comment by kmbMA** [comment]
So I am running Ubuntu 14.04 and I did get it from the GIFT PPA stable track.

**Comment by joachimmetz** [comment]
That is indeed 4.2, the dev track contains pytsk bundled with libtsk 4.3 if you want to give it a try, though it might be interesting to try the dev version of plaso as well since we're nearing 1.5.0 release

**Comment by kmbMA** [comment]
I tried installing the plaso dev from gift/dev which installed plaso 1.4.1 but that gave me the same results. I'm guessing that in order for me to install  the 1.5 release (RC) it's a manual install process?

**Comment by joachimmetz** [comment]
the 1.4.1 in version in GIFT dev is the 1.5.0 RC2

**Comment by joachimmetz** [comment]
I'm afraid this might be something not easily fixed. This looks like an issue somewhere in TSK or maybe EWF in combination with TSK.

Which file system is this?

> so when I mount the E01's with EWFMount, it still won't work until I run Mount against the RAW file making the folder structure visible. 

What error are you seeing here?

**Comment by kmbMA** [comment]
Same operating system (Ubuntu 14.01 LTS) same error that I'm getting trying to run it normally.

**Comment by joachimmetz** [comment]
File system not operating system?

**Comment by joachimmetz** [comment]
btw 1.5 now has been released.

**Comment by joachimmetz** [comment]
Newer version of plaso available and no response from OP. Closing issue, create a new one if issue persists.
